### ISSUE TITLE
[error] cannot open 'files/wrap-key'

### ISSUE THREAD

**Issue by Camelliavin** [gramineproject/gramine#1004]
I refer to the [document](https://gramine.readthedocs.io/en/latest/tutorials/pytorch/index.html) to operate 'End-To-End Confidential PyTorch Workflow'.

After I run `make app dcap RA_TYPE=dcap`. This is what is in 'gramine/CI-Examples/ra-tls-secret-prov'
![1666429618739](https://user-images.githubusercontent.com/87418508/197331058-e067db51-96cc-4932-aa7f-25ca45414517.png)
so I guess secret_prov_server_dcap is  the secret provisioning server (secret_prov_pf/server_dcap) mentioned in the  [document](https://gramine.readthedocs.io/en/latest/tutorials/pytorch/index.html).

But when I want to  launch the secret provisioning server ( run `./secret_prov_server_dcap &`), an error occurred
> --- Reading the master key for protected files from 'files/wrap-key' ---
[error] cannot open 'files/wrap-key'

![1666429980431](https://user-images.githubusercontent.com/87418508/197331417-913d8c84-0305-4c90-9217-517588c1ee35.png)

So what should I do to fix this? Thanks for any replies.

**Comment by boryspoplawski** [comment]
You should read the document carefully - https://gramine.readthedocs.io/en/latest/tutorials/pytorch/index.html#preparing-input-files

**Comment by dimakuv** [comment]
Yes, @boryspoplawski is right, you seem to have forgotten the step:
```
mkdir files
dd if=/dev/urandom of=files/wrap_key bs=16 count=1
```

By the way, we'll need to fix the PyTorch tutorial, since now we have Gramine v1.3.1.
