### ISSUE TITLE
Gramine always use ocall_gettime() instead of rdtsc in QEMU VMs

### ISSUE THREAD

**Issue by lejunzhu** [gramineproject/gramine#1009]
### Description of the problem

When trying performance tuning in a QEMU VM, I found that Gramine always goes to the slow path to get current time. But in the host environment on the same physical machine, Gramine uses RDTSC.

The root cause is QEMU does not expose CPUID 0x15 and 0x16 to the guest:
```
$ cpuid -1 -l 0x15 -r
CPU:
   0x00000015 0x00: eax=0x00000000 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
$ cpuid -1 -l 0x16 -r
CPU:
   0x00000016 0x00: eax=0x00000000 ebx=0x00000000 ecx=0x00000000 edx=0x00000000
```

According to [this patch](https://patchwork.kernel.org/project/qemu-devel/patch/1484749457-87117-1-git-send-email-phil@philjordan.eu/) the CPU frequency is exposed to the guest from a different CPUID leaf 0x40000010. So, I think we can detect the CPU frequency like this:
- CPUID[0x1].ECX & (1<<31)  we are in a VM.
- CPUID[0x40000000].EAX >= 0x40000010 CPU frequency is reported
- CPUID[0x40000010].EAX * 1000 is the CPU frequency.

Also, when starting the VM, QEMU needs these CPU feature flag "+invtsc,+vmware-cpuid-freq" to report Invariant TSC and CPU frequency through CPUID.

### Steps to reproduce

Run this C program both in the host environment and in the VM:
```
#include <time.h>

int main()
{
        int i;
        for (i = 0; i < 1000*1000; ++i) {
                time(NULL);
        }
        return 0;
}
```

### Expected results

Gramine running inside the VM should have similar performance as what in the host.

### Actual results

On the host, only a few EEXITS are observed:
```
----- Total SGX stats for process 49 -----
  # of EENTERs:        398
  # of EEXITs:         324
  # of AEXs:           2078
  # of sync signals:   70
  # of async signals:  0
```

Inside the VM, a lot of EEXITS are observed:
```
----- Total SGX stats for process 2067 -----
  # of EENTERs:        1000328
  # of EEXITs:         1000287
  # of AEXs:           3669
  # of sync signals:   37
  # of async signals:  0
```

### Gramine commit hash

8b4ebdf

**Comment by dimakuv** [comment]
@lejunzhu For some orthogonal work on Gramine, I also encountered this issue. For your reference, my fix was like this:
```c
// in arch/x86_64/db_arch_misc.c

int tsc_init(void) {
    uint32_t words[CPUID_WORD_NUM];

    /*
     * We rely on the "invariant TSC" hardware feature (bit CPUID.80000007H:EDX[8]).
     * We also rely on the Generic CPUID space for hypervisors (KVM in particular):
     *   - 0x40000000: EAX: The maximum input value for CPUID supported by the hypervisor
     *   - 0x40000010: EAX: (Virtual) TSC frequency in kHz
     */
    _DkCpuIdRetrieve(0x80000007, 0, words);
    if (!(words[CPUID_WORD_EDX] & (1 << 8))) {
        /* invariant TSC is not available */
        return -PAL_ERROR_DENIED;
    }

    _DkCpuIdRetrieve(0x40000000, 0, words);
    if (words[CPUID_WORD_EAX] < 0x40000010) {
        /* virtual TSC frequency is not available */
        return -PAL_ERROR_DENIED;
    }

    _DkCpuIdRetrieve(0x40000010, 0, words);
    g_tsc_mhz = words[CPUID_WORD_EAX] / 1000;
    if (!g_tsc_mhz)
        return -PAL_ERROR_DENIED;

    g_start_tsc = get_tsc();

    /* FIXME: ideally should be set to some real time (number of seconds since the Epoch) on
     *        startup, e.g., a command-line argument from VMM */
    g_start_usec = 0;
    return 0;
}
```

In my case, I ran QEMU with these flags: `cpu host,+tsc-deadline,+invtsc`.

**Comment by dimakuv** [comment]
@lejunzhu Are you going to fix this in Gramine? We'll need to introduce a fallback path in `tsc_init()` function (the fallback should be something like I showed above). And we'll probably need to whitelist required CPUID "hypervisor" leaves, see https://github.com/gramineproject/gramine/blob/8b4ebdfe02b1a8334d2dbc7eaf7cdb3e3586f3a8/pal/src/host/linux-sgx/pal_misc.c#L394-L396

**Comment by lejunzhu** [comment]
@dimakuv Thank you. Your fix is exactly what I'm looking for. If you are going to add this fix along with other work you have, I can wait for it. It is not urgent.

**Comment by dimakuv** [comment]
@lejunzhu No, the other work is not happenning any time soon.

If you want to, I can create a PR with this hypervisor stuff. Or, you can create a PR. I don't mind either way.

**Comment by lejunzhu** [comment]
Yes, please create a PR. I haven't written any code for this issue right now.

**Comment by dimakuv** [comment]
@lejunzhu Could you test https://github.com/gramineproject/gramine/pull/1012 ?

**Comment by lejunzhu** [comment]
> @lejunzhu Could you test #1012 ?

Just tried it. The stat now shows < 300 EEXIT, which means the patch is working.

**Comment by dimakuv** [comment]
We hit the same problem on MS Azure VMs.

There, the Hyper-V hypervisor is used. It emulates the "Invariant TSC" CPUID leaves as dummies (zeros):
```
$ cpuid
...
   Time Stamp Counter/Core Crystal Clock Information (0x15):
      TSC/clock ratio = 0/0
      nominal core crystal clock = 0 Hz
...
```

Instead, Hyper-V instructions guest kernels to use a special MSR and a special physical-memory page: https://learn.microsoft.com/en-us/virtualization/hyper-v-on-windows/tlfs/timers#partition-reference-tsc-mechanism

So my first try with #1012 won't work on MS Azure. I'm working on another approach, where we put the time variable in shared untrusted memory (the helper untrusted thread periodically updates it) and enclave threads grab this variable (instead of trying RDTSC or OCALLs).

**Comment by dimakuv** [comment]
@lejunzhu I wonder if you could test your QEMU/KVM VM workload on #1012 again? I rebased and updated it a bit.

**Comment by lejunzhu** [comment]
> @lejunzhu I wonder if you could test your QEMU/KVM VM workload on #1012 again? I rebased and updated it a bit.

It works in my VM, and the number of EEXITs is reduced as expected.
