### ISSUE TITLE
[LibOS] `g_allocated_pages` integer overflow

### ISSUE THREAD

**Issue by llly** [gramineproject/gramine#1017]
### Description of the problem

During `clone` and `execve` flow, `g_allocated_pages` which traces allocated enclave memory get integer overflow. So there is a penitential bug in new VMA Bookkeep, though it doesn't break cases.
I also checked the commit just before VMA Bookkeep rework, this issue doesn't exist.

### Steps to reproduce

Add a log ` log_error("g_allocated_pages = %#lx, size = %#lx", g_allocated_pages, size);` after
https://github.com/gramineproject/gramine/blob/f01b21540c46e43ddd5a6c5cc46ef900b13e09ad/pal/src/host/linux-sgx/pal_memory.c#L63
then build and install Gramine.

Build `CI-Examples/bash` with all log.
Run `gramine-sgx bash` then type `ls` to trigger syscall `clone` and `execve`.

### Expected results

All logs in `error: g_allocated_pages = ?, size = ?`, `g_allocated_pages`  are positive as signed int.

### Actual results

```
[P2:T2:bash] trace: ---- execve("/bin/ls", [ls,], [LD_LIBRARY_PATH=/lib:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu,PWD=/,]) ...
error: g_allocated_pages = 0x96d, size = 0x5000
error: g_allocated_pages = 0x968, size = 0x5000
error: g_allocated_pages = 0x963, size = 0x5000
.......
error: g_allocated_pages = 0x213, size = 0x104000
error: g_allocated_pages = 0x14, size = 0x1ff000
error: g_allocated_pages = 0x10, size = 0x4000
error: g_allocated_pages = 0x7, size = 0x9000
error: g_allocated_pages = 0xfffffffffffffffd, size = 0xa000
error: g_allocated_pages = 0xfffffffffffffffc, size = 0x1000
error: g_allocated_pages = 0xffffffffffffffbc, size = 0x40000
error: g_allocated_pages = 0xffffffffffffffbb, size = 0x1000
[P2:T2:ls] debug: loading "file:/bin/ls"
error: g_allocated_pages = 0xffffffffffffffbb, size = 0x5000
error: g_allocated_pages = 0xffffffffffffffbb, size = 0x5000
error: g_allocated_pages = 0xffffffffffffffbb, size = 0x5000
error: g_allocated_pages = 0xffffffffffffffbb, size = 0x5000
[P2:T2:ls] debug: find_interp: searching for interpreter: /lib/ld-linux-x86-64.so.2
```

### Gramine commit hash

181fb270826a8cbe924d5caba59107e8b26f56c7

**Comment by boryspoplawski** [comment]
It works correctly for me...
More information please: host OS, compile flags etc.
Btw, `g_allocated_pages` should be accessed using atomic ops, but that's probably not a problem (on x86 plain load will be atomic anyway).

**Comment by llly** [comment]
I'm using Ubuntu 18.04.6 LTS. Not `gramine-sgx bash -c ls`, but `gramine-sgx bash` then `ls` can reproduce.

By using a debug version Gramine without modification build by `meson setup build-debug/ -Dtests=enabled -Ddirect=enabled --buildtype=debug -Dsgx=enabled` , run with command `gramine-sgx bash` then `cat /sys/devices/system/node/node0/meminfo`, I can trigger an assert
```
[P2:T2:cat] assert failed ../libos/src/fs/sys/node_info.c:109 node_mem_total >= node_mem_free
```
because they are calculated by `g_allocated_pages`.

**Comment by dimakuv** [comment]
Strange, I also cannot reproduce this problem. Even after doing the exact steps as @llly provided, I can't trigger the assert.

Even decreasing SGX enclave size to `"256M"`, everything still works.

I tried on the latest master.

**Comment by boryspoplawski** [comment]
Same, tried a docker with ubuntu18.04 (oot driver on host), no repro

**Comment by llly** [comment]
Close it now. I need to investigate what causes my result.

**Comment by mkow** [comment]
@llly: Please debug the issue yourself, as you're the only one who can reproduce it, and we don't see where the bug could be.

**Comment by boryspoplawski** [comment]
I've hit a similar issue, albeit on a modified Gramine (which actually fixed a another bug related to `g_allocated_pages`). Investigating it atm.

**Comment by boryspoplawski** [comment]
@llly Could you check if https://github.com/gramineproject/gramine/pull/1036 fixed the issue for you? Note `g_allocated_pages` was removed, so you would have to check original issue (like proc/sys entries with wrong data)

**Comment by llly** [comment]
@boryspoplawski Yes. It fixes this issue. I can get reasonable values now.
```
Node 0 MemTotal:         521964 kB
Node 0 MemFree:          512088 kB
Node 0 MemUsed:            9876 kB
```
