### ISSUE TITLE
dns error

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#1019]
### Description of the problem

my gramine-sgx version is 1.2.

making http request by domain name instead of ip would get an error: getaddrinfo EAI_AGAIN.
![Uploading A9DEEE56-4E72-4221-B502-B5290EF8CBE4.png…]()

### Steps to reproduce

in nodejs:
http.request("http://www.baidu.com/",function(){})

### Expected results

work well

### Actual results

![55B9B49C-B6DB-44CF-8618-16EA643BA4BA](https://user-images.githubusercontent.com/18025276/198836772-33613118-539c-4f23-8120-ec95de3e5656.png)

### Gramine commit hash

fd2e30274a2c0eb5aa7f9b95938f185345965eb4

**Comment by mccoysc** [comment]
and i already add all files in /etc/ to be "allowed"
![Uploading A7FC4578-2D7F-46BB-870F-5631F54585C4.png…]()

**Comment by boryspoplawski** [comment]
1. Update to the newest version (v1.3.x) and try again
2. Don't post screenshot of logs.
