### ISSUE TITLE
Gramine Failures for Ubuntu 22.04

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1043]
### Description of the problem

**List of failures for Ubuntu 22.04**

1. Python Fix [#938](https://github.com/gramineproject/gramine/pull/938) (SGX)
2. Nginx (Native, SGX)
3. R (4.1.2) (SGX)

**Nginx:**
```
With the latest Ubuntu 22.04 support nginx-1.16 is not compatible with openssl version(3.0.2).
For most of the cases, we were getting deprecated messages
src/event/ngx_event_openssl.c:5125:5: error: ‘ENGINE_set_default’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
src/event/ngx_event_openssl.c:5117:5: error: ‘ENGINE_by_id’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
etc.
```

**We upgraded the nginx version to 1.22 for both Ubuntu 18.04 & 22.04 and it worked.**

**Ubuntu 18.04**
```
ls
Makefile   install              nginx-gramine.conf.template  nginx.manifest.template  nginx_args
OUTPUT     nginx-1.22.0         nginx.manifest               nginx.sig                result-221114-064543
README.md  nginx-1.22.0.tar.gz  nginx.manifest.sgx           nginx.token              ssl


openssl version
OpenSSL 1.1.1  11 Sep 2018


LOOP=1 CONCURRENCY_LIST="1 32" ../common_tools/benchmark-http.sh http://127.0.0.1:8002
wrk -c 300 -d 30 -t 1 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 1 Concurrency = 1 Per thread Throughput (bytes) = 6950.00, Latency (ms) = 2500.00
wrk -c 300 -d 30 -t 32 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 1 Concurrency = 32 Per thread Throughput (bytes) = 222.09, Latency (ms) = 2340.00
Concurrency =   1: Per Thread Median Througput (bytes) =  6950.000, Latency (ms) =  2500.000
Concurrency =  32: Per Thread Median Througput (bytes) =   222.090, Latency (ms) =  2340.000
Result file: result-221114-064543

```

**Ubuntu 22.04**
```
ls
Makefile   install              nginx-1.22.0.tar.gz          nginx.manifest.sgx       nginx.token           ssl
OUTPUT     nginx-1.16.1.tar.gz  nginx-gramine.conf.template  nginx.manifest.template  nginx_args
README.md  nginx-1.22.0         nginx.manifest               nginx.sig                result-221114-064453

openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)


LOOP=1 CONCURRENCY_LIST="1 32" ../common_tools/benchmark-http.sh http://127.0.0.1:8002
wrk -c 300 -d 30 -t 1 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 1 Concurrency = 1 Per thread Throughput (bytes) = 10430.00, Latency (ms) = 4.26
wrk -c 300 -d 30 -t 32 -R 10000 http://127.0.0.1:8002/random/10K.1.html
Run = 1 Concurrency = 32 Per thread Throughput (bytes) = 329.51, Latency (ms) = 1.30
Concurrency =   1: Per Thread Median Througput (bytes) = 10430.000, Latency (ms) =     4.260
Concurrency =  32: Per Thread Median Througput (bytes) =   329.510, Latency (ms) =     1.300
Result file: result-221114-064453
```

**R:** R version has been updated in Ubuntu 22.04 and now, it fails with below error. Also, R.manifest.template is not being updated to use max_threads
error: There are no available TCS pages left for a new thread!
Please try to increase sgx.max_threads in the manifest.
The current value is 4
Segmentation fault (core dumped)

### Steps to reproduce

Gramine: 670cc12609520d01ca4e73af37d57f975faa215d
Ubuntu 22.04 Dockerfile: [Dockerfile](https://github.com/jinengandhi-intel/graphene_local_ci/blob/master/ci/dockerfile/ubuntu22.04.dockerfile)

Create a docker container for Ubuntu 22.04
Build Gramine
Run Python, Nginx and R workload

### Expected results

Python, R and nginx all should be passed

### Actual results

Python & R as well for Gramine-SGX whereas nginx is failed for both Gramine-Direct & Gramine SGX

### Gramine commit hash

670cc12609520d01ca4e73af37d57f975faa215d

**Comment by dimakuv** [comment]
1. We can update the version of Nginx, no problems. Feel free to submit a PR.
2. Python's PR is pending on original author's actions (see my and Borys's comments there).
3. I didn't get the problem for R -- is it just a small number of enclave threads? What if you increment this number, or (better) restrict R to use a subset of threads via some environment variable?

**Comment by anjalirai-intel** [comment]
@dimakuv If we increment the number of max_threads to 8, it passes. But in the past we have already restricted the number of threads
https://github.com/gramineproject/examples/blob/master/r/R.manifest.template#L15

**Comment by dimakuv** [comment]
Looks like newer versions of R create some "helper threads" in addition to the "worker threads" (which you restrict to 4 via the environment variable).

So please submit a PR that increases max_threads to 8, and add a comment that R on Ubuntu 22.04 requires more threads than specified in `OMP_NUM_THREADS` because it spawns some additional helper threads.

**Comment by anjalirai-intel** [comment]
The issue can be closed the fix was pushed from https://github.com/gramineproject/gramine/commit/a54515b7ea38a19891bb3cb5de7fe379ada00b38 ,and https://github.com/gramineproject/examples/commit/553394fcee0f6f878bea19fadb0de6548d824f1a
