### ISSUE TITLE
failed to run rust example

### ISSUE THREAD

**Issue by chuan-xu** [gramineproject/gramine#1045]
![image](https://user-images.githubusercontent.com/92707056/201883462-ce248d75-5820-4478-a041-1317a80d7771.png)

Changing the number of threads does not work!

**Comment by dimakuv** [comment]
@chuan-xu So what happens when you increase the number of threads? To for example `sgx.thread_num = 64`?

**Comment by chuan-xu** [comment]
think you, 64 is ok.
I saw "max_threads = 8" , assumed thread_nums was no more than 8

**Comment by dimakuv** [comment]
The maximum number of threads can be more or less arbitrary. It depends on the machine on which you're running Gramine (apparently, you have a large machine, with many CPU cores).

Since you resolved your issue, I'll close it.
