### ISSUE TITLE
how to use dns name?

### ISSUE THREAD

**Issue by chuan-xu** [gramineproject/gramine#1056]
rust demo will panic in gramine!
```
TcpStream::connect("api.trustedservices.intel.com:443").unwrap();
```
error:
```
{ kind: Uncategorized, error: "failed to lookup address information: Temporary failure in name resolution" }
```

**Comment by dimakuv** [comment]
Could you please provide more information?
- What is the OS distro.
- What is the Gramine version.
- What is your Gramine manifest for this demo.
- What is the Gramine log (with `loader.log_level = "trace"`), so that we can see the root cause of this problem?

In general, looks like you should add `sys.enable_extra_runtime_domain_names_conf = true` manifest option.

**Comment by chuan-xu** [comment]
@dimakuv 
+ ubuntu20.04
+ 
![image](https://user-images.githubusercontent.com/92707056/202998179-e56d401d-a27f-41de-ade3-57ba1bc16fc6.png)

+ 
```
[loader]
entrypoint = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"
log_level = "error"

[libos]
entrypoint = "target/release/rust-hyper-http-server"

[fs]
[[fs.mounts]]
path = "/lib"
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc"

[[fs.mounts]]
path = "/lib/x86_64-linux-gnu"
uri = "file:/lib/x86_64-linux-gnu"

[[fs.mounts]]
type = "encrypted"
path = "/root/save"
uri = "file:save_dir"
key_name = "_sgx_mrenclave"

[[fs.mounts]]
path = "/etc/hosts"
uri = "file:./helper-files/hosts"

[sgx]
debug = false
nonpie_binary = true
enclave_size = "256M"
thread_num = 64
isvprodid = 0
isvsvn = 0
remote_attestation = "epid"
ra_client_linkable = true
ra_client_spid = "146C4876D473281CF0EAB88139C8FB5C"
require_avx = false
require_avx512 = false
require_mpx = false
require_pkru = false
require_amx = false
support_exinfo = false
enable_stats = false
enable_extra_runtime_domain_names_conf = true
allowed_files = [
  "file:save_dir"
]

[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/libsysdb.so"

[[sgx.trusted_files]]
uri = "file:target/release/rust-hyper-http-server"

[[sgx.trusted_files]]
uri = "file:/usr/lib/x86_64-linux-gnu/gramine/runtime/glibc/"

[[sgx.trusted_files]]
uri = "file:/lib/x86_64-linux-gnu/"

[[sgx.trusted_files]]
uri = "file:./helper-files/hosts"

[sys]
insecure__allow_eventfd = true

[loader.env]
LD_LIBRARY_PATH = "/lib:/lib/x86_64-linux-gnu"
MALLOC_ARENA_MAX = "1"
RUST_BACKTRACE = "full"
```
+ 
![image](https://user-images.githubusercontent.com/92707056/202998726-fe6670c2-a6c2-437e-949d-7ae68a541bb6.png)

**Comment by dimakuv** [comment]
> What is the Gramine log (with `loader.log_level = "trace"`), so that we can see the root cause of this problem?

You haven't showed the Gramine log itself.

**Comment by chuan-xu** [comment]
@dimakuv 

![image](https://user-images.githubusercontent.com/92707056/203006569-a9d0aa63-e3f3-4a2e-a4f4-b5c6ad2e7b7b.png)

**Comment by dimakuv** [comment]
Please do not post screenshots. Copy-paste text or attach text files.

Anyway, looking at the screenshot, I don't see anything bad happenning in Gramine. Maybe the error happened before what you showed in this screenshot. Maybe there is no error, and your Rust demo is incorrect or something?

**Comment by boryspoplawski** [comment]
You have `sgx.enable_extra_runtime_domain_names_conf`, instead of `sys.enable_extra_runtime_domain_names_conf`
