### ISSUE TITLE
Add new system calls to gramine

### ISSUE THREAD

**Issue by ying2liu** [gramineproject/gramine#1058]
### Description of the feature

One of the cloud use cases is to pull docker image and unpack the image. During the unpacking process, directory timestamps need to be updated after all files are extracted using utimenstat system call, but this system call is not available in gramine. Both symlink and hardlink are used to keep the link files during unpacking, but symlink and linkat system calls are not available in gramine either. We need add these three system calls: utimenstat, symlink and linkat. You could find more details here: https://github.com/confidential-containers/enclave-cc

### Why Gramine should implement it?

tar-rs crate only preserve timestamps of files. symlink file and directory are not covered, which is the reason why utimenstat is needed to add time stamp to directory and symlink file.

Without symlink and linkat, the only way to work around it will be to copy files, but it is not only inefficient for the large files, but also could not keep files syn-up with each other.

**Comment by boryspoplawski** [comment]
We need more clarification on the links case. Do you want them (e.g. symlinks) shared with host OS or is purely in-Gramine implementation enough?

**Comment by mkow** [comment]
1. Please fix the issue topic, right now it's like "improve gramine", conveys almost no information about the contents of the issue.
2. Are you trying to run Docker inside Gramine? Or what exactly? This description sounds weird and unclear.

**Comment by ying2liu** [comment]
@boryspoplawski Agent enclave calls symlink and hard link system calls when it unpacks the image. I think the files should be shared with host OS, because app enclave needs access these files later.

**Comment by ying2liu** [comment]
@mkow You could find more detailed information here: https://github.com/confidential-containers/enclave-cc. Gramine should run inside agent and app containers. I will add the link to this issue.

**Comment by mkow** [comment]
Closing, we already have an issue for `link()` (#786) and a few for symlinks. @ying2liu: if something is missing from other issues then please create one, but please be precise in the description (it's pretty chaotic and hard to extract from it what you actually need) and the title (right now the title is "Add new system calls to gramine", which tells almost nothing to the readers of the issue list).
