### ISSUE TITLE
need create process out of enclave from enclave

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#1063]
### Description of the feature

some time i need execute some cmds out of enclave instead of in enclave.
and i know,maybe you would say that for security reasons i should not do this.
but , "safe" or "un-safe" is a choice for business.

### Why Gramine should implement it?

implement some rules in manifest that allow run some process in "normal" host os.
for example,the rule can like the following:

[host-process]
path="/usr/bin/python3"
rule="*outEnclave"
sub=3

this would means:
execute /usr/bin/python3 with an "outEnclave"-ended param would be run in "normal" host os env,not in enclave. and its 3-level sub process also run in normal host os,and 4-level or more sub process would run back to enclave.

i would run like this:

exec("/usr/bin/python3","test.py","outEnclave","otherParams")

**Comment by mkow** [comment]
I don't think we'll ever support this, as it breaks the overall Gramine design. Gramine is supposed to run a single Linux application inside a "virtualized" environment. If you want to run something outside it, then you should wrap Gramine in some orchestrator tool which will spawn Gramine and whatever other helper processes you need.
Doing it the other way is like asking Docker to allow the containerized apps to start processes outside the container.

**Comment by mccoysc** [comment]
> I don't think we'll ever support this, as it breaks the overall Gramine design. Gramine is supposed to run a single Linux application inside a "virtualized" environment. If you want to run something outside it, then you should wrap Gramine in some orchestrator tool which will spawn Gramine and whatever other helper processes you need.
> 
> Doing it the other way is like asking Docker to allow the containerized apps to start processes outside the container.

or,maybe,an "in enclave process"?
now the process model is based in new enclave,it's so expensive for creation and memory.
