### ISSUE TITLE
Low-level /dev/attestation interface

### ISSUE THREAD

**Issue by weitianyuan** [gramineproject/gramine#1064]
### Description of the problem

read   file /dev/attestation/my_target_info failed . I donot  gnow why 
 There is no exception when running hellowrld in the grain environment, but an error is reported when calling the low level interface

### Steps to reproduce

    sgx_target_info_t target_info;
    bytes = file_read_f("/dev/attestation/my_target_info", (char*)&target_info,
                        sizeof(target_info));
    if (bytes != sizeof(target_info)) {
        /* error is already printed by file_read_f() */
        return FAILURE;
    }
return 0;

### Expected results

I want the return value to be 0

### Actual results

In fact, reading the interface failed and returned - 1

### Gramine commit hash

1.1.3

**Comment by mkow** [comment]
> I donot gnow why

> running hellowrld in the grain environment

> Gramine commit hash
> 1.1.3

@weitianyuan: If you want us to spend time helping you, then you also need to give some effort from your side - in this case, by proofreading your messages before sending. There's no Gramine version 1.1.3, I don't know what "grain environment" is and you didn't say what's the manifest config you're using.
