### ISSUE TITLE
ECREATE failed in enclave creation ioctl (errno = -5) when running on Azure VM

### ISSUE THREAD

**Issue by liorbond** [gramineproject/gramine#1070]
### Description of the problem

When I'm running one of the exmaples (GCC) in this repo I'm getting the following error:
```Gramine is starting. Parsing TOML manifest file, this may take some time...
error: ECREATE failed in enclave creation ioctl (errno = -5)
error: Creating enclave failed: -5
error: load_enclave() failed with error -5
```
Was trying to take a refernce from #955 but nothing there helped.
The output of 
```cpuid | grep "SAVE area"```
is
```      SAVE area size in bytes                     = 0x000003c0 (960)
      SAVE area size in bytes                     = 0x000003c0 (960)
      SAVE area size in bytes                     = 0x000003c0 (960)
      SAVE area size in bytes                     = 0x000003c0 (960)
      SAVE area size in bytes                     = 0x000003c0 (960)
      SAVE area size in bytes                     = 0x000003c0 (960)
      SAVE area size in bytes                     = 0x000003c0 (960)
      SAVE area size in bytes                     = 0x000003c0 (960)
```

### Gramine commit hash

e18bc05b17fd704b259cb0401f928dc4ec5199a6

**Comment by dimakuv** [comment]
1. Do any other examples work? Like `helloworld`?

2. Are you using a virtual machine (VM)?

3. What is your OS distro, Linux kernel and SGX driver?

**Comment by liorbond** [comment]
@dimakuv Thanks for your answer
1. I can't see an example named helloworld. The reason I tried the examples is because I had the same issue with my own application.
2. It is a VM running on Microsoft Azure 
3. 
**OS:**
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
Linux lior 5.15.0-1020-azure #25~20.04.1-Ubuntu SMP Thu Sep 1 19:20:56 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**SGX:**
```
OOT driver detected.
Version: 2.11.0
```

**Comment by dimakuv** [comment]
> OOT driver detected.

But why? You already have a built-in SGX driver, since your Linux kernel is 5.15.

Did you install this OOT driver?

> I can't see an example named helloworld

I guess you're talking about the `examples` repository? Well, anyway, it looks like the problem is that you installed an additional OOT SGX driver on this platform, which is **not needed** and probably confuses Gramine.

**Comment by liorbond** [comment]
Actually I had this issue before installing the OOT driver I installed it 10 minutes ago while checking the driver version just for a test

**Comment by liorbond** [comment]
Found it. The issue is was with sgx.debug which should have been true in my case
Thank you so much!

**Comment by chuan-xu** [comment]
@liorbond 
I have the same problem, how did you solve it?
