### ISSUE TITLE
run python runtime error

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#1078]
### Description of the problem

after init python runtime,call any python runtime api would get process crashed(it seems that if python runtime has not been inited.

``` 
Py_InitializeEx(0)
if (!PyEval_ThreadsInitialized())
            PyEval_InitThreads();

Py_DECREF(PyImport_ImportModule("threading"));
auto m_state = PyEval_SaveThread(); 

```

and after this code,if i call any python runtime api(PySys_GetObject("path") for example) ,process would crashed for "access null ptr".

the above code would work with no error in normal linux env.

the version for python runtime is 3.8.10 x64
，and gramine env is from the **gramine docker hub image version 1.3.1**.

### Gramine commit hash

i don't know

**Comment by mccoysc** [comment]
![image](https://user-images.githubusercontent.com/18025276/206843932-9277624a-74ad-4007-89d3-90861d98cce0.jpeg)

**Comment by mkow** [comment]
Same as with other your issues: Please proof-read your issues before posting, they are all unreadable and the descriptions you provide are very chaotic. If you want us to spend time helping you, then you also should spend some time to make it easier for us.

**Comment by mccoysc** [comment]
> Same as with other your issues: Please proof-read your issues before posting, they are all unreadable and the descriptions you provide are very chaotic. If you want us to spend time helping you, then you also should spend some time to make it easier for us.

i want to make libpython3.8.0.so embeded in my program.

```

Py_InitializeEx(0)
if (!PyEval_ThreadsInitialized())
            PyEval_InitThreads();

Py_DECREF(PyImport_ImportModule("threading"));
auto m_state = PyEval_SaveThread(); 

PySys_GetObject("path");

```

the above code would always make process crash but run well in normal linux env.

**Comment by mccoysc** [comment]
@mkow

**Comment by dimakuv** [comment]
It's actually an interesting workload to try in Gramine, but I'm afraid this is not a priority for the Gramine team. @mccoysc Would it be possible for you to debug this problem a bit? Give some more information where it fails and why, based on debugging with `loader.log_level = "trace"` and GDB.
