### ISSUE TITLE
[LibOS,PAL/Linux-SGX] Reenable `test_002_attestation_deprecated` on EDMM-enabled machines

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#1100]
### Description of the problem

PR https://github.com/gramineproject/gramine/pull/1054 implemented an initial version of EDMM support.

There is some bug such that `test_002_attestation_deprecated` and `test_003_attestation_deprecated_stdio` LibOS regression tests failed, for no apparent reason. @boryspoplawski didn't have time to debug them, so someone else has to do the debugging, fix the issue and re-enable these tests.

The root cause is not about EDMM, but about the DCAP remote-attestation infrastructure. We mention EDMM here simply because the only machine with the DCAP remote-attestation infrastructure is used for testing EDMM.

### Steps to reproduce

Run these two regression tests on a EDMM-enabled machine (e.g., on the `Jenkins-SGX-EDMM` pipeline).

### Gramine commit hash

Branch `borys/edmm`

**Comment by boryspoplawski** [comment]
This is completely unrelated to EDMM, it's about DCAP, which we didn't test in CI before (because our only EDMM capable host uses DCAP)

**Comment by dimakuv** [comment]
@boryspoplawski Got it. Updated the issue description to reflect this.
