### ISSUE TITLE
can not start gramine

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#1103]
### Description of the problem

![87F7B379-ED93-44F2-A499-20C07AFA135F](https://user-images.githubusercontent.com/18025276/210728880-ae8b74e2-7495-4162-9583-e188d5ea760a.png)

### Gramine commit hash

i do not know(the latest docker image in docker hub)

**Comment by dimakuv** [comment]
Please try to do `mount -o remount,exec /dev`.

See explanations e.g. here: https://docs.oasis.io/node/run-your-node/prerequisites/set-up-trusted-execution-environment-tee/#ensure-dev-is-not-mounted-with-the-noexec-option

**Comment by dimakuv** [comment]
Can you show your `ls -la /dev/*sgx*`?

**Comment by mccoysc** [comment]
> Can you show your `ls -la /dev/*sgx*`?

this is the host ls /dev
![image](https://user-images.githubusercontent.com/18025276/210743119-7c20e7a9-4ef8-482d-aaa7-07ae9038dcfe.jpeg)



this is the docker cmd line:
![image](https://user-images.githubusercontent.com/18025276/210743290-40af96cb-2075-4d34-a2ae-ae47861cebbd.png)



this is the ls /dev in docker:
![image](https://user-images.githubusercontent.com/18025276/210743400-f34d9047-83b1-4fe9-853f-857debcf9a53.png)

**Comment by dimakuv** [comment]
Please post the output of the exact command that I asked for.

**Comment by mccoysc** [comment]
and my host os is "centos 8"

**Comment by mccoysc** [comment]
> Please post the output of the exact command that I asked for (on the host and inside Docker container).

 this is the ls -la /dev/*sgx* in host os:
![image](https://user-images.githubusercontent.com/18025276/210744570-5e34a4f1-067c-4f63-aa7b-fcd0befa19c5.png)

this is the ls -la /dev/*sgx* in docker instance:
![image](https://user-images.githubusercontent.com/18025276/210744677-8a05fbd9-a4bd-43b3-9538-12fd3f072529.png)

**Comment by dimakuv** [comment]
Looks legit, given that you're running everything under `root` user.

What is the output of `ls -la / | grep dev`?

**Comment by mccoysc** [comment]
> Looks legit, given that you're running everything under `root` user.
> 
> 
> 
> What is the output of `ls -la / | grep dev`?

![image](https://user-images.githubusercontent.com/18025276/210753935-a74c6368-f024-4caf-a89f-65450da85a38.png)

**Comment by dimakuv** [comment]
I'm out of ideas. Things look correct.

Could you check this: https://github.com/gramineproject/graphene/issues/2437#issuecomment-880498414

**Comment by mkow** [comment]
@mccoysc: Please stop posting logs as screenshots.

Anyways, CentOS 8 is not supported anymore neither by us nor by its original vendor, so I'm closing this issue.
