### ISSUE TITLE
Tensorflow failing with latest Gramine Commit

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1121]
### Description of the problem
We have verified it by running with previous commit where it works.
1.  Tensorflow-serving is failing with commit e73da5e2a0b77c5ea88585bb52a75b9d4e65c55b
The steps to reproduce and debug logs is attached for tensorflow
Debug Logs:
[Tensorflow_Gramine-SGX_Failure_Log.txt](https://github.com/gramineproject/gramine/files/10423338/Tensorflow_Gramine-SGX_Failure_Log.txt)

### Steps to reproduce
 
**Tensorflow**
[Steps_to_reproduce.txt](https://github.com/gramineproject/gramine/files/10423337/Steps_to_reproduce.txt)

### Actual results

warning: Unknown or illegal instruction executed at 0x4178f4
[P1:T1:sandstone] debug: Illegal instruction during app execution at 0x4178f4; delivering to app

### Gramine commit hash

e73da5e2a0b77c5ea88585bb52a75b9d4e65c55b

**Comment by dimakuv** [comment]
I'm working on it.
