### ISSUE TITLE
Gramine-sgx-gen-private-key fails when intel-tensorflow-avx512 is installed in the system

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1142]
### Description of the problem

When we install intel-tensorflow-avx512 in the system, it installs all the other dependencies, As part of its dependencies, Werkzeug-2.2.2 is installed and it requires MarkUpSafe also to be updated to 2.1.2. 

**werkzeug 2.2.2 requires MarkupSafe>=2.1.1, but you have markupsafe 2.0.1 which is incompatible.**

After MarkUpSafe is upgraded gramine-sgx-gen-private-key -f is failed with unicode error

### Steps to reproduce

1. pip3 install intel-tensorflow-avx512
2. Run gramine-sgx-gen-private-key -f

### Expected results

gramine-sgx-gen-private-key should work and we should be able to run tensorflow-avx512

### Actual results

**gramine-sgx-gen-private-key -f**
```
Traceback (most recent call last):
  File "/home/gramineperf2/gramerf_framework/gramine_install/usr/bin/gramine-sgx-gen-private-key", line 11, in <module>
    from graminelibos import sgx_sign
  File "/home/gramineperf2/gramerf_framework/gramine_install/usr/lib/python3.8/site-packages/graminelibos/__init__.py", line 18, in <module>
    from .gen_jinja_env import make_env
  File "/home/gramineperf2/gramerf_framework/gramine_install/usr/lib/python3.8/site-packages/graminelibos/gen_jinja_env.py", line 7, in <module>
    import jinja2
  File "/usr/lib/python3/dist-packages/jinja2/__init__.py", line 33, in <module>
    from jinja2.environment import Environment, Template
  File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 15, in <module>
    from jinja2 import nodes
  File "/usr/lib/python3/dist-packages/jinja2/nodes.py", line 23, in <module>
    from jinja2.utils import Markup
  File "/usr/lib/python3/dist-packages/jinja2/utils.py", line 656, in <module>
    from markupsafe import Markup, escape, soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/home/gramineperf2/.local/lib/python3.8/site-packages/markupsafe/__init__.py)
```

### Gramine commit hash

5e70d64ebf5824d13fe3517a8666705a0ed3d589

**Comment by anjalirai-intel** [comment]
The current solution is to downgrade MarkUpSafe==2.0.1 once we install intel-tensorflow-avx512

**Comment by woju** [comment]
Not our bug: you've mixed packages installed from apt with packages installed from pip. This never works. The solution if for user to also upgrade jinja from pip, but we can't force user to do it (we're installed from apt, not from pip).

**Comment by cse0001** [comment]
The fundamental issue with your question stems from a dependency management conflict between two software ecosystems. According to the error message, your 'markupsafe' was installed using 'pip' at the path `/home/gramineperf2/.local/lib/python3.8/site-packages/markupsafe/`. The 'jinja2' that depends on it was installed using 'apt' at the path `/usr/lib/python3/dist-packages/jinja2`. The versions of the two are not compatible. In fact, there is a version of 'markupsafe' in the system that 'jinja2' correctly depends on, but the Python interpreter prioritizes the 'markupsafe' installed by 'pip', leading to this issue. There are typically two solutions to this problem: (1) Use 'pip' to uninstall markupsafe, and then reinstall it using 'apt', or uninstall 'jinja2' using 'apt' and reinstall it using 'pip'. (2) Use Python's imp module to customize the path and import the 'markupsafe' from the 'apt' path before importing 'jinja2'. An example is as follows:

    import imp
    path = ['/usr/lib/python3/dist-packages']
    fp, pathname, description = imp.find_module('markupsafe', path)
    imp.load_module("markupsafe", fp, pathname, description)

I have developed an automated tool to solve problems like yours and am currently collecting real-world issues. I would really appreciate it if you could reply.
