### ISSUE TITLE
app crashed for " Failed to reserve virtual memory for CodeRange"

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#1174]
### Description of the problem

after enabled edmm, app crashed as the title.
my app is nodejs.
my gramine env is from the docker image version 1.4.

### Gramine commit hash

i don'tknow

**Comment by mccoysc** [comment]
my linux kernel version is 6.1.11

**Comment by mccoysc** [comment]
the sgx.enclave_size is omitted in template file.

**Comment by dimakuv** [comment]
> after enabled edmm, app crashed as the title.

And with EDMM disabled, the app works?

Does `gramine-direct` work?

**Comment by mccoysc** [comment]
yes,work well without edmm enabled.

**Comment by mccoysc** [comment]
> > after enabled edmm, app crashed as the title.
> 
> 
> 
> And with EDMM disabled, the app works?
> 
> 
> 
> Does `gramine-direct` work?

i never used the gramine-direct.

**Comment by dimakuv** [comment]
Could you:

1. Show the `manifest.template` file.
2. Add `loader.log_level = "all"` (and keep EDMM enabled), rebuild the app, rerun it, and attach the resulting log.

**Comment by mccoysc** [comment]
this is the working template:
```

[loader]
entrypoint = "file:{{ gramine.libos }}"
log_level = "{{ log_level }}"
insecure__use_cmdline_argv = true
python_entrypoint="{{python_entrypoint}}"

[loader.env]
LD_LIBRARY_PATH = "{{ python.stdlib }}/lib:/lib:{{ arch_libdir }}:/usr/lib:/usr{{ arch_libdir }}"


[libos]
entrypoint="{{ nodejs_dir }}/node"

# Node.js requires eventfd2() emulation otherwise fails on `(uv_loop_init(&tracing_loop_)) == (0)'
[sys]
insecure__allow_eventfd = true
[sys.stack]
size="4M"


[fs]
mounts=[
{type = "chroot",path = "{{ nodejs_dir }}",uri = "file:{{ nodejs_dir }}"},
{type = "chroot",path = "/lib",uri = "file:{{ gramine.runtimedir()}}"},
{type = "chroot",path = "{{ arch_libdir }}",uri = "file:{{ arch_libdir }}"},
{type = "chroot",path = "/etc/",uri = "file:/etc/"},
{ path = "/usr/", uri = "file:/usr/" },
{% for path in python.get_sys_path(python_entrypoint) %}
  { path = "{{ path }}", uri = "file:{{ path }}" },
{% endfor %}
{ path = "/usr/local/lib/", uri = "file:/usr/local/lib/" },
{type = "tmpfs",path = "/tmp"},
{type = "encrypted",path="/encrypted/",uri = "file:encrypted",key_name = "_sgx_mrenclave"}
]

[sgx]
edmm_enable=true
remote_attestation = "none"
nonpie_binary = true
enclave_size = "4G"
max_threads = 64
isvprodid = 0
isvsvn = 0
debug = true
require_avx = false
require_avx512 = false
require_mpx = false
require_pkru = false
require_amx = false
support_exinfo = false
enable_stats = false
require_exinfo = true

trusted_files=[
{% for path in python.get_sys_path(python_entrypoint) %}
  "file:{{ path }}/",
{% endfor %}
"file:{{ nodejs_dir }}/",
"file:{{ gramine.runtimedir()}}/",
"file:{{ gramine.libos }}",
"file:{{ arch_libdir }}/",
"file:/usr/{{ arch_libdir }}/",

"file:/usr/local/lib/",
"file:/etc/mime.types",
"file:start.js",
"file:node_modules/"
]

allowed_files=[
"file:py_executor.py",
"file:main.js",
"file:mqttConfig.json",
"file:worker_processor_runfilescript.js",
"file:worker_processor_runsql.js",
"file:worker_processor_runpy.js",
"file:worker_processor_runevtcode.js",
"file:work_pool.js",
"file:numjs.min.js",
"file:client_pub.json",
"file:data/",
"file:/etc/",
"file:/etc/nsswitch.conf",
"file:/etc/ethers",
"file:/etc/hosts",
"file:/etc/group",
"file:/etc/passwd",
"file:/etc/gai.conf",
"file:/etc/host.conf",
"file:/etc/resolv.conf",
]

```

**Comment by mccoysc** [comment]
if i ommit the "enclave_size"，the would crash as title.

**Comment by dimakuv** [comment]
> if the "enclave_size" ommited,the app would crash as title.

Ok, now I don't understand you. So if `sgx.enclave_size = "4G"`, then everything works fine, even with EDMM enabled?

**Comment by mccoysc** [comment]
> > if the "enclave_size" ommited,the app would crash as title.
> 
> 
> 
> Ok, now I don't understand you. So if `sgx.enclave_size = "4G"`, then everything works fine, even with EDMM enabled?

yes,only "enclave_size" omitted and edmm enabled,app would crash

**Comment by dimakuv** [comment]
Ah, this is expected. The enclave size still must be specified (in case of EDMM, this size serves as the maximum limit).

So because you didn't specify the enclave size, it was by default set to `256M`, which is not enough to run Node.JS.

**Comment by monavij** [comment]
We should fix the documentation and mention this clearly in EDMM enabling section and say that enclave size must be specified and it serves as the maximum limit. We have this in enclave size section, but it's a bit confusing.

**Comment by dimakuv** [comment]
@monavij Fair enough, done in https://github.com/gramineproject/gramine/pull/1178
