### ISSUE TITLE
lazy vertification needed

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#1177]
### Description of the feature

verifying trusted file cost too much time.
if it can be done before being used?(i don't know if this is the gramine code's way now)

### Why Gramine should implement it?

as description

**Comment by dimakuv** [comment]
> if it can be done before being used?(i don't know if this is the gramine code's way now)

Yes, this is already how it's done -- lazy verification.

Trusted files are verified **upon the first file open**. If the trusted file is never used by the application, there is not verification and thus no performance overhead.
