### ISSUE TITLE
python 3.11 or higher needed

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#1179]
### Description of the feature

now the default python version in gramine docker image is 3.8.
for performance reasons and some bugfixs(python 3.8 bug report has not been  accepted),3.11 or higher python version needed.

### Why Gramine should implement it?

as the title

**Comment by dimakuv** [comment]
@mccoysc Python version 3.8 is the default for Ubuntu 20.04.

Is there any particular reason to update to Python 3.11 or higher? I don't see a reason...

In general, you can always start with our default Gramine Docker image and then update it to have Python 3.11. I see no reason to do some magic actions in the Docker image -- it should be minimal and straight-forward.

**Comment by mccoysc** [comment]
> @mccoysc Python version 3.8 is the default for Ubuntu 20.04.
> 
> 
> 
> Is there any particular reason to update to Python 3.11 or higher? I don't see a reason...
> 
> 
> 
> In general, you can always start with our default Gramine Docker image and then update it to have Python 3.11. I see no reason to do some magic actions in the Docker image -- it should be minimal and straight-forward.

for example,using node-calls-python with libpython3.8.so in nodejs would get app crashed(which work well in non-gramine env.).
i want to report the python bug to offical python github but then do not accept bug report for version 3.8.

**Comment by dimakuv** [comment]
@mccoysc Interesting. We'd be interested in reading this bug report once you publish it.

But as mentioned -- I don't want to overcomplicate the official Gramine Docker image. If needed, please update the Python version yourself.

**Comment by mccoysc** [comment]
> @mccoysc Interesting. We'd be interested in reading this bug report once you publish it.
> 
> 
> 
> But as mentioned -- I don't want to overcomplicate the official Gramine Docker image. If needed, please update the Python version yourself.

and,i think,maybe,this is gramine's bug(work well in normal linux but crashed for access null pointer in gramine).
you can reproduce the bug in nodejs with node-calls-python

**Comment by mccoysc** [comment]
@dimakuv
