### ISSUE TITLE
multiple definition of `abort` function in tools/sgx/common/util.c and glibc

### ISSUE THREAD

**Issue by IceCY** [gramineproject/gramine#1182]
### Description of the problem

 A function named `abort` is defined in tools/sgx/common/util.c and included into `libra_tls_verify_dcap.so` after compilation. The function is exported and conflicts with the `abort` function in `libc.so`. That means which `abort` function would be invoked by application at runtime depends on which dynamic library is loaded firstly with no warning/error information. Since the implementations of two functions are different, I thought that may be problematic while using `libra_tls_verify_dcap.so` in applications.

### Steps to reproduce

Firstly, compile the project from the source code.
``` 
meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled -Ddcap=enabled
cd build
ninja tools/sgx/ra-tls/libra_tls_verify_dcap.so
```
After compilation. Suppose we are at still at the `build` directory
``` bash
cd tools/sgx/ra-tls
nm libra_tls_verify_dcap.so | grep abort
```

### Expected results

Then we could see `abort` function is included and exported. 
```
000000000001d3b0 T abort
......
```

### Gramine commit hash

aefd5d0875c4fdf76edd67f5043952bdd32b0f7a

**Comment by dimakuv** [comment]
Yes, I just checked and you're correct. This is a bug, we'll need to sort out the header includes...

**Comment by mkow** [comment]
It's not about the header, but linking visibility. I think it shouldn't be exported from `libra_tls_verify_dcap.so`, it most likely got there by an accident.

**Comment by dimakuv** [comment]
I fixed this bug as part of this PR: https://github.com/gramineproject/gramine/pull/1114

Now the symbol is local, just like @mkow proposed:
```
$ nm libra_tls_verify_dcap.so | grep abort
0000000000051233 t abort
```
