### ISSUE TITLE
Unable to build gramine successfully on Ubuntu 22.04 without prefix option

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1201]
### Description of the problem

When you try to build Gramine from sources in a fresh 22.04 system and you don’t specify the prefix, Graminelibos library is not installed in correct path. Graminelibos should install in **/usr/local/lib/python3.10/dist-packages/graminelibos** but instead of that it is getting installed in **/usr/local/graminelibos.** 

**Ubuntu 20.04:**
```
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_20.04_6.0/gramine/build/python/graminelibos/__init__.py to /usr/local/lib/python3.8/dist-packages/graminelibos
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_20.04_6.0/gramine/python/graminelibos/gen_jinja_env.py to /usr/local/lib/python3.8/dist-packages/graminelibos
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_20.04_6.0/gramine/python/graminelibos/manifest.py to /usr/local/lib/python3.8/dist-packages/graminelibos

```
**Ubuntu 22.04:**
```
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_22.04_6.0.9/gramine/build/python/graminelibos/__init__.py to /usr/local/graminelibos
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_22.04_6.0.9/gramine/python/graminelibos/gen_jinja_env.py to /usr/local/graminelibos
Installing /home/intel/jenkins/workspace/local_ci_graphene_sgx_22.04_6.0.9/gramine/python/graminelibos/manifest.py to /usr/local/graminelibos
```

**_Because graminelibos is not correctly installed, gramine-sgx-gen-private-key results in ModuleNotFoundError: No module named 'graminelibos'_**

### Steps to reproduce

Build Gramine from source 
1. meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled
2. ninja -C build/
3. sudo ninja -C build/ install
4. gramine-sgx-gen-private-key

### Expected results

Graminelibos should be installed in correct path and gramine-sgx-gen-priavte-key or gramine python libraries should be working

### Actual results

Currently, it fails with **ModuleNotFoundError: No module named 'graminelibos'**

Logs attached
[Ubuntu_22_04_ninja_install_log.txt](https://github.com/gramineproject/gramine/files/10836743/Ubuntu_22_04_ninja_install_log.txt)
[Ubuntu_20_04_ninja_install_log.txt](https://github.com/gramineproject/gramine/files/10836744/Ubuntu_20_04_ninja_install_log.txt)

### Gramine commit hash

37cd3068493ee9b064b1845d1c0bbc55080aa6fe

**Comment by dimakuv** [comment]
@woju There is indeed such problem, we looked at it with @anjalirai-intel together.

I don't understand what causes this problem. Looks like some Python3 auto-finding magic that you have in our Meson doesn't work on Ubuntu 22.04.

**Comment by woju** [comment]
#1203 is WIP (currently only the reproducer for CI)

**Comment by woju** [comment]
@anjalirai-intel @dimakuv: please test #1203, it's ready for review

**Comment by anjalirai-intel** [comment]
@woju, 

We tested the #1203 across different distributions **(Ubuntu 18.04, Ubuntu 20.04, Ubuntu 22.04, Centos 8, Debian 11 and RHEL)** and the build was successful

**Comment by woju** [comment]
> and the build was successful with both prefix and without prefix option

Thanks, that's what I hoped to hear.
