### ISSUE TITLE
Error while secret provisioning RA

### ISSUE THREAD

**Issue by arkish** [gramineproject/gramine#1202]
Followed documentation and started secret provisioning server. Then executed `gramine-sgx ./pytorch pytorchexample.py` from the client.

The output from client side:
```
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - loader.insecure__use_host_env = true       (forwarding environment vars from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

secret_provision_start: Secret Provisioning failed during mbedtls_x509_crt_parse_file with error -15872
secret_provision_common_close: Secret Provisioning failed during connection close with mbedTLS error -28928
WARNING: Closing the secret-prov context failed with error -1.
secret_provision_constructor: Secret provisioning failed, terminating the whole process
```
Output from server side after executing the above command:
```
--- Reading the master key for encrypted files from 'wrap_key' ---
--- Starting the Secret Provisioning server on port 4433 ---
client_connection: Secret Provisioning failed during mbedtls_ssl_handshake with error -29312
```

Any suggestions on how to resolve this?

**Comment by dimakuv** [comment]
@arkish How is this different from https://github.com/gramineproject/gramine/issues/1200?

**Comment by arkish** [comment]
In #1200 I was getting `secret_provision_start: Secret Provisioning failed during mbedtls_x509_crt_parse_file with error -15872` from the server. I then added the ssl folder to the parent directory and I was able to start the server. 
Now I seem to get the above error from the client side and `client_connection: Secret Provisioning failed during mbedtls_ssl_handshake with error -29312` on the server whenever I execute `gramine-sgx ./pytorch pytorchexample.py` from the client

**Comment by dimakuv** [comment]
No, I think you're confusing. You still have the outputs from both the server and the client, intermingled in your output. I can see this line in your output:
```
secret_provision_start: Secret Provisioning failed during mbedtls_x509_crt_parse_file with error -15872
```

Which is exactly the same as in #1200.

**Comment by arkish** [comment]
Ok, yes. I'm getting the same error, but from the client. You had asked me to execute `openssl x509 -in ssl/server.crt -text -noout -certopt ext_parse` 
Here is the output:
```
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number:
            52:70:6b:22:03:d8:35:ad:13:82:02:8c:e8:81:bc:8f:f1:64:ff:4f
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: C = XX, L = XXXXX, O = My Company, OU = Department, CN = localhost, emailAddress = me@example.com
        Validity
            Not Before: Feb 23 05:13:52 2023 GMT
            Not After : Feb 18 05:13:52 2024 GMT
        Subject: C = XX, L = XXXXX, O = My Company, OU = Department, CN = localhost, emailAddress = me@example.com
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:a9:8a:e2:c7:66:bf:90:62:8f:98:00:60:e5:af:
                    74:7c:7e:f4:bd:c3:3e:3e:fb:e2:f2:47:54:37:08:
                    42:6b:80:9a:d4:b9:92:52:8a:de:2f:a8:4a:cb:0d:
                    e2:01:83:6d:d4:2e:fb:39:25:c2:f5:e4:10:b0:39:
                    e1:ec:db:83:f1:2b:33:65:b8:6d:57:b8:90:d7:26:
                    cf:81:c5:9b:16:73:22:4f:19:5f:e6:db:c2:8a:1e:
                    5e:3d:8a:8f:35:29:24:d7:06:70:eb:04:ed:c0:76:
                    94:e9:e4:25:92:b7:cf:93:ec:28:42:f3:1f:8d:38:
                    a1:66:69:bb:ed:2e:5b:24:c0:a6:ed:ed:39:99:6e:
                    4c:5d:79:10:84:53:3b:91:d1:3f:46:1a:e1:1b:1b:
                    6b:a8:31:2b:1e:52:c1:f9:56:3e:c4:7f:95:6f:55:
                    c7:4e:cc:f2:ff:fa:f1:1d:91:ed:f0:0c:23:6e:e4:
                    b3:a4:b6:fd:57:6d:23:6d:76:2b:3a:e5:ce:cb:c7:
                    a4:bb:fb:49:89:54:4d:ad:85:b9:bc:cf:d6:7f:6a:
                    06:df:87:cd:32:66:14:30:47:af:5e:6b:09:9c:8d:
                    85:90:a3:44:a9:16:69:db:c3:c3:51:21:5a:54:b4:
                    0d:1b:3e:b5:6f:1a:62:b2:6f:be:45:0e:c3:aa:47:
                    cd:f7
                Exponent: 65537 (0x10001)
    Signature Algorithm: sha256WithRSAEncryption
    Signature Value:
        4d:2a:4e:20:c4:dd:51:fc:b7:22:72:d0:1f:6b:04:57:97:17:
        dc:80:6a:57:3d:97:fe:f9:13:31:cd:d4:13:67:9f:62:ee:0d:
        d1:e6:86:0a:45:95:2f:10:f2:8c:ca:0f:34:0b:67:b4:c6:e3:
        a6:57:9c:14:42:3b:8c:38:7f:e1:23:78:1d:f9:1e:04:ae:fe:
        62:a4:a2:93:1e:5b:75:06:05:61:70:d7:64:5b:ad:10:b5:36:
        45:a2:8e:d5:0a:54:21:93:eb:95:f3:45:69:d3:ae:a6:8e:69:
        9a:b7:5f:21:26:4d:1d:51:84:0a:d5:b3:02:4f:74:6d:cf:67:
        c1:b6:ff:33:61:ed:9e:c4:da:12:9b:02:b9:67:94:11:e3:a3:
        65:15:03:e8:ec:5a:b1:17:e2:aa:3e:8d:69:ef:77:04:1c:d0:
        06:a2:f5:25:a7:7d:4b:9c:24:87:eb:8a:a1:1b:f4:22:7c:76:
        dc:af:a7:40:c0:31:3c:49:05:12:93:f7:85:8f:dd:d5:f5:84:
        ae:77:c8:45:23:cc:e1:5a:be:ac:6e:77:4a:f9:69:40:cf:f1:
        dd:cf:33:e5:b4:a2:1f:56:60:5a:1c:4d:f5:d1:13:5a:00:3f:
        67:be:99:9c:d3:d9:e2:a1:2a:e2:46:f3:77:1f:ff:83:88:38:
        1f:ee:ec:46
```
Please let me know if this helps to detect what the issue is.

**Comment by arkish** [comment]
I tried implementing it again from the beginning and now I'm getting 
```
--- Reading the master key for encrypted files from 'files/wrap_key' ---
--- Starting the Secret Provisioning server on port 4433 ---
ra_tls_verify_callback: sgx_qv_verify_quote failed: 57372
client_connection: Secret Provisioning failed during mbedtls_ssl_handshake with error -12288
``` from the server.

and
```
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - loader.insecure__use_host_env = true       (forwarding environment vars from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

secret_provision_start: Secret Provisioning failed during mbedtls_ssl_handshake with error -30592
secret_provision_constructor: Secret provisioning failed, terminating the whole process
``` from the client.

**Comment by dimakuv** [comment]
> ra_tls_verify_callback: sgx_qv_verify_quote failed: 57372

Ok, this is the important part. Your attestation flow fails at this logic: https://github.com/gramineproject/gramine/blob/1b1242f05630d461bf904a907d57b4222232b391/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L155

This means that your DCAP software infrastructure is incorrectly installed. How did you install it? Are you using the Intel SGX DCAP packages (https://download.01.org/intel-sgx/dcap-1.1/linux/docs/Intel_SGX_DCAP_ECDSA_Orientation.pdf)? If yes, are you sure you correctly set up this whole infrastructure, including the PCCS service configuration?

**Comment by arkish** [comment]
I have linux kernel version 5.19.0-32-generic. I thought dcap support is integrated within this and don't have to install separately. I'm not sure how to check if the infrastructure is working as it should

**Comment by dimakuv** [comment]
> I thought dcap support is integrated within this and don't have to install separately.

No. DCAP attestation software infrastructure must be installed and configured additionally.

The installation guide is here, but I warn you, this is a **complex thing to install & configure**: https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html

**Comment by arkish** [comment]
Is it possible to only perform encryption and decryption and run inference using `gramine-sgx ./pytorch pytorchexample.py` without attestation?
I tried doing so by following this step: https://gramine.readthedocs.io/en/latest/tutorials/pytorch/index.html#preparing-input-files and this step: https://gramine.readthedocs.io/en/latest/tutorials/pytorch/index.html#preparing-manifest-file

However I get the error below, after executing `gramine-sgx ./pytorch pytorchexample.py`:
```Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - loader.insecure__use_host_env = true       (forwarding environment vars from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Traceback (most recent call last):
  File "//pytorchexample.py", line 8, in <module>
    alexnet = torch.load("alexnet-pretrained.pt")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'alexnet-pretrained.pt'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 28, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 36, in <module>
    apt_pkg.init_system()
apt_pkg.Error: E:Error reading the CPU table

Original exception was:
Traceback (most recent call last):
  File "//pytorchexample.py", line 8, in <module>
    alexnet = torch.load("alexnet-pretrained.pt")
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 771, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 270, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 251, in __init__
    super(_open_file, self).__init__(open(name, mode))
PermissionError: [Errno 13] Permission denied: 'alexnet-pretrained.pt'

```

**Comment by dimakuv** [comment]
> However I get the error below, after executing `gramine-sgx ./pytorch pytorchexample.py`

Did you download the `alexnet-pretrained.pt` file? If yes, then you probably encrypted it with Gramine tools but didn't correctly update the manifest? Like, Gramine can't decrypt this file if Gramine wasn't provided a key (either through attestation or through `fs.insecure__keys` I mentioned above).

**Comment by arkish** [comment]
Yes, the inference works after mentioning key through `fs.insecure__keys`. Thanks.
