### ISSUE TITLE
[PAL] Memory fault when running with enclave_size > 1TB

### ISSUE THREAD

**Issue by fnerdman** [gramineproject/gramine#1207]
I'm creating an enclave with `enclave_size=2048G`. The enclave behaves normally up until the point where it (presumably) exceeds memory usage of 1TB. This however is just an assumption I made by observing that it fails around the same time an enclave with 1TB enclave size errors out with an out-of-memory exception.

```
# Gramine 1.4, edmm=true (tried 3x)
(pal_exception.c:236:_PalExceptionHandler) error: Unexpected memory fault occurred inside PAL (0x1fffd1dd553)
(pal_exception.c:243:_PalExceptionHandler) debug: (untrusted PAL sent PAL event 0x2)
(pal_process.c:248:_PalProcessExit) debug: PalProcessExit: Returning exit code 1
# Gramine 1.4, edmm=false
error: Unexpected memory fault occurred inside PAL (0x1fffd1f8e78)
# Gramine 1.3.1-1
error: Unexpected memory fault occurred inside PAL (0x1fffce2ce78)
```

**Comment by dimakuv** [comment]
Heh, we never expected anyone to run more than 1TB enclaves... @mkow ^

There are a couple assumptions in Gramine that make 1TB brittle (but I think only in debug mode):
- Debug metainfo is put at 1TB address exactly
- The AddressSanitizer shadow space is put at 1.5TB address

But both of the above happen only in debug mode of Gramine...

We'll need to debug this.

**Comment by mkow** [comment]
> We'll need to debug this.

Assuming it's not just @lead4good running it in debug mode ;) Then it would be a known limitation and nothing more to debug.

**Comment by lead4good** [comment]
@mkow The errors occurred while executing Gramine without the debug flag set.

**Comment by mkow** [comment]
But we aren't talking about the debug flag (I assume you mean `sgx.debug` manifest setting) but building in debug mode vs release mode.
Anyways, at least from my side, unfortunately I don't have access to any system where I could reproduce it, due to the required resources. So, hard to say anything more than "this for sure collides with debugging features". I'm afraid you'll need to debug it yourself.

**Comment by dimakuv** [comment]
Same on my side, no idea how to debug this... I don't have access to 2TB-RAM servers :)

**Comment by lead4good** [comment]
> but building in debug mode vs release mode.
The errors were discovered while using the official gramine release builds 1.3.1-1 and 1.4

> no idea how to debug this
If you have a 2TB swap disk this should be fairly simple. The system we have been using was one with 256GB EPC memory, 384GB total memory + 2GB swap.

In fact, you can just use [this repo](https://github.com/flashbots/geth-sgx-gramine), put a file which is > 1TB into `/root/.ethereum.synced/` and start the enclave with `COPY_DATABASE=true`. The init script will copy the file into ramfs.

**Comment by dimakuv** [comment]
> If you have a 2TB swap disk this should be fairly simple. The system we have been using was one with 256GB EPC memory, 384GB total memory + 2TB swap.

I mean... This is surely doable, but it will need a lot of patience :)

**Comment by mkow** [comment]
@lead4good: Any luck debugging this? I'm afraid it will have to be you doing this, as none of the maintainers has access to a machine which could create such a huge enclave. We have some basic hints how to debug gramine in our docs: https://gramine.readthedocs.io/en/latest/devel/debugging.html.

**Comment by monavij** [comment]
@jinengandhi-intel  Maybe something you guys should also look at testing?

**Comment by lead4good** [comment]
After seeing that no easy fix for this exists, we've decided to mitigate the issue by using max 1TB memory. There's currently no priority for this issue so we can't allocate resources to look at this for the time being.

**Comment by mkow** [comment]
@lead4good: Could you check #1826? It doesn't solve the problem, but at least prints a nicer error message :)

Regarding the problem itself: I just noticed when implementing that PR, that the debug range is actually also used in release mode (which is ok, because it's written only by the untrusted PAL). So, I guess that's the culprit? Could you try changing `DBGINFO_ADDR` to e.g. 8TB? If it fixes the problem, then we can do such a change, these hardcoded addresses are arbitrary.

**Comment by dimakuv** [comment]
> Regarding the problem itself: I just noticed when implementing that PR, that the debug range is actually also used in release mode (which is ok, because it's written only by the untrusted PAL). So, I guess that's the culprit? 

I don't think it can be the culprit: https://github.com/gramineproject/gramine/blob/0ee48eebb24c38bdad193fa9945a3b26d4a89dc6/pal/src/host/linux-sgx/host_main.c#L577-L597

Based on this code snippet, Gramine's untrusted loader tries to mmap a bit of space at 1TB address. But if this address ends up inside the SGX enclave, then this mmap will fail (as Intel SGX won't allow this). So Gramine will print `Cannot allocate debug information (GDB will not work)` and that's it, nothing bad should happen really.

**Comment by mkow** [comment]
Yup, but that's just a warning. Gramine will proceed and e.g. in case of dynamic threads will try writing to it: https://github.com/gramineproject/gramine/blob/bbc4068d3d907b72b02b2071fc1372555a7ddb88/pal/src/host/linux-sgx/host_thread.c#L171

Not sure what happens in non-EDMM case though.

**Comment by mkow** [comment]
> @lead4good: Could you check #1826? It doesn't solve the problem, but at least prints a nicer error message :)

@fnerdman: maybe you could take a look?
If this is indeed the case, then the fix should be trivial, but we'd need to know how much memory you actually need - we'll just shift these hardcoded regions further in the address space.

**Comment by fnerdman** [comment]
Sorry, we're currently exploring TDX as an alternative approach and have put working on SGX on ice
