### ISSUE TITLE
[tools/sgx] RA-TLS verification error wrapping

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#1209]
### Discussed in https://github.com/gramineproject/gramine/discussions/1208

<div type='discussions-op-text'>

<sup>Originally posted by **lonerapier** March  2, 2023</sup>
We're trying to write a Golang [wrapper](https://github.com/konvera/gramine-ratls-golang/tree/gramine-ratls-wrapper) on top of Gramine's RA-TLS verification module. While trying to show the errors to the user, we discovered that most of the SGX errors, although logged, are [abstracted](https://github.com/gramineproject/gramine/blob/master/tools/sgx/ra-tls/ra_tls_verify_dcap.c#L166-L184) in the verification function and only a few errors are reported.

What was the design decision behind this approach? What are your thoughts about returning the original error to the user so that it can be handled accordingly? Would it involve too large a change, or some other factors are involved? 

One use case of having more verbose return values is to know why the attestation verification failed, and every user might not have access to stdout/stderr for logs.

For example: we might want to handle `SGX_QL_QV_RESULT_SW_HARDENING_NEEDED` according to our use case but `MBEDTLS_ERR_X509_CERT_VERIFY_FAILED` doesn't give enough information about the error.</div>

**Comment by dimakuv** [comment]
@kailun-qin @lejunzhu @billionairiam I think this task will be a good fit for one of you.

**Comment by kailun-qin** [comment]
The proposal looks reasonable to me. @dimakuv I can take this.

**Comment by kailun-qin** [comment]
When taking a look at the impl. detail, I notice that the current `ra_tls_verify_callback_der()` public API does not take the `void*` data opaque argument at all:
https://github.com/gramineproject/gramine/blob/361dfff60161550fd9c77164f42712a795410053/tools/sgx/ra-tls/ra_tls_verify_common.c#L248

We need to keep the current RA-TLS API unaffected but we also need the callback args (via the opaque args) to be passed thru into our RA-TLS callback. @dimakuv Is this sth. you expected? WDYT?

**Comment by dimakuv** [comment]
@kailun-qin Yes, I see the problem. The RA-TLS API is like this: https://github.com/gramineproject/gramine/blob/361dfff60161550fd9c77164f42712a795410053/tools/sgx/ra-tls/ra_tls.h#L64

So there is no "spare argument" where we could cram my proposed `struct ra_tls_verify_callback_args` object.

I can see two solutions here:
1. Do **not** change the function signature and instead introduce a global variable `g_verify_callback_args` in RA-TLS.
    - This will be kinda similar to how `errno` works in Glibc (a global variable that must be zeroed out before the call and read right-after the call).
    - This is clearly ugly and not thread-safe...
2. Introduce **a new** function like: `int ra_tls_verify_callback_extended_der(uint8_t* der_crt, size_t der_crt_size, struct ra_tls_verify_callback_args args)`.
    - The old func (`ra_tls_verify_callback_der()`) will still be available for backwards compatibility, and it will simply be a wrapper around `ra_tls_verify_callback_extended_der(der_crt, der_crt_size, NULL)`.
    - This should be a pretty harmless addition to RA-TLS API.

I like solution 2. If we'll decide to ignore backward compatibility problem, then it will be easy to change solution 2 to change "add a new argument to the existing func" during PR discussions.

**Comment by kailun-qin** [comment]
> I like solution 2. If we'll decide to ignore backward compatibility problem, then it will be easy to change solution 2 to change "add a new argument to the existing func" during PR discussions.

Yes, agree. Made a quick draft following solution 2 - let's discuss the details there.
