### ISSUE TITLE
[Tracking] Support for Hashicorp Vault

### ISSUE THREAD

**Issue by svenkata9** [gramineproject/gramine#1216]
[There is no issue in Gramine at present; This issue is filed only for tracking purposes]

The issue is with building Hashicorp Vault source as a dynamically linked binary instead of a statically linked library which comes by default.

Vault source code present at https://github.com/hashicorp/vault was previously using gox for building the binary. That did not support dynamically linked binary. Over the second half of last year vault scripts were updated to use `go` directly, but by default the binary is built as statically linked. As we know, this binary has inline syscalls that degrades performance while running in Gramine.

When I tried to introduce `--linkshared` option there are three dependent ingredients that fail to link properly. There are issues discussed in GitHub and other forums, but I couldn't find any resolution for those.

I also tried to build a `hello` binary with `--linkshared` and that builds and works without issues.

```
root@gramine-sgx:/home/svenkat9/vault/vault1# make dev
==> Checking that build is using go version >= 1.20...
==> Using go version 1.20.1...
==> Removing old directory...
==> Building...
# github.com/cespare/xxhash/v2
asm: xxhash_amd64.s:120: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00092 (/home/svenkat9/go/pkg/mod/github.com/cespare/xxhash/v2@v2.1.1/xxhash_amd64.s:120)  ADDQ    R15, AX
asm: assembly failed
# github.com/cloudflare/circl/math/fp25519
asm: fp_amd64.s:68: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00215 (/home/svenkat9/go/pkg/mod/github.com/cloudflare/circl@v1.1.0/math/fp25519/fp_amd64.s:68)        MULXQ    24(SI), AX, R15
asm: assembly failed
# github.com/cloudflare/circl/math/fp448
asm: fp_amd64.s:68: when dynamic linking, R15 is clobbered by a global variable access and is used here: 00350 (/home/svenkat9/go/pkg/mod/github.com/cloudflare/circl@v1.1.0/math/fp448/fp_amd64.s:68)  MULXQ   48(SI), AX, R15
asm: assembly failed
Makefile:36: recipe for target 'dev' failed
make: *** [dev] Error 1
```

![image](https://user-images.githubusercontent.com/29835993/223330906-5ea986c6-33f7-42b8-a1e8-8b141b38eab4.png)

**Comment by kailun-qin** [comment]
> github.com/cespare/xxhash/v2

For `xxhash`, pls consider update it to v2.1.2+(https://github.com/cespare/xxhash/releases/tag/v2.1.2) as a fix had been introduced since then (see https://github.com/cespare/xxhash/issues/54 for details).

> github.com/cloudflare/circl/math/fp25519
> github.com/cloudflare/circl/math/fp448

For `circl`, pls consider try its latest main branch. A fix addressing the issue has been introduced recently (https://github.com/cloudflare/circl/pull/407, https://github.com/cloudflare/circl/issues/391).

**Comment by svenkata9** [comment]
Thanks, Kailun. Updating with your suggestions made that build error go away, but landed in another error related to azure go sdk.

```
# github.com/hashicorp/vault
2023/03/07 13:53:12 duplicated definition of symbol github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime.(*Poller[go.shape.struct { github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4.VirtualMachineAssessPatchesResult }]).PollUntilDone.func1, from github.com/Azure/azure-sdk-for-go/sdk/resourcemanager/compute/armcompute/v4 and github.com/hashicorp/vault-plugin-auth-azure
Makefile:36: recipe for target 'dev' failed
```

**Comment by dimakuv** [comment]
I don't know how to fix the latest build error (maybe some googling will help?).

But it looks like slowly but steadily Golang itself and its popular libraries/modules are embracing the "dynamic linking" world. This is very good news for Gramine :)

> Why?: The main reason is that Go compiler uses R15 to access to global variables, so it alters its value (do not restore it).
> [ taken from https://github.com/cloudflare/circl/pull/407 ]

Go is full of such ad-hoc tricks...

**Comment by svenkata9** [comment]
Yeah. I tried updating some modules in azure-sdk-for-go to their latest, but that ends up in other issues.

**Comment by kailun-qin** [comment]
> I tried updating some modules in azure-sdk-for-go to their latest, but that ends up in other issues.

The latest related modules do not resolve the issue. A more straightforward one is to disable azure plugin in building, however it's a built-in vault plugin which IDK how to make it...

**Comment by svenkata9** [comment]
The hashicorp dependencies that I encountered for building a dynamically linked binary are (possibly) resolved now, but there are errors internal to vault source that prevents the shared object build. I raised a GitHub issue with vault yesterday, and they closed saying it won't be supported.

[Error building with `-linkshared` flag · Issue #22228 · hashicorp/vault (github.com)](https://github.com/hashicorp/vault/issues/22228#issuecomment-1670101107)

**Comment by dimakuv** [comment]
Not sure what to do with this GitHub issue. Does anyone want to re-test support for Hashicorp Vault and report on the results? Maybe it's fully supported by now.

**Comment by mkow** [comment]
This should be closed, as it doesn't represent any concrete issue with Gramine and there's nothing to do on our side. If you find some specific problems with Vault then please file separate issues for each.
