### ISSUE TITLE
Getting DeprecationWarning for gramine-sgx-get-token on Ubuntu 20.04 & 22.04 (upstream SGX driver) and not on Ubuntu18.04/Cent/RHEL

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1220]
### Description of the problem
Label: bug
Priority: P1

On Ubuntu 20.04 and 22.04 we are getting DeprecationWarning for gramine-sgx-get-token whereas we don't see this error on Ubuntu 18.04, CentOS and RHEL systems

### Steps to reproduce

Run Pal layer tests
gramine-test --sgx build -v

### Expected results

No DeprecationWarning for gramine-sgx-get-token should be reported.
[96/96] gramine-sgx-get-token --quiet --sig AttestationReport.sig --output AttestationReport.token
[ubuntu_1804_token.log](https://github.com/gramineproject/gramine/files/10921670/ubuntu_1804_token.log)

### Actual results

[96/96] gramine-sgx-get-token --quiet --sig AttestationReport.sig --output AttestationReport.token
/home/intel/gramine_install/usr/bin/gramine-sgx-get-token:17: DeprecationWarning: gramine-sgx-get-token is deprecated on upstream SGX driver, and calling it will be a hard error in the future
  warnings.warn(
[ubuntu_2204_token.log](https://github.com/gramineproject/gramine/files/10921666/ubuntu_2204_token.log)

### Gramine commit hash

26f36c47d178e178889ffcd20ada29593272605f

**Comment by kailun-qin** [comment]
Excuse me that I don't quite get the issue here.

> On Ubuntu 20.04 and 22.04 we are getting DeprecationWarning for gramine-sgx-get-token whereas we don't see this error on Ubuntu 18.04, CentOS and RHEL systems

It looks reasonable for distros using upstream/DCAP driver since we've merged https://github.com/gramineproject/gramine/commit/e73da5e2a0b77c5ea88585bb52a75b9d4e65c55b and also documented the reason and the planned deprecation here:
https://github.com/gramineproject/gramine/blob/26f36c47d178e178889ffcd20ada29593272605f/Documentation/manpages/gramine-sgx-get-token.rst?plain=1#L20-L24.

Anything I may've missed here?

**Comment by jinengandhi-intel** [comment]
@kailun-qin the issue we have raised here is with respect to the deprecation warning seen on some distros and not seen on others. Ubuntu 18/Cent/RHEL don't seem to be printing this msg whereas Ubuntu20/22 are printing, when all systems have upstream driver installed.

**Comment by kailun-qin** [comment]
> when all systems have upstream driver installed.

OK, I see - this is the point. Then the expected results described in the issue are a bit misleading:
> Expected results
No DeprecationWarning for gramine-sgx-get-token should be reported.
[96/96] gramine-sgx-get-token --quiet --sig AttestationReport.sig --output AttestationReport.token

We should instead expect deprecation warnings, right?

Back to the issue itself, which SGX driver (`-Dsgx_driver`) are you building Gramine with? Would you pls kindly check the value of `CONFIG_SGX_DRIVER_xxx` in `_graminelibos_offsets.py` and `host_sgx_driver.h` generated in your build directory? Thanks!

**Comment by anjalirai-intel** [comment]
@kailun-qin We don't expect deprecation warnings. As per our understanding, token should be automatically handled by gramine-sgx, and when we are not making explicit calls to gramine-sgx-get-token, then we should also not get warning.

We are building with upstream driver, we don't specify specifically -Dsgx_driver.

I will check the value of CONFIG__SGX_DRIVER_xxx and get back to you

**Comment by anjalirai-intel** [comment]
In host_sgx_driver.h it is **#define CONFIG_SGX_DRIVER_UPSTREAM**

**Comment by dimakuv** [comment]
I marked it as `bug` and `P:3` because it's very much irrelevant to end users.

**Comment by mkow** [comment]
I'm closing this issue, it would be nice if someone fixed it but it's not part of the final product which is shipped to the users, so it's not too relevant.
Also, as Dmitrii said, when doing this change we decided that we don't know any simple way to fix it and it's not too annoying for us.
