### ISSUE TITLE
SSL handshake exception in .NET application

### ISSUE THREAD

**Issue by marcelamelara** [gramineproject/gramine#1234]
### Description of the problem

I've been trying to get a .NET web client application running with gramine-direct, but the application throws an exception during the SSL handshake. The application runs normally on bare-metal Ubuntu 22.04, and I have also sanity-checked network connectivity with the web server using curl inside of Gramine.

Based on my application's logs, I've been able to narrow down the exception to the `Interop.Crypto.X509StoreSetVerifyTime(SafeX509StoreHandle ctx, DateTime verifyTime)` call in the .NET `System.Net.Http.ConnectHelper.EstablishSslConnectionAsync` function of the application. 

But I haven't been able to pinpoint the cause of the exception in the Gramine logs. Hoping you can see something I can't.

A few more notes: 
* I did not write this application, but am choosing not to disclose the exact application for IP reasons. 
* I am running the application on top of #1166 as this was the only way to even get the client to run.
* My machine is running behind a network proxy, so I am passing the proxy environment vars into Gramine
* The version of TLS used by the web server is 1.2

I've attached a truncated Gramine log:
[gramine-direct-trunc.log.gz](https://github.com/gramineproject/gramine/files/10985511/gramine-direct-trunc.log.gz)

### Steps to reproduce

Gramine build: I built from source on #1166 rebased on the current main branch. 
OS: Ubuntu 22.04 with 5.19.0-32-generic
Arch: x86_64 (Intel 10th gen i7)

I've attached my Gramine manifest.
[app.manifest.txt](https://github.com/gramineproject/gramine/files/10985410/app.manifest.txt)

### Expected results

An HTTPS connection to the target web server can be established.

### Actual results

Exception trace attached. This was collected within Gramine.
[app.log](https://github.com/gramineproject/gramine/files/10985467/app.log)

### Gramine commit hash

634d0392c3ace

**Comment by marcelamelara** [comment]
PTAL @monavij @dimakuv

**Comment by monavij** [comment]
Just to be sure. Does this app run fine without Gramine?

**Comment by kailun-qin** [comment]
Hi @marcelamelara, would you pls kindly take a look at https://github.com/gramineproject/gramine/issues/466 and try some of the proposed workarounds there? I suspect the exception from `Interop.Crypto.X509StoreSetVerifyTime(SafeX509StoreHandle ctx, DateTime verifyTime)` might be related to the timezone setting. Thanks!

**Comment by dimakuv** [comment]
@marcelamelara I looked at the logs and the manifest file, and I don't see anything special.

By the way, the Gramine commit is shown as `a9cd0d98e0cc15b3521ef9c57e70cb0d47f0971f` in the log. I couldn't find this commit in Gramine's master branch and in commits from #1166. Did you play with Gramine commits?

**Comment by marcelamelara** [comment]
Thank you @monavij @kailun-qin @dimakuv for your prompt replies!

Yes, the app works as expected outside Gramine on bare-metal Ubuntu. The commits likely look different because I rebased the PR branch onto the master branch, I should have been more explicit about in my problem description.

I will go take a look at #466, and let you know!

**Comment by marcelamelara** [comment]
The workaround from #466 that ended up working for me was to copy the `/etc/localtime` file into `/usr/local/etc`, so thank you @kailun-qin for that pointer! 

I do hope the solutions described in both #466 and #1166 can be merged into main soon, as I'm sure those would be very helpful to others as well :)

**Comment by dimakuv** [comment]
Great, thanks @marcelamelara for checking this!
