### ISSUE TITLE
examples/pytorch# gramine-direct ./pytorch ./pytorchexample.py [P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)

### ISSUE THREAD

**Issue by bai18331272258** [gramineproject/gramine#1251]
### Description of the problem

root@bai-OptiPlex-5080:/home/bai/examples/pytorch# gramine-direct ./pytorch ./pytorchexample                  .py
[P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)

### Steps to reproduce

I followed the tutorial to install gramine environment. When I run the pytorch program,the compiler displays this error. [P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT).   Look forward to your help

### Actual results

root@bai-OptiPlex-5080:/home/bai/examples/pytorch# make SGX=1
gramine-manifest \
        -Dlog_level=error \
        -Dpillow_path=/root/anaconda3/lib/python3.9/site-packages/ \
        -Darch_libdir=/lib/x86_64-linux-gnu \
        -Dentrypoint=/root/anaconda3/bin/python3.9 \
        pytorch.manifest.template > pytorch.manifest
gramine-sgx-sign \
        --manifest pytorch.manifest \
        --output pytorch.manifest.sgx
Attributes:
    size:        0x100000000
    edmm:        False
    max_threads: 32
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0x4
    attr.xfrm:   0x3
    misc_select: 0x0
SGX remote attestation:
    None
Memory:
    00000001feab7000-0000000200000000 [REG:R--] (manifest) measured
    00000001fe9b7000-00000001feab7000 [REG:RW-] (ssa) measured
    00000001fe997000-00000001fe9b7000 [TCS:---] (tcs) measured
    00000001fe977000-00000001fe997000 [REG:RW-] (tls) measured
    00000001fe937000-00000001fe977000 [REG:RW-] (stack) measured
    00000001fe8f7000-00000001fe937000 [REG:RW-] (stack) measured
    00000001fe8b7000-00000001fe8f7000 [REG:RW-] (stack) measured
    00000001fe877000-00000001fe8b7000 [REG:RW-] (stack) measured
    00000001fe837000-00000001fe877000 [REG:RW-] (stack) measured
    00000001fe7f7000-00000001fe837000 [REG:RW-] (stack) measured
    00000001fe7b7000-00000001fe7f7000 [REG:RW-] (stack) measured
    00000001fe777000-00000001fe7b7000 [REG:RW-] (stack) measured
    00000001fe737000-00000001fe777000 [REG:RW-] (stack) measured
    00000001fe6f7000-00000001fe737000 [REG:RW-] (stack) measured
    00000001fe6b7000-00000001fe6f7000 [REG:RW-] (stack) measured
    00000001fe677000-00000001fe6b7000 [REG:RW-] (stack) measured
    00000001fe637000-00000001fe677000 [REG:RW-] (stack) measured
    00000001fe5f7000-00000001fe637000 [REG:RW-] (stack) measured
    00000001fe5b7000-00000001fe5f7000 [REG:RW-] (stack) measured
    00000001fe577000-00000001fe5b7000 [REG:RW-] (stack) measured
    00000001fe537000-00000001fe577000 [REG:RW-] (stack) measured
    00000001fe4f7000-00000001fe537000 [REG:RW-] (stack) measured
    00000001fe4b7000-00000001fe4f7000 [REG:RW-] (stack) measured
    00000001fe477000-00000001fe4b7000 [REG:RW-] (stack) measured
    00000001fe437000-00000001fe477000 [REG:RW-] (stack) measured
    00000001fe3f7000-00000001fe437000 [REG:RW-] (stack) measured
    00000001fe3b7000-00000001fe3f7000 [REG:RW-] (stack) measured
    00000001fe377000-00000001fe3b7000 [REG:RW-] (stack) measured
    00000001fe337000-00000001fe377000 [REG:RW-] (stack) measured
    00000001fe2f7000-00000001fe337000 [REG:RW-] (stack) measured
    00000001fe2b7000-00000001fe2f7000 [REG:RW-] (stack) measured
    00000001fe277000-00000001fe2b7000 [REG:RW-] (stack) measured
    00000001fe237000-00000001fe277000 [REG:RW-] (stack) measured
    00000001fe1f7000-00000001fe237000 [REG:RW-] (stack) measured
    00000001fe1b7000-00000001fe1f7000 [REG:RW-] (stack) measured
    00000001fe177000-00000001fe1b7000 [REG:RW-] (stack) measured
    00000001fe167000-00000001fe177000 [REG:RW-] (sig_stack) measured
    00000001fe157000-00000001fe167000 [REG:RW-] (sig_stack) measured
    00000001fe147000-00000001fe157000 [REG:RW-] (sig_stack) measured
    00000001fe137000-00000001fe147000 [REG:RW-] (sig_stack) measured
    00000001fe127000-00000001fe137000 [REG:RW-] (sig_stack) measured
    00000001fe117000-00000001fe127000 [REG:RW-] (sig_stack) measured
    00000001fe107000-00000001fe117000 [REG:RW-] (sig_stack) measured
    00000001fe0f7000-00000001fe107000 [REG:RW-] (sig_stack) measured
    00000001fe0e7000-00000001fe0f7000 [REG:RW-] (sig_stack) measured
    00000001fe0d7000-00000001fe0e7000 [REG:RW-] (sig_stack) measured
    00000001fe0c7000-00000001fe0d7000 [REG:RW-] (sig_stack) measured
    00000001fe0b7000-00000001fe0c7000 [REG:RW-] (sig_stack) measured
    00000001fe0a7000-00000001fe0b7000 [REG:RW-] (sig_stack) measured
    00000001fe097000-00000001fe0a7000 [REG:RW-] (sig_stack) measured
    00000001fe087000-00000001fe097000 [REG:RW-] (sig_stack) measured
    00000001fe077000-00000001fe087000 [REG:RW-] (sig_stack) measured
    00000001fe067000-00000001fe077000 [REG:RW-] (sig_stack) measured
    00000001fe057000-00000001fe067000 [REG:RW-] (sig_stack) measured
    00000001fe047000-00000001fe057000 [REG:RW-] (sig_stack) measured
    00000001fe037000-00000001fe047000 [REG:RW-] (sig_stack) measured
    00000001fe027000-00000001fe037000 [REG:RW-] (sig_stack) measured
    00000001fe017000-00000001fe027000 [REG:RW-] (sig_stack) measured
    00000001fe007000-00000001fe017000 [REG:RW-] (sig_stack) measured
    00000001fdff7000-00000001fe007000 [REG:RW-] (sig_stack) measured
    00000001fdfe7000-00000001fdff7000 [REG:RW-] (sig_stack) measured
    00000001fdfd7000-00000001fdfe7000 [REG:RW-] (sig_stack) measured
    00000001fdfc7000-00000001fdfd7000 [REG:RW-] (sig_stack) measured
    00000001fdfb7000-00000001fdfc7000 [REG:RW-] (sig_stack) measured
    00000001fdfa7000-00000001fdfb7000 [REG:RW-] (sig_stack) measured
    00000001fdf97000-00000001fdfa7000 [REG:RW-] (sig_stack) measured
    00000001fdf87000-00000001fdf97000 [REG:RW-] (sig_stack) measured
    00000001fdf77000-00000001fdf87000 [REG:RW-] (sig_stack) measured
    00000001fdf20000-00000001fdf6d000 [REG:R-X] (code) measured
    00000001fdf6d000-00000001fdf77000 [REG:RW-] (data) measured
    0000000100000000-00000001fdf20000 [REG:RWX] (free)
Measurement:
    42df376501b68d1e2eef8911f84a3ff40fd5c51d1a7ba0ac47fa7c765268a4a1
root@bai-OptiPlex-5080:/home/bai/examples/pytorch# gramine-direct ./pytorch ./pytorchexample                  .py
[P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)

### Gramine commit hash

The gramine version is v1.4

**Comment by oshogbo** [comment]
What manifest file do you use?

**Comment by kailun-qin** [comment]
Hi @bai18331272258, thanks for your report!

> [P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)

It seems that the executable/binary (`pytorch` in your case) is not found in Gramine. Basically, you'll need to expose the `pytorch` executable/binary to Gramine via e.g., `fs.mounts` and `sgx.trusted_files`, as well as setting it as the `libos.entrypoint` in your manifest file.

Would you pls give another check or share us with your manifest file if it still not works? Thanks!

**Comment by dimakuv** [comment]
> I followed the tutorial to install gramine environment.

If I remember correctly, the tutorial assumes that you install PyTorch system-wide, with root permissions (i.e., via `sudo pip3 install`). But looks like you're using Anaconda virtual environment. Thus, you'll need to modify the manifest template of Gramine accordingly, so that Gramine finds the correct paths/executables; basically, as @kailun-qin mentioned.

**Comment by bai18331272258** [comment]
> Hi @bai18331272258, thanks for your report!
> 
> > [P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)
> 
> It seems that the executable/binary (`pytorch` in your case) is not found in Gramine. Basically, you'll need to expose the `pytorch` executable/binary to Gramine via e.g., `fs.mounts` and `sgx.trusted_files`, as well as setting it as the `libos.entrypoint` in your manifest file.
> 
> Would you pls give another check or share us with your manifest file if it still not works? Thanks!

Thanks for your reply!
My "pytorch.manifest.template" file is as follows:  (This configuration file is from "https://github.com/gramineproject/examples.git" and I didn't change it.)

# PyTorch manifest template
loader.entrypoint = "file:{{ gramine.libos }}"
libos.entrypoint = "{{ entrypoint }}"

loader.log_level = "{{ log_level }}"

loader.env.LD_LIBRARY_PATH = "/lib:/usr/lib:{{ arch_libdir }}:/usr/{{ arch_libdir }}"

# Restrict the maximum number of threads to prevent insufficient memory
# issue, observed on CentOS/RHEL.
loader.env.OMP_NUM_THREADS = "8"

loader.insecure__use_cmdline_argv = true
loader.insecure__use_host_env = true

loader.pal_internal_mem_size = "128M"

fs.mounts = [
  { uri = "file:{{ gramine.runtimedir() }}", path = "/lib" },
  { uri = "file:{{ arch_libdir }}", path = "{{ arch_libdir }}" },
  { uri = "file:/usr", path = "/usr" },
  { uri = "file:/etc", path = "/etc" },
  { uri = "file:{{ pillow_path }}", path = "{{ pillow_path }}" },

  { type = "tmpfs", path = "/tmp" },
]

# PyTorch loads its pre-trained models from here
# Add below uncommented line to fs.mounts array if you want to use torchvision.model.alexnet(pretrained=True)
# { type = "chroot", uri = "file:{{ env.HOME }}/.cache/torch", path = "{{ env.HOME }}/.cache/torch" }

sgx.enclave_size = "4G"
sgx.max_threads = 32
sgx.edmm_enable = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}

sgx.trusted_files = [
  "file:{{ gramine.libos }}",
  "file:{{ entrypoint }}",
  "file:{{ gramine.runtimedir() }}/",
  "file:{{ arch_libdir }}/",
  "file:/usr/{{ arch_libdir }}/",
  "file:{{ python.stdlib }}/",
  "file:{{ python.distlib }}/",
  "file:{{ pillow_path }}",
  "file:{{ python.get_path('stdlib', vars={'installed_base': '/usr/local'}) }}/",

  "file:pytorchexample.py",

  "file:classes.txt",
  "file:input.jpg",
  "file:alexnet-pretrained.pt",  # Pre-trained model saved as a file

  # Uncomment line below if you want to use torchvision.model.alexnet(pretrained=True)
  # "file:{{ env.HOME }}/.cache/torch/checkpoints/alexnet-owt-4df8aa71.pth",
]

sgx.allowed_files = [
  "file:result.txt",
]

**Comment by bai18331272258** [comment]
> > I followed the tutorial to install gramine environment.
> 
> If I remember correctly, the tutorial assumes that you install PyTorch system-wide, with root permissions (i.e., via `sudo pip3 install`). But looks like you're using Anaconda virtual environment. Thus, you'll need to modify the manifest template of Gramine accordingly, so that Gramine finds the correct paths/executables; basically, as @kailun-qin mentioned.

@dimakuv  Thanks for your reply! I tested it without using Anaconda virtual environment and the error did not change.

**Comment by Yusen877** [comment]
[P1:T1:] error: libos_init() failed in init_exec_handle: No such file or directory (ENOENT)

We also meet this error. Thank you for the further solutions.

**Comment by cliu717** [comment]
We also meet this error. Thank you for the further solutions.

**Comment by kailun-qin** [comment]
Hi @bai18331272258 @Yusen877 @cliu717!

I tested the [pytorch example](https://github.com/gramineproject/examples/tree/master/pytorch) with Gramine (commit: https://github.com/gramineproject/gramine/commit/af7caa9813029c2b5a4656de098113a18863eda2) last week -- all seemed to work fine in my setup. I basically followed the [PPML tutorial](https://gramine.readthedocs.io/en/latest/tutorials/pytorch/index.html) and the [pytorch example README](https://github.com/gramineproject/examples/blob/3be77927bbac64c2a4412f7e49dd5e0a59692b5b/pytorch/README.md).

Would you pls provide more info on your failed setups? Did you follow the same example/docs similar to what I did or you acutally tested it differently? Thanks!

**Comment by Smart-Yanmeng** [comment]
I solved this problem:
I uninstalled pytorch from conda, exited the conda environment, downloaded a new pytorch with pip, and ran successfully.
