### ISSUE TITLE
gramine-test command not found

### ISSUE THREAD

**Issue by imranmehdi5511** [gramineproject/gramine#1263]
### Description of the problem

gramine-test command not found

### Steps to reproduce

the gramine-test is not found and no way to install it

### Expected results

the gramine-test should work

### Actual results

Command not found error

### Gramine commit hash

Latest

**Comment by dimakuv** [comment]
> the gramine-test should work

Why should `gramine-test` work? I assume that you installed Gramine from the repo, which is shipped as a **production release**. Why would a production release have a tool that is used for debugging and CI (Continious Integration)?

**Comment by imranmehdi5511** [comment]
I need gramine for testing and research purposes, can you guide about how to install gramine for non production use? I need gramine-test to do regression tests.

**Comment by dimakuv** [comment]
I see. You need to build Gramine manully then. Please follow this guide: https://gramine.readthedocs.io/en/stable/devel/building.html

**Comment by imranmehdi5511** [comment]
so if i use sudo apt-get install gramine, gramine-test doesnt work right?

**Comment by dimakuv** [comment]
> so if i use sudo apt-get install gramine, gramine-test doesnt work right?

Yes.

**Comment by imranmehdi5511** [comment]
Yes it worked, thanks for help, the issue is solved, we need to build from source and not run sudo apt-get install gramine for gramine-test to work.
