### ISSUE TITLE
RFC: graphene invocation

### ISSUE THREAD

**Issue by woju** [gramineproject/gramine#13]
# Introduction

I'd like to propose a unified way of running files in graphene. This will certainly be a very visible, very incompatible change, so I'd like to write some explanation and seek review, so we can get this right. Also, I'm not that knowledgeable about the architecture, so I apologize in advance if i had some misconceptions.

### Requirements
- command line invocations (hard)
- invocation from shebang's manifest (nice to have)
- easy way of running under GDB (nice to have, developers love it, so probably a must)

### Status quo ante
Today it is mainly done with `Runtime/pal_loader` script. Script may be invoked in various ways. SGX can be specified in two ways, as argument (without `--` in front, which breaks convention) or environment variable. Interaction between those is either-or, ie. it is not possible to "disable again", only ensure it is enabled. The same is true for GDB.

It is autodetected if the file specified is executable or manifest, and different decisions taken. Which one, it is not always obvious.

### Related work
- #14
- that CMake/meson/whatever effort to rewrite buildsystem, which I can't find the issue number for
- gramineproject/graphene#994 

# the proposal (DRAFT)

### From command line:
1. `graphene[-sgx] {--manifest|-f} MANIFEST`, and manifest contains path to executable and argv
2. `graphene[-sgx] {--manifest|-f} MANIFEST [--] EXECUTABLE [ARGS ...]`, and the manifest contains neither executable nor argv
3. `graphene[-sgx] [--] EXECUTABLE [ARGS]` for the cases when the explicit manifest file specification is not needed (it is either autogenerated, discovered from standard location like `/etc/`, inferred from executable name or for other reasons)
4. `graphene-gdb graphene[-sgx] [...]`, which does required GDB magic (this is expected to be obsoleted when rewriting for in-tree SGX driver to be upstreamed)

No `Linux`, `Linux-SGX` or `FreeBSD`, since user knows what the `uname` is or should be.

It is an error to specify arguments twice, both in command line and in manifest, even if they match.

Environment variables are not accepted.

### From shebang in the manifest:
```
#!/usr/bin/graphene[-sgx] -f
```

This will be documented as One, True, Portable Way irrespective of any specific distro-related issues (for *BSD installation guidelines, see below).

## installation
After proper installation (`apt-get install` or `make DESTDIR=/ install`), the following paths are available (either executables or symlinks thereto):
- `/usr/bin/graphene`
- `/usr/bin/graphene-sgx`
- `/usr/bin/graphene-gdb`

On *BSD, the executables may be in `/usr/local`, but symlinks in `/usr/bin` are nevertheless mandatory at least for `graphene` and `graphene-sgx`. `graphene-gdb` symlink is optional.

**Comment by boryspoplawski** [comment]
This is already done. For the `--version` we have #507
