### ISSUE TITLE
Error path for Gramine manifest file in CI-example/bash 

### ISSUE THREAD

**Issue by blossomin** [gramineproject/gramine#1315]
### Description of the problem

When I tried to use the command listed in the README.md of ./CI-Example/bash to generate the manifest file, I found some strange path. 

[[sgx.trusted_files]]
uri = "file:/usr/bin/["
sha256 = "2f21394f6286277752aa17dc798943c3a7e70ba53998a06315b7f02a0c1690f0"

I checked the directory /usr/bin/, but I don't find the '[' file.

I think there must be some error.

### Steps to reproduce

Just follow the instruction to install Gramine then try the CI example:

When compiling the bash example:

make SGX=1 clean
make SGX=1 

Then check the generated manifest file.

### Gramine commit hash

a01265b22b20abe47f119

**Comment by mkow** [comment]
`[` is a standard shell command installed on all (or most) systems and also a built-in, at least in Bash.

> I checked the directory /usr/bin/, but I don't find the '[' file.

You probably checked incorrectly, you should have it there.

**Comment by blossomin** [comment]
Yes, I find it. It's my fault. Sorry for that.
