### ISSUE TITLE
Initializing Enclave Failed, Operation not permitted EPERM

### ISSUE THREAD

**Issue by 1234mohsin** [gramineproject/gramine#1356]
### Description of the problem

Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Initializing enclave failed: Operation not permitted (EPERM)
error: load_enclave() failed with error: Operation not permitted (EPERM)

### Steps to reproduce

i followed the helloworld example of gramine

### Expected results

enclave should run the helloworld

### Actual results

Error

### Gramine commit hash

stable

**Comment by dimakuv** [comment]
Do you have the `/dev/sgx/enclave` device? What are the permissions on this device? What is the Linux kernel version you're using?

**Comment by dimakuv** [comment]
> How to check permission ?

You don't know how to check permissions on files in Linux? Please google it. I'm afraid we won't be able to help you with such requests.

> Kernel version is latest in which sgx built in. Upstream

I do not understand this answer. There are version numbers in the Linux kernel, and it is easy to check what is the version number on your particular machine.

**Comment by FongKPW** [comment]
Hi @1234mohsin let us know if you are still facing the issue. Thank you.

**Comment by mkow** [comment]
Not enough information in the report (but most likely it's a misconfiguration) and no response from the reporter for a long time, so I'm closing this.
