### ISSUE TITLE
[Linux-SGX] Debugger doesn't work on child thread on certain conditions

### ISSUE THREAD

**Issue by llly** [gramineproject/gramine#1375]
### Description of the problem

I debug Gramine and multi-threading app using `GDB=1 gramine-sgx`. After adding one breakpoint in child thread and run a multi-threading test, the exception handling causes unexpected error.

### Steps to reproduce

Build GDB enabled SGX with `-Dtests=enabled --buildtype=debug -Dsgx=enabled` 

 and run `GDB=1 gramine-test --sgx run multi_pthread`

### Expected results

No failure when run after adding checkpoints.

### Actual results

Scenario 1: fail
```
(gdb) b pal_set_tcb_stack_canary
Breakpoint 3 at 0xfcdc872: pal_set_tcb_stack_canary. (2 locations)
(gdb) c
Continuing.
......
[Switching to LWP 4027055]

Thread 2 "loader" hit Breakpoint 2, pal_set_tcb_stack_canary (canary=13810047679094446917)
    at ../pal/src/host/linux-sgx/pal_tcb.h:87
87          ((char*)&canary)[0] = 0; /* prevent C-string-based stack leaks from exposing the cookie */
(gdb) c
Continuing.
......
----- SGX stats for thread 4027055 -----
  # of EENTERs:        15
  # of EEXITs:         14
  # of AEXs:           17
  # of sync signals:   0
  # of async signals:  0
[LWP 4027055 exited]
[New LWP 4027063]

Thread 3 "loader" received signal SIGSEGV, Segmentation fault.
[Switching to LWP 4027063]
0x00007fff7d1ec9b0 in ?? ()

```

Scenario 2: fail
```
(gdb) b inc
Breakpoint 2 at 0x4011b6: file ../libos/test/regression/multi_pthread.c, line 12.
(gdb) c
Continuing.
......
Thread 7 "loader" hit Breakpoint 2, inc (arg=0x0) at ../libos/test/regression/multi_pthread.c:12
12      static void* inc(void* arg) {
......
(gdb) c
Thread 10 "loader" hit Breakpoint 2, inc (arg=0x0) at ../libos/test/regression/multi_pthread.c:12
12      static void* inc(void* arg) {
......
(gdb) c
Thread 13 "loader" hit Breakpoint 2, inc (arg=0x0) at ../libos/test/regression/multi_pthread.c:12
12      static void* inc(void* arg) {
(gdb) c
Continuing.
......
[New LWP 4047457]
[LWP 4047422 exited]
[LWP 4047421 exited]
error: Unexpected illegal instruction (SIGILL) occurred inside untrusted PAL (ld-linux-x86-64.so.2+0x27eef38)
[LWP 4047457 exited]
[LWP 4047402 exited]
[LWP 4047367 exited]
[Inferior 1 (process 4047335) exited with code 01]

```

Scenario 3: success.
```
(gdb) b inc
Breakpoint 2 at 0x4011b6: file ../libos/test/regression/multi_pthread.c, line 12.
(gdb) b pthread_join
Breakpoint 3 at 0xd20c4a0: file pthread_join.c, line 23.
(gdb) c
Continuing.
......
```

### Gramine commit hash

78c4d8006f910309333696cf20182e1397145606

**Comment by dimakuv** [comment]
Interesting. I don't remember such problems. What is the OS distro you're using? What is the GDB version you're using?

> error: Unexpected illegal instruction (SIGILL) occurred inside untrusted PAL (ld-linux-x86-64.so.2+0x27eef38)

Did you analyze what is that place? And why does it say "inside untrusted PAL", even though the address seems to point inside the `ld-linux-...` shared library (which is NOT a part of Gramine at all)?

> `GDB=1 gramine-test --sgx run multi_pthread`

That's a rather unexpected way of running Gramine with GDB. Why not a normal `GDB=1 gramine-sgx ...`?

**Comment by llly** [comment]
> Interesting. I don't remember such problems. What is the OS distro you're using? What is the GDB version you're using?
 
Ubuntu 20.04.4 LTS, GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2

> Did you analyze what is that place? And why does it say "inside untrusted PAL", even though the address seems to point inside the `ld-linux-...` shared library (which is NOT a part of Gramine at all)?
```
(libos_thread.c:87:alloc_thread_libos_stack) error: [alloc_thread_libos_stack] bookkeeped memory at 0xfb49000-0xfb51000!
(host_exception.c:146:handle_sync_signal) error: Unexpected illegal instruction (SIGILL) occurred inside untrusted PAL (0xfb50f38:ld-linux-x86-64.so.2+0x9bf38)
```
The address is always in the bottom page of libos stack of main thread. The offset is 0xf38. I haven't checked what it is.
> That's a rather unexpected way of running Gramine with GDB. Why not a normal `GDB=1 gramine-sgx ...`?

Same as `gramine-sgx multi_pthread`

**Comment by dimakuv** [comment]
I was able to reproduce it (both scenario 1 and scenario 2).

I am currently looking at scenario 2, as it is easier to analyze. There is clearly a bug in our GDB wrapper code: the application gets a SIGILL with an `ucontext::rip` that points into the SGX enclave -- which is impossible, since RIP cannot show the actual place inside the SGX enclave (instead, RIP must always show in such cases the AEX landing pad).

Let's see if I'll figure out what's wrong with GDB...

**Comment by dimakuv** [comment]
@llly Please check https://github.com/gramineproject/gramine/pull/1377.

All scenarios pass for me now.
