### ISSUE TITLE
[Pal/Linux-SGX] Add `onlyif` syntax for IOCTL logic

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#1378]
### Description of the feature

We recently merged IOCTL feature, the main logic starts here: https://github.com/gramineproject/gramine/blob/e3ca2020d2cce5571011e03d9d7d083760af288b/pal/src/host/linux-sgx/pal_devices.c#L225

One add-on that enables more real-world IOCTLs is the `onlyif` syntax (new keyword for IOCTL struct descriptions in the manifest).

`onlyif = "simple boolean expression"` allows to condition the sub region based on a boolean expression. The proposed formats of expressions are:
1. `token1 == token2`, 
2. `token1 != token2`,
3. `token1 &= token2` (all bits of `token2` are set in `token1`),
4. `token1 |= token2` (at least one bit of `token2` is set in `token1`),

where `token1` and `token2` may be constant integers or sub region names.

I've seen many usages for formats 1 and 2, but I think formats 3 and 4 are not required (in the sense that they seem nice to have, but I haven't seen real IOCTLs rely on such stuff).

For an example of how the code would look like, check my old branch: https://github.com/gramineproject/gramine/compare/master...dimakuv/allow-devices-mmap-ioctl5#diff-32abb61da79b7f3fad6d83ec22a016b128a43e3b1172ac2c9f816b055fdbede4R704

The important new helper function is `calculate_boolean_expr()`. Given the very restricted format of `onlyif` expressions, this function is trivial in its implementation.

### Why Gramine should implement it?

A good example of a real-world IOCTL that would benefit from this sub-feature is [`struct drm_i915_gem_context_param`](https://elixir.free-electrons.com/linux/v6.3.5/source/include/uapi/drm/i915_drm.h#L1949).

For convenience, here is a snippet of this struct:
```c
struct drm_i915_gem_context_param {
	/** @ctx_id: Context id */
	__u32 ctx_id;
	/** @size: Size of the parameter @value */
	__u32 size;
	/** @param: Parameter to set or query */
	__u64 param;
#define I915_CONTEXT_PARAM_BAN_PERIOD	0x1
#define I915_CONTEXT_PARAM_NO_ZEROMAP	0x2
#define I915_CONTEXT_PARAM_GTT_SIZE	0x3
#define I915_CONTEXT_PARAM_NO_ERROR_CAPTURE	0x4
#define I915_CONTEXT_PARAM_BANNABLE	0x5
#define I915_CONTEXT_PARAM_PRIORITY	0x6
	/*
	 * When using the following param, value should be a pointer to
	 * drm_i915_gem_context_param_sseu.
	 */
#define I915_CONTEXT_PARAM_SSEU		0x7

        ...

	/** @value: Context parameter value to be set or queried */
	__u64 value;
};
```

The fields after the `param` field vary depending on the `param` value. A corresponding Gramine manifest would look something like this:
```
sgx.ioctl_structs.drm_i915_gem_context_param = [
    {size=4, type="out", name = "ctx_id"},
    {size=4, type="out", name="size"},
    {size=8, type="out", name="param"},
    {onlyif="param == 0x1", size=8, type="out"}, # value I915_CONTEXT_PARAM_BAN_PERIOD
    {onlyif="param == 0x2", size=8, type="out"}, # value I915_CONTEXT_PARAM_NO_ZEROMAP
    {onlyif="param == 0x3", size=8, type="out"}, # value I915_CONTEXT_PARAM_GTT_SIZE
    {onlyif="param == 0x4", size=8, type="out"}, # value I915_CONTEXT_PARAM_NO_ERROR_CAPTURE
    {onlyif="param == 0x5", size=8, type="out"}, # value I915_CONTEXT_PARAM_BANNABLE
    {onlyif="param == 0x6", size=8, type="out"}, # value I915_CONTEXT_PARAM_PRIORITY
    {onlyif="param == 0x7", ptr=[                  # value I915_CONTEXT_PARAM_SSEU
             # pointer to drm_i915_gem_context_param_sseu
             {size=32, type="out"}, # engine, flags, slice_mask, subslice_mask, eus_per_subsplice, rsvd
           ] },
]
```

**Comment by mkow** [comment]
> * `token1 &= token2` (all bits of `token2` are set in `token1`),
> * `token1 |= token2` (at least one bit of `token2` is set in `token1`),

I don't like recycling C operators and giving them different semantics than in C.

> [`struct drm_i915_gem_context_param`](https://elixir.free-electrons.com/linux/latest/C/ident/drm_i915_gem_context_param)

Please fix the link to not point at `latest`.

**Comment by dimakuv** [comment]
> > * `token1 &= token2` (all bits of `token2` are set in `token1`),
> > * `token1 |= token2` (at least one bit of `token2` is set in `token1`),
> 
> I don't like recycling C operators and giving them different semantics than in C.

Yes, I'll remove them from the PR.

> > [`struct drm_i915_gem_context_param`](https://elixir.free-electrons.com/linux/latest/C/ident/drm_i915_gem_context_param)
> 
> Please fix the link to not point at `latest`.

Done.

**Comment by mkow** [comment]
> Yes, I'll remove them from the PR.

:+1: 

> For an example of how the code would look like, check my old branch: [master...dimakuv/allow-devices-mmap-ioctl5#diff-32abb61da79b7f3fad6d83ec22a016b128a43e3b1172ac2c9f816b055fdbede4R704](https://github.com/gramineproject/gramine/compare/master...dimakuv/allow-devices-mmap-ioctl5#diff-32abb61da79b7f3fad6d83ec22a016b128a43e3b1172ac2c9f816b055fdbede4R704)

And this one also plz :)
