### ISSUE TITLE
Cloud Deployment Instructions Out of Date

### ISSUE THREAD

**Issue by SammyTbeile** [gramineproject/gramine#138]
## Description of the problem
When attempting to setup gramine on a clean install of an Azure DC2s_v2 VM following the instructions here: https://gramine.readthedocs.io/en/latest/cloud-deployment.html , the following error occurs during the `meson setup` step:
```
 ~/.local/bin/meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled
The Meson build system
Version: 0.59.2
Source dir: /home/azureuser/gramine
Build dir: /home/azureuser/gramine/build
Build type: native build
Project name: gramine
Project version: 1.2-rc1
C compiler for the host machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the host machine: cc ld.bfd 2.30
C++ compiler for the host machine: c++ (gcc 7.5.0 "c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the host machine: c++ ld.bfd 2.30
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program check-no-reloc.sh found: YES (/home/azureuser/gramine/Scripts/check-no-reloc.sh)
Program gen-offsets.py found: YES (/home/azureuser/gramine/Scripts/gen-offsets.py)
Program gen-pal-map.py found: YES (/home/azureuser/gramine/Scripts/gen-pal-map.py)
Program get-python-platlib.py found: YES (/home/azureuser/gramine/Scripts/get-python-platlib.py)
Program meson-clang-format.sh found: YES (/home/azureuser/gramine/Scripts/meson-clang-format.sh)
Program objcopy found: YES (/usr/bin/objcopy)
Program protoc-c found: YES (/usr/bin/protoc-c)
WARNING: Project targeting '>=0.55' but tried to use feature deprecated since '0.48.0': python3 module.
Compiler for C supports arguments -Wtrampolines: YES 
Compiler for C supports arguments -Wnull-dereference: YES 
meson.build:63: WARNING: Consider using the built-in warning_level option instead of using "-Wall".
meson.build:63: WARNING: Consider using the built-in warning_level option instead of using "-Wextra".
Has header "/usr/include/asm/sgx.h" : NO 
Has header "/usr/src/linux-headers-5.4.0-1059-azure/arch/x86/include/uapi/asm/sgx.h" : NO 

meson.build:129:12: ERROR: Problem encountered: Invalid SGX driver configuration (-Dsgx_driver and/or -Dsgx_driver_include_path); searched for "asm/sgx.h" under directories: ['/usr/include/', '/usr/src/linux-headers-5.4.0-1059-azure/arch/x86/include/uapi']

A full log can be found at /home/azureuser/gramine/build/meson-logs/meson-log.txt
```

It looks like there's a step missing in acquiring the `asm/sgx.h` file (and presumably other headers).'
Please advise on how best to proceed

## Steps to reproduce
On the current master (6689c8463ffb9d67205b0d6bb415c765a9552b25) follow https://gramine.readthedocs.io/en/latest/cloud-deployment.html on a new Azure DCs_v2 VM:
```
sudo apt-get update
sudo apt-get install -y build-essential \
    autoconf bison gawk libcurl4-openssl-dev libprotobuf-c-dev ninja-build \
    protobuf-c-compiler python3 python3-click python3-jinja2 python3-pip \
    python3-protobuf wget
python3 -m pip install 'meson>=0.55' 'toml>=0.10'
sudo apt-get install -y libunwind8 python3-pyelftools python3-pytest
git clone https://github.com/gramineproject/gramine.git
cd gramine
openssl genrsa -3 -out Pal/src/host/Linux-SGX/signer/enclave-key.pem 3072
meson setup build/ --buildtype=release -Dsgx=enabled -Ddirect=disabled
```

## Expected results
The command completes and presumably sets up for the ninja build

## Actual results
The error above

**Comment by dimakuv** [comment]
@SammyTbeile Indeed there is a problem in our documentation. Our building steps for Gramine assume that the Azure DC2s_v2 VM has an in-kernel SGX driver (which is the default), but it is not true. Actually, this VM has an out-of-tree DCAP driver.

Can you try to add `-Dsgx_driver` and `-Dsgx_driver_include_path` parameters to Meson setup like this:
```
 ~/.local/bin/meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled \
    -Dsgx_driver=dcap1.10 -Dsgx_driver_include_path=/usr/src/linux-headers-`uname -r`/arch/x86/
```

If this doesn't work, then maybe the DCAP SGX driver on this VM is a bit old, then please try with ` -Dsgx_driver=dcap1.6`.

Please report the results back to us, so we can fix the documentation. Also, maybe @veenasai2 or @aneessahib could look into this?

**Comment by dimakuv** [comment]
What about `sgx_oot.h`?

**Comment by aneessahib** [comment]
is this a confidential compute VM? and was basic DCAP tested on this?

**Comment by SammyTbeile** [comment]
It was setup using the docs for setting up a confidential compute VM https://docs.microsoft.com/en-us/azure/confidential-computing/quick-create-portal but I haven't tested dcap.

I'll try that workaround now

**Comment by mythi** [comment]
@SammyTbeile I checked this on Ubuntu 20.04 w/ both v2 and v3 instances and all seem OK. Can you confirm?

**Comment by SammyTbeile** [comment]
@mythi 
The workaround that @dimakuv suggested worked on our instances. I'm still not sure where Azure decided to hide that header file

**Comment by mythi** [comment]
@SammyTbeile FYI #216
