### ISSUE TITLE
[LibOS] Auxiliary vector (`aux`) in Gramine forces Musl into `secure` mode

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#1394]
### Description of the problem

See this snippet: https://github.com/lsds/musl/blob/6516282d2adfad2c7e66d854cde3357120c75dbd/ldso/dynlink.c#L1524-L1531

Gramine creates the `aux` vector like this: https://github.com/gramineproject/gramine/blob/514df189a6867c92dac83923649cd2a124866e62/libos/src/libos_rtld.c#L1116-L1133

Such aux vector results in Musl doing `libc.secure = true` and thus ignoring `LD_LIBRARY_PATH` and `LD_PRELOAD`. This looks wrong, though I didn't observe any applications breaking because of this. But surely this is wrong behavior.

**TODO**: Check if Glibc has something similar, and also fix for Glibc.

### Steps to reproduce

I detected this on Alpine 3.18.0 with Musl 1.2.4, while debugging Musl with GDB.

### Expected results

NA

### Actual results

NA

### Gramine commit hash

514df189a6867c92dac83923649cd2a124866e62

**Comment by mkow** [comment]
> ```C
> libc.secure = ((aux[0]&0x7800)!=0x7800 || aux[AT_UID]!=aux[AT_EUID]
> 		|| aux[AT_GID]!=aux[AT_EGID] || aux[AT_SECURE]);
> ```

> Such aux vector results in Musl doing `libc.secure = true`

But which of the sub-checks actually triggers this? None of our entries you pasted seem to be matching this check.

**Comment by dimakuv** [comment]
The very first one: `aux[0]&0x7800)!=0x7800`

In Gramine, `aux[0]` is AT_PHDR -- which is the base address of the app binary loaded into Gramine memory.

Note that `bin(0x7800) = 0b111100000000000` or `0111 1000 0000 0000`. So Musl sets `secure = true` if `aux[0]` has bits 11-14 **unset** (or not fully set). What this magic is, I need to understand. But surely Gramine's "PHDR base address" accidentally has these bits not fully set.

I'll go read POSIX/UNIX specs and the Linux code to understand what's this `aux[0]` is supposed to be.

**Comment by dimakuv** [comment]
Ok, there was no magic here.

`aux[0]` is a special entry in Musl which reports all set aux (`AT_`) vectors. This is the helper function that does this (and which I missed originally): https://elixir.bootlin.com/musl/v1.2.4/source/ldso/dynlink.c#L214

So what these `0x7800` check means is: *does the kernel-provided list of aex vectors contain vectors 11, 12, 13 and 14*?

These vectors are `AT_UID`, `AT_EUID`, `AT_GID`, and `AT_EGID`. See https://elixir.bootlin.com/linux/v6.3/source/include/uapi/linux/auxvec.h#L20-L23.

So Musl first checks whether those vectors exist at all, and then checks those vectors' values for equality. For reference, I'm talking about this:
- https://elixir.bootlin.com/musl/v1.2.4/source/ldso/dynlink.c#L1817
- https://github.com/bminor/musl/commit/b7f6e0c6f848b7a8c64b3f7b72014b48a9923729

**Comment by dimakuv** [comment]
Glibc does it differently. Glibc uses `AT_SECURE`: https://github.com/bminor/glibc/blob/1d44530a5be2442e064baa48139adc9fdfb1fc6b/sysdeps/unix/sysv/linux/dl-parse_auxv.h#L46

**Comment by dimakuv** [comment]
**Solution**: I will create a PR that adds `AT_UID`, `AT_EUID`, `AT_GID` and `AT_EGID`, as well as `AT_SECURE` in LibOS, to be passed to the app (more specifically to the Musl/Glibc loader).

Since we don't have support for SUID binaries, and we run in the Gramine sandbox, we can just set all this stuff to force `secure = false` (btw, misleading name of the variable, a better name would be `enforce_security_sanitizations`).

**Comment by mkow** [comment]
> Gramine sandbox

nit: please don't use this term in relation to Gramine, this can make people think that we're a sandbox, which we are not (we aren't protecting host from the enclave).

**Comment by dimakuv** [comment]
@mkow Done, replaced with "environment", but what should be the actual wording? What I'm trying to say is that Gramine is like a VM, but I don't know what should be the word for it.

**Comment by mkow** [comment]
I'd just say "inside Gramine" or "inside Gramine emulated environment"? Dunno, just not "sandbox", because it usually is used to mean "security sandbox" :)
