### ISSUE TITLE
RFC: Reorganize the repository

### ISSUE THREAD

**Issue by boryspoplawski** [gramineproject/gramine#14]
Currently this repository has a bit messy layout. Proposed changes:
1. Move .h files into "include" directories (now there are symlinks pointing to src/.h)
2. Move shared code (between Pal and LibOS) out of the Pal directory
   ...
Please suggest more

**Comment by mkow** [comment]
I went through the discussion here and almost everything is already done. I extracted two things we still need to do into https://github.com/gramineproject/gramine/issues/1273 and https://github.com/gramineproject/gramine/issues/1274, so that we can close this overloaded issue now.
