### ISSUE TITLE
Pal/src/host/Linux-SGX/tools/ra-tls/meson.build failed

### ISSUE THREAD

**Issue by RodgerZhu** [gramineproject/gramine#142]
## Description of the problem

Pal/src/host/Linux-SGX/tools/ra-tls/meson.build:86: WARNING: Passed invalid keyword argument "args".
WARNING: This will become a hard error in the future.
Program /bin/sh found: YES (/bin/sh)
Pal/src/host/Linux-SGX/tools/ra-tls/meson.build:106: WARNING: Passed invalid keyword argument "args".
WARNING: This will become a hard error in the future.
Program /bin/sh found: YES (/bin/sh)
Pal/src/host/Linux-SGX/tools/ra-tls/meson.build:127: WARNING: Passed invalid keyword argument "args".

## Steps to reproduce
 gramine dir > meson setup build/ --buildtype=debug -Ddirect=enabled -Dsgx=enabled -Ddcap=enabled

## Expected results
libsecret_prov_verify_dcap can be built successfully. 
BTW, where can I find the libsecret_prov_verify_dcap.so?

**Comment by dimakuv** [comment]
@RodgerZhu Could you show the complete log from the `meson setup` command? The part of the log you pasted is not helpful.

I just tried building with `-Ddcap=enabled` myself on the latest Gramine, it works for me.

> BTW, where can I find the libsecret_prov_verify_dcap.so?

It is installed under `<prefix>/lib/x86_64-linux-gnu/libsecret_prov_verify_dcap.so`. If you didn't specify the prefix in your `meson setup` command, then by default this path is `/usr/local/lib/x86_64-linux-gnu/libsecret_prov_verify_dcap.so`.
