### ISSUE TITLE
Problem reading the FS using rust code

### ISSUE THREAD

**Issue by democ98** [gramineproject/gramine#1422]
### Description of the problem

Description of the problem:
I put the rust program into the docker container upgraded based on the official gramine docker container and run it with sgx. The program loops to detect whether a file under the file path `DEFAULT_FILE_SAVE_PATH` exists, and `DEFAULT_FILE_SAVE_PATH` is mapped to the root directory of the host by docker on a certain path `A`, when an untrusted program on the host computer deletes a file in path `A` , my rust program running in gramine can still detect the existence of the file, but it cannot open the file ( Error No such file or directory (os error 2))

### Steps to reproduce

```rust
const DEFAULT_FILE_SAVE_PATH: &str = "/sgx/";
	let mut file_path = DEFAULT_FILE_SAVE_PATH.to_string() + &bs58::encode(&request_body.peer_id).into_string();
	let mut duplicate_file = 0;
	loop {
		let tmp_file_path = file_path.clone() + &format!(".{}", duplicate_file );
		let path = std::path::Path::new(&tmp_file_path);
		if path.try_exists().unwrap() && path.is_file() {
			warn!("File {:?} already exists ,it means rotator still not finished",&tmp_file_path);
			duplicate_file+=1;
			let tmp_file= match File::open(path){
				Ok(f) => {f}
				Err(e) => {
					error!("error when read file {:?},because {:?}",&tmp_file_path,e.to_string());
					continue
				}
			};
			warn!("the file {:?} in gramine system length is {}",&tmp_file_path,tmp_file.metadata().unwrap().len());
			continue
		}
		break
	};
```
You can try to run this code, after adding a file such as "/sgx/12D3KooWQHuPnuXCqR3c5JhfsM2K6rQUKXwWdoeBuPNV3kQjj3mr.0" on the host host delete (by the way "/sgx/12D3KooWQHuPnuXCqR3c5JhfsM2K6rQUKXwWdoeBuPNV3kQ jj3mr.0" file is generated from within sgx), there will be an error,The following is the content of the manifest file.

```sh
[fs]
mounts = [
  { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
  { path = "{{ arch_libdir }}", uri = "file:{{ arch_libdir }}" },
  { path = "/usr{{ arch_libdir }}", uri = "file:/usr{{ arch_libdir }}" },
  { path = "/sgx", uri = "file:/sgx" },
  { path = "/kaleido", uri = "file:/kaleido"},
  { path = "/kaleido/encrypted", uri = "file:/kaleido/encrypted", type = "encrypted", key_name = "_sgx_mrsigner" },
  { path = "/etc", uri = "file:/etc", type = "chroot"},
]

[sgx]
debug = true
nonpie_binary = true
enclave_size = "2G"
max_threads = 128
trusted_files = [
  "file:{{ gramine.libos }}",
  "file:{{ self_exe }}",
  "file:{{ gramine.runtimedir() }}/",
  "file:/usr{{ arch_libdir }}/",
  "file:{{ arch_libdir }}/",
]
allowed_files = [
  "file:/kaleido",
  "file:/sgx",
  "file:/etc/hosts",
  "file:/etc/resolv.conf",
]
```

### Expected results

```
[2023-06-27T02:25:19Z WARN  xxx::api] File "/sgx/12D3KooWQHuPnuXCqR3c5JhfsM2K6rQUKXwWdoeBuPNV3kQjj3mr.0" already exists ,it means rotator still not finished
[2023-06-27T02:25:19Z WARN xxx::api] the file "/sgx/12D3KooWQHuPnuXCqR3c5JhfsM2K6rQUKXwWdoeBuPNV3kQjj3mr.0" in gramine system length is 8388608
```

### Actual results

```
[2023-06-27T02:25:19Z WARN  xxx::api] File "/sgx/12D3KooWQHuPnuXCqR3c5JhfsM2K6rQUKXwWdoeBuPNV3kQjj3mr.0" already exists ,it means rotator still not finished
[2023-06-27T02:25:19Z ERROR xxx::api] error when read file "/sgx/12D3KooWQHuPnuXCqR3c5JhfsM2K6rQUKXwWdoeBuPNV3kQjj3mr.0",because "No such file or directory (os error 2)"
```

### Gramine commit hash

gramineproject/gramine digest:7e5b8b6111a6

**Comment by kailun-qin** [comment]
@democ98 Thanks for the issue report!

> Expected results
> [2023-06-27T02:25:19Z WARN  xxx::api] File "/sgx/12D3KooWQHuPnuXCqR3c5JhfsM2K6rQUKXwWdoeBuPNV3kQjj3mr.0" already exists ,it means rotator still not finished
> [2023-06-27T02:25:19Z WARN xxx::api] the file "/sgx/12D3KooWQHuPnuXCqR3c5JhfsM2K6rQUKXwWdoeBuPNV3kQjj3mr.0" in gramine system length is 8388608

I'm a bit confused -- shouldn't you expect the non-existence of the deleted file?

> when an untrusted program on the host computer deletes a file in path A , my rust program running in gramine can still detect the existence of the file, but it cannot open the file ( Error No such file or directory (os error 2))

In your case, it looks like you're trying to modify (allowed) files from the host. However, Gramine doesn't share FS state with the host (i.e., the files in mounted directories are only expected to be modified by Gramine processes) so the issue is kind of by-design.

**Comment by democ98** [comment]
Thank you very much for your answer!could you please explain why it is designed like this? Or is there any documentation to explain why FS is not synchronous? thanks! @kailun-qin

**Comment by dimakuv** [comment]
@democ98 Could you check the PR #1423?

**Comment by kailun-qin** [comment]
> I wouldn't call your explanation correct. Technically, allowed files can be modified by other processes other than Gramine process. There should be nothing in Gramine that would prevent such scenarios.

Ah yes, I understand. Perhaps I made some confusions, I was NOT talking about can or can't (for different types of FS mounts), but mostly Gramine's current design that doesn't expect such modifications w/o Gramine's notice.

> I don't know what syscall(s) are invoked in the Rust's std::fs::try_exists() function that you use, but I would assume something like stat().

It should try `statx()` first and fallback to `newfstatat()` if it's not supported, see https://github.com/rust-lang/rust/blob/b5e51db16dfbf5685e32dfe2d9a835a5c695afe4/library/std/src/sys_common/fs.rs#L45-L51 and https://github.com/rust-lang/rust/blob/b5e51db16dfbf5685e32dfe2d9a835a5c695afe4/library/std/src/sys/unix/fs.rs#L838-L856.

> Do we want to fix this behavior? It should be actually pretty simple: e.g. perform a dummy open() on the file to make sure it still exists on the host. 

Make sense to me.

**Comment by kailun-qin** [comment]
> @democ98 Could you check the PR #1423?

I tested on my setup using some similar Rust code snippets as @democ98 provided, it works fine (showing non-existence of the file, if deleted from host).
