### ISSUE TITLE
gramine-direct works great but gramine-sgx cannot access text files for encryption

### ISSUE THREAD

**Issue by imranmehdi5511** [gramineproject/gramine#1444]
I am unable to access text files for encryption inside gramine-sgx, gramine-direct works great:
solved

**Comment by imranmehdi5511** [comment]
gramine-direct can find it but gramine-sgx cannot

**Comment by dimakuv** [comment]
@imranmehdi5511 Please format your message correctly. It's impossible to read.

> gramine-direct can find it but gramine-sgx cannot

Find what?

**Comment by dimakuv** [comment]
Ah, you mean `libcrypto.so.3`. This means that you didn't add the path to it into `sgx.trusted_files` list in the manifest file. Please add the path to this library.

**Comment by imranmehdi5511** [comment]
@dimakuv this is my manifest file.
`
loader.entrypoint = "file:{{ gramine.libos }}"
libos.entrypoint = "/test-gramine"
loader.log_level = "{{ log_level }}"

loader.env.LD_LIBRARY_PATH = "/lib:/usr/lib/x86_64-linux-gnu/"

fs.mounts = [
  { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
  { path = "/test-gramine", uri = "file:test-gramine" },
  { path = "/usr/lib/x86_64-linux-gnu", uri = "file:/usr/lib/x86_64-linux-gnu" },
]

sgx.debug = true
sgx.edmm_enable = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}

sgx.trusted_files = [
  "file:{{ gramine.libos }}",
  "file:test-gramine",
  "file:{{ gramine.runtimedir() }}/",
  "file:libcrypto.so.3",
]

fs.entrypoint = "/test-gramine"
loader.argv0_override = "/test-gramine"
loader.insecure__use_cmdline_argv = true

`

**Comment by imranmehdi5511** [comment]
my question is how do i add it, i tried to ad but it is not being detected

**Comment by dimakuv** [comment]
You need to know where (in which directory) the `libcrypto.so.3` file is located.

The simplest way is like this:
```
cd /
sudo find . -name "libcrypto.so.3"
```

This will give you the absolute path to the file. Use this whole path in `sgx.trusted_files`, not just the base name of the file.

**Comment by imranmehdi5511** [comment]
worked. but now it is unable to access the sample text files for encryption inside gramine sgx:
Error
```
imran@Imran:~/gramine/CI-Examples/test-gramine$ gramine-sgx test-gramine logs.txt 
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Error opening file: logs.txt
```

My code: loader.entrypoint = "file:{{ gramine.libos }}"
libos.entrypoint = "/test-gramine"
loader.log_level = "{{ log_level }}"

loader.env.LD_LIBRARY_PATH = "/lib:/usr/lib/x86_64-linux-gnu/"

fs.mounts = [
  { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
  { path = "/test-gramine", uri = "file:test-gramine" },
  { path = "/usr/lib/x86_64-linux-gnu", uri = "file:/usr/lib/x86_64-linux-gnu" },
]

sgx.debug = true
sgx.edmm_enable = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}

sgx.trusted_files = [
  "file:{{ gramine.libos }}",
  "file:test-gramine",
  "file:logs.txt",
  "file:{{ gramine.runtimedir() }}/",
  "file:/usr/lib/x86_64-linux-gnu/libcrypto.so.3",
  "file:/usr/lib/x86_64-linux-gnu/",
  "file:/home/imran/gramine/CI-Examples/test-gramine/logs.txt",
  
  
]

fs.entrypoint = "/test-gramine"
loader.argv0_override = "/test-gramine"
loader.insecure__use_cmdline_argv = true
```

i just want to know how to access a sample txt file inside gramine sgx

**Comment by imranmehdi5511** [comment]
@dimakuv any idea how to solve this

**Comment by imranmehdi5511** [comment]
sgx.allowed_files is needed. the text files should be in it
