### ISSUE TITLE
I need to add all contents of a Folder to sgx.allowed_files via single command instead of typing all file names

### ISSUE THREAD

**Issue by imranmehdi5511** [gramineproject/gramine#1445]
### Description of the problem

I am confused as to how to add all contents of the folder to sgx.allowed_files.

My code:
```
loader.entrypoint = "file:{{ gramine.libos }}"
libos.entrypoint = "/test-gramine"
loader.log_level = "{{ log_level }}"

loader.env.LD_LIBRARY_PATH = "/lib:/usr/lib/x86_64-linux-gnu/"

fs.mounts = [
  { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
  { path = "/test-gramine", uri = "file:test-gramine" },
  { path = "/usr/lib/x86_64-linux-gnu", uri = "file:/usr/lib/x86_64-linux-gnu" },
]

sgx.debug = true
sgx.edmm_enable = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}

sgx.trusted_files = [
  "file:{{ gramine.libos }}",
  "file:test-gramine",
  "file:logs.txt",
  "file:{{ gramine.runtimedir() }}/",
  "file:/usr/lib/x86_64-linux-gnu/libcrypto.so.3",
  "file:/usr/lib/x86_64-linux-gnu/",
  "file:/home/imran/gramine/CI-Examples/test-gramine/logs.txt",
  "file:/home/imran/gramine/CI-Examples/test-gramine/logs1.txt",
  ]
sgx.allowed_files = [
  #"file:/home/imran/gramine/CI-Examples/test-gramine/logs.txt",
  "file:logs.txt",
  #"file:/home/imran/gramine/CI-Examples/test-gramine/logs1.txt",
  "file:logs1.txt",
  


]

fs.entrypoint = "/test-gramine"
loader.argv0_override = "/test-gramine"
loader.insecure__use_cmdline_argv = true

```

there are 100 logs*.txt how do i add all contents of a directory to the allowed list?

### Gramine commit hash

latest

**Comment by dimakuv** [comment]
Your log files should be created in some specific directory (not just in the application directory). E.g. a sub-directory named `logs/`. Then you do this:
```
sgx.allowed_files = [
  "file:logs/",  # all files under this directory are allowed
```

No need to add any log files to `sgx.trusted_files`. Actually, a single file can be **in only one** of these two lists.

**Comment by imranmehdi5511** [comment]
@dimakuv worked great thanks, just a suggestion add this part to the manifest syntax directory readme and the docs, so people dont get confused

**Comment by imranmehdi5511** [comment]
just a question, does the directory has to be inside the pwd?

**Comment by dimakuv** [comment]
> just a question, does the directory has to be inside the pwd?

No. But in this case you need to specify the absolute path. For example, you have this entry in `sgx.trusted_files`, that illustrates this:
```
  "file:/usr/lib/x86_64-linux-gnu/libcrypto.so.3",
```

**Comment by imranmehdi5511** [comment]
so if i set "file:/usr/lib/", for example all files in lib folder are now allowed?

**Comment by dimakuv** [comment]
> so if i set "file:/usr/lib/", for example all files in lib folder are now allowed?

You mean "trusted", not "allowed", right?

Yes, you are right, all files under the this directory will become trusted.

**Comment by imranmehdi5511** [comment]
thanks for the help! suggest to add these guidelines to the docs. of manifest syntax

**Comment by imranmehdi5511** [comment]
> > so if i set "file:/usr/lib/", for example all files in lib folder are now allowed?
> 
> You mean "trusted", not "allowed", right?
> 
> Yes, you are right, all files under the this directory will become trusted.

i wanted to add to the allowed files a folder not in pwd. i am working on encryption tests and cannot move the entire directory to pwd of the project.

**Comment by dimakuv** [comment]
So what is the problem currently?

Also, please show your manifest file.

**Comment by imranmehdi5511** [comment]
the codes are in home/$USER/gramine/CI-Examples/test-gramine-short/
I pasted some dummy data into /home/$USER/gramine/CI-Examples/test-gramine/test-data
this data cannot be accessed. but the data in home/$USER/gramine/CI-Examples/test-gramine-short/test-data is getting accessed. I need to encrypt HUGE GBs of data which cannot be copied to home/$USER/gramine/CI-Examples/test-gramine-short/test-data
this is the issue or bug.
```
current manifest:
loader.entrypoint = "file:{{ gramine.libos }}"
libos.entrypoint = "/test-gramine-short"
loader.log_level = "{{ log_level }}"

loader.env.LD_LIBRARY_PATH = "/lib:/usr/lib/x86_64-linux-gnu/"

fs.mounts = [
  { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
  { path = "/test-gramine-short", uri = "file:test-gramine-short" },
  { path = "/usr/lib/x86_64-linux-gnu", uri = "file:/usr/lib/x86_64-linux-gnu" },
]

sgx.debug = true
sgx.edmm_enable = {{ 'true' if env.get('EDMM', '0') == '1' else 'false' }}

sgx.trusted_files = [
  "file:{{ gramine.libos }}",
  "file:test-gramine-short",
  "file:logs.txt",
  "file:{{ gramine.runtimedir() }}/",
  "file:/usr/lib/x86_64-linux-gnu/libcrypto.so.3",
  "file:/usr/lib/x86_64-linux-gnu/",
  "file:/home/imran/gramine/CI-Examples/test-gramine-short/logs.txt",
  "file:/home/imran/gramine/CI-Examples/test-gramine-short/logs1.txt",
  ]
#sgx.allowed_files = [
#  #"file:/home/imran/gramine/CI-Examples/test-gramine-short/logs.txt",
#  "file:test-data/file0.txt",
#  #"file:/home/imran/gramine/CI-Examples/test-gramine-short/logs1.txt",
#]



sgx.allowed_files = [
  "file:test-data/",  # all files under this directory are allowed
  "file:/home/imran/gramine/CI-Examples/test-gramine/test-data/", #This line is not working the folder is in another directory
]

  
fs.entrypoint = "/test-gramine-short"
loader.argv0_override = "/test-gramine-short"
loader.insecure__use_cmdline_argv = true
```

**Comment by dimakuv** [comment]
You should add one more item to the `fs.mounts` list:
```
fs.mounts = [
  ...
  { path = "/home/imran/gramine/CI-Examples/test-gramine-short", uri = "file:/home/imran/gramine/CI-Examples/test-gramine-short" },
  ...
]
```

**Comment by imranmehdi5511** [comment]
worked thanks!!!
