### ISSUE TITLE
can we just make entrypoint always be one of trusted_files implictly

### ISSUE THREAD

**Issue by sammyne** [gramineproject/gramine#147]
## Problem
Currently, `entrypoint` needs always placing on `trusted_files` explicitly as follows.
https://github.com/gramineproject/gramine/blob/e3a1bccbc77dc59270b0efd595c3e730b9461b56/Pal/regression/manifest.template#L19-L21

This is tedious and error-prone. Can we just make `entrypoint` always be one of trusted_files implicitly?

## Proposal
During filling in manifest templates, `gramine-manifest` just prepend `file:{{ entrypoint }}` to `trusted_files` in the generated manifest.

**Comment by mkow** [comment]
+1 to what @dimakuv said, and one more argument: It doesn't really need to be a trusted file, it can also be allowed (for debugging/testing) or protected.
