### ISSUE TITLE
[ra-tls-mbedtls] run error

### ISSUE THREAD

**Issue by reclock** [gramineproject/gramine#1480]
### Description of the problem

I encountered an error on the client side while running grain/CI Examples/ra tls mbedtls, resulting in a handshake failure

### Steps to reproduce

server:
**gramine-sgx ./server**

attestation_type_str = dcap 
  . Seeding the random number generator... ok

  . Creating the RA-TLS server cert and key (using "dcap" as attestation type)... ok
  . Bind on https://localhost:5433/ ... ok
  . Setting up the SSL data.... ok
  . Waiting for a remote connection ...

**gramine-sgx-sigstruct-view server.sig**
Attributes:
    mr_signer: 4a95b4676fcbe0b10100bc39a3d88d7984476e09d8f271883e2c4ef0e95f2ed5
    mr_enclave: e4314a88caaaa1400e3d3e0e83fa7c9572f4a99205d21efa34fa74e9150cc2b5
    isv_prod_id: 0
    isv_svn: 0
    debug_enclave: True

client:
**RA_TLS_MRENCLAVE=e4314a88caaaa1400e3d3e0e83fa7c9572f4a99205d21efa34fa74e9150cc2b5 RA_TLS_MRSIGNER=4a95b4676fcbe0b10100bc39a3d88d7984476e09d8f271883e2c4ef0e95f2ed5 RA_TLS_ISV_PROD_ID=0 RA_TLS_ISV_SVN=0 ./client dcap**
 
  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/5433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Installing RA-TLS callback ... ok
g_expected_mrenclave: 
g_expected_mrsigner: 
  . Performing the SSL/TLS handshake...ra_tls_verify_callback: Quote: verification failed with error SW_HARDENING_NEEDED
 failed
  ! mbedtls_ssl_handshake returned -0x3000
  ! ra_tls_verify_callback_results:
    attestation_scheme=2, err_loc=3, 
    dcap.func_verify_quote_result=0x0, dcap.quote_verification_result=0xa007

Last error was: -12288 - X509 - A fatal error occurred, eg the chain is too long or the vrfy callback failed

![图片](https://github.com/gramineproject/gramine/assets/23696606/c276a74c-2caa-4a4a-af43-a3a1326f7cd8)

![图片](https://github.com/gramineproject/gramine/assets/23696606/93e41a68-0131-4387-8e38-7cb6cce1be15)

Where did the error come from??

### Expected results

mbedtls_ssl_handshake success.

### Actual results

[ using default SGX-measurement verification callback (via RA_TLS_* environment variables) ]
11111111 0000000000000

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/5433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Installing RA-TLS callback ... ok
g_expected_mrenclave: 
g_expected_mrsigner: 
  . Performing the SSL/TLS handshake...ra_tls_verify_callback: Quote: verification failed with error SW_HARDENING_NEEDED
 failed
  ! mbedtls_ssl_handshake returned -0x3000
  ! ra_tls_verify_callback_results:
    attestation_scheme=2, err_loc=3, 
    dcap.func_verify_quote_result=0x0, dcap.quote_verification_result=0xa007

Last error was: -12288 - X509 - A fatal error occurred, eg the chain is too long or the vrfy callback failed

### Gramine commit hash

v1.5

**Comment by dimakuv** [comment]
> Quote: verification failed with error SW_HARDENING_NEEDED failed

You need to use the environment variable `RA_TLS_ALLOW_SW_HARDENING_NEEDED`. Please read here: https://gramine.readthedocs.io/en/stable/attestation.html#ra-tls-verify-epid-so

You can also see that we ask to set this variable in the README of `ra-tls-mbedtls` example: https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-mbedtls#quick-start

**Comment by reclock** [comment]
thanks , it run ok.

**Comment by mkow** [comment]
> You need to use the environment variable `RA_TLS_ALLOW_SW_HARDENING_NEEDED`. Please read here: https://gramine.readthedocs.io/en/stable/attestation.html#ra-tls-verify-epid-so

@reclock: Please first verify that the vulnerabilities pointed out in the Intel server's response can actually be ignored without any changes to the software you run inside Gramine (changes in terms of security workarounds/mitigations).

**Comment by hiram-abif** [comment]
For SW_HARDENING_NEEDED Intel recommends to [turn of HT](https://www.intel.com/content/www/us/en/security-center/technical-details/sgx-attestation-technical-details.html). I tested the exact same server using the [attested TLS sample from EGO](https://github.com/edgelesssys/ego/tree/master/samples/attested_tls), and it works fine after disabling HT. Gramine however keeps failing with SW_HARDENING_NEEDED on a server with `Intel(R) Xeon(R) E-2388G CPU @ 3.20GHz`.
Could there be any other cause than HT? Is gramine performing this check differently than EGo?

**Comment by hiram-abif** [comment]
Apparently the error is a false positive from Intel because it can't check the version of the SDK that was used to build the software.

Source:
- https://community.intel.com/t5/Intel-Software-Guard-Extensions/SW-HARDENING-NEEDED-quot-INTEL-SA-00657-quot-but-microcode-it-s/td-p/1435751
- https://community.intel.com/t5/Intel-Software-Guard-Extensions/SW-HARDENING-NEEDED-quot-INTEL-SA-00657-quot-but-microcode-it-s/m-p/1436546

What version of SGX SDK does gramine use?

**Comment by ghe0** [comment]
Open Enclave (and by consequence Edgeless RT and EGo) just ignore this. More details here:
https://github.com/openenclave/openenclave/blob/2517ec75c25b07fa6fdff815bac361f403f63856/common/sgx/tcbinfo.c

In case of Occlum it's just a warning:
https://github.com/occlum/ngo/blob/4bb48def5e1151bc13444d239b5bed09545971c2/demos/ra_tls/grpc/v1.38.1/src/cpp/sgx/sgx_ra_tls_occlum.cc#L251

Maybe for gramine it should not be mandatory to set the env var to `RA_TLS_ALLOW_SW_HARDENING_NEEDED=1` to bypass this?

**Comment by mkow** [comment]
> What version of SGX SDK does gramine use?

Gramine does not use SGX SDK.

> Maybe for gramine it should not be mandatory to set the env var to `RA_TLS_ALLOW_SW_HARDENING_NEEDED=1` to bypass this?

I don't like this idea, potential security issues should require explicit user reaction, not a warning which you may easily miss.

**Comment by dimakuv** [comment]
I agree with @mkow. It's better to be explicit in these situations.
