### ISSUE TITLE
two app run in gramine?

### ISSUE THREAD

**Issue by reclock** [gramineproject/gramine#1486]
I want to run two apps, app1 and app2, in sgx. How to write a manifest file? Is there an example of this type？

**Comment by dimakuv** [comment]
How do the two apps interact exactly? Is app1 the parent process, and it spawns app2?

Or do these apps run more or less independently? If the latter, then why do you want to run them in a single Gramine SGX instance (with a single manifest file)?

Anyway, if you just want to run two apps one after another, then the simplest is to wrap them in a Bash script:
```bash
#!/bin/bash
./app1
./app2
```

and specify `/bin/bash` as the entrypoint in your `bash.manifest.template`. Something like this.

I don't think we have a particular example for this, but it should be rather trivial to implement.

**Comment by mkow** [comment]
@reclock: Please don't use GitHub issues for general support (see the information in the issue template), we use issues to keep track of bugs in Gramine. If you need support then either:
- use GitHub Discussions,
- ask on our Gitter (https://gitter.im/gramineproject/community),
- or send an email to users@gramineproject.io.
