### ISSUE TITLE
how to do localattestation 

### ISSUE THREAD

**Issue by imranmehdi5511** [gramineproject/gramine#1499]
### Description of the problem

There is a docs page but no commands or instructions how how to do it. I wanted to run geth in sgx but got the error that dev/attestation/attestation_type doesnt exist.

I want to run this project: https://github.com/flashbots/geth-sgx-gramine

### Gramine commit hash

latest

**Comment by dimakuv** [comment]
> I want to run this project: https://github.com/flashbots/geth-sgx-gramine

Sorry, this project is not maintained by us. I recommend to ask the maintainers of that project directly: https://github.com/flashbots/geth-sgx-gramine/issues

Also note that `gramine-direct` is a no-SGX version of Gramine, so it won't have any files related to SGX attestation. The files for SGX attestation appear only in the `gramine-sgx` version of Gramine.

**Comment by imranmehdi5511** [comment]
![image](https://github.com/gramineproject/gramine/assets/74496936/f4b37bff-f444-4317-9d0d-62f26d60829f)
issue is i get a gramine related error, i just want to learn how to do local attestation even for hello world project

**Comment by imranmehdi5511** [comment]
> > I want to run this project: https://github.com/flashbots/geth-sgx-gramine
> 
> Sorry, this project is not maintained by us. I recommend to ask the maintainers of that project directly: https://github.com/flashbots/geth-sgx-gramine/issues
> 
> Also note that `gramine-direct` is a no-SGX version of Gramine, so it won't have any files related to SGX attestation. The files for SGX attestation appear only in the `gramine-sgx` version of Gramine.

how to get the local attestation to produce /dev/attestation/attestation_type for any project ignore this one

**Comment by imranmehdi5511** [comment]
Your docs here mention it, but fail to mention how to actually do it:https://gramine.readthedocs.io/en/stable/attestation.html

**Comment by dimakuv** [comment]
Ok, let me ignore your error. But once again: you can't access SGX attestation in `gramine-direct` mode.

The only local attestation example we have is here: https://github.com/gramineproject/gramine/blob/9ef75ebc18ab9b390e7c248d6068237d433a4b20/libos/test/regression/attestation.c#L89

Unfortunately, we don't have more interesting examples currently than this one...

**Comment by imranmehdi5511** [comment]
the gramine-sgx is too heavy for my pc, so i need to get it working in gramine-direct for debug

**Comment by imranmehdi5511** [comment]
> Ok, let me ignore your error. But once again: you can't access SGX attestation in `gramine-direct` mode.
> 
> The only local attestation example we have is here:
> 
> https://github.com/gramineproject/gramine/blob/9ef75ebc18ab9b390e7c248d6068237d433a4b20/libos/test/regression/attestation.c#L89
> 
> Unfortunately, we don't have more interesting examples currently than this one...

can you just explain the steps to do this attestation.c i will figure out the rest for my project

**Comment by mkow** [comment]
Please don't use GitHub issues for general support (see the information in the issue template), we use issues to keep track of bugs in Gramine. If you need support then either:
- use GitHub Discussions,
- ask on our Gitter (https://gitter.im/gramineproject/community),
- or send an email to users@gramineproject.io.
