### ISSUE TITLE
[RFC] New interface for calling host-level syscalls

### ISSUE THREAD

**Issue by boryspoplawski** [gramineproject/gramine#15]
## Description
For reasons why we would want this, please look at pros&cons.

The new version would change the way blocking host-level syscalls are done, the non-blocking, or rather "fast" syscalls would be called directly (same way as now). We would consider `futex` with `FUTEX_WAKE` to be a "fast" syscall and `read`to be a "slow" syscall. The "slow" syscalls wouldn't be called directly, but using a helper thread. E.g. it could look like:
1) We want to issue a host-level syscall `read(fd, buf, size)`
2) Write syscall number and arguments in some shared buffer.
3) Wake-up a dedicated host helper thread (probably using futexes).
4) Wait for helper thread being done - sleep using special sleeping function.
5) Helper thread issues a syscall, saves the return value, wakes up the original thread and goes back to sleep.

The assumption is that host-level thread are cheap and we could have one for each Graphene thread (which would basically double the number of host threads).

If an interrupt (signal) comes, then we notify the helper thread about it and wait for it finishing the job (it either goes back to sleep or writes the return values, if syscall was completed already).
Why even bother with all of this and not just call syscalls directly? To use the special sleeping function (basically a futex, but that's not really important), which would be signals (Graphene level signals) aware.

Pros:
- We would be able to handle signals coming at any moment, even when we are inside LibOS/PAL before issuing the syscall (currently we can block in such cases).
- This would simplify signal handling, especially in Linux-SGX  PAL (e.g. no need for weird `EINTR` injection and losing PAL state in case of ocall interrupt).

Cons:
- Double the number of threads.
- Some additional overhead on each "slow" syscall. I'm not sure how much would that slow the execution, but I suspect not much - need to be determined empirically. Note that we would do this only on "slow" syscalls, so this shouldn't be that bad (as they are "slow" anyway). The most (only?) noticeable overhead would be in case of "slow" syscall that actually do not block, e.g. `read` on file descriptor with some data already ready to be read.

Note that in case of PAL Linux-SGX we would do all of this in the **untrusted** part, so the overhead would probably be negligible.

## Idea v2
Another approach could be wrapping each blocking syscall with something like this:
```
xor r11, r11
xchg r11, [some_per_thread_variable] ; this variable would be set to 1 by signal handling routines
cmp r11, 0
jne .skip
syscall
jmp .syscall_done
.skip:
mov rax, -EINTR
.syscall_done:
```
`some_per_thread_variable` would be set by LibOS code in an appropriate upcall iff we were interrupted inside LibOS or PAL code.
What I don't like about this approach:
- There is a 3 instruction window, which can still miss a signal (between `xchg` and `syscall`). The window could probably be narrowed down to 2 instructions, e.g. by replacing `xchg` and `cmp` with `sub r11, [addr]`, but that does not solve the issue.
- This would require accessing an untrusted variable `some_per_thread_variable` from LibOS. While this can be done in a secure manner (e.g. writing inline asm), the idea does sound nice and sets a dangerous precedence. Besides we would need to provide an interface for such access just because SGX needs it.

I personally dislike this idea even more than the first one.

**Comment by dimakuv** [comment]
@boryspoplawski Was there anything new on this issue since March? Looks like not really, we haven't worked on this problem.

**Comment by boryspoplawski** [comment]
No there was not, though a similar issue for untrusted part of PAL Linux-SGX was solved in https://github.com/gramineproject/graphene/pull/2602

**Comment by dimakuv** [comment]
I'll close this PR as it seems to be not a problem for Gramine.
