### ISSUE TITLE
[P1:T1:] error: Error during libos_init() in init_exec_handle (-13)

### ISSUE THREAD

**Issue by Jansper-x** [gramineproject/gramine#1511]
When I use gramine-sgx to run my application I got this error:
**[P1:T1:] error: Error during libos_init() in init_exec_handle (-13)**
<img width="677" alt="image" src="https://github.com/gramineproject/gramine/assets/43697225/07f31290-c231-4e3d-a8c5-a4fbba79a080">
But when I use gramine-direct to run my application,it works well. Why this happen?

**Comment by dimakuv** [comment]
Please use our bug-reporting template, and do not include screenshots.

Maybe you have very low `sgx.enclave_size` option in your manifest file? Try to increase its value.

**Comment by mkow** [comment]
Most likely a misconfiguration and no response from the reporter for a long time, so I'm closing it.
