### ISSUE TITLE
Gramine Fuzzing: assert failed IS_ALIGNED_PTR(xstate, LIBOS_XSTATE_ALIGN) at libos_context.c:113

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1515]
### Description of the problem

Syzkaller has been modified in order to run with Gramine (https://github.com/JaewonHur/syzkaller). We were able to run it with Gramine v1.5 for Gramine-Direct and below crash is reported by the tool.

**[P2:T2:crash-68b52d938b74b3a5] assert failed ../libos/src/arch/x86_64/libos_context.c:113 IS_ALIGNED_PTR(xstate, LIBOS_XSTATE_ALIGN)**

### Steps to reproduce

1. Extract the zip file and cd to the drive
2. Build the Gramine(v1.5) in DEBUG mode
3. make DEBUG=1 CRASH=68b52d938b74b3a5
4. gramine-direct crash
[crash-68b52d938b74b3a5.zip](https://github.com/gramineproject/gramine/files/12451746/crash-68b52d938b74b3a5.zip)

### Actual results

```
(libos_init.c:505:libos_init) [P2:T2:crash-68b52d938b74b3a5] debug: LibOS initialized
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-68b52d938b74b3a5] trace: ---- set_robust_list(0x381e24056a20, 0x18) = 0x0
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-68b52d938b74b3a5] trace: ---- write(1, 0x381e24270004, 0x12) ...
executing program
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-68b52d938b74b3a5] trace: ---- return from write(...) = 0x12
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-68b52d938b74b3a5] trace: ---- write(2, 0x381e24270017, 0xa) ...
### start
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-68b52d938b74b3a5] trace: ---- return from write(...) = 0xa
(libos_context.c:113:is_xstate_extended) [P2:T2:crash-68b52d938b74b3a5] assert failed ../libos/src/arch/x86_64/libos_context.c:113 IS_ALIGNED_PTR(xstate, LIBOS_XSTATE_ALIGN)
(libos_parser.c:1628:buf_write_all) [P1:T1:crash-68b52d938b74b3a5] trace: ---- return from clone(...) = 0x2
(libos_parser.c:1628:buf_write_all) [P1:T1:crash-68b52d938b74b3a5] trace: ---- wait4(-1, 0x381e242b3d7c, |0x40000000, 0) ...
(libos_ipc_child.c:21:ipc_child_disconnect_callback) [P1:libos] error: Child process (vmid: 0x2) got disconnected
(libos_parser.c:1628:buf_write_all) [P1:T1:crash-68b52d938b74b3a5] trace: ---- return from wait4(...) = -512
(libos_parser.c:1628:buf_write_all) [P1:T1:crash-68b52d938b74b3a5] trace: ---- wait4(-1, 0x381e242b3d7c, |0x40000000, 0) ...
(libos_parser.c:1628:buf_write_all) [P1:T1:crash-68b52d938b74b3a5] trace: ---- return from wait4(...) = 0x2
(libos_exit.c:212:libos_syscall_exit_group) [P1:T1:crash-68b52d938b74b3a5] debug: ---- exit_group (returning 0)
(libos_fs_lock.c:785:file_lock_clear_pid) [P1:T1:crash-68b52d938b74b3a5] debug: clearing file (POSIX) locks for pid 1
(libos_sync_client.c:331:shutdown_sync_client) [P1:T1:crash-68b52d938b74b3a5] debug: sync client shutdown: closing handles
(libos_sync_client.c:346:shutdown_sync_client) [P1:T1:crash-68b52d938b74b3a5] debug: sync client shutdown: waiting for confirmation
(libos_sync_client.c:359:shutdown_sync_client) [P1:T1:crash-68b52d938b74b3a5] debug: sync client shutdown: finished
(libos_ipc_worker.c:285:ipc_worker_main) [P1:libos] debug: IPC worker: exiting worker thread
(libos_exit.c:58:libos_clean_and_exit) [P1:T1:crash-68b52d938b74b3a5] debug: process 1 exited with status 0
```
Logs are also attached in zip file

### Gramine commit hash

0b552696d4f402c291c8c2cce525e7117d06d397

**Comment by dimakuv** [comment]
#1521 has the same underlying problem, but shows how Gramine fails in release mode.

**Comment by anjalirai-intel** [comment]
This issue is also reproducible with Gramine SGX. Logs are attached
[crash-68b52d938b74b3a5-sgx.log](https://github.com/gramineproject/gramine/files/12496162/crash-68b52d938b74b3a5-sgx.log)

**Comment by mkow** [comment]
This isn't an issue, Gramine assumes that the app is trusted. Yes, calling `rt_sigreturn()` with garbage arguments will crash Gramine (in a benign way, actually) - the app just asked to load random garbage, from a misaligned address, into its registers. No same app would do that. Same goes for calling `read()` with random pointers or just straight overwriting Gramine memory.

I don't see a point in fuzzing a trusted interface, most of the issues will be bogus and we'll just waste our time analyzing them.
