### ISSUE TITLE
Gramine Fuzzing: assert failed ../libos/src/libos_parser.c:833 flags & MAP_PRIVATE

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1516]
### Description of the problem

Syzkaller has been modified in order to run with Gramine (https://github.com/JaewonHur/syzkaller). We were able to run it with Gramine v1.5 for Gramine-Direct and below crash is reported by the tool.

**(libos_parser.c:833:parse_mmap_flags) [P2:T2:crash-9c6c868499364b53] assert failed ../libos/src/libos_parser.c:833 flags & MAP_PRIVATE**

### Steps to reproduce

1. Extract the zip file and cd to the drive
2. Build the Gramine(v1.5) in DEBUG mode
3. make DEBUG=1 CRASH=9c6c868499364b53
4. gramine-direct crash
[crash-9c6c868499364b53.zip](https://github.com/gramineproject/gramine/files/12451770/crash-9c6c868499364b53.zip)

### Actual results

```
(libos_init.c:505:libos_init) [P2:T2:crash-9c6c868499364b53] debug: LibOS initialized
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-9c6c868499364b53] trace: ---- set_robust_list(0x57726df27a20, 0x18) = 0x0
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-9c6c868499364b53] trace: ---- write(1, 0x57726e142004, 0x12) ...
executing program
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-9c6c868499364b53] trace: ---- return from write(...) = 0x12
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-9c6c868499364b53] trace: ---- write(2, 0x57726e142017, 0xa) ...
### start
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-9c6c868499364b53] trace: ---- return from write(...) = 0xa
(libos_socket.c:111:libos_syscall_socket) [P2:T2:crash-9c6c868499364b53] warning: unsupported socket type 3
(libos_parser.c:1628:buf_write_all) [P1:T1:crash-9c6c868499364b53] trace: ---- return from clone(...) = 0x2
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-9c6c868499364b53] trace: ---- socket(INET, RAW, 2) = -93
(libos_parser.c:1628:buf_write_all) [P1:T1:crash-9c6c868499364b53] trace: ---- wait4(-1, 0x57726e185d7c, |0x40000000, 0) ...
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-9c6c868499364b53] trace: ---- write(2, 0x57726e185bd0, 0x14) ...
### call=0 errno=93
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-9c6c868499364b53] trace: ---- return from write(...) = 0x14
(libos_parser.c:835:parse_mmap_flags) [P2:T2:crash-9c6c868499364b53] assert failed ../libos/src/libos_parser.c:835 flags & MAP_PRIVATE
(libos_ipc_child.c:21:ipc_child_disconnect_callback) [P1:libos] error: Child process (vmid: 0x2) got disconnected
(libos_parser.c:1628:buf_write_all) [P1:T1:crash-9c6c868499364b53] trace: ---- return from wait4(...) = -512
(libos_parser.c:1628:buf_write_all) [P1:T1:crash-9c6c868499364b53] trace: ---- wait4(-1, 0x57726e185d7c, |0x40000000, 0) ...
(libos_parser.c:1628:buf_write_all) [P1:T1:crash-9c6c868499364b53] trace: ---- return from wait4(...) = 0x2
(libos_exit.c:212:libos_syscall_exit_group) [P1:T1:crash-9c6c868499364b53] debug: ---- exit_group (returning 0)
(libos_fs_lock.c:785:file_lock_clear_pid) [P1:T1:crash-9c6c868499364b53] debug: clearing file (POSIX) locks for pid 1
(libos_sync_client.c:331:shutdown_sync_client) [P1:T1:crash-9c6c868499364b53] debug: sync client shutdown: closing handles
(libos_sync_client.c:346:shutdown_sync_client) [P1:T1:crash-9c6c868499364b53] debug: sync client shutdown: waiting for confirmation
(libos_sync_client.c:359:shutdown_sync_client) [P1:T1:crash-9c6c868499364b53] debug: sync client shutdown: finished
(libos_ipc_worker.c:285:ipc_worker_main) [P1:libos] debug: IPC worker: exiting worker thread
(libos_exit.c:58:libos_clean_and_exit) [P1:T1:crash-9c6c868499364b53] debug: process 1 exited with status 0
```

### Gramine commit hash

0b552696d4f402c291c8c2cce525e7117d06d397

**Comment by kailun-qin** [comment]
Looking into the source code, it has:
```
  ...
  res = syscall(__NR_socket, 2ul, 3ul, 2);
  fprintf(stderr, "### call=0 errno=%u\n", res == -1 ? errno : 0);
  if (res != -1)
    r[0] = res;
  res = syscall(__NR_mmap, 0x20ffa000ul, 0x3000ul, 0x280000bul, 0x80010ul, r[0],
                0x92109000ul);
  fprintf(stderr, "### call=1 errno=%u\n", res == -1 ? errno : 0);
  ...
```
I would argue that `0x80010` (`MAP_FIXED|MAP_SYNC`, actually w/ implicit `|MAP_FILE`) is not a valid flag for `mmap()`.

**Comment by jinengandhi-intel** [comment]
Since we are running a fuzz tool, its expected that invalid flags will be passed to syscalls to check their behavior, so is Gramine exhibiting the right behavior in failing with the above assert? The return code or `res` of `syscall(__NR_mmap, 0x20ffa000ul, 0x3000ul...` when run natively is 9

**Comment by dimakuv** [comment]
@jinengandhi-intel is right, Gramine has a bug here. Gramine needs to parse the flags and fail with the same error as Linux does (on incorrect flags).

**Comment by kailun-qin** [comment]
> Gramine needs to parse the flags and fail with the same error as Linux does (on incorrect flags)

@dimakuv Are you suggesting that we should parse the flags "faithfully"? I'm asking because we currently make some assumptions in flag parsing (e.g., if not specified, then default to some valid flag): https://github.com/gramineproject/gramine/blob/02f7a8565fec54b5fa4e81c20e827cb954f2dff3/libos/src/libos_parser.c#L836-L840 and https://github.com/gramineproject/gramine/blob/02f7a8565fec54b5fa4e81c20e827cb954f2dff3/libos/src/libos_parser.c#L697-L699

OR you simpy mean in this case that we should remove the `assert()` as it blocks the app in debug mode. For release build, I think it does parse the flags and fail with the same error as Linux does (on incorrect flags).

**Comment by dimakuv** [comment]
> OR you simply mean in this case that we should remove the `assert()` as it blocks the app in debug mode. 

Yes, that's what I mean. It's incorrect to have an `assert()` on user-supplied data, like in this case (I mean [this line](https://github.com/gramineproject/gramine/blob/02f7a8565fec54b5fa4e81c20e827cb954f2dff3/libos/src/libos_parser.c#L837)).

**Comment by anjalirai-intel** [comment]
This issue is also reproducible with Gramine SGX. Logs are attached
[crash-9c6c868499364b53-sgx.log](https://github.com/gramineproject/gramine/files/12496186/crash-9c6c868499364b53-sgx.log)
