### ISSUE TITLE
Malloc Tuning link does not exist now, it should be updated in manifest file

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1533]
### Description of the problem

As part of rust manifest template, a link has been specified related to Gramine Readme Docs for profiling, the link page does not exist

https://github.com/gramineproject/gramine/blob/10c2668e35b11eacc0182c831f285113eeedc2b9/CI-Examples/rust/rust-hyper-http-server.manifest.template#L9

**Old link:**
https://gramine.readthedocs.io/en/latest/devel/performance.html#glibc-malloc-tuning

**New Link:**
https://gramine.readthedocs.io/en/stable/performance.html#glibc-malloc-tuning

### Gramine commit hash

39b529fbf88b77a33b5e625e4d9ed4a6a8d7d7af

**Comment by dimakuv** [comment]
Let me quickly fix it.
