### ISSUE TITLE
Gramine-SGX Fuzzing: Unexpected memory fault occurred inside PAL

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1536]
### Description of the problem

Syzkaller has been modified in order to run with Gramine (https://github.com/JaewonHur/syzkaller). We were able to run it with Gramine v1.5 for Gramine and below crash is reported by the tool for Gramine-SGX not for Gramine-Direct

**(pal_exception.c:290:_PalExceptionHandler) error: Unexpected memory fault occurred inside PAL (_PalSegmentBaseGet at pal_misc.c, libpal.so+0x1f09e (addr = 0xffffe4909e))**

### Steps to reproduce

1. Extract the zip file and cd to the drive
2. Build the Gramine(v1.5) in DEBUG mode
3. make DEBUG=1 CRASH=cd5c95d39c29b541
4. gramine-sgx crash
[crash-cd5c95d39c29b541_sgx.log](https://github.com/gramineproject/gramine/files/12512073/crash-cd5c95d39c29b541_sgx.log)
[crash-cd5c95d39c29b541.zip](https://github.com/gramineproject/gramine/files/12644586/crash-cd5c95d39c29b541.zip)

### Actual results

```
(libos_init.c:505:libos_init) [P2:T2:crash-cd5c95d39c29b541] debug: LibOS initialized
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-cd5c95d39c29b541] trace: ---- set_robust_list(0xe03ac31a20, 0x18) = 0x0
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-cd5c95d39c29b541] trace: ---- write(1, 0xe03ae4b004, 0x12) ...
executing program
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-cd5c95d39c29b541] trace: ---- return from write(...) = 0x12
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-cd5c95d39c29b541] trace: ---- write(2, 0xe03ae4b017, 0xa) ...
### start
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-cd5c95d39c29b541] trace: ---- return from write(...) = 0xa
(pal_exception.c:290:_PalExceptionHandler) error: Unexpected memory fault occurred inside PAL (_PalSegmentBaseGet at pal_misc.c, libpal.so+0x1f09e (addr = 0xffffe4909e))
(pal_exception.c:297:_PalExceptionHandler) debug: (untrusted PAL sent PAL event 0x2)
(pal_process.c:248:_PalProcessExit) debug: PalProcessExit: Returning exit code 1
(libos_ipc_child.c:21:ipc_child_disconnect_callback) [P1:libos] error: Child process (vmid: 0x2) got disconnected
```

### Gramine commit hash

0b552696d4f402c291c8c2cce525e7117d06d397

**Comment by kailun-qin** [comment]
> Extract the zip file and cd to the drive

@anjalirai-intel Would you pls attach the zip (which seems to be missing) here?

**Comment by anjalirai-intel** [comment]
@kailun-qin My bad. I have attached it

**Comment by kailun-qin** [comment]
@anjalirai-intel Thanks!

From the reproduction program source, we have `arch_prctl(ARCH_GET_FS, 0)` invoked:
```
  fprintf(stderr, "### start\n");
  res = syscall(__NR_arch_prctl, 0x1003ul, 0ul);
  fprintf(stderr, "### call=0 errno=%u\n", res == -1 ? errno : 0);
```
while from the error log, it showed:
```
### start
(libos_parser.c:1628:buf_write_all) [P2:T2:crash-cd5c95d39c29b541] trace: ---- return from write(...) = 0xa
(pal_exception.c:290:_PalExceptionHandler) error: Unexpected memory fault occurred inside PAL (_PalSegmentBaseGet at pal_misc.c, libpal.so+0x1f09e (addr = 0xffffe4909e))
(pal_exception.c:297:_PalExceptionHandler) debug: (untrusted PAL sent PAL event 0x2)
(pal_process.c:248:_PalProcessExit) debug: PalProcessExit: Returning exit code 1
(libos_ipc_child.c:21:ipc_child_disconnect_callback) [P1:libos] error: Child process (vmid: 0x2) got disconnected
```

So I suppose the "unexpected memory fault occurred inside PAL" happened during `arch_prctl()` and a recent PR should've addressed it: https://github.com/gramineproject/gramine/commit/4ef6abbf64a9c0db62a444d3fb93dc62bc0b7dc2.

I quickly checked that the issue cannot be reproduced on Gramine's latest master: dc9206760a562f3df6c5dedb471e2d46c96ecf1e. Would you pls double check? @anjalirai-intel Thanks!

**Comment by anjalirai-intel** [comment]
@kailun-qin I verified with latest master and it indeed passed there.
