### ISSUE TITLE
Remove preload support in PAL and remove `loader.preload` in manifest

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#158]
## Description of the problem

After #152, we should remove the "preload libraries" support in PAL and `loader.preload` in the manifest.

There is no reason to have PAL-level preloaded libraries. In reality, we only ever load one ELF binary: either the PAL regression test or the LibOS library.

So we can remove the following:
- Remove preload libraries in PAL regression tests
- Remove `loader.preload = "libsysdb.so"`
- Remove `g_loaded_maps` -- we will only have `g_pal_map` and resolve symbols through it
- Change `CALL_ENTRY` in `db_rtld.c` and the corresponding caller code (only call once)
- Get rid of `enum elf_object_type` -- we will only have EXEC type (for a single loaded ELF binary)

**Comment by boryspoplawski** [comment]
> Remove loader.preload = "libsysdb.so"

Then we also need to add some other entry, as I think we need the full path to libsysdb (and we definitely need it's hash).
