### ISSUE TITLE
Workloads requiring memfault handling are failing on Old Intel CPUs which does not have exinfo support

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1587]
### Description of the problem

Certain workloads which requires memfault handling are now failing on old Intel CPU's which does not have exinfo support

We verified on the KBL-R system, we don't have Coffee Lake or Comet Lake to test this issue.

For more details refer #1570 #1561 #1562

As part of the discussion, there will be no fix available and this issue can be closed with documentation update

### Steps to reproduce

LTP test: setrlimit01
Workloads: java

Build Gramine in release mode
Run either of the specified test

### Expected results

The test were working before commit #1502 went into Gramine Master.

### Actual results

**setrlimit01**
[23.398] error: Tried to handle a memory fault with no faulting address reported by SGX. Please consider enabling 'sgx.use_exinfo' in the manifest.

### Gramine commit hash

9f80c4245a8a852a2d6ac30c81840c94db447305

**Comment by anjalirai-intel** [comment]
@mkow We don't support officially support LTP, there are several other applications like openjdk where we would get this issue. 

This issue is specifically for old Intel CPU's specifying that they will not work post #1502

**Comment by dimakuv** [comment]
I think the purpose of this issue is summarized in this sentence from the original post:

> As part of the discussion, there will be no fix available and **this issue can be closed with documentation update**

So we need to document this somehow.
