### ISSUE TITLE
[RFC] Standard installation paths

### ISSUE THREAD

**Issue by woju** [gramineproject/gramine#16]
# Statement of the problems

Those are problems that we need to be aware when solving

## Stable paths
After signing the manifest, paths are baked in, so Graphene needs a standardised set of installed paths. The immediate problem concerns `libsysdb.so` and libc. Paths need to be the same across distributions.

## Multiple libcs installed together
There is an ongoing proposal to make graphene work with executables compiled against musl: gramineproject/graphene#2269. It's a choice of enclave developer, which libc will be used (probably using `fs.mount.` manifest option), so we need to make multiple libcs available concurrently.

## Multiple versions installed together, for signing
`libpal.so` is needed to calculate the expected measurement of the enclave. Also, loader might change between versions. So for each Graphene version, we need to install `libpal.so` and the respective python script which emulates loading for the purpose of signing. This signing script will be discovered/loaded/invoked by common `graphene-sgx-sign` command.

# Proposed solution

## PAL, LibOS, runtime

```
/usr/lib/graphene-<version>/direct/libpal.so
/usr/lib/graphene-<version>/direct/loader
/usr/lib/graphene-<version>/sgx/libpal.so
/usr/lib/graphene-<version>/sgx/loader
/usr/lib/graphene-<version>/libsysdb.so
/usr/lib/graphene-<version>/runtime/{glibc,musl,...}-<version>/*.so
```

TODO: gdb, headers, -dev packages, 

## Command line tools

Those might be ELFs, python scripts and/or shell scripts. I'm not sure if those need to be standardised. Possibly related: gramineproject/gramine#13. 
```
/usr/bin/graphene-direct
/usr/bin/graphene-sgx
/usr/bin/graphene-sgx-sign
/usr/bin/graphene-sgx-get-token
/usr/bin/graphene-manifest
# and possibly others
```

# Package names

Packages (whether deb, rpm or else) should be named:

## `graphene`

Metapackage depending on `graphene-direct` and `graphene-sgx`.

## `graphene-direct`

Non-SGX Graphene (`libpal.so`, `loader`, `/usr/bin/` loader script, manpage).

## `graphene-sgx`

metapackage depending on the latest version

## `graphene-sgx-1.23`

Graphene SGX compiled against upstream 5.11+ driver.

## `graphene-sgx-oot-1.23`

Graphene SGX compiled against SDK driver.

## `graphene-sgx-dcap-1.23`

Graphene SGX compiled against DCAP driver. (Not sure if needed, possibly the same as upstream driver).

## `graphene-libos`

`libsysdb.so`

## `graphene-runtime-glibc-1.23`

`runtime/glibc-1.23`

## `graphene-runtime-musl-4.56`

Musl.

# Not part of this RFC

All those don't need to be standardised, instead the decision should be taken by packager for the respective distro.

- Documentation, manpages, readmes, ... all this goes according to distro guidelines.
- Python package (depends on distro and system Python version).
- Non-essential tools: `Linux-SGX/tools`, GSC, ...

**Comment by dimakuv** [comment]
@woju Is this meta-issue still relevant? What are the unfinished items? Can we close this issue?

**Comment by dimakuv** [comment]
I'm closing this issue. I think we solved everything here.
