### ISSUE TITLE
RFC: building tests in Meson

### ISSUE THREAD

**Issue by pwmarcz** [gramineproject/gramine#161]
## The problem

We would like to move compiling (and possibly running) tests from Makefile to Meson. This is the last part of old Makefiles remaining. However, the transition is difficult for the following reasons:

1. **Building the manifests depends on Gramine being installed** (not only built). That makes it hard to build the tests (binaries + manifests) together with Gramine.

  * Python tools (`gramine-manifest`, `gramine-sgx-sign`) currently require installing
  * SGX manifests depend on the target paths for PAL and LibOS libraries
  * SGX manifests depend on *hashes* of PAL and LibOS libraries, and these hashes change after installing by Meson (Meson adds `rpath` to libraries in the build dir, and strips them during install).

2. **Test binaries depend on Gramine internals** that we don't install. That makes it hard to build the test binaries separately from Gramine.

  * PAL tests use large parts of the `common` library
  * PAL tests use the public PAL interface (`pal.h`)
  * LibOS tests use `mbedtls` (which we install, but without header files)
  * LibOS `attestation` interface test uses `sgx_arch.h`
  
## Wishlist

Some use cases that should be easy:

* **Rebuild Gramine and/or tests**. Ideally, that should be 1-2 commands, after which there are no problems with outdated manifests etc.
* **Run the tests, or a single test, from Python**. This is useful when working with Pytest sources (coming up with the right assertions, etc.)
* **Run a single test binary from command line**, without Python/Pytest. This is indispensable for debugging (GDB, strace, different command line args, etc.)

## Solution ideas

Some of these were discussed with @woju and @mkow already, but I don't think we had a conclusion.

### Start by compiling binaries only, leave manifests to Make

The test binaries are relatively easy to compile in Meson. I have a branch that compiles all test binaries in Meson, and installs them in `/lib/.../graphene/tests/`.

The rest (compiling manifests + running tests) is still handled by Makefiles. In order to run tests, you need to first `ninja install`, then `make regression`.

The upside is that Makefiles no longer compile C code. But is it worth it to merge a temporary solution like this?

### Compile binaries only, build manifests on demand

Since it's problematic to build manifests together with everything else, don't build them! Build them in Python tests when they're necessary. Introduce a utility (`gramine-rebuild-manifest`) or wrapper (`gramine-rebuild-manifest-or-run`)?

I find this idea problematic for several reasons:

* **Need to track dependencies**. I don't want to rebuild a manifest every time I'm about to run a program, but do it only if something changed. The dependencies for manifest are kind of complicated: `x.manifest.sgx` depends on `x.manifest` (which depends on `x.template`), but also on the files that need to be hashed (including LibOS), and `x.sig` additionally depends on the PAL library.

  We can't escape *generating* these dependencies (`.d` files), but it's much easier (and faster!) to plug them into something like Make or Ninja than checking them ourselves.
  
* **External variables**: the manifest template uses some variables (entrypoint, remote attestation parameters). I'm not sure what to do with them: eliminate entirely? introduce a separate "environment" file? If we complicate the Python solution, we'll be building our own mini build system.

### Introduce a separate Meson project for tests

Ideally, test binaries and manifests should be a separate project, which you can build after Gramine is built and installed.

The problem here is mostly decoupling from the rest of Gramine. The worst offender is PAL regression tests. We could remove them, but they actually provide some coverage.

What would probably work is some combination of inlining (copy the necessary parts of `common` to the tests) and installing (Gramine should install `pal.h` specifically for use in tests, only when a specific Meson flag is enabled), but it sounds pretty ugly.

**Comment by woju** [comment]
> Ideally, I'd do both: only rebuild when some files have changed, and then only do as much work as necessary.

yes, of course those aren't mutually exclusive

**Comment by dimakuv** [comment]
@pwmarcz Is this meta-issue still relevant? Or can we close it now?

**Comment by pwmarcz** [comment]
Yes, I think we can close - the discussion seems finished.
