### ISSUE TITLE
test_sgx_sign.py failed on RHEL 8 & Centos Stream 8 with error `fixture 'tmp_path' not found`

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1661]
### Description of the problem

test_sgx_sign.py failed on RHEL 8 & Centos Stream 8 with error `fixture 'tmp_path' not found`. Python version on these systems are 3.6 and pytest version is 3.4.2 whereas on Ubuntu 20.04 Pytest version is 7.4.3 and Python Version is 3.8

```
 def test_sign_from_pem_path_with_passphrase(tmp_rsa_key):
file /home/intel/jenkins/workspace/local_ci_graphene_sgx_rhel_server_6.2/gramine/tests/test_sgx_sign.py, line 13
  @pytest.fixture
  def tmp_rsa_key(tmp_path):
E       fixture 'tmp_path' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_xml_attribute, record_xml_property, recwarn, tmp_rsa_key, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

### Steps to reproduce

 python3 -m pytest -v --junit-xml tests.xml tests/

### Expected results

Tests should not throw error, instead passes successfully

### Actual results

Test fails with error 
```
  def tmp_rsa_key(tmp_path):
E       fixture 'tmp_path' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_xml_attribute, record_xml_property, recwarn, tmp_rsa_key, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.
```

### Gramine commit hash

273b95d

**Comment by kailun-qin** [comment]
`tmp_path` seems to be introduced since pytest version 3.9.0 (pls see https://docs.pytest.org/en/stable/changelog.html#pytest-3-9-0-2018-10-15-not-published-due-to-a-release-automation-bug). So pytest version 3.4.2 on RHEL 8 & Centos Stream 8 does not meet this minimum requirement.

**Comment by anjalirai-intel** [comment]
@kailun-qin ,yes you are correct, should we have any fix for this, or okay to have this failure for this distros
