### ISSUE TITLE
[PAL] Print a human-readable error if Gramine detects that it is started inside Gramine

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#1666]
### Description of the feature

Gramine doesn't supported nesting (running a Gramine process inside a Gramine environment, e.g. `gramine-direct gramine-direct`). Nor Gramine should support it.

But when this accidentally happens, Gramine prints errors about missing pieces of the environment (like the missing debug info in `/proc/self/maps`). This is confusing and leads users to believe the problem is in their Linux environment.

### Why Gramine should implement it?

To avoid future confusions of users, and long debugging sessions.

**Comment by mkow** [comment]
Why should we artificially disallow this? Technically it should be fine, if the emulation was more complete and transparent. Also, how one can hit this accidentally? Your example doesn't seem convincing to me, `gramine-direct gramine-direct` is a very visible error.

**Comment by dimakuv** [comment]
> Why should we artificially disallow this? Technically it should be fine, if the emulation was more complete and transparent.

1. But we're not at this stage now.
2. Why would we want such nested execution?

> Also, how one can hit this accidentally? Your example doesn't seem convincing to me, gramine-direct gramine-direct is a very visible error.

This was a real issue happening in production. Basically, GSC was used to produce a graminized Docker image. This graminized Docker image was accidentally put in a wrong image repository (with a hard-to-read image name). This wrong image repository is supposed to host original images, so the CI took this graminized Docker image and applied GSC on it again. The GSC "graminization" went fine, but the subsequent CI test execution failed with cryptic messages, which were red herrings and made people (including myself) suspect totally irrelevant things.

**Comment by mkow** [comment]
Maybe it should then be implemented on GSC level? Adding such IFs on the core Gramine level seems wrong to me...

**Comment by dimakuv** [comment]
Hm, I don't like the idea of checking this on GSC level. Ok, I concur, this is a very corner case issue, let me just close this.
