### ISSUE TITLE
Manifest syntax check is missing for `sgx.allowed_files` and `sgx.protected_files`

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1678]
### Description of the problem

gramine-manifest does not throw error when manifest file has old syntax file for `sgx.allowed_files` and `sgx.protected_files`

Earlier Gramine Releases has different syntax for sgx
`sgx.identifier.uri = value`

Update the manifest file to use old syntax for allowed_files and protected_files, gramine-manifest does not throw error while generating manifest.sgx file

### Steps to reproduce

1. cd CI-Examples/bash
2. Update manifest.template with below changes
 	- Remove existing sgx.allowed_files section
 	- Add `sgx.allowed_files.scripts = "file:scripts/"`
3. Run make SGX=1   #build goes through
4. Run gramine-sgx ./bash -c "cd scripts && bash bash_test.sh 1"

### Expected results

It should throw error while generating manifest.sgx file

### Actual results

It throws error `bash: bash_test.sh: Permission denied`

If we build in Debug Mode, the error message is bit clear but it does not tell what is the root cause
```
(libos_rtld.c:1045:register_library) [P1:T1:bash] debug: glibc register library /lib/libc.so.6 loaded at 0x1e5c8000
(libos_parser.c:1647:warn_unsupported_syscall) [P1:T1:bash] warning: Unsupported system call rseq
(pal_files.c:77:file_open) warning: Disallowing access to file 'scripts/bash_test.sh'; file is not trusted or allowed.
bash: bash_test.sh: Permission denied
(libos_exit.c:212:libos_syscall_exit_group) [P1:T1:bash] debug: ---- exit_group (returning 126)
(libos_fs_lock.c:785:file_lock_clear_pid) [P1:T1:bash] debug: clearing file (POSIX) locks for pid 1
```

### Gramine commit hash

cdca1e36d7186a91e9536402de294c022c358cd8

**Comment by mkow** [comment]
> Earlier Gramine Releases has different syntax for sgx
> `sgx.identifier.uri = value`

I think that was a long time ago and since then we had a deprecation warning, and now the support was removed. Same as we do with all manifest syntaxes?

> ### Expected results
> 
> It should throw error while generating manifest.sgx file

IMO the current behavior is ok. If we want to verify the syntax of user's manifest then we should use some schema, not handcrafted IFs for each possible error.

**Comment by kailun-qin** [comment]
> It should throw error while generating manifest.sgx file
>
> If we want to verify the syntax of user's manifest then we should use some schema, not handcrafted IFs for each possible error.

Yes, I think this was actually discussed before and an issue was created here: https://github.com/gramineproject/gramine/issues/1336.
