### ISSUE TITLE
[curl] Gramine's minimized `libcurl.a` doesn't have support for network proxies

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#1719]
### Description of the problem

I bumped into this problem when experimenting with the Intel Trust Authority (ITA) attestation service. I was trying the `ra-tls-mbedtls` example, and its `client` failed (note that the client doesn't even execute inside Gramine, it's a normal standalone program).

The `client` program is linked against the RA-TLS library. The RA-TLS library itself is statically linked against `libcurl.a`, which is a minimized version of libcurl that we have as a subproject.

At some point the Gramine team applied a `libcurl.a` minimization strategy as recommended here: https://github.com/curl/curl/blob/curl-8_4_0/docs/INSTALL.md#reducing-size

One recommendation from that web page is `--disable-proxy`. We applied it blindly to our curl build (in several places):
- https://github.com/gramineproject/gramine/blob/35f5d4b8b89bf713668bb1cfb5bae86c5d9ee387/subprojects/packagefiles/curl-8.4.0/compile.sh#L56?plain=1
- https://github.com/gramineproject/contrib/blob/eafc46ffb4c4782d83525d116a6450705bfa72eb/Integrations/azure/ra_tls_maa/subprojects/packagefiles/curl-7.84.0/compile.sh#L56
- (also in ITA PR that I was experimenting with: https://github.com/gramineproject/contrib/pull/59)

However, many companies have a proxy. This would imply that any app that would use our RA-TLS curl-based verification libraries (these are currently two: EPID and MAA) **fails** in such a company-proxy environment. In my case, the connection just hanged until the connection timeout (~60 seconds) triggered.

Some Curl references:
- https://github.com/curl/curl/blob/9034a16d974a826e1ba8ef7262646a941bb79fb2/docs/CURL-DISABLE.md?plain=1#L133
- https://github.com/curl/curl/blob/9034a16d974a826e1ba8ef7262646a941bb79fb2/configure.ac#L839-L854

### Solution

Remove the `--disable-proxy` build option.

Here is the current size of `libcurl.a`:
```
$ ls -lah build/subprojects/curl-7.84.0/
625K libcurl.a
```

Here is the new size of `libcurl.a` (when we re-enable proxy):
```
$ ls -lah build/subprojects/curl-7.84.0/
668K libcurl.a
```

I guess we can live with the `668 - 625 = 43` KB increase in size (~7% increase).

### Gramine commit hash

35f5d4b8b89bf713668bb1cfb5bae86c5d9ee387

**Comment by kailun-qin** [comment]
> Remove the --disable-proxy build option.
>
> I guess we can live with the 668 - 625 = 43 KB increase in size (~7% increase).

Yeah, I think it's reasonable to be enabled and the size increase should be fine.
