### ISSUE TITLE
stress-ng fstat test fails with BUG `reached PID limit when allocating a new ID, not safe to proceed` for RHEL-8

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#1759]
### Description of the problem

stress-ng tests are designed to stress the hardware to detect/identify potential issues.

stress-ng fstat test specially fails for RHEL-8 with BUG `reached PID limit when allocating a new ID, not safe to proceed`  with Gramine-Direct and works for all other distro supported by Gramine

### Steps to reproduce

1. Install stress-ng
2. Makefile, manifest template, logs has been attached in zip
3. gramine-direct stress-ng --fstat 0 --timeout 60s -v

[stress-ng fstat.zip](https://github.com/gramineproject/gramine/files/14175496/stress-ng.fstat.zip)

### Expected results

gramine-direct stress-ng --fstat 0 --timeout 60s -v
```
stress-ng: info:  [1] setting to a 60 second run per stressor
stress-ng: info:  [1] dispatching hogs: 144 fstat
stress-ng: info:  [1] successful run completed in 60.26s
```

### Actual results

```
[P1:libos] error: reached PID limit when allocating a new ID, not safe to proceed
[P1:libos] error: BUG() ../libos/src/ipc/libos_ipc_pid.c:72
[P1:libos] error: Illegal instruction during Gramine internal execution at 0x7fffffd19690 (0x7fffffd19690, VMID = 1, TID = 0)
[P134:T782438:stress-ng] error: Could not allocate a tid!
[P128:T572416:stress-ng] error: Could not allocate a tid!
[P133:T782437:stress-ng] error: Could not allocate a tid!
[P126:T572414:stress-ng] error: Could not allocate a tid!
[P114:T572402:stress-ng] error: Could not allocate a tid!
[P86:T309814:stress-ng] error: Could not allocate a tid!
[P72:T309800:stress-ng] error: Could not allocate a tid!
[P71:T309799:stress-ng] error: Could not allocate a tid!
[P69:T309797:stress-ng] error: Could not allocate a tid!
[P68:T309796:stress-ng] error: Could not allocate a tid!
[P59:T76571:stress-ng] error: Could not allocate a tid!
[P53:T76565:stress-ng] error: Could not allocate a tid!
[P57:T76569:stress-ng] error: Could not allocate a tid!
[P45:T76557:stress-ng] error: Could not allocate a tid!
[P47:libos] error: Failed to send IPC msg to 1: Broken pipe (EPIPE)
```

### Gramine commit hash

1cf1f46646646a3b9c6b371e67c80e945577456a

**Comment by dimakuv** [comment]
I'm not sure how this is possible, because the limit of possible PIDs is ~4 million: https://github.com/gramineproject/gramine/blob/1cf1f46646646a3b9c6b371e67c80e945577456a/libos/include/libos_types.h#L30-L31

Apparently this sub-test of `stress-ng` allocate a crazy amount of processes, each with a crazy amount of threads...

**Comment by jinengandhi-intel** [comment]
The main purpose of raising the bug was to understand why the test would fail only on RHEL but pass on Ubuntu distro. Is there any distro specific parameter that we need to check?

**Comment by dimakuv** [comment]
Good question. This would need further debugging.

**Comment by dimakuv** [comment]
I'm closing this issue as there were no updates for several months.

@anjalirai-intel @jinengandhi-intel If this is still relevant, please provide additional details and reopen.
