### ISSUE TITLE
Unexpected illegal instruction occurred inside VDSO error seen after emulate inline syscalls commit

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/gramine#176]
## Description of the problem

Issue is seen on one of the internal CI machines and for all test suites like LibOS, PAL, FS LTP etc.

The tests fail with the following error:

```
Emulating a raw system/supervisor call. This degrades performance, consider patching your application to use Gramine syscall API.
error: Unexpected illegal instruction occurred inside VDSO (0x7ffff3fd366d, PID = 6098, TID = 6100)
```

## Steps to reproduce

Machine details have been shared with Dmitrii/Michal/Borys via email.

**Comment by aniket-intelx** [comment]
> @aniket-intelx This doesn't seem related in any way, could you try doing a clean build and rechecking?

The issue is not seen after the recent commits.
