### ISSUE TITLE
[PAL/Linux-SGX] At least in debug builds, cannot have enclaves overlapping 1TB and 1.5TB mem regions

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#1787]
Theoretically an SGX enclave can be of any size up to the limit found in CPUID leaf 12H, sub-leaf 0, bits in the EDX register.

Gramine has at least a couple assumptions that limit the actual possible enclave size:
- [`DBGINFO_ADDR`](https://github.com/gramineproject/gramine/blob/63ee38d5eb28f5a880a973c28de7be6f0dc6f290/pal/src/host/linux-sgx/gdb_integration/sgx_gdb.h#L7-L14) is hard-coded to 1TB, which means that a helper debug info must be stored at 1TB base address.
- [Address Sanitizer shadow memory](https://github.com/gramineproject/gramine/blob/63ee38d5eb28f5a880a973c28de7be6f0dc6f290/common/include/asan.h#L133) is hard-coded to start at 1.5TB.
- (These are the only ones I'm aware of, and they happen only in debug mode.)

Thus, we already have some (implicit) limits on the enclave size. However there seem to be no explicit checks for this. Such checks must be added.

@mkow:
> we could have that hardcoded enclave size limit checked only for debug builds

**UPDATE:** There is also [Untrusted Shared Memory](https://github.com/gramineproject/gramine/blob/63ee38d5eb28f5a880a973c28de7be6f0dc6f290/pal/src/host/linux-sgx/pal_linux_defs.h#L44-L49), but this one is hard-coded to 64 ~~GB~~ TB.

**Comment by mkow** [comment]
> > we could have that hardcoded enclave size limit checked only for debug builds
> 
> **UPDATE:** There is also [Untrusted Shared Memory](https://github.com/gramineproject/gramine/blob/63ee38d5eb28f5a880a973c28de7be6f0dc6f290/pal/src/host/linux-sgx/pal_linux_defs.h#L44-L49), but this one is hard-coded to 64GB.

That's fortunately a lie :) It's 64 TB, not GB, see the lines you linked to.
