### ISSUE TITLE
Incorrect or missing error conditions in Gramine leading to LTP test failures

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/gramine#179]
## Description of the problem

We are in the process of upgrading LTP to the latest version and that's where we are seeing failures with the new/modified LTP tests when run with Gramine. Collating multiple such tests which are failing due to incorrect/missing error conditions in Gramine.

- [ ] bind01
- [x] readv02  (UPDATE: failure is due to a bug in new LTP test code being added)
- [ ] sendfile03. 

Log of the test run with Gramine-direct is attached to the bug.

## Steps to reproduce

Since the issues are seen with the LTP upgraded tests and something that we are still migrating to the local CI, follow the below steps to checkout and run the latest LTP test in your local workspace.

Checkout the local CI repo present here `https://github.com/jinengandhi-intel/graphene_local_ci/tree/ltp_upgrade`

```
cd gramine/LibOS/shim/test/ltp
cp -rf <ltp_upgrade_localci_branch>/ltp_src .
cp -rf <ltp_upgrade_localci_branch>ltp_config/* .

# To build the tests and generate manifest files
make -j8 -f Makefile.LTP all LTPCFG=ltp_tests.cfg LTPTESTFILE=./install/runtest/syscalls-new 

# To run the tests
cd install/testcases/bin/
gramine-direct bind01
gramine-direct readv02
gramine-direct sendfile03

```

## Actual results

[bind01_readv02_sendfile03_error.txt](https://github.com/gramineproject/gramine/files/7439038/bind01_readv02_sendfile03_error.txt)

**Comment by dimakuv** [comment]
Any volunteers to take on this? @vijaydhanraj @svenkata9 ?

**Comment by vijaydhanraj** [comment]
@dimakuv please assign this to me

**Comment by mkow** [comment]
@vijaydhanraj: Any updates on this?

**Comment by svenkata9** [comment]
@Satya1493 took it up this sprint

**Comment by dimakuv** [comment]
@Satya1493 Could you please comment here? I need you to comment on GitHub to be able to assign you.

**Comment by Satya1493** [comment]
@dimakuv Please assign this to me.

**Comment by boryspoplawski** [comment]
Could you elaborate more on what the bug in LTP is?

**Comment by Satya1493** [comment]
@boryspoplawski , 
The new test case added was to pass a bad fd and gramine is expected to fail with `EBADF`. 
The tc is `{&badfd, valid_iovec, 3, EBADF}` where 3rd param is number of buffers passed, which is 3 in this case.
But `valid_iovec` contains only 1 buffer. `static struct iovec valid_iovec[] = { {buf1, CHUNK} };`

The right tc would be `{&badfd, valid_iovec, 1, EBADF}`.
