### ISSUE TITLE
A aesm error

### ISSUE THREAD

**Issue by tyxben** [gramineproject/gramine#1810]
### Description of the problem

I ran the program in Docker, and after installing AESM, it keeps reporting this error, but I don't know what parameter is wrong.
sgx.edmm_enable = true
sgx.enclave_size = "1G"
sgx.remote_attestation = "dcap"
 I am runing in docker
(host_platform.c:127:request_aesm_service) error: Cannot communicate with AESM service (read/write failed: Invalid argument (EINVAL)).
Please check its status! (`service aesmd status` on Ubuntu)

### Steps to reproduce

Gramine1.6

### Expected results

run success，server start

### Actual results

(host_platform.c:127:request_aesm_service) error: Cannot communicate with AESM service (read/write failed: Invalid argument (EINVAL)).
Please check its status! (`service aesmd status` on Ubuntu)

### Gramine commit hash

1.6

**Comment by dimakuv** [comment]
> I ran the program in Docker, and after installing AESM

You're supposed to install AESM on the host, not inside the Docker. Then you forward the AESM socket from the host to inside the Docker container. Here's an example of how Docker container is supposed to run: https://gramine.readthedocs.io/projects/gsc/en/latest/#example, see step 7.

**Comment by dimakuv** [comment]
> Mar 13 15:48:56 sgx-2 systemd[1]: aesmd.service: Main process exited, code=dumped, status=11/SEGV

@tyxben Wow, I have never seen AESM service crashing before. You need to ask the Intel SGX SDK/PSW team: https://github.com/intel/linux-sgx

**Comment by mkow** [comment]
I'm closing this issue, as it looks like a bug in AESM service, not Gramine, so please report it to them.
