### ISSUE TITLE
Internal memory fault at 0x00000000

### ISSUE THREAD

**Issue by mjkambex** [gramineproject/gramine#190]
## Description of the problem
Internal memory fault at 0x00000000

## Steps to reproduce
Using gramine release tag 1.0

We are running the OpenVINO Model Server within GSC signed docker image. In our case, OVMS is running along with NGINX configured in reverse proxy mode.

## Expected results
OVMS should be running and should be able to load the model successfully and inference should be successful

## Actual results
Error when executing sed command.

++ sed 's/ //g'
[P5:T65:bash] error: Internal memory fault at 0x00000000 (IP = +0x1aee0, VMID = 5, TID = 65)
[P4:shim] error: Child process (vmid: 0x5) got disconnected
+ [[ /sampleloader/sample.json != '' ]]

## Additional information
Attaching the logs & manifest file
[gsc_manifest.txt](https://github.com/gramineproject/gramine/files/7460804/gsc_manifest.txt)
[ovms_rel1.0_6.log](https://github.com/gramineproject/gramine/files/7460805/ovms_rel1.0_6.log)

**Comment by dimakuv** [comment]
Based on offline conversations with OVMS people, I assume this issue was fixed. I'm closing it. @mjkambex Please reopen the issue if it wasn't solved yet.
