### ISSUE TITLE
GSC | Run bash example on Azure

### ISSUE THREAD

**Issue by dzygann** [gramineproject/gramine#193]
Hi,

I try to run the GSC Bash example on an Azure machine. I followed the instructions in the README file.
I could build the container, but the last command `docker run ...` command runs into an error.

My first try was to run the command from the README file 
```
$ sudo docker run --device=/dev/sgx_enclave -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-ubuntu18.04-bash -c ls
docker: Error response from daemon: error gathering device information while adding custom device "/dev/sgx_enclave": no such file or directory.
```

On my Azure machine is no `/dev/sgx_enclave` directory. Should it be there? 
There is an `/dev/sgx` directory, which contains two character devices (`enclave` and  `provision`).
If I pass this directory `--device` argument I get the same message as above at the end, but with some more steps before:

```
docker run --device=/dev/sgx -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket gsc-ubuntu18.04-bash -c ls
++ find /gramine/meson_build_output/lib -type d -path '*/site-packages'
+ export PYTHONPATH=:/gramine/meson_build_output/lib/python3.6/site-packages
+ PYTHONPATH=:/gramine/meson_build_output/lib/python3.6/site-packages
++ find /gramine/meson_build_output/lib -type d -path '*/pkgconfig'
+ export PKG_CONFIG_PATH=:/gramine/meson_build_output/lib/x86_64-linux-gnu/pkgconfig
+ PKG_CONFIG_PATH=:/gramine/meson_build_output/lib/x86_64-linux-gnu/pkgconfig
+ '[' -z '' ']'
+ gramine-sgx-get-token --sig /entrypoint.sig --output /entrypoint.token
Attributes:
   ...
    date:        2021-11-02
+ gramine-sgx /entrypoint -c ls
error: Cannot open device /dev/sgx_enclave. Please make sure the Intel SGX kernel module is loaded.
error: load_enclave() failed with error -2
```

I can run the bash example in the CI-Examples folder without any issues.

Is something wrong with my initial GSC setup in azure or is it something else wrong?

**Comment by dimakuv** [comment]
@dzygann All GSC-related issues should be created in the corresponding repo: https://github.com/gramineproject/gsc/issues. Please raise it there. I'm closing it here.

> I try to run the GSC Bash example on an Azure machine. I followed the instructions in the README file.

Which README are you talking about? Please post a link.

Also make sure that you're using the latest GSC documentation: https://gramine-gsc.readthedocs.io/
