### ISSUE TITLE
[Pal/SGX] Unable to map executables from protected fs

### ISSUE THREAD

**Issue by lejunzhu** [gramineproject/gramine#196]
When trying to execute a binary via execve() or loading .so via dlopen(), if the file is an protected file, a warning is printed from the following line and the mmap() call will fail:

https://github.com/gramineproject/gramine/blob/3db1e28e27622cbf1265650cc92a87281803d31d/Pal/src/host/Linux-SGX/db_files.c#L401

therefore, the binary is not able to run.

The mmap() call actually comes with PAL_PROT_WRITECOPY (aka MAP_PRIVATE), and there's no need to write back to the underlying file. Perhaps we should ignore PAL_PROT_WRITE when PAL_PROT_WRITECOPY is present?

**Comment by lejunzhu** [comment]
To reproduce it: 
1. Product an executable that prints "hello world".
2. Put it in an "allowed" directory. Use python script "import os; os.execv('hello_world', ['hello_world'])" to run it. It will print the hello world string.
3. Use pf-crypt tool to encrypt it and put in protected FS instead.
4. Run the same script, it will _not_ print the hello world string. Instead, error can be seen in debug log.

**Comment by dimakuv** [comment]
Thanks @lejunzhu! This is clearly a bug in our Protected Files implementation.

We have plans to re-write the whole PF implementation in Gramine, so this bug will also be fixed as part of that effort. Unfortunately, that effort hasn't started yet. But "improve PF implementation" will be the next item in our TODO list.

**Comment by lejunzhu** [comment]
Fixed with PR #550
