### ISSUE TITLE
Quick start instructions missing protoc-c install  for non-SGX environment

### ISSUE THREAD

**Issue by mkbhanda** [gramineproject/gramine#201]
## Description of the problem
Quick start instructions missing protoc-c install  for non-SGX environment in Ubuntu 20 (focal) environment.
## Steps to reproduce
Fresh Ubuntu 20.04.2 LTS environment. Clone gramine.
while executing " meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=disabled" 
ran into an error. 

## Expected results
no errors
## Actual results
"meson.build:40:0: ERROR: Program 'protoc-c' not found"
## Additional information 
Please provide link to https://ubuntu.pkgs.org/20.04/ubuntu-universe-amd64/protobuf-c-compiler_1.3.3-1_amd64.deb.html
or inline the following two commands:
Update the package index:
> sudo apt-get update
Install protobuf-c-compiler deb package:
> sudo apt-get install protobuf-c-compiler

or alternately add in sudo apt-get command for build essentials both of "libprotobuf-c-dev  and
    protobuf-c-compiler"

**Comment by dimakuv** [comment]
@woju @pwmarcz We are not supposed to require and use Protobuf packages for non-SGX Gramine installs. But I see that we require Protobuf unconditionally in our Meson files: https://github.com/gramineproject/gramine/search?q=protoc_c_prog

Could we fix it to only use Protobuf (and build `aesm.pb-c.[ch]`) only for SGX?
