### ISSUE TITLE
In Gramine build instructions provide instruction to determine kernel version

### ISSUE THREAD

**Issue by mkbhanda** [gramineproject/gramine#202]
## Description of the problem
Help new users to more easily set up their Linux SGX environment.
Following build instructions on https://gramine.readthedocs.io/en/latest/building.html
Item 2 might be easier on the reader if titled
title: SGX minimal Linux kernel version"
 text: "SGX requires minimally Linux Kernel version 5.9. To determine your Linux kernel version run 
> uname -r

The kernel requirement is because SGX requires FSGSBASE,  a feature in recent processors which allows direct access to the FS and GS segment base addresses. See link(<to learn more about FSGSBASE>).
"
The remainder for upgrade steps is perfect.
## Steps to reproduce
An Ubuntu environment - bare metal or VM
Goal is to get SGX environment set up for new comers.

### PLEASE ENSURE THAT THE ISSUE REPRODUCES ON THE CURRENT MASTER BRANCH ###

-->

## Expected results
Help the user determine whether they need to apply Linux kernel patches, it they are at a version prior to 5.9. They should not have to read a separate document.

## Actual results
See kernel version with a quick command run
> uname -r
> 5.4.0-89-generic

**Comment by dimakuv** [comment]
Thanks @mkbhanda for the suggestions!

@vijaydhanraj Since you're working on various improvements to our documentation, could you also add the described changes in your PR #198 ? In particular, we want to modify this section: https://gramine.readthedocs.io/en/latest/building.html#upgrade-to-the-linux-kernel-patched-with-fsgsbase

Three things to modify, as requested by @mkbhanda:
- The title of the section will be different (`Required Linux kernel version for SGX`)
- The beginning of the section will be different (smth like `For effortless execution of SGX applications, Linux kernel version 5.9 or higher is required. <and so on>`)
- Somewhere after the first paragraph, note that the user can check Linux version using `uname -r` command.

**Comment by vijaydhanraj** [comment]
Sure, I can do these changes. Also, noticed that we don't talk about kernel versions less than `5.4` where we can use SGX with `OOT` driver and `gsgx.ko` module. Should we add this as well? 

If we don't support this configuration, then I suggest we remove this flag `oot for non-DCAP, out-of-tree version of the driver.` from https://gramine.readthedocs.io/en/latest/building.html#id2.

**Comment by dimakuv** [comment]
@vijaydhanraj I definitely don't want to remove the flags. I still use the Linux version 4.15 :)

We could add some text on Linux 5.3 and lower versions. But just a few sentences, since this is deprecated.

**Comment by vijaydhanraj** [comment]
yes agree, will add a few sentences, and a note saying this is deprecated.

**Comment by vijaydhanraj** [comment]
I have done 

> Thanks @mkbhanda for the suggestions!
> 
> @vijaydhanraj Since you're working on various improvements to our documentation, could you also add the described changes in your PR #198 ? In particular, we want to modify this section: https://gramine.readthedocs.io/en/latest/building.html#upgrade-to-the-linux-kernel-patched-with-fsgsbase
> 
> Three things to modify, as requested by @mkbhanda:
> 
> * The title of the section will be different (`Required Linux kernel version for SGX`)
> * The beginning of the section will be different (smth like `For effortless execution of SGX applications, Linux kernel version 5.9 or higher is required. <and so on>`)
> * Somewhere after the first paragraph, note that the user can check Linux version using `uname -r` command.

I have done 1 and 3 but left 2 as it seems redundant. We have something along these lines (our recommendation) in the `note` of this section.
