### ISSUE TITLE
Doc: provide actual output example from FSGSBASE test

### ISSUE THREAD

**Issue by mkbhanda** [gramineproject/gramine#203]
## Description of the problem
To help new comers use SGX, the easier the instructions are to follow the better.
On https://gramine.readthedocs.io/en/latest/building.html#fsgsbase the user is asked to verify that bit 2 is set. What is the corresponding output that they must expect? An example helps/
## Steps to reproduce
documentation issue

## Expected results
Please share how the output should look.

## Actual results
mkbhanda@sse-tme-wf-01:~$ LD_SHOW_AUXV=1 /bin/true | grep AT_HWCAP2
AT_HWCAP2:            0x0

**Comment by dimakuv** [comment]
@vijaydhanraj Could you add this as well to your #198 ?

In step 6 of https://gramine.readthedocs.io/en/latest/building.html#advanced-installing-linux-kernel-with-fsgsbase-patches, I would change to this example:
```
# Linux kernel doesn't support FSGSBASE: need to patch or use higher version!
$ LD_SHOW_AUXV=1 /bin/true | grep AT_HWCAP2
AT_HWCAP2:       0x0

# Linux kernel supports FSGSBASE
$ LD_SHOW_AUXV=1 /bin/true | grep AT_HWCAP2
AT_HWCAP2:       0x2
```

I verified the above outputs on two machines: one with vanilla Linux 5.4 (no FSGSBASE) and one with Linux 5.14 (with FSGSBASE).

**Comment by mkow** [comment]
@dimakuv But this example is misleading, e.g. 3 or 6 are also valid values indicating that FSGSBASE is supported. Also, this problem is quickly becoming the past, because almost everything supports it right now.

**Comment by dimakuv** [comment]
> @dimakuv But this example is misleading, e.g. 3 or 6 are also valid values indicating that FSGSBASE is supported.

Why misleading? This is just an example. Right before this example, we say that "bit 2 must be set". We can't enumerate all possible values with bit 2 set...

**Comment by mkow** [comment]
But you don't say that this is only an example ;)

**Comment by dimakuv** [comment]
Ok, now I understand. I added a blocking comment in #198.

**Comment by monavij** [comment]
I am not sure we need an example. An example may cause more confusion, as Michal pointed out. The documenation is pretty clear as far as I see it.
