### ISSUE TITLE
Wrong dist-packages folder in manifest

### ISSUE THREAD

**Issue by igor-davidyuk** [gramineproject/gramine#210]
Hello!
I have two pythons - 3.6 and 3.8
I use python 3.8 to run the gramine-manifest script in order to generate a manifest from the template. 
And for some reason, this line still sets dist-packages to the 3.6's path

https://github.com/gramineproject/gramine/blob/f15293dd26af9d7287a77cbd8d952b99639ec994/python/graminelibos/gen_jinja_env.py#L40

**Comment by dimakuv** [comment]
@woju may know better, but `sysconfig` in Python takes a system-wide installed Python directories.

So it looks like you have Python 3.6 installed on your system. And you're using Python 3.8 in a virtual environment (not system-wide) or something like this. Is my assumption correct?

If you want to use Python 3.8 directories and libraries, just replace `distlib` in your Gramine manifest file with the Python 3.8 path.

**Comment by igor-davidyuk** [comment]
Thanks for the quick response!
I do not use a virtual Python env. I just have both 3.6 and 3.8 installed on my machine.
As far as I understand, `gramine-manifest` is a python script and it runs with `python3` link:
https://github.com/gramineproject/gramine/blob/f15293dd26af9d7287a77cbd8d952b99639ec994/python/gramine-manifest#L1
That means jinja will fill variables in a template with correct addresses for the interpreter that runs the script.
So I do not see how I can parameterize even system-wide python version

**Comment by igor-davidyuk** [comment]
I mean, I found an intermediate solution, I run:
`
python3.8 gramine-manifest -args
`
and I made changes to `gen_jinja_env.py` so it returns a correct dist-packages location in my fork:
https://github.com/igor-davidyuk/gramine/commit/823b8aab4fdc9432208d0f1c372474e8e0f02dae

But I do not think it is a universal solution.

**Comment by igor-davidyuk** [comment]
Ideally, it would be nice if manifest could be created even from a virtual env.
From another perspective, we create a manifest not on the same machine that will run the application.
But again, the current solution do not work well either, as the running machine may have another python installed

**Comment by woju** [comment]
> igor-davidyuk@823b8aa

This seems wrong, because it will break default installation on Debian. Instead, we should do something like this: https://github.com/gramineproject/gramine/blob/1a42ee93f1ebe940a684c434cffb4c57ad4cb28d/Scripts/get-python-platlib.py#L63-L78 also in our manifest renderer. I'd be happy to review a PR to this effect.

**Comment by igor-davidyuk** [comment]
> If you run `gramine-manifest` by `/path/to/your/python /usr/bin/gramine-manifest` (i.e., substituting for your own interpreter), you'll get better results. I guess we could think about sourcing this information from other python interpreter (maybe write an exporting script and launch it with a subprocess), but that would be a feature request. Currently, we only support the default `python3` system-wide interpreter.

Thanks, but this also does not work right away, because the first-mentioned line returns dist-packages address for python3

**Comment by igor-davidyuk** [comment]
> > [igor-davidyuk/gramine@823b8aa](https://github.com/igor-davidyuk/gramine/commit/823b8aa)
> 
> This seems wrong, because it will break default installation on Debian. Instead, we should do something like this:
> 
> https://github.com/gramineproject/gramine/blob/1a42ee93f1ebe940a684c434cffb4c57ad4cb28d/Scripts/get-python-platlib.py#L63-L78
> 
> also in our manifest renderer. I'd be happy to review a PR to this effect.

Looks like it should be a universal path postprocessor that modifies all the paths. As it is rather a pathlib problem than `site` package's

**Comment by dimakuv** [comment]
I need to assign some label to this issue. From what I understand, this is not a bug per se but more of a feature request. Also, it doesn't seem too important, so assigning a low priority. If @woju has better ideas on how to handle this issue, please reply.

**Comment by dimakuv** [comment]
I think it was already solved by a recent rewrite of Python variables in the manifest: https://github.com/gramineproject/gramine/pull/999
