### ISSUE TITLE
LTP tests failing with receive_checkpoint_and_restore error after [Pal] Remove the 64MB static buffer commit

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/gramine#215]
## Description of the problem

After the above mentioned commit, seeing multiple LTP tests fail with the following error:

```
[::] error: failed restoring checkpoint at vma (-13)
[::] error: Error during shim_init() in receive_checkpoint_and_restore (-13)
[P1:T1:clock_nanosleep02] error: process creation failed
```

The issue is fixed by #214

**Comment by mkow** [comment]
@jinengandhi-intel Please don't retroactively create issues for which we already have open PRs, it just adds more noise to the repository.
