### ISSUE TITLE
Cannot run helloworld with SGX support

### ISSUE THREAD

**Issue by teotro** [gramineproject/gramine#224]
Hi,

I am using Ubuntu 18.04 and Linux kernel 5.11.0-051100-generic and I have installed sgx-1.36.2 in /usr/src path
I have succesfully completed all the steps of the Quick Start with SGX support

However, I can't run successfully a helloworld program with SGX support.
Specifically, when I give the command:

_**$ gramine-sgx helloworld**_ 

it gives me the following output:

**_Cannot open device /dev/sgx_enclave. Please make sure the Intel SGX kernel module is loaded.
error: load_enclave() failed with error -13_**

However, /dev/sgx_enclave exists, as you can see in the following picture:
![Στιγμιότυπο 2021-11-15, 4 52 04 μμ](https://user-images.githubusercontent.com/70296021/141859075-a9d4b3ed-8ae3-4bf4-aa80-0ae856b73178.png)

Does anyone have any ideas?

**Comment by boryspoplawski** [comment]
Please check `/dev/sgx_enclave` permissions, preferably paste output of `ls -al /dev/sgx_enclave` and `mount | grep devtmpfs`.

Also please don't attach screenshots - you can copy the output of you terminal and paste it here enclosed in triple backtics like this:
\`\`\`
$ ls
file1 file2
\`\`\`

**Comment by teotro** [comment]
Hi,

here are the outputs.

**$ ls -al /dev/sgx_enclave**

. . .
crw------- 1 root root 10, 126 Nov 14 22:21 /dev/sgx_enclave
. . .

**$ mount | grep devtmpfs**

. . . 
udev on /dev type devtmpfs (rw,nosuid,relatime,size=32756584k,nr_inodes=8189146,mode=755,inode64)
. . .

**Comment by teotro** [comment]
*Follow up, this idea struck my mind and proved that worked finally.
If I give the command:

**$ sudo gramine-sgx helloworld**

that works!! And runs the helloworld succesfully

**Comment by boryspoplawski** [comment]
Seems `/dev/sgx_enclave` is owned by `root` and noone else has permissions to access it.
I recommend creating a designated group, changing ownership of `/dev/sgx_enclave` to that group and adding `g+rw` perms to it (use udev have permanent changes). Then add your user to that group. This way you won't have to run everything from root, which is a security issue.
