### ISSUE TITLE
HelloWorld example doesn't output the string

### ISSUE THREAD

**Issue by oubotong** [gramineproject/gramine#237]
## Description of the problem
Running HelloWorld example inside `CI-Example` folder doesn't output any string in the terminal.

## Steps to reproduce

Build the gramine by 
```
meson setup build/ --buildtype=debug -Ddirect=enabled -Dsgx=disabled
sudo ninja -C build/ install

```
Build the helloworld example by `make DEBUG=1`

## Expected results
Output the helloworld string

## Actual results
Nothing is output in the terminal

**Comment by dimakuv** [comment]
@oubotong It works for me. What exactly happens when you try to run `gramine-direct helloworld`?

**Comment by dimakuv** [comment]
Are you using the latest master branch?

**Comment by oubotong** [comment]
No, I am using the `borys/o_calls` branch which as you mentioned that it contains a bug and hasn't been fixed yet. I will wait for th patch and look into the latest branch as well.

**Comment by dimakuv** [comment]
@oubotong Let's consolidate your problems with running Gramine in another of your issues (https://github.com/gramineproject/gramine/issues/236). All discussions will continue there. I'm closing this issue now.

**Comment by igor-davidyuk** [comment]
I having gramine installed from apt I also can not see output from helloworld example

**Comment by dimakuv** [comment]
@igor-davidyuk Please add a line `loader.preload = "file:{{ gramine.libos }}"` in your HelloWorld manifest file. There was a change in the manifest syntax between Gramine v1.0 (installed from apt) and latest Gramine (in the GitHub repo).

In general, you're not supposed to use CI-Examples from the GitHub repository (https://github.com/gramineproject/gramine) to test the apt-installed Gramine. The CI-Examples are tightly coupled with the latest Gramine version (that is found in the GitHub repo).

**Comment by igor-davidyuk** [comment]
@dimakuv Thank you, it worked!
I just followed the [`Quick start` docs page](https://gramine.readthedocs.io/en/latest/quickstart.html#clone-the-repository-and-run-sample-application)

**Comment by dimakuv** [comment]
@igor-davidyuk Sorry, you are right. In our QuickStart doc, we install Gramine v1.0 but ask to run the sample app from the latest Gramine repo.

Instead of changing the documentation, I created a PR (https://github.com/gramineproject/gramine/pull/287) to keep this backward-compatibility in our CI-Examples. Thanks for pointing this out!
