### ISSUE TITLE
[Python] Need a tool to extract/re-generate MRENCLAVE after Gramine enclave "build"

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#242]
## Description of the problem

After the Gramine app is "built" -- i.e., the SGX artifacts are generated: `manifest.sgx` (final manifest file), `.sig` (SIGSTRUCT), `.token` (EINITTOKEN) -- there is no way to extract or regenerate MRENCLAVE. We need some tooling to help Gramine developers and users. In particular, we need two tools:

- For Gramine app developers, a tool to extract MRENCLAVE (and other fields) from the `.sig` (SIGSTRUCT) file.

-  For Gramine app users, a tool to re-generate MRENCLAVE from the following inputs:
    - final `manifest.sgx` file
    - Gramine binaries or their SHA256 hash or Gramine version (in latter case, need a mapping from version -> SHA256 hash)
    - Other binaries (or not? everything is already specified in `manifest.sgx`)
    - Anything else?

For the first tool, we have snippets of this logic in our other code: https://github.com/gramineproject/gramine/blob/c14104a5ff12ef4894c8a6a230de5b7ba7de8900/python/graminelibos/sigstruct.py#L111 and https://github.com/gramineproject/gsc/blob/3c4f89a2b6fae06d4c5e5d030045dc115e58c16f/gsc.py#L333.

For the second tool, we have snippets of this logic: https://github.com/gramineproject/gramine/blob/c14104a5ff12ef4894c8a6a230de5b7ba7de8900/python/graminelibos/sgx_sign.py#L317

These tools are needed for cases where the developer forgot to memorize MRENCLAVE during gramine-sign process, and when the user wants to double-check the MRENCLAVE generated by e.g. independent software vendor. There is also a follow-up question: how can the user verify the correctness of SHA256 hashes inside `manifest.sgx` file?

**Comment by dimakuv** [comment]
@mkow @woju @boryspoplawski We discussed this offline several times, but I couldn't find a corresponding GitHub issue. So created this one.

We have more and more asks like this from different people. I know we have our `Python API` (https://gramine.readthedocs.io/en/latest/python/api.html), which makes it relatively easy to create tools like I described. But don't we want to have such tools shipped together with Gramine?

**Comment by dimakuv** [comment]
(Please note that the proposed tools are **not** for enclave signing purposes. The proposed tools are only for post-signing actions like checking existing-enclaves' measurements.)

**Comment by boryspoplawski** [comment]
Case 1:
```python
from graminelibos import Sgistruct
from pathlib import Path

print(Sigstruct.from_bytes(Path('path_to_sig_file').read_bytes())['enclave_hash'].hex())
```

Case 2a (requires exporting `get_mrenclave_and_manifest`):
```python
from graminelibos import get_mrenclave_and_manifest

mrenclave, _ = get_mrenclave_and_manifest(path_to_manifest, path_to_libpal)
```

Case 2b (works on current master):
```python
from graminelibos import get_tbssigstruct

sig = get_tbssigstruct(path_to_manifest, any_date, path_to_libpal)
print(sig['enclave_hash'].hex())
```

**Comment by dimakuv** [comment]
Thanks @boryspoplawski for the snippets. For the first tool, we probably want to have Click-style arguments and export different SIGSTRUCT fields, not only MRENCLAVE. Or we can simply dump the whole Sigstruct object to console.

The question is now about packaging: do we want to have such tools (with names like `gramine-get-measurements` and `gramine-regenerate-mrenclave`) in Gramine?

**Comment by vijaydhanraj** [comment]
Tools like `gramine-regenerate-mrenclave` would be much helpful for end-users (not Gramine developers) as they can now compare the `mrenclave` from the quote with the golden `mrenclave` generated by this tool and can proceed further with trust.

**Comment by monavij** [comment]
I believe this issue was initially discussed in Graphene issue #2208 that was closed with the assumption that it will be resolved by https://github.com/gramineproject/gramine/issues/11. So based on what Borys describes above we have the APIs, but we do need to have explicit tools like what Dmitrii and Vijay are suggesting.   I think the tools like gramine-regenerate-mrenlcave should be sufficient for FL use case as well, but we should verify with those teams to make sure that we are not missing something.

**Comment by dimakuv** [comment]
Reviving the old thread: @boryspoplawski @mkow @pwmarcz @woju Do you think such explicit tools would be useful?

We on the Intel side (me, Mona, Vijay and others) think that at least the `gramine-regenerate-mrenclave(path-to-manifest)` would be a useful tool. As @boryspoplawski mentioned above, it is just a couple of lines of code in Python.

**Comment by boryspoplawski** [comment]
I think we should finally add some tool for pretty printing sigstructs, that would be much more useful.
I don't think we need a separate Python API, existing functionality covers it in all cases. The best we can do is add some examples in docs.

**Comment by mkow** [comment]
@dimakuv: One problem which makes this harder than just creating a  "generate MRENCLAVE" is that MRENCLAVE is not enough. Remember the security issue which a lot of frameworks had some time ago - we need to consider other attributes too, which surprisingly aren't hashed into it.
So, we need a tool which generates a measurement / some token, but in such a way that it depends on everything that's important.

Anyways, this is a longer topic which IMO requires more discussions than it seems. Let's finish current tasks and then try to work on it.

**Comment by dimakuv** [comment]
@mkow Sure. These are details which we can hash out while working on this. Ideally, as Borys mentions, we have a tool that by default pretty-prints all relevant SIGSTRUCT fields (irrelevant ones are: date, header, header2). We have something similar in GSC, but I'd like to have it also as a completely separate tool: https://github.com/gramineproject/gsc/blob/master/gsc.py#L394-L408

Plus in this tool, we'll have a command-line switch to print only the subset of the fields (and if some important fields are ommitted from the output, the tool also prints a warning "Some security-relevant fields were not printed: field1, field2, ...").
