### ISSUE TITLE
Rust HTTP server freezes when receiving request (epoll)

### ISSUE THREAD

**Issue by tux3** [gramineproject/gramine#247]
## Description of the problem

This issue seems to have similar symptoms as in https://github.com/gramineproject/gramine/issues/186 (epoll_wait gets stuck), but it is not obvious to me whether the root cause is the same.

I have a minimal example that repros the bug almost all the time (on my machine), and since I'm using a completely different stack as #186 (Rust / tokio instead of the Golang runtime that does syscalls directly), it should be a good testcase.

Note that we hit this bug very easily whenever we use Rust with Tokio, or Boost (both use `epoll`) inside an enclave. It is usually in the form of a race condition. For some programs it fails only 1 in 10 times, or it can fail almost every time (this repro fails every time for me).

## Steps to reproduce

- Build and install Gramine e3c28cb85b379b8ed8ec5dc56e47ec5e0ef23a7d (master HEAD as of a few hours ago)
- Checkout https://github.com/tux3/gramine_epoll_repro
- Make sure you have a recent rust toolchain (https://rustup.rs)
- Run `make run-release`
- You should see the program run and freeze with the last few lines looking like:
```
[P1:T4:gramine_epoll_repro] trace: ---- return from shim_epoll_wait(...) = -514
[P1:T2:gramine_epoll_repro] trace: ---- return from shim_epoll_wait(...) = -514
[P1:T4:gramine_epoll_repro] trace: ---- shim_epoll_wait(10, 0x34001790, 1024, -1) ...
[P1:T2:gramine_epoll_repro] trace: ---- shim_epoll_wait(3, 0x2a274630, 1024, -1) ...
```
The pattern of T2 and T4 getting stuck on epoll_wait is the bug. It seems to happen because T3 consistently fails to wakeup T4.

In case you do not repro immediately (program outputs a message and aborts), run the following loop until the console freezes:

`while true; do gramine-sgx target/release/gramine_epoll_repro 2>&1 | tee badlog; done`

Press ^C and the log with call trace should appear in file `badlog`.

Platform details:
- Ubuntu 20.04.3 LTS (GNU/Linux 5.11.0-1021-azure x86_64)
- Azure Standard DC1ds v3 (1 vcpu, 8 GiB memory) (Icelake 8370C)

## Expected results

When the program is run directly (`cargo run --release`), the server sends itself an HTTP request, handles it, and shuts down.  
The program should not freeze, but print a message and abort.

## Actual results

The program freezes as shown above.

**Comment by dimakuv** [comment]
Thanks @tux3 for the awesome bug report!

@boryspoplawski Now *this* issue looks like a similar problem with our epoll implementation, right? The repro linked in this issue may be useful to you.

**Comment by boryspoplawski** [comment]
@tux3 thanks, such small repro will surely come in handy!

@dimakuv I don't think this is the same issue (well, I don't know, but at least it manifests differently), but it's definitely epoll bug. I've encountered deadlocks with rust aysncs before as well, but it was always some huge app and never got to debug it.

**Comment by boryspoplawski** [comment]
@tux3 could you verify that https://github.com/gramineproject/gramine/pull/340 fixes the issue? It did for my tests

**Comment by tux3** [comment]
@boryspoplawski

Thank you for the update. I tried #340 (as of 79e7a1afecafe20c1a9c6e89d7f27d777a12349c), and the good news is that I don't see the same error as before with `shim_epoll_wait`, and it doesn't deadlock every time for me anymore.  

However, I still see a deadlock about 30% of the time even with #340. The gramine log at the point where it gets stuck looks like this now (it always freezes in the same place):

```
[...]
[P1:T4:gramine_epoll_repro] trace: ---- shim_epoll_wait(10, 0x34001790, 1024, -1) ...
[P1:T3:gramine_epoll_repro] trace: ---- return from shim_futex(...) = 0x0
[P1:T3:gramine_epoll_repro] trace: ---- shim_write(11, 0x251716d0, 0x8) ...
[P1:T4:gramine_epoll_repro] debug: Creating pipe: pipe.srv:5ed68089ed2c5c69223f997c64ee5b016b27f097a28d0fe14835f9097128ef90
[P1:T3:gramine_epoll_repro] trace: ---- return from shim_write(...) = 0x8
[P1:T3:gramine_epoll_repro] trace: ---- shim_futex(0x340084a8, FUTEX_PRIVATE|FUTEX_WAIT, 0, 0, 0, 0) ...
<HTTP server freezes here>
```

I used the same code to repro than before, only updating the Gramine version on my test VM.  
I've also attached the full Gramine log, in case it helps: [badlog.log](https://github.com/gramineproject/gramine/files/7954763/badlog.log)

**Comment by boryspoplawski** [comment]
@tux3 thanks!

I was able to reproduce it as well. It did not trigger for me before on multi cpu system, but turning all cores but one offline made it trigger.

The problem is our emulation of `EPOLLET` with `eventfd` - we cannot emulate it 100% correctly and with exact same semantics as in Linux.
Rust (tokio) uses it in a peculiar way: it registers an `eventfd` with `EPOLLET` does `epoll_wait` and `write(eventfd, 1)`. It never does any reads - it doesn't have to, since each write always increases the counter by 1 and thanks to `EPOLLET` each event (so each write) is reported only once, regardless of the current eventfd counter state.

I've added a bit hacky workardound to #340 (60321f7e28bf12e707f36fae1fe20c4a16ea13ae at the time of writing this, but I'll push soon probably, any commit after that will do), could you try again?

**Comment by tux3** [comment]
@boryspoplawski Thank you, I can confirm it works with 60321f7e28bf12e707f36fae1fe20c4a16ea13ae !

**Comment by boryspoplawski** [comment]
Good to hear. Thanks for the detailed report, it was very helpful!
