### ISSUE TITLE
run a program calling "sgx_qe_get_target_info()", always show "Failed to open Intel SGX device."

### ISSUE THREAD

**Issue by dingfangming** [gramineproject/gramine#253]
Hi gays,

When i run a program which call sgx_qe_get_target_info() function to get QE3 target info, it always show "Failed to open Intel SGX device."

I am working on ubuntu21.04 with kernel 5.11.0-40-generic, on a SGX1 machine. And more info:

1.uname -a
Linux points 5.11.0-40-generic #44-Ubuntu SMP Wed Oct 20 16:16:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

2. is_sgx_available
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): false
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): false
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): false
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): false
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x1000000000
EPC size: 0xbd80000
SGX driver loaded: true
AESMD installed: true
SGX PSW/libsgx installed: true

3. ls -al /dev/sgx
points@points:~/fmding/gramine/CI-Examples/helloworld/QuoteGenerationSample$ ls -al /dev/sgx*
crw-rw---- 1 root sgx     10, 126 Nov 23 12:19 /dev/sgx_enclave
crw-rw---- 1 root sgx_prv 10, 125 Nov 23 12:19 /dev/sgx_provision
/dev/sgx:
total 0
drwxr-xr-x  2 root root   80 Nov 22 10:28 .
drwxr-xr-x 22 root root 4320 Nov 23 12:19 ..
lrwxrwxrwx  1 root root   14 Nov 23 12:19 enclave -> ../sgx_enclave
lrwxrwxrwx  1 root root   16 Nov 23 12:19 provision -> ../sgx_provision

4.gramine-sgx quotegen
[get_section /home/points/fmding/linux-sgx/psw/urts/parser/elfparser.cpp:82] section [22] .shstrtab: sh_addr = 0, sh_size = c4, sh_offset = d85bc, sh_name = 1
[enclave_create_ex sgx_enclave_common.cpp:594]
 secs->attibutes.flags = 14, secs->attributes.xfrm = 7
[get_driver_type /home/points/fmding/linux-sgx/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
[enclave_create_ex sgx_enclave_common.cpp:602]
create enclave: failed to find a driver
[load_pce ../pce_wrapper.cpp:175] Error, call sgx_create_enclave for PCE fail [load_pce], SGXError:2006.
[ecdsa_init_quote ../qe_logic.cpp:1197] Error, call sgx_pce_get_target [ecdsa_init_quote], pce_error:f004.
[CEnclavePool /home/points/fmding/linux-sgx/psw/urts/enclave.cpp:638] enter CEnclavePool constructor
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:hunter 204L, enclave_create_ex done, enclave_error=1

In linux-sgx/psw/urts/linux/edmm_utility.cpp:111,
102     int hdev = open("/dev/sgx/enclave", O_RDWR);    //attempt to open the in-kernel driver
103     if (-1 == hdev)
104     {
105         hdev = open("/dev/isgx", O_RDWR);    //attempt to open the out-of-tree driver
106         if (-1 == hdev)
107         {
108             hdev = open("/dev/sgx", O_RDWR);  //attempt to open the DCAP driver
109             if (-1 == hdev)
110             {
111                 SE_PROD_LOG("Failed to open Intel SGX device.\n");
112                 return false;
113             }
114             sgx_driver_type = SGX_DRIVER_DCAP;
115         }
116         else
117         {
118             sgx_driver_type = SGX_DRIVER_OUT_OF_TREE;
119         }
120     }

but sample code helloworld can work well in my machine. 
please help to check, thanks!

**Comment by dimakuv** [comment]
https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/107 -- please try to run your Gramine app with `SGX_AESM_ADDR=1`. This forces the SGX DCAP library to use out-of-proc mode to communicate with the QE (Quoting Enclave). From what I understand, you application fails because the SGX DCAP library by default tries to use the in-proc mode -- which makes no sense: all code is executed inside the SGX enclave already, and the SGX DCAP library tries to create a new enclave from inside an existing enclave, which is not allowed.

Unfortunately, noone from the SGX DCAP team replied to my request yet (as can be seen from the issue linked above).

So, please try to run your app like this: `SGX_AESM_ADDR=1 gramine-sgx quotegen`.

**Comment by mkow** [comment]
Yup, from the logs it seems that @dingfangming is running SGX SDK app inside Gramine... So I'm closing this as unrelevant to Gramine.
@dingfangming: Please either use SGX SDK or Gramine, you can't use two different SGX frameworks at the same time. Also, please format your issues using proper Markdown, it was very hard for me to see which parts of your message are the logs and which are your comments.
