### ISSUE TITLE
With Go program, when server program does a read, getting permission denied.

### ISSUE THREAD

**Issue by sudharkrish** [gramineproject/gramine#261]
## Description of the problem
With Go program, when server program does a read, getting permission denied.

## Steps to reproduce
Able to reproduce on a recent graphene pull(Aug 30th, 2021), commit-id-> c321726229eaf0a1b52dc5e2507c9cfab423ea94
Also able to reproduce on [https://github.com/oscarlab/graphene/releases/tag/v1.2-rc1](url)

Providing Sample Go program and scripts to reproduce the issue.

In graphene repo, under your /home->/graphene/Examples directory, copy this zip file->( 
[go_sample.zip](https://github.com/oscarlab/graphene/files/7109004/go_sample.zip)) , and then unzip it,
to create go_sample directory under /graphene/Examples/go_sample.
 
Under /graphene/Examples/go_sample$ 
Run the script -> ./launch_in_graphene_locally.sh 
This will build the sample Go program(in a docker container), and then do a graphene-sgx build, and
then it will launch it locally on your host system.

When the Go Server code does a read, getting permission denied.

## Expected results
Output below, when running the same Go program, outside of Graphene.
Examples/go_sample$ ./main 
SK_DBG: listening on  172.17.0.1:8805
client: wrote: hello
server: read: hello

## Actual results
In Graphene, when the Go Server code does a read, getting permission denied.

[P17460:T1:main] debug: Allocating stack at 0x0 (size = 8388608)
[P17460:T1:main] debug: loading "file:./main"
[P17460:T1:main] debug: adding a library for gdb: file:./main
[P17460:T1:main] debug: Creating pipe: pipe.srv:17460
debug: sock_getopt (fd = 11, sockopt addr = 0x7ffda07f52b0) is not implemented and always returns 0
[P17460:T1:main] debug: Shim process initialized
[P17460:shim] debug: IPC worker started
[P17460:T1:main] debug: Created sigframe for sig: 23 at 0xc4009390 (handler: 0x460be0, restorer: 0x460d20)
debug: sock_getopt (fd = 12, sockopt addr = 0x7ffda07f52b0) is not implemented and always returns 0
[P17460:T1:main] debug: Creating pipe: pipe.srv:8fcf6dd6dc08723b8328139ef1955390c16982da3379e1b7f6c07bc4bdc66514
debug: sock_getopt (fd = 15, sockopt addr = 0x7ffda07f52b0) is not implemented and always returns 0
debug: sock_getopt (fd = 16, sockopt addr = 0x7ffda07f52b0) is not implemented and always returns 0
debug: sock_getopt (fd = 17, sockopt addr = 0x7ffda07f52b0) is not implemented and always returns 0
[P17460:T1:main] debug: add fd 5 (handle 0xfb098610) to epoll handle 0xfb098550
[P17460:T1:main] debug: add fd 3 (handle 0xfb0983c0) to epoll handle 0xfb098550
SK_DBG: listening on  172.17.0.1:8805
Allowing access to an unknown file due to file_check_policy settings: file:/etc/localtime
2021/09/03 18:08:33 read udp 172.17.0.1:8805: read: permission denied

## Additional information
Go sample code under gopro2 folder in zip file attached.
When Go Program calls net.ListenUDP, this api invokes 2 syscalls, 1. to create socket, 2. bind
When Go server program calls net.ListenUDP these 2 syscalls are successful.
Go program launches a light-weight thread that runs the Client-function, which tries to connect to the server using
Go's net.DialUDP function, and then does  a write. Later, server code tries to do a read, and this is where it fails,
with permission denied error(shown in the log above).

**Comment by boryspoplawski** [comment]
@sudharkrish please verify that https://github.com/gramineproject/gramine/pull/579 fixes the issue. It does for me.

**Comment by skris14** [comment]
@boryspoplawski , due to system upgrade to newer ubuntu, and other setup issues, not able to quickly test this. Since, it works for you, you can close this PR.
