### ISSUE TITLE
[BUG] allow file in trusted files to not exist, fail during runtime read only

### ISSUE THREAD

**Issue by lead4good** [gramineproject/gramine#263]
I'm currently working on a buildpack port for gramine and I have run into the following issue: there's a script finalizing the manifest similar to the one in GSC, that scans the whole container for existing files. However the container where this happens is a special build container, which has additional binaries and libraries installed vs. the run container, which is a slimmer version of the build container.

Currently if gramine is run with a manifest including trusted files which do not exist, it fails on startup:
```
Attributes:
    mr_enclave:  df2a0a1aeb6a57d6ba6a6c4a06b0ca2600a642bf256ebc88266f37ffc284480c
    mr_signer:   d918341457d7237453d01a49fbff9735b5f99a951e34779bd69f99426ec55167
    isv_prod_id: 0
    isv_svn:     0
    attr.flags:  0000000000000004
    attr.xfrm:   0000000000000007
    mask.flags:  ffffffffffffffff
    mask.xfrm:   ffffffffffffff1b
    misc_select: 00000000
    misc_mask:   ffffffff
    modulus:     878f9a40fb19f26c34b15fc71cd1986a...
    exponent:    3
    signature:   d03c7d80422a1260e6cd550f18a3979a...
    date:        2021-12-03
error: Could not find size of file: file:/usr/bin/gcc-ranlib
error: Reading trusted files (in TOML-array syntax) from the manifest failed: Stream does not exist
error: Failed to initialize trusted files: -9
```
https://github.com/gramineproject/gramine/blob/c693d174f44808af556517a6c2109173364cec65/Pal/src/host/Linux-SGX/enclave_framework.c#L563
https://github.com/gramineproject/gramine/blob/c693d174f44808af556517a6c2109173364cec65/Pal/src/host/Linux-SGX/enclave_framework.c#L920

To deal with this case ideally there should be a flag that allows to skip checking non existent trusted files on startup but fail during a runtime read. With this behavior I do not see any security risks at the moment?

I also tried setting some non existing trusted files on the allowed_files list, which did not change the error, so it seems trusted_files are privileged in this case. Is this intentional?

**Comment by dimakuv** [comment]
You're mixing several things in your issue.

1. You're talking about Trusted Files, but your link is to Protected Files (it even says so in the log error). Trusted and Protected files are two different beasts, declared via two different manifest lists (`sgx.trusted_files` and `sgx.protected_files`). So which ones are you talking about in this issue?
2. Gramine **doesn't verify** that Trusted/Protected/Allowed files exist at startup. Gramine only verifies these files during a runtime open/read. Why do you think your error is connected to actually accessing files?

You may have confused `Reading ... files from the manifest` with `Reading ... files from the hard drive`. These are very different errors. If you got the `Reading ... files from the manifest` error, it means exactly what it means: something in your manifest file's `sgx.trusted_files`/`sgx.protected_files` lists cannot be parsed by our TOML parser.

My suspicion is that you have some weird filename (e.g., with a `"` in its name?) in the manifest list, and it is not correctly escaped. Another issue may be that you have duplicate list items.

**Comment by lead4good** [comment]
@dimakuv Sorry for the confusion, I did not double check my error message grepping and ended up looking at the wrong part of the code. I've updated the issue description accordingly.

Also to clarify things: this error only happens if the file mentioned does not exist. If I `touch` the non existing file and restart gramine it complains about a different file.

**Comment by dimakuv** [comment]
@lead4good Thanks for the clarifications!

Yes, now I can see the issue: https://github.com/gramineproject/gramine/blob/c693d174f44808af556517a6c2109173364cec65/Pal/src/host/Linux-SGX/enclave_framework.c#L563

Indeed, we have a strange code snippet when we register the trusted file. For whatever reason, we want to initialize `tf->size`, and for this we call `_DkStreamAttributesQuery()` which tries to access the file. So this indeed fails if the file doesn't exist.

This is a bug in our code... You are right, I don't see a reason to fail if some trusted file is not found (but also never accessed by the app). @mkow @boryspoplawski @pwmarcz What do you think about this?

**Comment by boryspoplawski** [comment]
I would say that the underlying problem is that we use host fs to store file metadata, but this particular issue is probably fixable by lazy initializing the size. I see no problem with that, but I'm not familiar with that part of the code.

**Comment by jkr0103** [comment]
Please assign to me.

**Comment by jkr0103** [comment]
Please assign to me
