### ISSUE TITLE
Is it possible to get trusted performance counters?

### ISSUE THREAD

**Issue by h4x3rotab** [gramineproject/gramine#266]
I'm looking for solutions to measure the execution time of the program inside the enclave in a trusted way for resource accounting, because we don't want to trust the system admin.

It's easy to check the performance counters or the wall time in the untrusted world, but I'm wondering if we can get the trusted measurements when we don't trust users. I noticed the sgx profiling section in the docs. Can it be attested, or is it still the untrusted metrics from the OS?

**Comment by mkow** [comment]
Please keep such questions to the mailing list ;) We use GitHub issues only to track bugs/missing features/etc. for the project.
