### ISSUE TITLE
Regression with musl commit: host_root_fs LibOS testcase is failing on CentOS/RHEL

### ISSUE THREAD

**Issue by aniket-intelx** [gramineproject/gramine#270]
## Description of the problem
`host_root_fs` LibOS testcase is failing on CentOS/RHEL with below error.
```
Error loading shared library ld-musl-x86_64.so.1: Permission denied (needed by host_root_fs)
Error relocating host_root_fs: putchar: symbol not found
Error relocating host_root_fs: printf: symbol not found
Error relocating host_root_fs: puts: symbol not found
Error relocating host_root_fs: readdir: symbol not found
Error relocating host_root_fs: opendir: symbol not found
Error relocating host_root_fs: __libc_start_main: symbol not found
Error relocating host_root_fs: closedir: symbol not found
```
When we tried to locate the file `ld-musl-x86_64.so.1`, it is found in below mentioned locations.
```
sudo find / -name "ld-musl-x86_64.so.1"
[sudo] password for intel:
find: ‘/run/user/1000/gvfs’: Permission denied
/usr/lib/ld-musl-x86_64.so.1
/usr/lib64/ld-musl-x86_64.so.1
/usr/local/lib64/gramine/runtime/musl/ld-musl-x86_64.so.1
```
After enabling the `trace` mode, the test is looking for the file at below path and failing.
```
shim_open("/usr/x86_64-linux-musl/lib64/ld-musl-x86_64.so.1", O_RDONLY|0x88000, 0000) ...
[P1:T1:host_root_fs] trace: ---- return from shim_open(...) = -2
Error loading shared library ld-musl-x86_64.so.1: No such file or directory (needed by [P1:T1:host_root_fs] trace: ---- shim_writev(2, 0x29f76bdd5780, 2) = 0x57
```
Please note that this is the only testcase which is failing on CentOS/RHEL. Similar failure is not seen in Ubuntu.
## Actual results
Please find the attached log.

[host_root_fs_cent_failure.txt](https://github.com/gramineproject/gramine/files/7667284/host_root_fs_cent_failure.txt)

**Comment by boryspoplawski** [comment]
@aniket-intelx Please verify if https://github.com/gramineproject/gramine/pull/271 fixes the issue

**Comment by aniket-intelx** [comment]
It works with this PR.

**Comment by boryspoplawski** [comment]
@aniket-intelx Thanks for confirmation, we will merge it then

**Comment by dimakuv** [comment]
#271 was merged, closing this.
