### ISSUE TITLE
SSL Certificate verification failed

### ISSUE THREAD

**Issue by saruvig** [gramineproject/gramine#292]
I am trying to run the following python script on gramine. I am using the same template as used in /examples/PyTorch/ and have followed all the prerequisite steps. The PyTorch example is working fine.
[basic_cifar_copy.txt](https://github.com/gramineproject/gramine/files/7749950/basic_cifar_copy.txt)

The issue comes on line 43 when trying to load the CIFAR10 dataset. It is an SSL certificate verification failed problem. I tried installing the certi using "python3 -m pip install certifi". It is already installed. 

![image](https://user-images.githubusercontent.com/23428423/146880458-2bf620b9-8e59-4cce-8bd8-25ae9ca46400.png)

**Comment by dimakuv** [comment]
Please add/change `loader.log_level = "all"` in your manifest file, rebuild the `manifest.sgx` file, and re-run the application.

Then please attach the resulting debug log to the issue (or analyze it yourself). This will give some hints what goes wrong with your application.

I have a suspicion that some files or FS mount points are not added to your manifest template.

Also, does this error happen in `gramine-direct`? Could you try it?

**Comment by saruvig** [comment]
I solved the above issue by editing my python script but am getting another error of permission denied while downloading the CIFAR 10 dataset.
[log.txt](https://github.com/gramineproject/gramine/files/7751013/log.txt)
 
above is the log file for the application now. 

When I try to run gramine-direct, I get the following error:
![image](https://user-images.githubusercontent.com/23428423/146902699-9cf0d727-5ce2-4966-b517-3339d4cf0004.png)

**Comment by saruvig** [comment]
The earlier SSL error resolved when i added the following lines to my basic_cifar.py code

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

**Comment by dimakuv** [comment]
@saruvig The log says it all:
```
[P1:T1:python3.8] trace: ---- shim_stat("./dataset/cifar-10-batches-py/data_batch_1", 0x1da041030) = 0x0
warning: Disallowing access to file 'dataset/cifar-10-batches-py/data_batch_1'; file is not protected, trusted or allowed.

... some more messages ...

Original exception was:
Traceback (most recent call last):
  File "./basic_cifar.py", line 128, in <module>
    main()
  File "./basic_cifar.py", line 110, in main
    trainloader, testloader = load_cifar_data()
  File "./basic_cifar.py", line 48, in load_cifar_data
    trainset = CIFAR10(DATA_ROOT, train=True, download=True, transform=transform)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 66, in __init__
    self.download()
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 141, in download
    if self._check_integrity():
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 136, in _check_integrity
    if not check_integrity(fpath, md5):
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 70, in check_integrity
    return check_md5(fpath, md5)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 62, in check_md5
    return md5 == calculate_md5(fpath, **kwargs)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 55, in calculate_md5
    with open(fpath, 'rb') as f:
PermissionError: [Errno 13] Permission denied: './dataset/cifar-10-batches-py/data_batch_1'
```

So, you forgot to add the `dataset/cifar-10-batches-py/data_batch_1` file in one of the `sgx.allowed_files`, `sgx.trusted_files`, `sgx.protected_files` lists. (In which list to add, depends on your purposes.)

As for `gramine-direct`, the "Emulating a raw system/supervisor call" is *not* an error. It's just a message from Gramine that tells you -- performance may be affected, because your Python script does something quite unorthodox -- it uses raw syscall calls. You can ignore this message for now.

**Comment by saruvig** [comment]
Thanks for pointing it out. I was able to run the code after adding the files to sgx.allowed in the manifest so closing the issue now.
