### ISSUE TITLE
GSC Failed to load entrypoint (missing shebang support in `execve()`)

### ISSUE THREAD

**Issue by dzygann** [gramineproject/gramine#320]
Hi,

as you can see in issue gramineproject/graphene#2632 we're trying to run Postgres in Graphene. OS is Ubuntu 20.04.

Contrary to issue gramineproject/graphene#2632 we didn't use our own dockerfile, but instead, we used one from Dockerhub `https://hub.docker.com/_/postgres`

Then again we build and signed it using gsc.
When trying to run this image however we encountered the following problem:
```
[P9:T1:docker-entrypoint.sh] error: Failed to load /docker-entrypoint.sh. This may be caused by the binary being non-PIE, in which case Graphene requires a specially-crafted memory layout. You can enable it by adding 'sgx.nonpie_binary = 1' to the manifest.
[P9:T1:docker-entrypoint.sh] error: Error during shim_init() in init_loader (-22)
```

If we follow the instruction to add the `sgx.nonpie_binary = 1` we get the following error: 

```
Parsing /entrypoint.manifest as TOML failed: Duplicate keys! (line 26 column 1 char 1073)
```

We have also used the -L option during the gsc build, but there are no more debug information available. 

Do you have any ideas to fix this issue?

Thanks in advance.

**Comment by Michael-M-Zhang** [comment]
Is this issue still exist now?

**Comment by mkow** [comment]
@Michael-M-Zhang The implementation of this feature is WIP at the moment: https://github.com/gramineproject/gramine/pull/459
