### ISSUE TITLE
[Discussion] best way to do argv parameter expansion

### ISSUE THREAD

**Issue by lead4good** [gramineproject/gramine#324]
I would like to make use of [bash paramater expansion](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html) within the application arguments. This does work if I run a gramine application via `bash -c "..."`. Are there any performance penalties with this approach?

**Comment by dimakuv** [comment]
No, there is no significant performance penalty (but read further!). I just verified it with the https://github.com/gramineproject/gramine/tree/master/CI-Examples/bash example.

I guess you were wondering whether Gramine creates a separate enclave when `bash` spawns a new process (e.g., `bash -c ls`). The (simplified) answer is **no**: Gramine does **not** create a separate enclave for the emulation of the `execve()` syscall. Instead, the same SGX enclave is "erased" and re-populated with the contents of the new process (`ls` in my example). This is a fast operation, in contrast to creating a new SGX enclave.

Here is my example: 
```
gramineproject/gramine/CI-Examples/bash$ gramine-sgx bash -c 'ls *.${0:5}' dummymanifest
bash.manifest
```

In this example, I'm asking bash to run `ls *.manifest` (the parameter expansion `${0:5}` removes the `dummy` prefix in the first argument `dummymanifest`). Which gives me only one output entry: `bash.manifest`.

But be aware! Bash is quite tricky, I highly recommend reading through this:
- https://unix.stackexchange.com/questions/466496/why-is-there-no-apparent-clone-or-fork-in-simple-bash-command-and-how-its-done
- https://unix.stackexchange.com/questions/401020/why-bash-does-not-spawn-a-subshell-for-simple-commands/466519
- https://unix.stackexchange.com/questions/144514/add-arguments-to-bash-c

As an experiment, I verified that my bash 4.4.20 on Ubuntu 18.04 performs a fork on this invocation:
```
bash -c 'string=dummymanifest; ls *.${string:5}'
# oops! above is slow in Gramine-SGX because it creates a child SGX enclave
```

**Comment by dimakuv** [comment]
(Of course, the best way to experiment with all this is to run your application natively under `strace` -- you'll get all the system calls that the app uses. And then run your graminized application with `loader.log_level = "trace"` in the manifest file -- you'll get all the system calls that Gramine intercepts and emulates.)

**Comment by lead4good** [comment]
@dimakuv Thanks, this was very helpful. I wonder why GSC does not use the approach of starting applications via bash. It would make situations work where the entrypoint is a script, which does happen quite often with docker containers.

**Comment by dimakuv** [comment]
> I wonder why GSC does not use the approach of starting applications via bash. It would make situations work where the entrypoint is a script, which does happen quite often with docker containers.

Hm, looks like you're right. @mkow @boryspoplawski @aneessahib Do you think it will just work if we replace the original Docker entrypoint with the `gramine-sgx "bash -c original-entrypoint"` value?

In GSC, the changes will be here (approximately, didn't give a lot of thought to it):
- https://github.com/gramineproject/gsc/blob/634ef1ad0a32795f4b61de66b13c1973a64af314/templates/entrypoint.manifest.template#L2 (`loader.entrypoint = "bash"`)
- https://github.com/gramineproject/gsc/blob/634ef1ad0a32795f4b61de66b13c1973a64af314/templates/apploader.template#L15 (adding `bash -c "..."` as the command-line arguments to `gramine-sgx`/`gramine-direct`)

**Comment by mkow** [comment]
Isn't this mostly to preserve resources? But after the EDMM support gets upstreamed to the kernel and implemented in Gramine we could think about changing this.

**Comment by dimakuv** [comment]
> Isn't this mostly to preserve resources?

Which resources? `bash -c <actual-app>` uses `execve()`, so there is no performance overhead of creating a child SGX enclave. Of course, overall startup time will be *slightly worse* because we first load the `bash` binary and only then the actual binary, but this is probably negligible.

**Comment by aneessahib** [comment]
This makes sense. We actually made bash as the default entry point for some of the validation teams to fix some issues they observed while running scripts. But I misunderstood this to be actually spawning another child underneath.

**Comment by mkow** [comment]
> `bash -c <actual-app>` uses `execve()`, so there is no performance overhead of creating a child SGX enclave.

Ah, ok, then this may make sense. Although I'm not sure if Docker uses bash, more likely `/bin/sh`? If so, then some popular minimal images may lack bash binary?

**Comment by dimakuv** [comment]
>  Although I'm not sure if Docker uses bash, more likely /bin/sh? If so, then some popular minimal images may lack bash binary?

Yes, bash was just a "common name" for shells. We should use the `/bin/sh` link actually.

**Comment by boryspoplawski** [comment]
`bash -c ...` doesn't use execve, at least not always. E.g. `bash -c 'ls ; ls'`
As for starting scripts: we should add interpreter scripts support (`#!`) and it should all work properly without `bash -c` then

**Comment by dimakuv** [comment]
> As for starting scripts: we should add interpreter scripts support (`#!`) and it should all work properly without `bash -c` then

I think you're talking about support for `execve("#!...")` in core Gramine. I was talking about GSC support (starting entrypoint *scripts*, currently GSC only supports starting entrypoint *binaries*).

> `bash -c ...` doesn't use execve, at least not always. E.g. `bash -c 'ls ; ls'`

Yes, but GSC won't use such multiple-command invocations.

**Comment by boryspoplawski** [comment]
Isn't Gramine entrypoint and `execve` handled in the same way/by the same code (ofc there are differences in cleaning old state in case of execve, but starting new exec should be the same)?

**Comment by dimakuv** [comment]
@boryspoplawski No, the code is different unfortunately:

- https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/LibOS/shim/src/shim_init.c#L503
- https://github.com/gramineproject/gramine/blob/e37f773d4d910799a854b90334f2ff8eb6f411bd/LibOS/shim/src/sys/shim_exec.c#L172

The first link contains the `shim_init()` code that simply calls the `execute_elf_object()` function -- this assumes an ELF binary. The second link contains the `shim_do_execve()` syscall that does more checks, including a TODO for the shebang implementation.

So the only code that is unified is the ELF-binary loading. Of course, we could refactor that code to support shebangs everywhere.

**Comment by boryspoplawski** [comment]
@dimakuv Both of these cases do mostly the same: `open_elf` -> `load elf` -> `execute_elf_object()`. The check you linked is just to handle errors in `execve`, before we kill other threads.

**Comment by dimakuv** [comment]
> But you are right, that's not the exactly same code, but the changes would be rather minor.

Yes, I meant to highlight line 171 but misclicked (the one with the shebang TODO comment). But anyway, you're right, the changes will be minor. Just wanted to highlight that *some changes* will be needed, it's not just one function to fix.
