### ISSUE TITLE
Remote Attestation EPID secret provisioning not working

### ISSUE THREAD

**Issue by haadeescott** [gramineproject/gramine#348]
## Description of the problem
I am unable to run the ra-tls-secret-prov sample provided even after following the documentation, using the dummy EPID API key. And how do i even generate the API key?
## Steps to reproduce

As per the docs i generated the input.txt and the epid server using the dummy EPID key:
```
$ RA_CLIENT_SPID=12345678901234567890123456789012 RA_CLIENT_LINKABLE=0 make app epid files/input.txt
```
And started the server:
```
$ RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 RA_TLS_EPID_API_KEY=12345678901234567890123456789012 ./secret_prov_server_epid &
```

The output that was produced indicated that the API key failed to be sent
```
ias_send_request: Attestation IAS request failed: code 401
ias_verify_quote_raw: Failed to send request to IAS and receive its response
```

Hope you are able to assist me on this.

**Comment by dimakuv** [comment]
> I am unable to run the ra-tls-secret-prov sample provided even after following the documentation, using the dummy EPID API key. And how do i even generate the API key?

You cannot use dummy SPID and EPID API keys. You must register at Intel SGX Attestation Service web page first: https://api.portal.trustedservices.intel.com/EPID-attestation. After you sign up, the Service will generate these two keys for you. These are the keys you must use in Gramine SGX attestation examples (including `ra-tls-secret-prov`).

You may also want to learn more about SGX attestation flows: https://gramine.readthedocs.io/en/latest/attestation.html. There is a section on EPID attestation flow.

**Comment by haadeescott** [comment]
Even after registering my own API keys. The client side is still unable to retrieve the secret.

Server side
```
--- Starting the Secret Provisioning server on port 4433 ---
********************************************************************
*** Secret Provisioning library detected mbedTLS test certificates *
*** loaded into it. If this is a production system, please         *
*** terminate this application.                                    *
********************************************************************
IAS report: signature verified correctly
IAS report: quote status OK
verify_quote_body_enclave_attributes: Quote: DEBUG bit in enclave attributes is set
```


Client side
```
********************************************************************
*** Secret Provisioning library detected mbedTLS test certificates *
*** loaded into it. If this is a production system, please         *
*** terminate this application.                                    *
********************************************************************
--- [main] Re-starting myself using execvp() ---
did not receive protected files master key!
child could not read the protected file
did not receive protected files master key!
parent could not read the protected file
```

Is there anything else that needs to be changed aside from EPID and API keys? 
Thanks for assisting me on this.

**Comment by dimakuv** [comment]
Did you add `RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1` when starting the server?

Please see the examples of how to run the server and the client here: https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov#quick-start

**Comment by haadeescott** [comment]
Yes i followed the exact steps for the EPID attestation:

Server side:
```
RA_CLIENT_SPID=<spid key> RA_CLIENT_LINKABLE=0 make app epid files/input.txt

RA_TLS_EPID_API_KEY=<api key> \
RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 ./secret_prov_server_epid &
```

Client side:
```
gramine-sgx ./secret_prov_pf_client
```
