### ISSUE TITLE
Feature request: Multiple PF keys corresponding to different PF mount

### ISSUE THREAD

**Issue by duanbing** [gramineproject/gramine#358]
## Description of the problem

Consider a situation similar to multi-parties computation, some clients try to do joint computing in an enclave cluster(we name it worker enclave), some of them provide data, and the others query or train an AI model.  the data providers encrypt their data and upload it to the cluster, and then do a Remote Verification before sending pf key into the enclave by secret provisioning server.    The problem comes that a worker enclave can only keep one pf key in memory after RA.     

## Expected results

So can we support multiple PF mounts with different PF keys?   

As we discussed in email,  we should provide a friendly user interface, and implement it as below: 
- new file `/dev/attestation/protected_files_perfile_keys`
- user is supposed to write into this file in a format like this:
`key1="file1;file2;file3", key2="file4;file5"`
- when user closes the file, Gramine parses this file and calls
`DkSetProtectedFilesKey(key_buf, path_buf)` for each key-file pair

I am considering realizing it firstly in the branch, but need some discuss about the long-term plan.  @dimakuv @pwmarcz

**Comment by boryspoplawski** [comment]
For the format of passing keys I suggest using TOML. We use that for manifests, so it should be easy (and we have a parser with some useful helper functions already).

As for PF: we encounter more and more issues and I've heard some voices that they might need a redesign/rework, but I'm not aware of any actual plans to do it. On the other hand it might be not worth to put the effort in implementing this, if the design changes...

If you need something "fast and for now" you could use existing interfaces, memorize all keys in your app, and just change the key each time you need to read/write file protected by a different key than recently used. That of course assumes you can set PF keys multiple times in the current version (I'm not sure). This is super ugly and hacky, but should be easily doable with the current state.

**Comment by dimakuv** [comment]
@duanbing Can your application assume something about where the files from different data providers are located?

For example, can we assume something like this:
```
<your app dir>/
    - files_from_data_provider_1/
    - files_from_data_provider_2/
    - files_from_data_provider_3/
```

In this case, we can introduce a syntax like this:
```
sgx.protected_files = [
  { path = "file:files_from_data_provider_1/", key_name = "dp1" },
  { path = "file:files_from_data_provider_2/", key_name = "dp2" },
  "file:some_other_dir/",   # uses default key
]
```

And then we will introduce `DkSetProtectedFilesKey(key_buf, key_name)` and `/dev/attestation/protected_files_keys = 'key1=0x1234, key1_name="dp1'"`. This will be cleaner, I think.

**Comment by duanbing** [comment]
@dimakuv  The assumption makes sense.  It's quite clear to import key_name to bridge the key and PF.

**Comment by duanbing** [comment]
Hi @dimakuv, just double check, if the malicious data provider sets up the wrong key_name, the data they provide will not be decrypted.  right?

**Comment by dimakuv** [comment]
> Hi @dimakuv, just double check, if the malicious data provider sets up the wrong key_name, the data they provide will not be decrypted. right?

@duanbing Could you clarify this on the example? I'm not sure what is the exact scenario you're thinking about. (But if I understood correctly, yes, the data will not be decrypted, instead there will be an error like "Failed to decrypt".)

**Comment by duanbing** [comment]
@dimakuv  You are right, that's what I need.  And then the application will catch errors like `Failed to decrypt` and terminate the process.

**Comment by svenkata9** [comment]
> @duanbing Can your application assume something about where the files from different data providers are located?
> 
> For example, can we assume something like this:
> 
> ```
> <your app dir>/
>     - files_from_data_provider_1/
>     - files_from_data_provider_2/
>     - files_from_data_provider_3/
> ```
> 
> In this case, we can introduce a syntax like this:
> 
> ```
> sgx.protected_files = [
>   { path = "file:files_from_data_provider_1/", key_name = "dp1" },
>   { path = "file:files_from_data_provider_2/", key_name = "dp2" },
>   "file:some_other_dir/",   # uses default key
> ]
> ```
> 
> And then we will introduce `DkSetProtectedFilesKey(key_buf, key_name)` and `/dev/attestation/protected_files_keys = 'key1=0x1234, key1_name="dp1'"`. This will be cleaner, I think.

I propose key_id instead of name. That's how most Crypto APIs/Standards use/implement it.

**Comment by pwmarcz** [comment]
This is implemented on master now (as `{ type = "encrypted", ..., key_name = "<key name>"}` mounts).
