### ISSUE TITLE
Failed to run flower example of "server.py" with the error of "Protocol not available" 

### ISSUE THREAD

**Issue by yanghongsing** [gramineproject/gramine#361]
## Description of the problem
Failed to run server.py with the error log below:
$gramine-sgx ./flower server.py
1 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1643255843.458833000","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}

server.py is from link below:
https://github.com/adap/flower/tree/main/examples/quickstart_pytorch

## Expected results
come error below:
1 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1643255843.458833000","description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}

## Actual results
it should be no such error.

**Comment by dimakuv** [comment]
Could you re-run this example with Gramine and have `loader.log_level = "all"` in the Gramine manifest file?

This will output a Gramine log, in addition to the application messages. Please attach the log (or copy-paste the last ~100 lines) here, so we can examine what exactly goes wrong inside Gramine.

**Comment by yanghongsing** [comment]
Here attached the logfile
[logfile.zip](https://github.com/gramineproject/gramine/files/7949479/logfile.zip)
.

**Comment by dimakuv** [comment]
Thanks. This is because we don't have `SO_REUSEPORT` reported inside Gramine's `getsockopt()` emulation: https://github.com/gramineproject/gramine/blob/df6ed60faef161ceec26fc019a21fadcd3756260/LibOS/shim/src/sys/shim_socket.c#L2068

Someone will need to add it. Since Gramine actually creates all sockets with `SO_REUSEPORT` (if I remember correctly), the change to support this can be trivial, by just adding `SO_REUSEPORT` inside the LibOS component.

Unfortunately, I don't have time to create such a PR. Maybe @jkr0103 could look into this?

**Comment by jkr0103** [comment]
@yanghongsing could you please share the application you are executing with manifest file?
@dimakuv please assign to me

**Comment by yanghongsing** [comment]
Dear Kumar

I tried to run flower in gramine. flower is an open source framwork for federated machine leaning. Please refer to the link below. It needs grpc to commmunication between server and clients.
https://flower.dev/

Regards
@yanghongsing

**Comment by dimakuv** [comment]
> Since Gramine actually creates all sockets with `SO_REUSEPORT` (if I remember correctly)

I remembered incorrectly. Gramine creates sockets with `SO_REUSEADDR` but not with `SO_REUSEPORT`.

Since `SO_REUSEPORT` is typically an optional feature for applications (and it is certainly optional for gRPC), Gramine will **not** implement this feature in the near future.

@yanghongsing I looked at the `socket_utils_common_posix.cc:223` gRPC source code which prints your error: https://github.com/grpc/grpc/blob/be723121fca2a1055aa4078ffdb3a9f414634769/src/core/lib/iomgr/socket_utils_common_posix.cc#L223. It's actually just a log message of gRPC, but **it is not a real error**. Looking at the log that you attached, it looks like your application actually runs fine and waits for some connections from clients.

So looks like your app runs fine.

If you want to supress this gRPC error message (`socket_utils_common_posix.cc:223] check for SO_REUSEPORT ...`), you can just set the environment variable to `GRPC_VERBOSITY="NONE"`. In particular, you can do it by adding this line in the Gramine manifest file: `loader.env.GRPC_VERBOSITY="NONE"`.

**Comment by yanghongsing** [comment]
@dimakuv 
It is acceptable if this error does not affect grpc communcation. 

But client side also get some errors. This example is supposed to run one server and two clients. The first client quits when it starts after server. below is the error messages. I also attached details log file for both server and client.

Thank you.


Detected a huge manifest, preallocating 128MB of internal memory.
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - loader.insecure__use_host_env = true       (forwarding environment vars from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Detected a huge manifest, preallocating 128MB of internal memory.
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1011, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 951, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "client.py", line 126, in <module>
    main()
  File "client.py", line 99, in main
[logfile01.zip](https://github.com/gramineproject/gramine/files/7962895/logfile01.zip)

    trainloader, testloader, num_examples = load_data()
  File "client.py", line 79, in load_data
    trainset = CIFAR10("./dataset", train=True, download=True, transform=transform)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 66, in __init__
    self.download()
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/cifar.py", line 144, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 427, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 130, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/home/azureuser/.local/lib/python3.8/site-packages/torchvision/datasets/utils.py", line 78, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:1131)>
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 27, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 36, in <module>
    apt_pkg.init_system()
apt_pkg.Error: E:Error reading the CPU table

Original exception was:
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py
(https://github.com/gramineproject/gramine/files/7962896/logfile01.zip)
", line 1251, in endheaders

[logfile01.zip]

**Comment by dimakuv** [comment]
The log of the client (`logfile_client01`) doesn't have any Gramine debug info; in other words, the client manifest was not created with `loader.log_level = "all"`. Could you please add this to the client manifest and re-run?

Also, did you verify why this error happens in your client:
```
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:1131)>
```

This is the crux of your problem. Something wrong with SSL certificates during the TLS handshake between the client and the server. It looks like the client doesn't recognize the server's certificate. Are you sure the client correctly loads the public key and the certificate chain corresponding to the server? Does it really work in normal, non-Gramine scenario? Did you forget to add an FS mount point and `sgx.trusted_files` in the manifest file, pointing to where these public key + certificate chain for the server are stored?
