### ISSUE TITLE
[PAL SGX] Secure pipe creation helper threads are not freed

### ISSUE THREAD

**Issue by boryspoplawski** [gramineproject/gramine#365]
## Description of the problem
To perform TLS handshake when creating a PAL pipe, Gramine creates a helper thread: https://github.com/gramineproject/gramine/blob/c4c88f9bc1db53460774cd8adb07267236cef039/Pal/src/host/Linux-SGX/db_pipes.c#L230
This thread's resources are never cleared, e.g. PAL_HANDLE is never freed. This leads to memory leaks, each time a PAL pipe is created (e.g. IPC communication, pollable events).

**Comment by boryspoplawski** [comment]
Seems we already had an issue about this in the old repo: https://github.com/gramineproject/graphene/issues/2467

**Comment by dimakuv** [comment]
@boryspoplawski I created PR #366 that should fix this problem. Could you please rebase it on top of your epoll PR and check it?
