### ISSUE TITLE
protected_mrsigner_files: Disallowing access to file ...; file is not protected, trusted or allowed.

### ISSUE THREAD

**Issue by alexander-lindner** [gramineproject/gramine#367]
## Description of the problem
warning: Disallowing access to file 'src/keys/private/8888'; file is not protected, trusted or allowed.

## Steps to reproduce
```bash
$ git rev-parse HEAD
66f58d0cc8673ab85e333d68f3c682e8ad20bc4d
```
I've got this line in my (python) code:
```python
print(os.path.isdir("./src/keys/private/")) # results in True
privKey = "./src/keys/private/8888"
with open(privKey, "wb") as wk:
```
and this part of the manifest
```toml
sgx.insecure__protected_files_key = "ffeeddccbbaa99887766554433221100"
sgx.protected_mrsigner_files = [
 "file:./src/keys/private/",
]
```
This dir or a parent one is not specified elsewhere like `sgx.allowed_files`. 
I've tried to specify the file direct, create the file before, use `sgx.protected_files` but nothing changed the result.

The final `app.manifest.sgx`:
```
[sgx]
nonpie_binary = true
enclave_size = "4G"
thread_num = 256
debug = false
isvprodid = true
isvsvn = true
remote_attestation = true
ra_client_spid = "..."
ra_client_linkable = true
insecure__protected_files_key = "ffeeddccbbaa99887766554433221100"
protected_mrsigner_files = [ "file:./src/keys/private/",]
allowed_files = []
require_avx = false
require_avx512 = false
require_mpx = false
require_pkru = false
require_amx = false
support_exinfo = false
enable_stats = false
```
## Actual results
When running the code it results in:

```
Traceback (most recent call last):
  File "src/main.py", line 168, in <module>
    main()
  File "src/main.py", line 19, in genKeys
    with open(privKey, "wb") as wk:
PermissionError: [Errno 13] Permission denied: './src/keys/private/8888'

```
The debug logs:
```
[P1:T1:python3.8] trace: ---- shim_time(0) = 0x61f8eb4d
[P1:T1:python3.8] trace: ---- shim_getpid() = 0x1
[P1:T1:python3.8] trace: ---- shim_getpid() = 0x1
[P1:T1:python3.8] trace: ---- shim_time(0) = 0x61f8eb4d
[P1:T1:python3.8] trace: ---- shim_clock_gettime(0, 0x6e94c350) = 0x0
warning: Disallowing access to file 'src/keys/private/8888'; file is not protected, trusted or allowed.
[P1:T1:python3.8] trace: ---- shim_openat(AT_FDCWD, "./src/keys/private/8888", O_WRONLY|O_CREAT|O_TRUNC|0x80000, 0666) = -13
[P1:T1:python3.8] trace: ---- shim_openat(AT_FDCWD, "src/main.py", O_RDONLY|0x80000, 0000) = 0x4
[P1:T1:python3.8] trace: ---- shim_fstat(4, 0x6e94b5c0) = 0x0
[P1:T1:python3.8] trace: ---- shim_ioctl(4, TCGETS, 0x6e94b6a0) ...
[P1:T1:python3.8] trace: ---- return from shim_ioctl(...) = -38

```

**Comment by mkow** [comment]
Does it work if you use absolute path to access it?

**Comment by alexander-lindner** [comment]
This doesn't change anything (I changed it in my py code as well as inside the manifest).
The current working directory is `/` and my `src/...` is mounted under `/` so it should make no difference?

This is the log:
```
[P1:T1:python3.8] trace: ---- shim_time(0) = 0x61f91d43
[P1:T1:python3.8] trace: ---- shim_getpid() = 0x1
[P1:T1:python3.8] trace: ---- shim_getpid() = 0x1
[P1:T1:python3.8] trace: ---- shim_time(0) = 0x61f91d43
[P1:T1:python3.8] trace: ---- shim_clock_gettime(0, 0x7774b340) = 0x0
warning: Disallowing access to file 'src/keys/private/8888'; file is not protected, trusted or allowed.
[P1:T1:python3.8] trace: ---- shim_openat(AT_FDCWD, "/src/keys/private/8888", O_WRONLY|O_CREAT|O_TRUNC|0x80000, 0666) = -13
[P1:T1:python3.8] trace: ---- shim_write(1, 0x76d2ea60, 0x9e) ...
```


In the warning message, the `/` disappears, I'm not sure if this is only a formatting thing.
I also noticed, that when I add

```toml
sgx.protected_mrsigner_files = [
 "file:",
]
```
it also doesn't change anything. I assumed that this should be the same as
```toml
sgx.protected_mrsigner_files = [
 "file:/",
]
```
and should prevent my application from start but both statements do not have an influence to my application. Right now I'm confused :laughing:

**Comment by pwmarcz** [comment]
>In the warning message, the / disappears, I'm not sure if this is only a formatting thing.

AFAICT, this is because the path in the warning message (`src/keys/private/8888) is the path _on host_, and it's relative to your working directory on host. (By default, `/` in Gramine corresponds to the working directory on host, i.e. `file:.` is mounted at `/`).

Can you check what happens if you change `"file:./src/keys/private/"` to `"file:src/keys/private/"` in the manifest? I suspect there might be a problem with path normalisation.

**Comment by alexander-lindner** [comment]
> AFAICT, this is because the path in the warning message (src/keys/private/8888) is the path on host, and it's relative to your working directory on host. (By default, / in Gramine corresponds to the working directory on host, i.e. file:. is mounted at /).

Good to know. Would be nice, if there is an easy way of differentiating a path on a host and a mounted path ...

> Can you check what happens if you change "file:./src/keys/private/" to "file:src/keys/private/" in the manifest? I suspect there might be a problem with path normalisation.

Nice, that worked. So it seems to be that path normalization is really the problem.

**Comment by dimakuv** [comment]
We have numereous small bugs in our allowed/trusted/protected files implementation... We are planning a complete rewrite of this implementation soon, hopefully this quarter.
