### ISSUE TITLE
[Linux-SGX] Intermittent LTP test failures seen with create_pollable_event: DkStreamOpen failed: -13 error

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/gramine#376]
## Description of the problem

For setrlimit01 and sendfile04, sendfile04_64 we are seeing intermittent failures when run with Gramine SGX. 

**Sendfile**
```
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)
  - fs.experimental__enable_sysfs_topology = true (forwarding sysfs topology from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------
sendfile04_64    1  TPASS  :  sendfile() returned 14 : Bad address
sendfile04_64    2  TBROK  :  /home/intel/jenkins/workspace/local_ci_graphene_sgx_centos_5.14/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/sendfile/sendfile04.c:233: client/server fork failed: Cannot allocate memory
[P1:T1:sendfile04_64] error: create_pollable_event: DkStreamOpen failed: -13
sendfile04_64    3  TBROK  :  /home/intel/jenkins/workspace/local_ci_graphene_sgx_centos_5.14/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/sendfile/sendfile04.c:233: Remaining cases broken
```
For sendfile it throws `cannot allocate memory` error even though the system has sufficient free memory and because of the intermittent nature of the issue, the immediate run tends to PASS.

**Setrlimit**

```
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)
  - fs.experimental__enable_sysfs_topology = true (forwarding sysfs topology from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

setrlimit01    1  TPASS  :  RLIMIT_NOFILE functionality is correct
setrlimit01    2  TFAIL  :  /home/intel/jenkins/workspace/local_ci_graphene_sgx_dcap/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/setrlimit/setrlimit01.c:185: setrlimit failed, expected 10 got 26
setrlimit01    0  TWARN  :  /home/intel/jenkins/workspace/local_ci_graphene_sgx_dcap/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/setrlimit/setrlimit01.c:226: Expected EAGAIN got 12
setrlimit01    0  TWARN  :  /home/intel/jenkins/workspace/local_ci_graphene_sgx_dcap/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/setrlimit/setrlimit01.c:226: Expected EAGAIN got 12
[P1:T1:setrlimit01] error: create_pollable_event: DkStreamOpen failed: -13
[P1:T1:setrlimit01] error: create_pollable_event: DkStreamOpen failed: -13
[P1:T1:setrlimit01] error: create_pollable_event: DkStreamWaitForClient failed: -13
```

For setrlimit the test hangs and is eventually killed by a timeout. 

Trace logs from different systems and runs are attached here.
[sendfile04_20.04_5.12_sgx.txt](https://github.com/gramineproject/gramine/files/7992258/sendfile04_20.04_5.12_sgx.txt)
[setrlimit.txt](https://github.com/gramineproject/gramine/files/7992259/setrlimit.txt)
[sendfile04_64_fail_log.txt](https://github.com/gramineproject/gramine/files/7992260/sendfile04_64_fail_log.txt)
[sendfile04_64_intermittent_fail_log.txt](https://github.com/gramineproject/gramine/files/7992261/sendfile04_64_intermittent_fail_log.txt)
[setrlimit_timeout_log.txt](https://github.com/gramineproject/gramine/files/7992263/setrlimit_timeout_log.txt)

## Steps to reproduce

`gramine-sgx sendfile04_64` --> the issue is more reproducible with this test.
`gramine-sgx setrlimit01`

**Comment by dimakuv** [comment]
@boryspoplawski What does this error `create_pollable_event: DkStreamOpen failed: -13` typically imply?

@jinengandhi-intel What is the enclave size specified in the manifest file for `sendfile04`?

**Comment by aniket-intelx** [comment]
The enclave size is 256 MB. Please find the attached `sendfile04.manifest.sgx` . 
[sendfile04_manifest_sgx.txt](https://github.com/gramineproject/gramine/files/7993886/sendfile04_manifest_sgx.txt)

**Comment by dimakuv** [comment]
> The enclave size is 256 MB. Please find the attached `sendfile04.manifest.sgx`.

Could you increase the enclave size to 512M for this particular test? Just to verify whether the failure persists or not.

Because of the recent epoll rework, it is possible that sockets-related applications (like `sendfile04`) use slightly more enclave memory than before. Maybe bumping the enclave size is the solution to this issue.

**Comment by aniket-intelx** [comment]
The testcase is still failing with enclave size of 512M.

**Comment by boryspoplawski** [comment]
@dimakuv no idea, -13 is default error for everything on SGX...

**Comment by boryspoplawski** [comment]
@aniket-intelx @jinengandhi-intel Could you provide more details, like compile flags, used host OS etc? I was not able to reproduce the issue locally.

**Comment by jinengandhi-intel** [comment]
@aniket-intelx Pls share the machine credentials so that Borys can reproduce and debug the issue faster.

**Comment by aniket-intelx** [comment]
I have shared the details via email.

**Comment by boryspoplawski** [comment]
@aniket-intelx Could you verify that https://github.com/gramineproject/gramine/pull/381 fixes this issue?

**Comment by aniket-intelx** [comment]
The issue is still persistent with the above mentioned PR. I will share the details of machine via email.

**Comment by boryspoplawski** [comment]
Turns out there were two similar issues, I've fixed the other one as well.

@aniket-intelx could you verify now?

**Comment by aniket-intelx** [comment]
The issue is no longer seen with the updated PR.
