### ISSUE TITLE
Documentation issue: Prepare signing key command in QuickStart guide doesn't work

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/gramine#377]
## Description of the problem

As part of the QuickStart guide we provide the users with steps to install and test the package and here one of the steps is generating the signing key using the following command:
`openssl genrsa -3 -out "$HOME"/.config/gramine/enclave-key.pem 3072`

The above command assumes there's already a `gramine` directory inside `"$HOME"/.config/` but that is not the case and the command results in the following error:
`genrsa: Can't open "/home/intel/.config/gramine/enclave-key.pem" for writing, No such file or directory`

## Steps to reproduce

Follow the steps in QuickStart guide: https://gramine.readthedocs.io/en/latest/quickstart.html

**Comment by dimakuv** [comment]
True. Adding `mkdir -p "$HOME"/.config/gramine/` before this `openssl ...` line fixes the problem.

@jinengandhi-intel Could you update our documentation (in particular, this file: https://github.com/gramineproject/gramine/blob/master/Documentation/quickstart.rst) with this?
