### ISSUE TITLE
Readir systemcall not able to detect directory deletion while running inside SGX enclave

### ISSUE THREAD

**Issue by sivashax** [gramineproject/gramine#390]
## Description of the problem
Readir systemcall not able to detect directory deletion while running inside SGX enclave. However, able to detect directory creation.

## Steps to reproduce
 - Please use attached sample program for reproducing this issue.
 - Extract the archive and compile as below.
     o cd subDir_experiments_SGX/Ctest
     o mkdir /tmp/dir_test
     o export GRAMINE_DIR=<Path of Gramine source dir>
     o make clean all SGX=1
     o ./ctest -> This is to run directly on host machine
     o gramine-sgx ctest -> This is to run in SGX enclave
     o This sample program checks the directories in /tmp/dir_test for every 2 secs and displays in the console (for 10 iterations). 
     o In another terminal cd /tmp/dir_test and create / delete directories as below
     o mkdir 1 2 3 4
     o rmdir 3 4

## Expected results
  - Able to detect directory creation & deletion while the program is running.
## Actual results
  - While running in enclave, able to detect only the directory creation and not directory deletion. The deleted directories are also getting read from readdir syscall.
  
## Gramine commit hash
 Tested with Release TAG v1.1
[subDir_experiments_SGX.tar.gz](https://github.com/gramineproject/gramine/files/8024672/subDir_experiments_SGX.tar.gz)

**Comment by sahason** [comment]
@dimakuv please reassign this to me.
