### ISSUE TITLE
Inline assembly produces wrong results in Clang release mode

### ISSUE THREAD

**Issue by pwmarcz** [gramineproject/gramine#391]
## Summary

Our inline assembly sometimes uses RBX as an input operand. However, this seems unsupported by LLVM, because LLVM reserves RBX to be a base pointer when code gets more complicated. As a result, Gramine-SGX crashes when compiled in release mode.

## Steps to reproduce

This is a crash reported in #208.

Compile Gramine with `CC=clang`, `--buildtype=debugoptimized`, and `-Dasan=enabled`.

Run any test case in which Gramine forks, e.g. `fork_and_exec`. Gramine will crash with:

```
Unexpected memory fault occurred inside PAL (_DkStreamReportRespond at enclave_framework.c, libpal.so+0x7eaa3)
```

## Gramine commit hash

9e1d1f6ea860323f1f50f054f1cf3fe472a9c12d

## Analysis

Looking more closely, it seems that the ENCLU instruction is called with wrong parameters. This is our code:

```c
static inline int sgx_report(const sgx_target_info_t* targetinfo, const void* reportdata,
                             sgx_report_t* report) {
    __asm__ volatile(
        ENCLU "\n"
        :: "a"(EREPORT), "b"(targetinfo), "c"(reportdata), "d"(report)
        : "memory");
    return 0;
}
```

This is the generated assembly (for `enclave_framework.c`, `_DkStreamReportRespond`):
```
        xorl    %eax, %eax
        movq    %r14, %rbx
        movq    496(%rbx), %rcx
        leaq    2048(%rbx), %rdx
        .byte   15
        .byte   1
        .byte   215
```

The RBX register is used throughout the function as a base pointer. This is a complicated case (because of ASan), but I believe LLVM does this for some functions without ASan too.

Notice how the RBX register is overwritten with the parameter for ENCLU early on, but still used afterwards, and not restored after ENCLU.

I believe that **LLVM does not support using RBX directly as input**. Here is what I found (nothing in official docs, though):

[[CodeGen] emit inline asm clobber list warnings for reserved (cont)](https://reviews.llvm.org/D51165)

> Currently, in line with GCC, when specifying reserved registers like sp or pc on an inline asm() clobber list, we don't always preserve the original value across the statement. And in general, overwriting reserved registers can have surprising results.

This does not state explicitly that RBX is reserved, but points out a similar case.

[Inline assembly](https://doc.rust-lang.org/nightly/reference/inline-assembly.html) (in Rust docs)

> Some registers cannot be used for input or output operands:
> `bx` (x86-64) - This is used internally by LLVM as a "base pointer" for functions with complex stack frames.

## Proposed solutions

Don't use RBX as operand. Instead, save it and restore within the inline assembly block.

```c
    __asm__ volatile(
        "xchgq %%rdi, %%rbx\n"
        ENCLU "\n"
        "movq %%rdi, %%rbx\n"
        :: "a"(EREPORT), "D"(targetinfo), "c"(reportdata), "d"(report)
        : "memory");
```

**Comment by boryspoplawski** [comment]
This is sad, I would expect a compile error (or warning at least)...

Another approach to solving this would be moving the problematic inline asm out of C, with advantage that nothing like this can go wrong anymore, but a disadvantage of one additional function call.

**Comment by dimakuv** [comment]
What an interesting bug!

I vote for never using RBX as an operand and adding `mov`s in the inline asm, just like in Pawel's example.

@pwmarcz Aren't you supposed to add `rbx` in the clobber list in your example?

**Comment by pwmarcz** [comment]
Should I? I'm restoring the old value.

>Another approach to solving this would be moving the problematic inline asm out of C, with advantage that nothing like this can go wrong anymore, but a disadvantage of one additional function call.

That sounds like a better option, but I don't mind doing either. @mkow what do you think?

**Comment by boryspoplawski** [comment]
>> @pwmarcz Aren't you supposed to add rbx in the clobber list in your example?
>
> Should I? I'm restoring the old value. And the whole point is that LLVM will not respect that either way...

No, you should not, we do not change the value from outsides point of view.

**Comment by dimakuv** [comment]
> Should I? I'm restoring the old value.

True, you're right.

> And the whole point is that LLVM will not respect that either way...

But GCC does respect this. But your first point makes my suggestion meaningless anyway.

**Comment by mkow** [comment]
Ugh, I expected more from Clang...

I'm voting for moving our assembly to separate files (in general, not only here). This will also allow some other nice things: we could switch to Intel syntax and to `nasm`.
I think the downside (additional `call`) is negligible, and if we find a hot-path where this actually makes a difference then we can use inline asm for that specific hot-path.
