### ISSUE TITLE
Gramine-SGX doesn't throw error/exit out when an application uses MAP_SHARED

### ISSUE THREAD

**Issue by aniket-intelx** [gramineproject/gramine#401]
## Description of the problem
Currently, when an application uses `MAP_SHARED`, Gramine throws the following warning and continues execution of the application.
```
warning: file_map does not currently support writable pass-through mappings on SGX. 
You may add the PAL_PROT_WRITECOPY (MAP_PRIVATE) flag to your file mapping to keep the writes inside the enclave but they won't be reflected outside of the enclave.
```
Are we supposed to throw an error and exit out of the application?
## Steps to reproduce

Few LTP testcases which use mmap `MAP_SHARED` flag and result in some error and application continues to run are `qmm01`, `msync03`, `mmap09` and `mincore01`.

Steps to reproduce this error after building Gramine with `sgx` and `tests` enabled:
1)	cd /LibOS/shim/test/ltp
2)	git clone https://github.com/jinengandhi-intel/graphene_local_ci.git
3)	cp -rf graphene_local_ci/ltp_src/ .
4)	cp -rf graphene_local_ci/ltp_config/* .
5)	cp -f toml_files/tests_sgx.toml tests.toml
6)	make -j144 -f Makefile.LTP SGX=1 all
7)	Run `gramine-sgx <testcase>` 

## Gramine commit hash

Please find the attached logs.
[mmap001_qmm01_sgx_log.txt](https://github.com/gramineproject/gramine/files/8059724/mmap001_qmm01_sgx_log.txt)
[msync03_sgx_log.txt](https://github.com/gramineproject/gramine/files/8059726/msync03_sgx_log.txt)
[mmap001_manifest_sgx.txt](https://github.com/gramineproject/gramine/files/8059727/mmap001_manifest_sgx.txt)

**Comment by mkow** [comment]
This is not a bug, but intended behavior. It's this way because some applications map memory with `MAP_SHARED` but don't really share it, so they work correctly under Gramine despite the lack of shared memory support.

**Comment by jinengandhi-intel** [comment]
@dimakuv @mkow we were asked to file this bug by Dmitrii in one of the bug scrub's, so just checking everybody is on the same page and this is indeed expected behavior.

**Comment by dimakuv** [comment]
This is indeed expected behavior. I don't remember discussing this during the bug scrub... When was it? Was it exactly this bug?
