### ISSUE TITLE
gramine-sgx-sign and gramine-sgx-gen-private-key failing

### ISSUE THREAD

**Issue by ssinha20** [gramineproject/gramine#424]
## Description of the problem
gramine-sgx-sign and gramine-sgx-gen-private-key failing

## Steps to reproduce

```
git clone https://github.com/gramineproject/gramine.git --depth=1
cd gramine
mkdir -p meson_build_output
meson setup build/ --prefix="$PWD/meson_build_output" --buildtype=release -Ddirect=enabled \
  -Dsgx=enabled -Ddcap=enabled
ninja -C build/
ninja -C build/ install
```

## Actual results
```
# gramine-sgx-sign --help
Traceback (most recent call last):
  File "/usr/bin/gramine-sgx-sign", line 11, in <module>
    from graminelibos import (
ImportError: cannot import name 'SGX_RSA_KEY_PATH' from 'graminelibos' (/usr/lib/python3/dist-packages/graminelibos/__init__.py)
# gramine-sgx-gen-private-key
Traceback (most recent call last):
  File "/usr/bin/gramine-sgx-gen-private-key", line 20, in <module>
    default=os.fspath(sgx_sign.SGX_RSA_KEY_PATH))
AttributeError: module 'graminelibos.sgx_sign' has no attribute 'SGX_RSA_KEY_PATH'
```

**Comment by ssinha20** [comment]
System HW
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Byte Order:                      Little Endian
Address sizes:                   39 bits physical, 48 bits virtual
CPU(s):                          4
On-line CPU(s) list:             0-3
Thread(s) per core:              1
Core(s) per socket:              4
Socket(s):                       1
NUMA node(s):                    1
Vendor ID:                       GenuineIntel
CPU family:                      6
Model:                           158
Model name:                      Intel(R) Xeon(R) E-2174G CPU @ 3.80GHz
Stepping:                        10
CPU MHz:                         3800.000
CPU max MHz:                     4700.0000
CPU min MHz:                     800.0000
BogoMIPS:                        7599.80
Virtualization:                  VT-x
L1d cache:                       128 KiB
L1i cache:                       128 KiB
L2 cache:                        1 MiB
L3 cache:                        8 MiB
NUMA node0 CPU(s):               0-3
Vulnerability Itlb multihit:     KVM: Mitigation: VMX disabled
Vulnerability L1tf:              Mitigation; PTE Inversion; VMX conditional cache flushes, SMT disabled
Vulnerability Mds:               Mitigation; Clear CPU buffers; SMT disabled
Vulnerability Meltdown:          Mitigation; PTI
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Full generic retpoline, IBPB conditional, IBRS_FW, RSB filling
Vulnerability Srbds:             Mitigation; Microcode
Vulnerability Tsx async abort:   Mitigation; TSX disabled
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb
                                 rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl v
                                 mx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm ab
                                 m 3dnowprefetch cpuid_fault epb invpcid_single pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust sg
                                 x bmi1 avx2 smep bmi2 erms invpcid mpx rdseed adx smap clflushopt intel_pt xsaveopt xsavec xgetbv1 xsaves dtherm ida arat pln pts hwp hwp_n
                                 otify hwp_act_window hwp_epp sgx_lc md_clear flush_l1d


```

**Comment by dimakuv** [comment]
Because of the `--prefix` option in your `meson setup` command, all Gramine binaries and scripts are installed under `"$PWD/meson_build_output"`. In other words, you installed Gramine *locally*, in a specific directory. I'm not sure this is what you wanted.

It is clear from the logs that you pasted that you also have Gramine installed *globally* (I see `/usr/lib/python3/dist-packages/graminelibos` which is a system-wide global dir).

So you have two Gramines now: one local and unused, and the other one global and used when you type `gramine-sgx-sign --help`.

The easiest option is to install the new Gramine (that you git-cloned) globally. For this, you simply need to remove the `--prefix` part in the `meson setup` command. Then the new Gramine will overwrite the old version, and you shouldn't have the issue anymore.

Another option is to use this locally-installed Gramine. For this, you need to export three environment variables, as described here: https://gramine.readthedocs.io/en/latest/devel/building.html#additional-build-options (see the table).

**Comment by ssinha20** [comment]
> Because of the `--prefix` option in your `meson setup` command, all Gramine binaries and scripts are installed under `"$PWD/meson_build_output"`. In other words, you installed Gramine _locally_, in a specific directory. I'm not sure this is what you wanted.
> 
> It is clear from the logs that you pasted that you also have Gramine installed _globally_ (I see `/usr/lib/python3/dist-packages/graminelibos` which is a system-wide global dir).
> 
> So you have two Gramines now: one local and unused, and the other one global and used when you type `gramine-sgx-sign --help`.
> 
> The easiest option is to install the new Gramine (that you git-cloned) globally. For this, you simply need to remove the `--prefix` part in the `meson setup` command. Then the new Gramine will overwrite the old version, and you shouldn't have the issue anymore.
> 
> Another option is to use this locally-installed Gramine. For this, you need to export three environment variables, as described here: https://gramine.readthedocs.io/en/latest/devel/building.html#additional-build-options (see the table).

Thanks a lot . This solves the error. Closing the issue.
