### ISSUE TITLE
Packaging issues to be fixed in 1.2

### ISSUE THREAD

**Issue by woju** [gramineproject/gramine#431]
- [ ] `-Ddcap=enabled`: requires Intel's repo with additional dependencies
- [ ] sed shebang to `#!/usr/bin/python3`, because using `env` is broken for custom (non-distro) python installs (see #429)
- [ ] consider separate packaging libratls verify libraries, maybe for other architectures (thread about arm64: https://groups.google.com/d/msgid/gramine-users/9f0bbc15-6e10-44e5-aada-6ea47c3423d9n%40googlegroups.com)
- [ ] missing dependency against `libprotobuf-c1`

**Comment by dimakuv** [comment]
@woju What do you mean by `sed shebang`?

**Comment by woju** [comment]
> @woju What do you mean by `sed shebang`?

When change the shebangs, we'll need some mechanism of controlling them when
packaging for different distros. Most likely in packaging (not in our meson),
because those are different on different distros, some packaging systems
already do it by default:
https://src.fedoraproject.org/rpms/redhat-rpm-config/blob/rawhide/f/brp-mangle-shebangs.
When packaging to different distros, I shall check if other also need and/or
support it or do we have to do it manually (hence sed).

**Comment by dimakuv** [comment]
@woju I see your point. Is it something that we want to do in the future, or do you want to see this change now?

If now, then what exactly should I do in https://github.com/gramineproject/gramine/pull/429?

**Comment by woju** [comment]
> @woju I see your point. Is it something that we want to do in the future, or
> do you want to see this change now?

This isn't either "now" or "in the future", this is something that I need to
adjust whenever I package for another distro. We need to do it now (gsc+python
image is also kinda distro, because it's different python), and will need do
again when new distro with new convention arrives (e.g. BSD).

Basically, we need a knob, whether it's meson option or just a sed
postprocessing in packaging scripts (most likely the latter). 

> If now, then what exactly should I do in
> https://github.com/gramineproject/gramine/pull/429?

We should do whatever is convenient for gsc. As long as GSC compiles from
source, I think it should be `/usr/bin/python3` (as the PR does). If we
switched GSC to `apt install gramine`, then we would be in position to keep
the "most correct" shebang of `/usr/bin/env python3` in the source and
postprocess it in debian/rules. But this is a big change, we can always do
that later, and for now I think it's OK to do `/usr/bin/python3`.

**Comment by mkow** [comment]
> We should do whatever is convenient for gsc. As long as GSC compiles from source, I think it should be `/usr/bin/python3` (as the PR does).

Why not an option to Meson when installing? We could keep the sources better this way and change the shebangs only on these weird Docker images.

**Comment by mkow** [comment]
> I don't think we can do it only on "some" images, at least I don't want to maintain a heurestics for detecting "weird" Docker images. We'll do it for all the Docker images, right?

@woju: I mean on _some installs_. I.e. GSC would pass an additional option to Meson build saying "please hardcode /usr/bin/python3". You wouldn't need this outside of GSC. This way we'd constrain this only to GSC.

**Comment by woju** [comment]
I want to have `#!/usr/bin/python3` by default, because it's a sane default which works on all distros we currently support. In debs, we have dependencies against other debs (`python3-*`), not `requirements.txt`-style dependencies against pypi packages, so in deb the only correct way is to have full path `/usr/bin/python3` (otherwise running `gramine-sgx-sign` for example in venv is likely to break). Same for RPM.

For other, unsupported distros like *BSD or NixOS, we can have meson option to override.

I'm not sure if I want to do `find_program('python3')`, because again, if someone has non-standard `python3` in `$PATH` while configuring builddir, then instructions in `quickstart.rst` are wrong: instead of `apt-get install python3-*` you need `python3 -m pip install`, and then there are some details like protobuf which gets compiled.

**Comment by dimakuv** [comment]
@mkow What do you think about Woju's reply?

**Comment by boryspoplawski** [comment]
@woju What's the state of this? v1.2 was released :)

**Comment by dimakuv** [comment]
This was fixed long time ago. Let me close it.
