### ISSUE TITLE
make check_dcap failing in ra-tls-secret-prov

### ISSUE THREAD

**Issue by fork-while-1** [gramineproject/gramine#432]
## Description of the problem
I'm trying to run the sample ra-tls-secret-prov, through the `make check_dcap` rule in the provided `Makefile` but it fails with the errors described below. I'm *very* new to gramine (and SGX in general), so I really appreciate your help! :)

## Steps to reproduce
Environment: Azure confidential compute VM (Standard DC2s v2 (2 vcpus, 8 GiB memory), Ubuntu 20.04 LTS
I have the SGX SDK built and installed, as well as gramine (built from source with `meson setup ... -Ddcap=enabled`)
I then try to run `make check_dcap` to see if it works, but it doesn't.

## Expected results

```
[ Success 1/4 ]
[ Success 2/4 ]
[ Success 3/4 ]
[ Success 4/4 ]
```

## Actual results
The command `gramine-sgx ./secret_prov_min_client > OUTPUT` fails with
```
[error] secret_provision_start() returned -30592
```
and the command `gramine-sgx ./secret_prov_pf_client >> OUTPUT` fails with
```
--- [main] Re-starting myself using execvp() ---
did not receive protected files master key!
child could not read the protected file
did not receive protected files master key!
parent could not read the protected file
```

## Additional information
I looked at the source code in the `src/secret_prov_pf_client.c`, and it had the following line:
```
char* secret = getenv("SECRET_PROVISION_SECRET_STRING");
if (!secret) {
        fprintf(stderr, "did not receive protected files master key!\n");
        return -1;
    }
```
So I thought perhaps the error is because I didn't set the environment variable. So I then re-ran the script after exporting the following value of the variable (taken from the Makefile)
```
export SECRET_PROVISION_SECRET_STRING=ffeeddccbbaa99887766554433221100
```
But I still keep getting the error

## Gramine commit hash
`b54f8e566af16123a95e27f4e5697692a25baeea`

**Comment by dimakuv** [comment]
Please try to follow the steps in the README: https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov#quick-start

If you experience any issues, please copy-paste the complete terminal output here.

In particular, have you set `RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1` when starting the server app?

> So I thought perhaps the error is because I didn't set the environment variable. So I then re-ran the script after exporting the following value of the variable (taken from the Makefile)

No, this is wrong. This envvar will be set up by Gramine. You're not supposed to export this variable yourself.

For general info, I highly recommend to read about SGX attestation: https://gramine.readthedocs.io/en/latest/attestation.html

**Comment by dimakuv** [comment]
I just tried exactly the same steps on my machine. Everything works. The output from the server (`secret_prov_server_dcap`) should look like this:
```
~/gramineproject/gramine/CI-Examples/ra-tls-secret-prov$ RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 ./secret_prov_server_dcap
--- Reading the master key for protected files from 'files/wrap-key' ---
--- Starting the Secret Provisioning server on port 4433 ---
********************************************************************
*** Secret Provisioning library detected mbedTLS test certificates *
*** loaded into it. If this is a production system, please         *
*** terminate this application.                                    *
********************************************************************
Received the following measurements from the client:
  - MRENCLAVE:   3c5a7f812a0676e38045478079c6f53b55447f2abb1ba05474e655ce2c8bbe9f
  - MRSIGNER:    0dedbe47afb6955e5f6109637c1fbd9cc4b4e073e1396da8ce2091075e5b0a3b
  - ...
```

It is very strange that the server *didn't even register any incoming request*. Looks like you have some issues with the network on this machine. Could it be that `localhost` connections are not allowed on this machine? Please try to run some network-based application with a server and client on this machine, e.g., `redis-server` and `redis-benchmark`. Or simply try to `nc -l 1234` in one terminal and `nc 127.0.0.1 1234` in another terminal -- can these programs connect to each other? Also try to connect on IPv4 and on IPv6 addresses -- maybe one of these protocols is blocked.

**Comment by fork-while-1** [comment]
Hi -- I tried communicating to `localhost` through `nc`, and everything seemed to work okay.

I also tried the `redis-benchmark` in all three scenarios: 
1) outside of gramine:
```
./redis-server --save '' --protected-mode no &
src/src/redis-benchmark
kill %%
```
1) through `gramine-direct` like so:
```
gramine-direct redis-server --save '' --protected-mode no &
src/src/redis-benchmark
kill %%
```
3) and through `gramine-sgx`, through the commands below:
```
gramine-sgx redis-server --save '' --protected-mode no &
src/src/redis-benchmark
kill %%
```
And in all 3 cases the benchmark ran to completion with no issues. I have no idea why the ra-tls sample code won't work.

On a side note, I ran the [RemoteAttestation sample code that comes with the intel sgxsdk](https://github.com/intel/linux-sgx/tree/master/SampleCode/RemoteAttestation), and that seems to work without any issues. Perhaps something is wrong with my gramine build?

**Comment by lejunzhu** [comment]
@fork-while-1 try this: RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 make check_dcap

**Comment by fork-while-1** [comment]
> @fork-while-1 try this: `RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 make check_dcap`

Just tried it, and the `OUTPUT` file has the following data from all three clients:
```
********************************************************************
*** Secret Provisioning library detected mbedTLS test certificates *
*** loaded into it. If this is a production system, please         *
*** terminate this application.                                    *
********************************************************************
--- Did not receive any secret! ---
[error] secret_provision_start() returned -30592
********************************************************************
*** Secret Provisioning library detected mbedTLS test certificates *
*** loaded into it. If this is a production system, please         *
*** terminate this application.                                    *
********************************************************************
********************************************************************
*** Secret Provisioning library detected mbedTLS test certificates *
*** loaded into it. If this is a production system, please         *
*** terminate this application.                                    *
********************************************************************
--- [main] Re-starting myself using execvp() ---
did not receive protected files master key!
child could not read the protected file
did not receive protected files master key!
parent could not read the protected file
```
And my terminal printed the following:
```
./secret_prov_server_dcap >/dev/null & SERVER_ID=$!; \
sleep 3; \
gramine-sgx ./secret_prov_min_client > OUTPUT; \
gramine-sgx ./secret_prov_client >> OUTPUT; \
gramine-sgx ./secret_prov_pf_client >> OUTPUT; \
kill -9 $SERVER_ID;
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

make: *** [Makefile:149: check_dcap] Error 1
```

**Comment by lejunzhu** [comment]
This example [https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/SampleCode](url) will show the verification detail. Do you see any "non-terminal" result code?

To run it with SGX SDK: 
```
cd QuoteGenerationSample
make
SGX_AESM_ADDR=1 ./app
cd ../QuoteVerificationSample
make SGX_DEBUG=1
./app
```

**Comment by dimakuv** [comment]
@fork-while-1 You run the server like this:
```
./secret_prov_server_dcap >/dev/null
```

Why do you remove the stdout output? This output may give you hints what goes wrong. Please remove this `>/dev/null` redirection and try again. You'll hopefully see more messages, and will be able to diagnose the problem.

**Comment by fork-while-1** [comment]
> @fork-while-1 You run the server like this:
> 
> ```
> ./secret_prov_server_dcap >/dev/null
> ```
> 
> Why do you remove the stdout output? This output may give you hints what goes wrong. Please remove this `>/dev/null` redirection and try again. You'll hopefully see more messages, and will be able to diagnose the problem.

Ooops, yeah I just realized that the `Makefile` directed output to `/dev/null`. Got rid of that, and I get the following output:
```
./secret_prov_server_dcap & SERVER_ID=$!; \
sleep 3; \
gramine-sgx ./secret_prov_min_client > OUTPUT; \
gramine-sgx ./secret_prov_client >> OUTPUT; \
gramine-sgx ./secret_prov_pf_client >> OUTPUT; \
kill -9 $SERVER_ID;
--- Reading the master key for protected files from 'files/wrap-key' ---
--- Starting the Secret Provisioning server on port 4433 ---
********************************************************************
*** Secret Provisioning library detected mbedTLS test certificates *
*** loaded into it. If this is a production system, please         *
*** terminate this application.                                    *
********************************************************************
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

make: *** [Makefile:148: check_dcap] Error 1
```
It seems that the server still doesn't register any incoming connections. 
The text in the `OUTPUT` file is the same as before.

**Comment by dimakuv** [comment]
At this point you'll need to look at the more detailed logs.

- Change the manifest file of your client (that runs inside Gramine) so that it has `loader.log_level = "all"`.
- Run your server under `strace`.

This will give you a lot of information on what the client and the server are trying to do. Please try to analyze this info.

**Comment by fork-while-1** [comment]
Hi,
apparently it was an issue with my PCCS configuration. I figured that part out now, and everything runs correctly. I am having issues with running my own sample application, but I will open a separate issue for that. Thank you so much for your help! :)

**Comment by ROF13ThFloor** [comment]
Hi @fork-while-1 , Can you describe what was the issue of PCCS ? 

I have the same error and the Server doesn't register anything and the PCCS logs seem well. 

> Hi, apparently it was an issue with my PCCS configuration. I figured that part out now, and everything runs correctly. I am having issues with running my own sample application, but I will open a separate issue for that. Thank you so much for your help! :)
