### ISSUE TITLE
Gramine fails to load Rust ELF files

### ISSUE THREAD

**Issue by TimotheeIsnard** [gramineproject/gramine#436]
## Description of the problem

After updating Gramine (and updating my manifest to use the new `loader.entrypoint`), `gramine-sgx` seems to fail to load ELF files produced by the Rust compiler.  
I'm able to work around the first error (missing old-style non-gnu DT_HASH section) by passing the right linker flag to rustc, but then I get various relocaions error that I cannot work around, such as these (on two different binaries):

- Unrecognized relocation type; PAL loader currently supports only R_X86_64_RELATIVE and R_X86_64_GLOB_DAT relocations
- Could not resolve symbol SSL_CTX_free needed by binary

This prevents me from running binaries that previously worked with Gramine.

## Steps to reproduce

These steps reproduce two of the errors, though I only have a workaround for the first one, and it's possible there might be more that I haven't hit yet after those.  
For the repro, please start by checking out https://github.com/tux3/gramine_epoll_repro and installing a rust toolchain ([rustup.rs](https://rustup.rs))

#### 1. DT_GNU_HASH error

By default Rust creates binaries with the newer `DT_GNU_HASH` section, but no sysv-style `DT_HASH`, and the loader does not support those.

- Run `make run-release` in the repository cloned above
- The output should end up looking like this:

> error: Loaded binary doesn't have string table, symbol table and/or hash table
error: Could not map the ELF file into memory and then relocate it
error: PAL failed at ../Pal/src/db_main.c:pal_main:543 (exitcode = 4, reason=Unable to load loader.entrypoint)
debug: DkProcessExit: Returning exit code 4
make: *** [Makefile:71: run-release] Error 4

#### 2. OpenSSL relocation error

We can work around problem 1. with a linker flag, and we hit the 2nd error:

- Run `RUSTFLAGS="-C link-arg=-Wl,--hash-style=both" make run-release`
- The output should end up looking like this:

>arning: DkVirtualMemoryProtect is unimplemented in Linux-SGX PAL
error: Could not resolve symbol SSL_CTX_free needed by binary target/release/gramine_epoll_repro
error: Failed to perform relocations on ELF file
error: Could not map the ELF file into memory and then relocate it
error: PAL failed at ../Pal/src/db_main.c:pal_main:543 (exitcode = 4, reason=Unable to load loader.entrypoint)
debug: DkProcessExit: Returning exit code 4
make: *** [Makefile:71: run-release] Error 4

#### 3. R_X86_64_RELATIVE and R_X86_64_GLOB_DAT

I only hit this error with another larger Rust project. I can try to reduce it into a small reproducer if that would help. I don't know if the error message is enough to guess what is happening.

## Expected results

With older Gramine versions, Rust binaries work out of the box, so the loader should try to keep supporting them

## Actual results

Cannot load Rust ELF binaries anymore.

## Gramine commit hash

Tested on 76d8285ce71c6af33f6e9a288c90517a06e88973 (current master)

**Comment by boryspoplawski** [comment]
It works for me. You have a typo in your last commit, you should change `loader.preload` -> `loader.entrypoint` instead.

**Comment by tux3** [comment]
Oh, I see! So I was trying to load my ELF file as the loader.. right.

Thank you, apologies for the noise.

**Comment by TimotheeIsnard** [comment]
Oh, I see! So I was trying to load my ELF file as the loader.. right.

Thank you, apologies for the noise.
