### ISSUE TITLE
Unable to run ra-tls-mbedtls example

### ISSUE THREAD

**Issue by saruvig** [gramineproject/gramine#448]
I am trying to execute the ra-tls-mbedtls example on gramine with RA-TLS flows with SGX and with Gramine, ECDSA-based (DCAP) attestation:

But I get the following error: 

  . Creating the RA-TLS server cert and key... ok
  . Bind on https://localhost:4433/ ... failed
  ! mbedtls_net_bind returned -70

Last error was: -70 - NET - Binding of the socket failed

I have not made any changes to the manifest files. 

This is link to log generated while running the server.txt
https://github.com/saruvig/Basic_Cifar/blob/main/RA_server_log.txt

I used -Ddcap=enabled \ -Dsgx_driver=dcap1.10 while building gramine. My is-sgx-available output is as below:

![image](https://user-images.githubusercontent.com/23428423/157398330-8ea4c2e6-2949-4079-ad39-e09db8c8d1c2.png)

**Comment by dimakuv** [comment]
The `Binding of the socket failed` error implies that the port 4433 is occupied by some other application (maybe the stale instance of `ra-tls-mbedlts` process?).

Please kill the process that uses the port 4433 and try again.
