### ISSUE TITLE
Need help regarding Pytorch PPML

### ISSUE THREAD

**Issue by Lio101** [gramineproject/gramine#452]
## Description of the problem
I am trying to follow [PyTorch PPML Framework Tutorial](https://gramine.readthedocs.io/en/latest/tutorials/pytorch/index.html), but having issue. Till now I am able to executing PyTorch with Gramine in SGX Enclave but now stuck on End-To-End Confidential PyTorch Workflow part, specifically secret provisioning part where these commands are used: 
```
cd <gramine repository>/CI-Examples/ra-tls-secret-prov
make -C ../../Pal/src/host/Linux-SGX/tools/ra-tls dcap
make dcap pf_crypt
```
to my understanding these commands are referring to the Graphine project as currently `Pal/src/host/Linux-SGX/tools/ra-tls` does not contain makefile. So what are the new steps to complete the End-To-End Confidential PyTorch Workflow?

**Comment by dimakuv** [comment]
@Lio101 Sorry for this mess. We haven't updated the PyTorch tutorial in a while, and the text got stale. We'll update it soon.

You don't need to do the `make -C ...` rule.

However, you need to build Gramine from scratch using `meson setup ... -Ddcap=enabled` option -- this will build Gramine with DCAP RA-TLS libraries. After building Gramine like this, you'll be able to perform `make dcap` (no need for `pf_crypt` target).

There are quite a few problems with the current tutorial text. I've only given solutions to a couple specific issues here. In reality, there are more inconsistencies in this tutorial. If you really want to, you can try to resolve them yourself; or you can wait for a couple weeks until the tutorial is fixed.

**Comment by Lio101** [comment]
@dimakuv Thanks for update, I will try the steps you have provided.
