### ISSUE TITLE
Failed at running RA-TLS flows with SGX and with Gramine, running DCAP client in SGX on the sample of ra_tls_mbedtls

### ISSUE THREAD

**Issue by yanghongsing** [gramineproject/gramine#455]
## Description of the problem
I failed to run client in gramine on the sample codes of ra_tls_mbedtls on Azure VM using DC2s_v3 and Ubuntu 20.04LTS Gen2. 
Here attached the log file with all option in Makefile.

[m_client.txt](https://github.com/gramineproject/gramine/files/8243519/m_client.txt)

[m_server.txt](https://github.com/gramineproject/gramine/files/8243511/m_server.txt)

I can run client without gramine by using the same server in gramine. The outputs are as below:
~/g/gramine/CI-Examples/ra-tls-mbedtls$ RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 ./client dcap c6afcacad720891651c4f3dbfdfd3cc71166cf1f39980d1872f03ec0f890e062 4726c492ad00998b21b08fc2b50faecbaa19851e24baccccda002dc446a8d19b 0 0
[ using our own SGX-measurement verification callback (via command line options) ]
  - ignoring ISV_PROD_ID
  - ignoring ISV_SVN

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Installing RA-TLS callback ... ok
  . Performing the SSL/TLS handshake... ok
  . Verifying peer X.509 certificate... ok
  > Write to server: 18 bytes written

GET / HTTP/1.0

  < Read from server: 156 bytes read

HTTP/1.0 200 OK
Content-Type: text/html

<h2>mbed TLS Test Server</h2>
<p>Successful connection using: TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256</p>

**Comment by dimakuv** [comment]
You seem to be using a Gramine package. This package currently doesn't support DCAP. Please see this reply: https://github.com/gramineproject/gramine/issues/452#issuecomment-1064845240

**Comment by yanghongsing** [comment]
@dimakuv
I actuall built Gramine from scratch using meson setup ... -Ddcap=enabled option 
I can run RA-TLS flows with SGX and with Gramine, ECDSA-based (DCAP) attestation following the step below as in READ.me
- RA-TLS flows with SGX and with Gramine, ECDSA-based (DCAP) attestation:

```sh
# replace dummy values with your MRENCLAVE, MRSIGNER, etc!
make clean
make app dcap

gramine-sgx ./server dcap &

RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 \
RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 \
RA_TLS_MRENCLAVE=1234567890123456789012345678901234567890123456789012345678901234 \
RA_TLS_MRSIGNER=1234567890123456789012345678901234567890123456789012345678901234 \
RA_TLS_ISV_PROD_ID=0 RA_TLS_ISV_SVN=0 \
./client dcap

But it failed to run RA-TLS flows with SGX and with Gramine, running DCAP client in SGX with steps below
```sh
make clean
make app dcap

gramine-sgx ./server dcap &

RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 gramine-sgx \
    ./client_dcap dcap \
    1234567890123456789012345678901234567890123456789012345678901234 \
    1234567890123456789012345678901234567890123456789012345678901234 \
    0 0

It seems that DCAP is working now. Could you take a look at log file to help to check what is missing to prevent the client to run in gramine? Thank you.

**Comment by llly** [comment]
According to the client log
```
[P1:T1:client] trace: ---- shim_openat(AT_FDCWD, "/usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1", O_RDONLY|0x80000, 0000) = -2
[sgx_dcap_load_qpl config.cpp:150] Couldn't find the Quote Provider library libdcap_quoteprov.so.1 or libdcap_quoteprov.so
```
The failure is caused by SGX DCAP Quote Provider library libdcap_quoteprov.so.1 not loaded. Perhaps this file is not in manifest.sgx.

**Comment by yanghongsing** [comment]
It looks like the libdcap_quoteprov.so is not in locations searched by client. I put the file at "/lib/libdcap_quoteprov.so", "/lib/x86_64-linux-gnu/libdcap_quoteprov.so" and "/usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so while they are added as trusted file. It successfully builds the handshake. The outputs are as below. It still reports an error of "Failed to open Intel SGX device". How should I correct this error? Thank you.
 [ using our own SGX-measurement verification callback (via command line options) ]
  - ignoring ISV_PROD_ID
  - ignoring ISV_SVN

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Installing RA-TLS callback ... ok
  . Performing the SSL/TLS handshake...[get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.
[get_driver_type /home/sgx/jenkins/ubuntuServer2004-release-build-trunk-215.1/build_target/PROD/label/Builder-UbuntuSrv20/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
[get_driver_type edmm_utility.cpp:111] Failed to open Intel SGX device.
[get_driver_type /home/sgx/jenkins/ubuntuServer2004-release-build-trunk-215.1/build_target/PROD/label/Builder-UbuntuSrv20/label_exp/ubuntu64/linux-trunk-opensource/psw/urts/linux/edmm_utility.cpp:111] Failed to open Intel SGX device.
 ok
  . Verifying peer X.509 certificate... ok
  > Write to server: 18 bytes written

GET / HTTP/1.0

  < Read from server: 156 bytes read

HTTP/1.0 200 OK
Content-Type: text/html

<h2>mbed TLS Test Server</h2>
<p>Successful connection using: TLS-ECDHE-RSA-WITH-CHACHA20-POLY1305-SHA256</p>

**Comment by llly** [comment]
It's correct. Simple ignore this error.
"Failed to open Intel SGX device" comes from SGX PSW components and is already handled because SGX device is not available inside Gramine LibOS.

**Comment by yanghongsing** [comment]
@llly Thank you! I close this issue

**Comment by dimakuv** [comment]
@yanghongsing You can find our discussion with @llly about this benign error message here: https://github.com/intel/linux-sgx/issues/756

It will be fixed in the new Intel SGX SDK/PSW release (or maybe it was already fixed in the latest release, not sure).

**Comment by yanghongsing** [comment]
@dimakuv noted. Thank you!
