### ISSUE TITLE
bind01 is failing with gramine-sgx

### ISSUE THREAD

**Issue by aniket-intelx** [gramineproject/gramine#458]
## Description of the problem
`bind01` was earlier failing with `gramine-direct` and was reported in #179 which got fixed later. However, it continues to fail with `gramine-sgx`.
## Steps to reproduce

Run `gramine-sgx bind01`
## Actual results

```
/home/intel/jenkins/workspace/local_ci_graphene_sgx_18.04_5.14/gramine/LibOS/shim/test/ltp/ltp_src/lib/tst_test.c:1364: TINFO: Timeout per run is 0h 05m 00s
/home/intel/jenkins/workspace/local_ci_graphene_sgx_18.04_5.14/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/bind/bind01.c:52: TPASS: invalid salen : EINVAL (22)
/home/intel/jenkins/workspace/local_ci_graphene_sgx_18.04_5.14/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/bind/bind01.c:52: TPASS: invalid socket : ENOTSOCK (88)
/home/intel/jenkins/workspace/local_ci_graphene_sgx_18.04_5.14/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/bind/bind01.c:55: TPASS: INADDR_ANYPORT passed
/home/intel/jenkins/workspace/local_ci_graphene_sgx_18.04_5.14/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/bind/bind01.c:52: TPASS: UNIX-domain of current directory : EAFNOSUPPORT (97)
/home/intel/jenkins/workspace/local_ci_graphene_sgx_18.04_5.14/gramine/LibOS/shim/test/ltp/ltp_src/testcases/kernel/syscalls/bind/bind01.c:52: TFAIL: non-local address expected EADDRNOTAVAIL: EACCES (13)

```

**Comment by dimakuv** [comment]
@jkr0103 @aneessahib This looks like a simple thing to fix. Can we assign someone to look into this?

**Comment by aneessahib** [comment]
@jkr0103  can look into it

**Comment by dimakuv** [comment]
@jkr0103 Can you put a comment here so that I can assign you on GitHub interface?

**Comment by jkr0103** [comment]
please assign to me

**Comment by boryspoplawski** [comment]
Please don't bother, I'm already reworking all of sockets code, so bind implementation will be different

**Comment by jinengandhi-intel** [comment]
Adding @Satya1493. This issue is an extension of #179 which was fixed by  Satya but he missed fixing for SGX. So he has agreed to look at it in the current sprint.

**Comment by mkow** [comment]
@jinengandhi-intel, @Satya1493: Please don't work on this, Borys will delete this whole implementation soon. There's no point in fixing it in the old one, especially that it's just LTP, not a real workload failing.

**Comment by boryspoplawski** [comment]
This test uses shared memory on SGX and as such does not pass. Could not verify if https://github.com/gramineproject/gramine/pull/579 would make it work.

**Comment by jinengandhi-intel** [comment]
@mkow any reason the bug was closed? For all LTP tests to run with Gramine SGX we have a way to run with MAP_PRIVATE flag, so Borys's comment is actually not valid. We will try to run the test with the PR and we should re-open the bug if the failure still exists. Will get back to you with the results.

**Comment by boryspoplawski** [comment]
@jinengandhi-intel I said I have no way of verifying if that PR makes it work - I don't see how's that invalid.

@aniket-intelx Pleasae try now, it was a bug unrelated to that PR, but I've stashed the fix there (just a missing errno translation in SGX PAL).

**Comment by aniket-intelx** [comment]
> @jinengandhi-intel I said I have no way of verifying if that PR makes it work - I don't see how's that invalid.
> 
> @aniket-intelx Pleasae try now, it was a bug unrelated to that PR, but I've stashed the fix there (just a missing errno translation in SGX PAL).

It continues to fail, please find the attached log.
[bind01_sgx_fail_log_after_fix.txt](https://github.com/gramineproject/gramine/files/8699375/bind01_sgx_fail_log_after_fix.txt)

**Comment by aniket-intelx** [comment]
> No idea, it works for me (I just changed the mapping to be non shared, since it's for reporting tests results only),

Could you please send the patch file along with the pass log so that we can try on our machine?

**Comment by boryspoplawski** [comment]
Note that this works only in this specific case, where we can just ignore this shared mapping (only used for tests results).
```
diff --git a/Pal/src/host/Linux-SGX/db_files.c b/Pal/src/host/Linux-SGX/db_files.c
index 7cd02913..e70c04d3 100644
--- a/Pal/src/host/Linux-SGX/db_files.c
+++ b/Pal/src/host/Linux-SGX/db_files.c
@@ -283,7 +283,8 @@ static int file_map(PAL_HANDLE handle, void** addr, pal_prot_flags_t prot, uint6
             "may add the PAL_PROT_WRITECOPY (MAP_PRIVATE) flag to your file mapping to keep "
             "the writes inside the enclave but they won't be reflected outside of the "
             "enclave.");
-        return -PAL_ERROR_DENIED;
+        //return -PAL_ERROR_DENIED;
+        prot |= PAL_PROT_WRITECOPY;
     }
 
     mem = get_enclave_pages(mem, size, /*is_pal_internal=*/false);
```

**Comment by aniket-intelx** [comment]
The testcase continues to fail with latest master. Please find the attached logs.
[bind01_fail_log.txt](https://github.com/gramineproject/gramine/files/8938989/bind01_fail_log.txt)
[bind01.manifest_sgx.txt](https://github.com/gramineproject/gramine/files/8938991/bind01.manifest_sgx.txt)

**Comment by boryspoplawski** [comment]
@aniket-intelx it works for me.
Are you sure you are using the latest master? From the log I see you are not building from git but some local copy, so cannot confirm, please make sure it's up to date.
Also does this test pass for you without Gramine? Maybe it's an issue with your machine configuration? The tests has some assumptions, quoting the source: `assumes 10.255.254.253 is not a local interface address!`

**Comment by aniket-intelx** [comment]
With latest master, it is working for me now. Thanks for the help.
