### ISSUE TITLE
Progress bar for large enclave or app

### ISSUE THREAD

**Issue by qiyuangong** [gramineproject/gramine#46]
## Description of the problem
When launching a large enclave with graphene, e.g, 32-128GB,  we need to wait for a few minutes for enclave creation and app/lib copy etc. However, current command line output show nothing to end users. We don't know which stage we are and how much time we need to wait for. That's not user friendly. :(

Adding a progress bar can simply fix this problem. 

## Steps to reproduce
Changing enclave size to 128GB in tensorflow example. 

## Expected results

```
Preparing Graphene Env 
[######         20%]  Creating enclave
Time used XXs
```

**Comment by mkow** [comment]
+1, this could be useful (despite it sounds a bit like bells and whistles). Any volunteer for implementing this?

**Comment by vijaydhanraj** [comment]
Based on profiling it shows that `adding_pages_to_enclaves` IOCTL for larger enclave memory requests and loading TOML takes most of the time. So, it is not possible to show a true progress bar (can display spinning hourglass animation) without splitting the IOCTL into smaller requests. But this makes the code more complicated and doesn't completely solve the issue (as TOML loading could be slow and not divisible). Also, in production environments, it is highly unlikely one runs Gramine in terminal mode to check the progress.

Given this, the current plan is to just add a log warning which will display a message saying "Adding pages to the enclave. Might take some time ..." which could help developers.

**Comment by qiyuangong** [comment]
> Based on profiling it shows that `adding_pages_to_enclaves` IOCTL for larger enclave memory requests and loading TOML takes most of the time. So, it is not possible to show a true progress bar (can display spinning hourglass animation) without splitting the IOCTL into smaller requests. But this makes the code more complicated and doesn't completely solve the issue (as TOML loading could be slow and not divisible). Also, in production environments, it is highly unlikely one runs Gramine in terminal mode to check the progress.
> 
> Given this, the current plan is to just add a log warning which will display a message saying "Adding pages to the enclave. Might take some time ..." which could help developers.

OK. That's much better than empty output. :)

**Comment by dimakuv** [comment]
@qiyuangong Please note that these log messages appear only with `loader.log_level = "warning"` or below ("debug", "trace", "all"). In other words, these log messages do not appear (except the very first one) if `loader.log_level = "error"`.

**Comment by qiyuangong** [comment]
> @qiyuangong Please note that these log messages appear only with `loader.log_level = "warning"` or below ("debug", "trace", "all"). In other words, these log messages do not appear (except the very first one) if `loader.log_level = "error"`.

Got it. Thanks :)
