### ISSUE TITLE
EAGAIN while accept()

### ISSUE THREAD

**Issue by xraw** [gramineproject/gramine#469]
## Description of the problem
While launching a simple asynch. HTTPS server with gramine-direct v1.1, I am running into an accept() error (11, EAGAIN).
The timeout value (5 * 60 * 1000 s.) is hardcoded in the boost headers. The source for the HTTPS
server is the unmodified example from:

https://www.boost.org/doc/libs/develop/libs/beast/example/http/server/async-ssl/http_server_async_ssl.cpp

## Gramine log excerpt
```
[P1:T1:exhttps] trace: ---- shim_getpid() = 0x1
[P1:T1:exhttps] trace: ---- shim_time(0) = 0x623adaa7
[P1:T1:exhttps] trace: ---- shim_eventfd2(0, 526336) = 0x3
[P1:T1:exhttps] trace: ---- shim_epoll_create1(524288) = 0x4
[P1:T1:exhttps] warning: Unsupported system call timerfd_create
[P1:T1:exhttps] debug: epoll: added 3 (0x7ffff3ef9e18) to epoll handle 0x7ffff3ef9f28
[P1:T1:exhttps] trace: ---- shim_epoll_ctl(4, ADD, 3, {.events=EPOLLIN|EPOLLERR|EPOLLET, .data=0x2327bec4b780}) = 0x0
[P1:T1:exhttps] trace: ---- shim_write(3, 0x2327bf649360, 0x8) ...
[P1:T1:exhttps] trace: ---- return from shim_write(...) = 0x8
[P1:T1:exhttps] trace: ---- shim_socket(INET, STREAM, 6) = 0x5
[P1:T1:exhttps] debug: epoll: added 5 (0x7ffff3efa038) to epoll handle 0x7ffff3ef9f28
[P1:T1:exhttps] trace: ---- shim_epoll_ctl(4, ADD, 5, {.events=EPOLLIN|EPOLLPRI|EPOLLERR|EPOLLHUP|EPOLLET, .data=0x2327bec4b7f0}) = 0x0
[P1:T1:exhttps] trace: ---- shim_setsockopt(5, 1, 2, 0x2327bf64972c, 4) = 0x0
[P1:T1:exhttps] trace: ---- shim_bind(5, 0x2327bf6497d0, 16) = 0x0
[P1:T1:exhttps] trace: ---- shim_listen(5, 4096) = 0x0
[P1:T1:exhttps] trace: ---- shim_ioctl(5, FIONBIO, 0x2327bf649828) ...
[P1:T1:exhttps] trace: ---- return from shim_ioctl(...) = 0x0
[P1:T1:exhttps] trace: ---- shim_accept(5, 0, 0) ...
[P1:T1:exhttps] trace: ---- return from shim_accept(...) = -11
[P1:T1:exhttps] trace: ---- shim_epoll_wait(4, 0x2327bf649340, 128, 300000) ...
[P1:T1:exhttps] trace: ---- return from shim_epoll_wait(...) = 0x1
[P1:T1:exhttps] trace: ---- shim_epoll_wait(4, 0x2327bf649340, 128, 300000) ...
```

While investigating the sources I have found some points I'd like to mention:

Code exccerpt from **v1.1**:
```c
static int __do_accept(struct shim_handle* hdl, int flags, struct sockaddr* addr, int* addrlen) {
    assert(WITHIN_MASK(flags, O_CLOEXEC | O_NONBLOCK));
```

Since flags is 0, this assert is true and the reason for returning with EAGAIN.
Whereas in **v1.0** it was handled in a way which caused no problems:
```c
static int __do_accept(struct shim_handle* hdl, int flags, struct sockaddr* addr, int* addrlen) {
    if (hdl->type != TYPE_SOCK)
        return -ENOTSOCK;
```

The flags are passed from shim/src/bookkeep/shim_handle.c and by checking the relevant structures I have foudn two suspicious comments:
```c
struct shim_handle* __get_fd_handle(uint32_t fd, int* fd_flags, struct shim_handle_map* map) {
  ...
    struct shim_fd_handle* fd_handle = NULL;
	...
    *fd_flags = fd_handle->flags;
  ...
```

shim/include/shim_handle.h we have for the **struct shim_handle**:
```c
    /* TODO: the `flags` and `acc_mode` fields contain duplicate information (the access mode).
     * Instead of `flags`, we should have a field with different name (such as `options`) that
     * contain the open flags without access mode (i.e. set it to `flags & ~O_ACCMODE`). */
    int flags; /* Linux' O_* flags */
    int acc_mode;
```

And for the **struct shim_fd_handle**:
```c
struct shim_fd_handle {
    uint32_t vfd; /* virtual file descriptor */
    int flags;    /* file descriptor flags, only FD_CLOEXEC */
  ...
```

The flags of shim_fd_handle is about FD_CLOEXEC only and flags for shim_handle is
about the O_ flags. In __get_fd_handle though, the shim_fd_handle flags are assigned and checked against O_ flags.

**Comment by boryspoplawski** [comment]
Your socket is set as non-blocking, so `EAGAIN` is perfectly normal return value.

> Since flags is 0, this assert is true and the reason for returning with EAGAIN.

That makes no sense to me. What the assert has to do with the return value?

**Comment by monavij** [comment]
@boryspoplawski - but main point walantis is making is that this code worked in v1.0, but they are seeing problems in v1.1.

**Comment by mkow** [comment]
@monavij: What Borys meant is that the problem as described is just a normal Linux behavior. So, if the user app relies on it to _not_ happen, then it can also fail on Linux. So, here I guess either the analysis posted by @xraw is misleading or the example he used is buggy. Of course in the first case it may mean that we actually have a bug in Gramine, it's just different than described ;)

Anyways, we can take a look at this example and verify whether it's correct or not.

**Comment by boryspoplawski** [comment]
I've managed to isolate the problem on a small repro, still trying to rootcause it.

**Comment by boryspoplawski** [comment]
@xraw Please verify if https://github.com/gramineproject/gramine/pull/499 fixes the issue
