### ISSUE TITLE
 Error: Error during shim_init() in init_elf_objects (-2)

### ISSUE THREAD

**Issue by cavidan1** [gramineproject/gramine#475]
Hello,

I have installed and built Gramine. helloworld example runs in both mod with SGX and without SGX. I am trying to build my code with GRAMINE and [PALISADE library](https://gitlab.com/palisade/palisade-release). When I do `make SGX=1`, it goes well. When I say `gramine-sgx myProject`, it returns this error: 

`[P1:T1:myProject] error: Error during shim_init() in init_elf_objects (-2)`

I couldn't understand if my Makefile or manifest file is wrong.

Thank you for your help.

**Comment by boryspoplawski** [comment]
Maybe `myProject` is not an ELF file, but e.g. a bash script with a shebang (support for these is pending)?

**Comment by cavidan1** [comment]
It is a .cpp file. I tried two code versions. 1. A basic fully homomorphic encryption key generation operation from [PALISADE library](https://gitlab.com/palisade/palisade-release), 2. just printing hello world, but it has `#include "palisade.h"`( to check if key generation fails in SGX mode.) Both versions give the error I mentioned above.

**Comment by boryspoplawski** [comment]
> It is a .cpp file.

Then you need to build it first :) Assuming you already are, then we need some more details, makefile and manifest would be good starters.

**Comment by cavidan1** [comment]
Yes, I already built it. My project name is `small_pal`. When I make SGX=1, it creates the necessary files. ` small-pal.manifest.sgx, small-pal.o, small-pal.token, small-pal, small-pal.manifest,  small-pal.manifest.template  small-pal.sig`. 

You can find the manifest and makefile as follow:

Makefile: 

 ` #defination for compiler 
CC:= clang++ -std=c++11 -fPIC
ifeq ($(DEBUG),1)
GRAMINE_LOG_LEVEL = debug
CFLAGS += -g
else
GRAMINE_LOG_LEVEL = error
CFLAGS += -O3
endif
#defination for compiler flag
CFLAG:= -g -Wall -Werror -O3 -fopenmp

SRCDIR:= src
DEMODIR:= demo
BUILDFLDR:= build
LIB:=/usr/local
PALISADEDIR:= /usr/local/include/palisade
export CPLUS_INCLUDE_PATH:=$(PALISADEDIR)
INCLUDES:= $(shell find $(PALISADEDIR) -name "pke" -o -name "core" -o -name "cereal"  | sed -e 's/^/-I /'| xargs)
LINKDIR:= -L$(LIB)/lib

all: small-pal small-pal.manifest
ifeq ($(SGX),1)
all: small-pal.manifest.sgx small-pal.sig small-pal.token
endif

#build for files
%.o : %.cpp
	$(CC) $(CFLAG) $(INCLUDES) -c $< -o $@

#Link the files with libraries
small-pal: small-pal.o
	$(CC) $(CFLAG) -o $@ $^ $(LINKDIR) -lPALISADEbinfhe -lPALISADEcore -lPALISADEpke
	


small-pal.manifest: small-pal.manifest.template
	gramine-manifest \
		-Dlog_level=$(GRAMINE_LOG_LEVEL) \
		$< $@

small-pal.manifest.sgx: small-pal.manifest small-pal
	gramine-sgx-sign \
		--manifest $< \
		--output $@

small-pal.sig: small-pal.manifest.sgx

small-pal.token: small-pal.sig
	gramine-sgx-get-token \
		--output $@ --sig $<

ifeq ($(SGX),)
GRAMINE = gramine-direct
else
GRAMINE = gramine-sgx
endif

		 
.PHONY: clean
	
clean:
	rm -rf small-pal small-pal.o  small-pal.sig small-pal.token small-pal.manifest.sgx  small-pal.manifest
` 

small-pal.manifest.template file:

` # small-pal manifest file example

loader.entrypoint = "file:{{ gramine.libos }}"
libos.entrypoint = "small-pal"
loader.log_level = "{{ log_level }}"
loader.argv0_override = "small-pal"
##loader.env.LD_LIBRARY_PATH = "/usr/local/lib"
loader.env.LD_LIBRARY_PATH = "/lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu:/usr/local/lib/:/usr/local/lib/"

fs.mounts = [
  { path = "/lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu:/usr/local/lib/:/usr/local/lib/", uri = "file:{{ gramine.runtimedir() }}" },
]

sgx.debug = true
sgx.nonpie_binary = true

sgx.trusted_files = [
  "file:{{ gramine.libos }}",
  "file:small-pal",
  "file:{{ gramine.runtimedir() }}/",
]


` 
Thank you for your help.

**Comment by NieDzejkob** [comment]
The issue is that you have told Gramine to mount the directory with Gramine's libc at `/lib:/lib/x86_64-linux-gnu:/usr/lib:/usr/lib/x86_64-linux-gnu:/usr/local/lib/:/usr/local/lib/`, instead of the more traditional `/lib`. Thus Gramine can't find the `ld-linux-x86-64.so.2` requested by your application, because it's somewhere deep in the weirdly-named `/lib:` folder, and it didn't think to look there.

So, read the [documentation on the manifest fields](https://gramine.readthedocs.io/en/latest/manifest-syntax.html) you're changing.

Though I do agree the error message is atrocious.

**Comment by cavidan1** [comment]
When I only add ` /lib` to fs.mount, it returns `small-pal: error while loading shared libraries: libPALISADEbinfhe.so.1: cannot open shared object file: No such file or directory`. `libPALISADEbinfhe.so.1` is under `/usr/local/lib/`. I am still confused how to set the paths properly. Thank you for your help.

**Comment by NieDzejkob** [comment]
Try this:
```
fs.mounts = [
  { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
  { path = "/usr/local/lib", uri = "file:/usr/local/lib" },
]
```

**Comment by cavidan1** [comment]
Thank you so much. Your suggestion helped me a lot. 

I edited my manifest file as follows. I also added these new paths to `sgx.trusted_files`. 

```
fs.mounts = [
{ path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
{path = "/usr/local/lib", uri = "file:/usr/local/lib" },
{path="/usr/lib/x86_64-linux-gnu/",uri="file:/usr/lib/x86_64-linux-gnu/"},
]
```
