### ISSUE TITLE
Ubuntu install gramine from apt, missing bin file

### ISSUE THREAD

**Issue by CodingBen** [gramineproject/gramine#477]
```sh
sudo apt-get install gramine
gramine-sgx-gen-private-key: command not found
```

**Comment by jkoston** [comment]
I am seeing this same issue these are the only commands I see available

gramine-argv-serializer        gramine-sgx                    gramine-sgx-pf-crypt
gramine-direct                 gramine-sgx-get-token          gramine-sgx-pf-tamper
gramine-gen-depend             gramine-sgx-ias-request        gramine-sgx-quote-dump
gramine-manifest               gramine-sgx-ias-verify-report  gramine-sgx-sign
