### ISSUE TITLE
Issue with NGINX in reverse proxy mode in Gramine plus Ubuntu 20.04.4

### ISSUE THREAD

**Issue by mjkambex** [gramineproject/gramine#485]
## Steps to reproduce
Step 1:
Update to latest Ubuntu 20.04.4

Step 2:
Download GRPC sources - https://github.com/grpc/grpc
Compile and verify using the cpp helloworld example is working
(https://grpc.io/docs/languages/cpp/quickstart/)

Step 3:
Download NGINX 1.18 sources and compile
Configure NGINX in reverse proxy mode to forward request to the GRPC server from Step 1.

Step 4:
Run GRPC client submitting request to NGINX port. (NGINX should forward request to GRPC server and get back the response and return to the GRPC client)

Step 5:
Graminse the NGINX server. Run NGINX with gramine-direct.

## Actual results

No response is received by the GRPC client, while it works without gramine.

## Gramine commit hash
e37f773d4d910799a854b90334f2ff8eb6f411bd

**Comment by ravikumarbhattiprolu** [comment]
This issue seems to be related to #489. After #489 is fixed, we can try this again.

**Comment by boryspoplawski** [comment]
@mjkambex @ravikumarbhattiprolu You can try https://github.com/gramineproject/gramine/pull/499 to check if the issue still persists.
