### ISSUE TITLE
user mode linux

### ISSUE THREAD

**Issue by aep** [gramineproject/gramine#486]
## Description of the problem

wondering what the limitations are of gramine loading a user-mode linux kernel.
but it can't even load the binary.

## Steps to reproduce
```
cd linux ; make ARCH=um
gramine-direct ./vmlinuz
Checking that ptrace can change system call numbers...ptrace: Function not implemented
```

this is fine and what i wanted to see. however, gramine-sgx does this:

```
gramine-sgx ./vmlinuz
[P1:T1:helloworld] error: Failed to map file://root/gramine/CI-Examples/helloworld/vmlinuz. This may be caused by the binary being non-PIE, in which case Gramine requires a specially-crafted memory layout. You can enable it by adding 'sgx.nonpie_binary = true' to the manifest.
```

i do have sgx.nonpie_binary = true in the manifest.
the vmlinux binary doesn't look in any way special to me, other than being non-PIE

```
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 03 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - GNU
  ABI Version:                       0
  Type:                              EXEC (Executable file)
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x60017140
  Start of program headers:          64 (bytes into file)
  Start of section headers:          44306384 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         7
  Size of section headers:           64 (bytes)
  Number of section headers:         66
  Section header string table index: 65

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  LOAD           0x0000000000000000 0x0000000060000000 0x0000000060000000
                 0x00000000000001c8 0x00000000000001c8  R      0x1000
  LOAD           0x0000000000001000 0x0000000060001000 0x0000000060001000
                 0x000000000030126d 0x000000000030126d  R E    0x1000
  LOAD           0x0000000000303000 0x0000000060303000 0x0000000060303000
                 0x0000000000139f90 0x0000000000139f90  RWE    0x1000
  LOAD           0x000000000043d000 0x000000006043d000 0x000000006043d000
                 0x000000000004cc08 0x0000000000076388  RW     0x1000
  NOTE           0x0000000000438e48 0x0000000060438e48 0x0000000060438e48
                 0x0000000000001700 0x0000000000001700  R      0x8
  TLS            0x0000000000489be0 0x0000000060489be0 0x0000000060489be0
                 0x0000000000000028 0x0000000000000078  R      0x8
  GNU_STACK      0x0000000000000000 0x0000000000000000 0x0000000000000000
                 0x0000000000000000 0x0000000000000000  RWE    0x10

```

how do i even debug the ELF loader when its inside the sgx?

note that it doesnt have a loader. i tried setting the kernel as loader.entrypoint instead but got 
```
error: Loaded binary doesn't have string table, symbol table and/or hash table
```

it doesnt need a symbol table because it has nothing to load. anyway, this appears to be the wrong direction, as it worked fine with gramine-direct before and just failed with gramine-sgx

## Gramine commit hash

e37f773d4d910799a854b90334f2ff8eb6f411bd

**Comment by boryspoplawski** [comment]
Try increasing the enclave size in the manifest. Your entrypoint address (`0x60017140`) is beyond 1.5gb and due to how SGX works and how Gramine deals with that, we map memory from address `0` for non-pie binaries. This means you need enclave size at least 1.5gb + binary size + some memory for Gramine (2bg should be enough, if the binary is < 400mb). Also note that the enclave size must be a power of 2.

> i tried setting the kernel as loader.entrypoint instead

`loeader.entrypoint` is rather an internal thing - it points to the LibOS binary that the PAL layer will load. It has nothing to do with dynamic loading/interpreters (PT_INTERP).
You can find more information in our docs: https://gramine.readthedocs.io/en/latest/manifest-syntax.html#loader-entrypoint

**Comment by aep** [comment]
sgx.enclave_size = "4G"

didn't really solve the issue

looks like i forgot a relevant part of the error message:

    [P1:T1:helloworld] error: Error during shim_init() in init_elf_objects (-22)

poking around that part of the code and changing all log_debug to log_error i see

    [P1:T1:helloworld] error: execute_loadcmd: failed to map segment: -12

the parameters that get passed to mmap are

    map_start: 0x60000000
    map_size: 4096
    prot: 1
    flags: 18
    off: 0

which seems fine? that's at 1.6GB

**Comment by boryspoplawski** [comment]
> i got confused how the config syntax works and wrote sgx.enclave_size = "4G" at the bottom. it works fine on the top of the file.

That should not matter, you should be able to put it anywhere as long as it's a valid TOML (well, actually a jinja template which is then rendered to TOML).

> apparantly the manifest is parsed on syscall?

No, manifest is loaded (and parsed) at the begining. The log message could be from the child process, that's why it's itermixed like that.
It could fail due to some not supported flags to `clone()`, but seems that the child process is spawned, just initial setup inside it fails.
Maybe try running with `log_level = "all"`, there will be a lot of information there.

**Comment by aep** [comment]
> The log message could be from the child process, 

a clone actually starts a new shim? hm, not how i expected this works. anyway, good to know.

> Maybe try running with `log_level = "all"`, there will be a lot of information there.

oh yeah that helps!

```
Checking that ptrace can change system call numbers...[P1:T1:helloworld] trace: ---- return from shim_write(...) = 0x36
[P1:T1:helloworld] trace: ---- shim_clone(CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|[SIGCHLD], 0, 0, 0x9b35fa10, 0) ...
[P1:T1:helloworld] debug: Creating pipe: pipe.srv:cbd4cc45928df10c0e3fe86435f43b0a7988a253fd9117bad13bd9226ca594fa
Parsing TOML manifest file, this may take some time...
warning: Parsed TOML manifest file successfully
debug: Token file: ./helloworld.token
debug: Read dummy DCAP token
debug: enclave created:
debug:     base:           0x0000000000000000
debug:     size:           0x0000000100000000
debug:     misc_select:    0x00000000
debug:     attr.flags:     0x0000000000000007
debug:     attr.xfrm:      0x0000000000000003
debug:     ssa_frame_size: 4
debug:     isv_prod_id:    0x00000000
debug:     isv_svn:        0x00000000
warning: Adding pages to SGX enclave, this may take some time...
debug: adding pages to enclave: 0xffffd000-0x100000000 [REG:R--] (manifest) measured
debug: adding pages to enclave: 0xfffdd000-0xffffd000 [REG:RW-] (ssa) measured
debug: adding pages to enclave: 0xfffd9000-0xfffdd000 [TCS:---] (tcs) measured
debug: adding pages to enclave: 0xfffd5000-0xfffd9000 [REG:RW-] (tls) measured
debug: adding pages to enclave: 0xfff95000-0xfffd5000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xfff55000-0xfff95000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xfff15000-0xfff55000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xffed5000-0xfff15000 [REG:RW-] (stack) measured
debug: adding pages to enclave: 0xffec5000-0xffed5000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xffeb5000-0xffec5000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xffea5000-0xffeb5000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xffe95000-0xffea5000 [REG:RW-] (sig_stack) measured
debug: adding pages to enclave: 0xffa5c000-0xffabd000 [REG:R-X] (code) measured
debug: adding pages to enclave: 0xffabd000-0xffac1000 [REG:RW-] (data) measured
debug: adding pages to enclave: 0xffac1000-0xffe95000 [REG:RW-] (bss) measured
debug: adding pages to enclave: 0x10000-0xffa5c000 [REG:RWX] (free)
[P1:T1:helloworld] error: process creation failed
[P1:T1:helloworld] trace: ---- return from shim_clone(...) = -13
[P1:T1:helloworld] trace: ---- shim_write(2, 0x9b5d06a0, 0x35) ...
start_ptraced_child : fork failed: Permission denied
[P1:T1:helloworld] trace: ---- return from shim_write(...) = 0x35
[P1:T1:helloworld] debug: ---- shim_exit_group (returning 1)
[P1:T1:helloworld] debug: clearing POSIX locks for pid 1
[P1:T1:helloworld] debug: sync client shutdown: closing handles
[P1:T1:helloworld] debug: sync client shutdown: waiting for confirmation
[P1:T1:helloworld] debug: sync client shutdown: finished
[P1:shim] debug: IPC worker: exiting worker thread
[P1:T1:helloworld] debug: process 1 exited with status 1
```

or not. it still just says fork failed: Permission denied.


these pages look huge. i wonder if this garbo NUC is just running out of memory

**Comment by aep** [comment]
> these pages look huge. i wonder if this garbo NUC is just running out of memory

spoiler: yes. just upgrading it to 8GB fixed it.
it's now failing as expected in ptrace
thanks for the help!

now the question is, should i start implementing ptrace? I was wondering if UML might be an easy hack to get most userspace to just work without having to fix the other syscalls.
but UML cannot be built as PIE, and if non-PIE allocation actually requires the real memory to exist from addr 0 up, this is game ending overhead.

**Comment by aep** [comment]
> how would you implement it on other backends (e.g. Windows).

oh. well, actually in that case it might be easier to just patch that in the kernel. Or even directly throw the gramine abi in there.

> I guess you could work around that by increasing swap space 

that sounds not great. Is there a fundamental reason it has to allocate the entire space? 
I suppose because enclaves don't have a virtual address space so their mem starts at 0?
could probably hack up the kernel to load somewhere else then.

> why do you want to run UML in Gramine? 

Ah mostly just a quick shower idea.
I couldn't really figure out how the docker thing works (lots of python errors, i dont know python).
UML would be an easy cheat to get any existing userspace working immediately without retooling anything.

**Comment by boryspoplawski** [comment]
> that sounds not great. Is there a fundamental reason it has to allocate the entire space?
I suppose because enclaves don't have a virtual address space so their mem starts at 0?
could probably hack up the kernel to load somewhere else then.

Enclaves do have a virtual address space, and we can choose the start and end, but there are limitations, like size must be a power of two and starting address must be a multiple of size, or something like that, don't remember at the moment. That's why for non-pie binaries we pick starting address `0` - they cannot be relocated.
Note that a lot of this will change with SGX2 (actually EDMM which is dynamic memory management in SGX) - then we will be able to add pages dynamically and won't have such restictions. HW is already there (I believe), Linux kernel support is pending - Gramine will shortly follow.

> UML would be an easy cheat to get any existing userspace working immediately without retooling anything.

Docker stuff we have (GSC) is just for ease of deployment and running containers you already have. Gramine emulates the Linux kernel and as such just runs unmodified ELF files - so any binary you have, you should be able to run (of course some syscalls might not be implemented, but most of them are), you just need to write a manifest. Basically what you did with UML binary, there is no need to use docker.

**Comment by aep** [comment]
very interesting. thanks for the help and explanation.
i'm going to retry this again when virtual memory works, for curiosity mostly.
UML adds interesting options like having your network stack inside SGX.
but for now going back to using gramine the proper way :)

**Comment by boryspoplawski** [comment]
Dynamic memory won't help you with `ptrace` not being implemented (and we have no plans for implementing it).
What's the point of running network stack inside SGX? All of it (like routing, addresses, headers etc) can still be changes by untrusted host OS.

**Comment by dimakuv** [comment]
@aep Running some app on top of UML on top of Gramine-SGX sounds like a fun idea. If you're doing it just for research or for your own entertainment/curiosity, it would be interesting to try out.

Doing it for some production stuff doesn't seem to make much sense... A lot of overhead and engineering effort for dubious advantages (e.g., there are user-level network stack implementations like `mTCP`, it makes more sense to put something like this in Gramine if you really need to).

I second everything that @boryspoplawski said in this thread.

> I couldn't really figure out how the docker thing works (lots of python errors, i dont know python).
> UML would be an easy cheat to get any existing userspace working immediately without retooling anything.

I would say that Docker images would definitely be easier than UML hackery :)

With the GSC tool, changing a base Docker image into a "Graminized" Docker image is a matter of two command-line steps: https://gramine.readthedocs.io/projects/gsc/en/latest/#example

**Comment by aep** [comment]
> for dubious advantage

i dunno, i still like the idea. Linux has a well established ABI and getting the gramine libos bug compatible with that sounds like a lot of effort.  linux is also a hypervisor, so you could actually run an entire os like windows inside SGX.

Either way, this is just a shower thought, so i'm going to close this and focus on using gramine correctly ;)


> With the GSC tool

yeah that didn't work for me, but i'll try to get some actual useful info before filing a bug later.

**Comment by boryspoplawski** [comment]
> Linux has a well established ABI 

We have the very same ABI.

> linux is also a hypervisor, so you could actually run an entire os like windows inside SGX.

If you mean KVM then no, it won't work. Otherwise I have no idea, but generally speaking I don't think it's possible.

**Comment by mkow** [comment]
> i dunno, i still like the idea. Linux has a well established ABI and getting the gramine libos bug compatible with that sounds like a lot of effort.

But what you're trying to do here is quite analoguous to running docker inside docker ;) I don't think that UML will work, because it most likely uses a lot of syscalls and subsystems intended for debugging/introspection, which aren't useful for Gramine and are not implemented.

> linux is also a hypervisor, so you could actually run an entire os like windows inside SGX.

Yes, it's a hypervisor, but not an x86 emulator. It uses hardware acceleration to do this, for which you need ring0 and enclaves run in ring3. And even if that wouldn't be an issue, there are tons of other problems which IMO make this approach infeasible.
