### ISSUE TITLE
LibOS does not know about PAL allocating pages

### ISSUE THREAD

**Issue by boryspoplawski** [gramineproject/gramine#50]
Currently when PAL allocates a page (for its internal purposes e.g. memory for event objects) LibOS has no idea about it. This sometimes leads to LibOS allocating a page on the same address and _lie​s of_ **Man ALL IS LOST ALL I​S L**OST the _pon̷y he comes_ he c̶̮om~~es he come~~**s the ich​**or permeates _all_ MY FACE _MY FACE ᵒh god n_**o NO NOO̼O​O N**Θ stop the an​*​gle̠̅s ͎a̧͈͖re n​**ot reaͨl ZALGΌ IS T**OƝ̴ȳ̳ TH̘**Ë͖́̉ ͠P̯͍̭O̚​N̐Y̡ HE COMES**
([source](https://stackoverflow.com/questions/1732348/regex-match-open-tags-except-xhtml-self-contained-tags))

**Comment by dimakuv** [comment]
This was resolved by https://github.com/gramineproject/gramine/pull/839 and co, closing.
