### ISSUE TITLE
[Pal/Linux-SGX] getsockname() get wrong addr and port on unbind SOCK_STREAM socket

### ISSUE THREAD

**Issue by llly** [gramineproject/gramine#500]
## Description of the problem
I reproduce https://github.com/gramineproject/graphene/issues/2046 on Gramine master using C code instead of Java.

## Steps to reproduce
TCP server locate at `10.239.34.5:4433` and TCP client locate at `10.239.45.129`
Run sample code from https://gist.github.com/listnukira/4045436
## Expected results
```
$ ./get_ip_v1
Local ip address: 10.239.45.129
Local port : 41200
$ gramine-direct get_ip_v1
Local ip address: 10.239.45.129
Local port : 41204
```
## Actual results
```
$ gramine-sgx get_ip_v1
Local ip address: 10.239.34.5
Local port : 4433
```
## Additional information
`getsockname` syscall is called with `connect` in LibOS. `getsockname` in LibOS only returns the cached data.
As my description in https://github.com/gramineproject/graphene/issues/2046.
The root cause is in Linux-SGX, `bind_addr` is NULL.
https://github.com/gramineproject/gramine/blob/f0ff0944a0ca0639c0b8a626a8165e731ce18283/Pal/src/host/Linux-SGX/db_sockets.c#L356-L357
SGX ocall `ocall_connect` cannot allocate memory in enclave and doesn't call `getsockname`.
 https://github.com/gramineproject/gramine/blob/f0ff0944a0ca0639c0b8a626a8165e731ce18283/Pal/src/host/Linux-SGX/sgx_enclave.c#L453-L455.
however, Linux pal can work because `bind_addr` reassigned. https://github.com/gramineproject/gramine/blob/f0ff0944a0ca0639c0b8a626a8165e731ce18283/Pal/src/host/Linux/db_sockets.c#L460-L464
I'll create a PR to fix it.

## Gramine commit hash

c56a3536b182021fa0655d9d55f3076ceced6fff

**Comment by dimakuv** [comment]
> I'll create a PR to fix it.

@boryspoplawski is fixing the whole subsystem of sockets/networking in Gramine currently.

But if your fix is small and contained, then we can review & merge it now, to unblock such workloads.

**Comment by llly** [comment]
Yes, a small one. 
Will #262 also be fixed? This `getsockname` issue has one more root cause that sockname of UDP cannot be retrieved right after connect, but after a `sendto`.

**Comment by boryspoplawski** [comment]
Yes, everything will be fixed (hopefully). The new version will is written from scratch.

**Comment by boryspoplawski** [comment]
@llly Please verify if https://github.com/gramineproject/gramine/pull/579 fixes this. I did with my tests.

**Comment by llly** [comment]
Yes. It fixes issue.
