### ISSUE TITLE
[LibOS] Errors from writing to a pseudo-file are not propagated to user

### ISSUE THREAD

**Issue by pwmarcz** [gramineproject/gramine#502]
## Description of the problem

When writing malformed data to pseudo-files in `/dev/attestation`, all operations will succeed.

## Steps to reproduce

Use the busybox example:

```
gramine-sgx busybox sh -c 'echo foo> /dev/attestation/protected_files_key'
```

## Expected results

`busybox` should complain at some point.

## Actual results

The operation succeeds. Here is the log from Gramine:

```
[P1:T1:busybox] trace: ---- shim_openat(AT_FDCWD, "/dev/attestation/protected_files_key", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 0x3
[P1:T1:busybox] trace: ---- shim_fcntl(1, OP 1030, 0xa) = 0xa
[P1:T1:busybox] trace: ---- shim_dup2(3, 1) = 0x1
[P1:T1:busybox] trace: ---- shim_close(3) = 0x0
[P1:T1:busybox] trace: ---- shim_write(1, 0x16155410, 0x4) ...
[P1:T1:busybox] trace: ---- return from shim_write(...) = 0x4
[P1:T1:busybox] debug: /dev/attestation/protected_files_key: invalid length
[P1:T1:busybox] debug: pseudo_str_flush() failed, proceeding with close
[P1:T1:busybox] trace: ---- shim_dup2(10, 1) = 0x1
[P1:T1:busybox] trace: ---- shim_close(10) = 0x0
```

## Gramine commit hash

c56a3536b182021fa0655d9d55f3076ceced6fff

## Explanation

The pseudo-files are stored as in-memory strings. You can write to them, and flush/close operation will trigger the `save` callback (see `shim_fs_pseudo.c`).

This callback fails ("invalid length"), and the error code is propagated to the `close` callback, which returns it. However, our implementation of the close syscall only decreases the reference count on a handle, and **always returns 0**.

So the call chain is:

```
shim_do_close()  (returns 0)
put_handle()     (returns void, swallows error from pseudo_close())
pseudo_close()   (returns -EINVAL)
pfkey_save()     (returns -EINVAL)
```

## Possible solutions

* ~~Propagate error through the above chain~~: I don't think this works. `shim_do_close` might not actually end up closing the file (e.g. if there are multiple FDs).
* Always flush the file in `shim_do_close`: This will also work, but is pretty hacky, and some applications might disregard errors from `close`.
* **Change semantics of pseudo-files so that `write` will already process the value** (and return an error): I think this is a good choice, but it means that all such files (`protected_files_key`, `user_report_data`, `target_info`) need to be written using a single `write` syscall.

**Comment by dimakuv** [comment]
I don't like the last solution (marked in bold). Unless you want to restrict this solution to only `/dev/attestation` files?

Still, this feels like an unnecessary restriction on the user. Why can't the user write the key byte by byte, and expect the key to be updated only when the file is flushed/closed? This would be the least surprising behavior.

What is wrong with solution 2 (flushing on close)? Isn't it the most straight-forward approach? What do you mean by `some applications might disregard errors from close`?

**Comment by pwmarcz** [comment]
>I don't like the last solution (marked in bold). Unless you want to restrict this solution to only /dev/attestation files?

Yes, since these are the only uses of this mechanism that we have.

>What is wrong with solution 2 (flushing on close)? Isn't it the most straight-forward approach? What do you mean by some applications might disregard errors from close?

I know of bash and busybox. If you do something like `echo foo > a.txt`, error from `write` will be reported to the user, but error from `close` will be silently disregarded.

```
user ~ $ strace -f -P a.txt -e inject=write:error=EACCES busybox sh -c "echo foo>a.txt"
strace: Requested path "a.txt" resolved into "/home/user/a.txt"
open("a.txt", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
dup2(3, 1)                              = 1
close(3)                                = 0
write(1, "foo\n", 4)                    = -1 EACCES (Permission denied) (INJECTED)
sh: write error: Permission denied
dup2(10, 1)                             = 1
+++ exited with 1 +++
```

```
user ~ $ strace -f -P a.txt -e inject=close:error=EACCES busybox sh -c "echo foo>a.txt"
strace: Requested path "a.txt" resolved into "/home/user/a.txt"
open("a.txt", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 3
dup2(3, 1)                              = 1
close(3)                                = -1 EACCES (Permission denied) (INJECTED)
write(1, "foo\n", 4)                    = 4
dup2(10, 1)                             = 1
+++ exited with 0 +++
```

As an added data point, this is how Linux sysfs is implemented: it expects all data in a single write. See `Documentation/filesystems/sysfs.rst`:

```
- On write(2), sysfs expects the entire buffer to be passed during the
  first write. Sysfs then passes the entire buffer to the store() method.
  A terminating null is added after the data on stores. This makes
  functions like sysfs_streq() safe to use.
```

**Comment by pwmarcz** [comment]
Looking at that bash example, it's actually even worse for us: the shell opens a file, duplicates the FD, then closes the old one _before_ writing. So the flush would be on empty string, not the actual written content. And the final "close" is done on process exit, without an explicit close syscall, so there's no chance to report anything to the user.

**Comment by dimakuv** [comment]
Ok, I'm convinced to use solution 3.

**Comment by mkow** [comment]
+1 to 3, this is a file in `/dev`, so the users should expect that it may not behave same as a regular file. Although this still keeps  `echo foo> /dev/attestation/protected_files_key` technically incorrect - one should use `dd` for this to ensure a single write.
