### ISSUE TITLE
Most LTP testcases will not work under SGX

### ISSUE THREAD

**Issue by woju** [gramineproject/gramine#51]
Multiple test cases fail with this message:
stdout:
```
tst_test.c:109: BROK: mmap((nil),4096,3,1,3,0) failed: EACCES
```
stderr:
```
*** No client info specified in the manifest. Graphene will not perform remote attestation ***
file_map does not currently support writable pass-through mappings on SGX.  You may add the PAL_PROT_WRITECOPY (MAP_PRIVATE) flag to your file mapping to keep the writes inside the enclave but they won't be reflected outside of the enclave.
```

The reason is because most test cases use standardised `main` function:

https://github.com/linux-test-project/ltp/blob/f2926be6514023bb94141792e4e2bfffd2aac0fc/include/tst_test.h#L279-L288

This function calls `do_setup()`:

https://github.com/linux-test-project/ltp/blob/f2926be6514023bb94141792e4e2bfffd2aac0fc/lib/tst_test.c#L1237

And `do_setup()` calls `setup_ipc()`:

https://github.com/linux-test-project/ltp/blob/f2926be6514023bb94141792e4e2bfffd2aac0fc/lib/tst_test.c#L816

`setup_ipc()` calls `mmap(..., MAP_SHARED, ...)`:
https://github.com/linux-test-project/ltp/blob/f2926be6514023bb94141792e4e2bfffd2aac0fc/lib/tst_test.c#L99

`MAP_SHARED` is unsupported under SGX.

Only tests which have their own `main()` function can possibly run under SGX. But I'd expect more, not less, testcases which would use this common setup function, because it is less code to write and maintain.

<details><summary>Tests that are disabled for this bug, because they're failing</summary>
<code><pre>
abort01
accept01
accept4_01
access01
access02
access03
access04
acct01
add_key01
add_key02
add_key03
add_key04
alarm02
alarm03
alarm05
alarm06
alarm07
bind03
brk01
chdir03
chmod05
chmod06
chmod07
clock_adjtime01
clock_adjtime02
clock_gettime02
clone09
copy_file_range01
creat01
creat03
creat04
creat05
creat06
creat07
delete_module01
delete_module02
delete_module03
dirtyc0w
epoll_create1_01
epoll_ctl01
epoll_ctl02
epoll_wait02
execl01
execle01
execlp01
execv01
execve01
execve02
execve03
execve04
execve05
execveat01
execveat02
execveat03
execvp01
exit02
fallocate05
fanotify01
fanotify02
fanotify03
fanotify04
fanotify05
fanotify07
fanotify08
fanotify09
fanotify10
fanotify11
fanotify12
fchdir03
fchmod01
fchmod02
fchmod05
fchmod06
fcntl02
fcntl02_64
fcntl03
fcntl03_64
fcntl04
fcntl04_64
fcntl33
fcntl33_64
fcntl35
fcntl35_64
fdatasync03
fgetxattr01
fgetxattr02
fgetxattr03
flistxattr01
flistxattr02
flistxattr03
flock01
flock02
flock04
flock06
fremovexattr01
fremovexattr02
fsetxattr01
fsetxattr02
fsync01
fsync04
ftruncate04
ftruncate04_64
futex_wait05
getcpu01
getcwd01
getcwd02
getcwd03
getcwd04
getpriority01
getpriority02
getrandom01
getrandom02
getrandom03
getrandom04
getrlimit03
getsockopt02
getxattr04
inotify01
inotify02
inotify03
inotify04
inotify05
inotify07
inotify08
ioctl03
ioctl04
ioctl05
ioctl06
ioctl07
kcmp01
kcmp02
kcmp03
keyctl01
keyctl02
keyctl03
keyctl04
keyctl05
keyctl06
keyctl08
lgetxattr01
lgetxattr02
link08
listxattr02
listxattr03
llistxattr01
llistxattr02
llistxattr03
lseek01
lseek07
lseek11
madvise01
madvise02
madvise05
madvise06
madvise07
madvise08
madvise09
madvise10
memfd_create01
memfd_create02
mkdir02
mkdir05
mlock201
mlock202
mlock203
mmap12
mmap16
mprotect02
msgctl01
msgctl02
msgctl03
msgctl04
msgctl12
msgget01
msgget02
msgget03
msgsnd02
msgsnd05
msgsnd06
msync03
msync04
nanosleep01
nanosleep02
nice02
nice03
nice04
open01
open02
open08
open11
pause01
pipe01
pipe02
pipe11
pivot_root01
poll01
poll02
posix_fadvise01
posix_fadvise01_64
posix_fadvise02
posix_fadvise02_64
posix_fadvise03
posix_fadvise03_64
posix_fadvise04
posix_fadvise04_64
ppoll01
prctl01
prctl02
prctl03
preadv03
preadv03_64
preadv201_64
preadv202
preadv202_64
pselect01
pselect01_64
pselect03
pselect03_64
ptrace07
pwrite02
pwrite02_64
pwrite03
pwrite03_64
pwritev03
pwritev03_64
pwritev201
pwritev201_64
pwritev202
pwritev202_64
quotactl01
read01
read02
readahead01
readahead02
readlink01
readlink03
realpath01
recvmsg02
remap_file_pages02
request_key01
request_key02
request_key03
request_key04
request_key05
rmdir01
rmdir02
rmdir03
rt_sigsuspend01
rt_tgsigqueueinfo01
sbrk03
sched_getaffinity01
sched_setscheduler03
select04
semctl01
sendto02
setpriority01
setpriority02
setregid01
setregid01_16
setregid02
setregid02_16
setregid03
setregid03_16
setregid04
setregid04_16
setrlimit02
setrlimit03
setrlimit04
setrlimit06
setsockopt02
setsockopt03
setuid01_16
setuid03
setuid03_16
setuid04
setuid04_16
setxattr01
setxattr02
shmat01
shmat02
shmat03
sigpending02
socket02
socketpair01
socketpair02
splice01
splice03
splice04
splice05
stat01
stat01_64
stat03
stat03_64
stime01
stime02
sync03
sync_file_range02
syncfs01
syscall01
sysctl01
sysctl03
sysctl04
tee01
tee02
tgkill01
tgkill02
tgkill03
umount01
umount02
umount03
uname04
unlink05
ustat01
ustat02
utimes01
vhangup01
vhangup02
vmsplice01
vmsplice02
wait401
waitpid01
waitpid06
waitpid07
waitpid08
waitpid09
waitpid10
waitpid11
waitpid12
waitpid13
write01
write02
write03
write04
write05
writev01
writev07
</pre></code></details>

<details><summary>Tests which have own main function (from grep), so are unaffected (by this issue)</summary>
<code><pre>
adjtimex01
adjtimex02
asyncio02
bdflush01
bind01
bind02
cacheflush01
capget01
capget02
capset01
capset02
chdir01
chdir02
chdir04
chmod01
chmod02
chmod03
chmod04
chown01
chown02
chown03
chown04
chown05
chroot01
chroot02
chroot03
chroot04
clone01
clone02
clone03
clone04
clone05
clone06
clone07
close01
close02
close08
confstr01
connect01
creat07_child
creat08
dup01
dup02
dup03
dup04
dup05
dup06
dup07
dup201
dup202
dup203
dup204
dup205
dup3_01
dup3_02
epoll-ltp
epoll_pwait01
epoll-test
epoll_wait03
eventfd01
eventfd2_01
eventfd2_02
eventfd2_03
execl01_child
execle01_child
execlp01_child
execv01_child
execve01_child
execveat_child
execveat_errno
execve_child
execvp01_child
exit01
exit_group01
faccessat01
fallocate01
fallocate02
fallocate03
fanotify_child
fchdir01
fchdir02
fchmod03
fchmod04
fchmodat01
fchown01
fchown02
fchown03
fchown04
fchown05
fchownat01
fchownat02
fcntl01
fcntl05
fcntl06
fcntl07
fcntl08
fcntl09
fcntl10
fcntl11
fcntl12
fcntl13
fcntl14
fcntl15
fcntl16
fcntl17
fcntl18
fcntl19
fcntl20
fcntl21
fcntl22
fcntl23
fcntl24
fcntl25
fcntl26
fcntl27
fcntl28
fcntl29
fcntl30
fcntl31
fcntl32
fdatasync01
fdatasync02
fmtmsg01
fork01
fork02
fork03
fork04
fork05
fork06
fork07
fork08
fork09
fork10
fork11
fork12
fork13
fork14
fpathconf01
fstat01
fstat02
fstat03
fstat05
fstatat01
fstatfs01
fstatfs02
fsync02
fsync03
ftruncate01
ftruncate02
ftruncate03
ftruncate04
futex_wait01
futex_wait02
futex_wait03
futex_wait04
futex_wake01
futex_wake02
futex_wake03
futex_wake04
futimesat01
getcontext01
getdents01
getdents02
getdomainname01
getdtablesize01
getegid01
getegid02
geteuid01
geteuid02
getgid01
getgid03
getgroups01
getgroups03
gethostbyname_r01
gethostid01
gethostname01
getitimer01
getitimer02
getitimer03
get_mempolicy01
getpagesize01
getpeername01
getpgid01
getpgid02
getpgrp01
getpid01
getpid02
getppid01
getppid02
getresgid01
getresgid02
getresgid03
getresuid01
getresuid02
getresuid03
getrlimit01
getrlimit02
get_robust_list01
getrusage01
getrusage02
getrusage03
getrusage03_child
getrusage04
getsid01
getsid02
getsockname01
getsockopt01
gettid01
gettimeofday01
getuid01
getuid03
getxattr01
getxattr02
getxattr03
inotify_init1_01
inotify_init1_02
io_cancel01
ioctl01
ioctl02
io_getevents01
ioperm01
ioperm02
iopl01
iopl02
kill01
kill02
kill03
kill04
kill05
kill06
kill07
kill08
kill09
kill10
kill11
kill12
lchown01
lchown02
lchown03
link02
link03
link04
link05
link06
link07
linkat01
linkat02
listen01
llseek01
llseek02
llseek03
lstat01
lstat02
lstat03
mallopt01
mem03
memcmp01
memcpy01
memset01
migrate_pages01
mincore01
mincore02
mkdir09
mkdirat01
mknod01
mknod02
mknod03
mknod04
mknod05
mknod06
mknod07
mknod08
mknod09
mknodat01
mknodat02
mlock01
mlock02
mlock03
mlock04
mlockall01
mlockall02
mlockall03
mmap001
mmap01
mmap02
mmap03
mmap04
mmap05
mmap06
mmap07
mmap08
mmap09
mmap10
mmap11
mmap13
mmap14
mmap15
mmap16
modify_ldt01
modify_ldt02
modify_ldt03
mount01
mount02
mount03
mount03_setuid_test
mount04
mount05
mount06
move_pages01
move_pages02
move_pages03
move_pages04
move_pages05
move_pages06
move_pages07
move_pages08
move_pages09
move_pages10
move_pages11
mprotect01
mprotect02
mprotect03
mprotect04
mq_notify02
mremap01
mremap02
mremap03
mremap04
mremap05
msgrcv01
msgrcv02
msgrcv03
msgrcv04
msgrcv05
msgrcv06
msgrcv07
msgrcv08
msgstress01
msgstress02
msgstress03
msgstress04
msync01
msync02
msync03
munlock01
munlock02
munlockall01
munmap01
munmap02
munmap03
nanosleep03
nanosleep04
newuname01
nftw
nftw64
open03
open04
open05
open06
open07
open09
open10
open12
open12_child
open13
open14
openat01
openat02
openat02_child
openat03
pathconf01
pause02
pause03
perf_event_open01
perf_event_open02
personality01
personality02
pipe04
pipe05
pipe06
pipe07
pipe08
pipe09
pipe10
pipe2_01
pipe2_02
pread01
pread02
pread03
process_vm01
process_vm_readv02
process_vm_readv03
process_vm_writev02
profil01
pselect02
ptrace01
ptrace02
ptrace03
ptrace04
ptrace05
ptrace06
pwrite01
pwrite04
read03
read04
readdir01
readdir21
readlinkat01
readlinkat02
readv01
readv02
readv03
reboot01
reboot02
recv01
recvfrom01
recvmsg01
remap_file_pages01
removexattr01
removexattr02
rename01
rename02
rename03
rename04
rename05
rename06
rename07
rename08
rename09
rename10
rename11
rename12
rename13
rename14
renameat01
renameat201
renameat202
rt_sigaction01
rt_sigaction02
rt_sigaction03
rt_sigprocmask01
rt_sigprocmask02
rt_sigqueueinfo01
sbrk01
sbrk02
sched_getattr01
sched_getattr02
sched_getparam01
sched_getparam02
sched_getparam03
sched_get_priority_max01
sched_get_priority_max02
sched_get_priority_min01
sched_get_priority_min02
sched_getscheduler01
sched_getscheduler02
sched_rr_get_interval01
sched_rr_get_interval02
sched_rr_get_interval03
sched_setaffinity01
sched_setattr01
sched_setparam01
sched_setparam02
sched_setparam03
sched_setparam04
sched_setparam05
sched_setscheduler01
sched_setscheduler02
sched_yield01
select01
select02
select03
semctl01
semctl02
semctl03
semctl04
semctl05
semctl06
semctl07
semget01
semget02
semget03
semget05
semget06
semop01
semop02
semop03
semop04
semop05
send01
sendfile02
sendfile03
sendfile04
sendfile05
sendfile06
sendfile07
sendfile08
sendfile09
sendmsg01
sendmsg02
sendto01
setdomainname01
setdomainname02
setdomainname03
setegid01
setegid02
setfsgid01
setfsgid02
setfsgid03
setfsuid01
setfsuid02
setfsuid03
setfsuid04
setgid01
setgid02
setgid03
setgroups01
setgroups02
setgroups03
setgroups04
sethostname01
sethostname02
sethostname03
setitimer01
setitimer02
setitimer03
setns01
setns02
setpgid01
setpgid02
setpgid03
setpgid03_child
setpgrp01
setpgrp02
setresgid01
setresgid02
setresgid03
setresgid04
setresuid01
setresuid02
setresuid03
setresuid04
setresuid05
setreuid01
setreuid02
setreuid03
setreuid04
setreuid05
setreuid06
setreuid07
setrlimit01
set_robust_list01
setsid01
setsockopt01
set_thread_area01
set_tid_address01
settimeofday01
settimeofday02
setxattr03
sgetmask01
shmctl01
shmctl02
shmctl03
shmctl04
shmdt01
shmdt02
shmget01
shmget02
shmget03
shmget04
shmget05
sigaction01
sigaction02
sigaltstack01
sigaltstack02
sighold02
signal01
signal02
signal03
signal04
signal05
signal06
signalfd01
signalfd4_01
signalfd4_02
sigprocmask01
sigrelse01
sigsuspend01
sigwaitinfo01
simple_tracer
socketcall02
socketcall03
socketcall04
sockioctl01
ssetmask01
statfs01
statfs02
statfs03
statvfs01
statvfs02
string01
swapoff01
swapoff02
swapon01
swapon02
swapon03
symlink01
symlink02
symlink03
symlink04
symlink05
symlinkat01
sync01
sync02
sync_file_range01
sysconf01
sysfs01
sysfs02
sysfs03
sysfs04
sysfs05
sysfs06
sysinfo01
sysinfo02
syslog11
syslog12
syslogtst
time01
time02
timerfd01
timerfd02
timerfd03
timerfd_create01
timerfd_gettime01
timerfd_settime01
timer_getoverrun01
timer_gettime01
times01
tkill01
tkill02
truncate01
truncate02
truncate03
ulimit01
umount2_01
umount2_02
umount2_03
uname01
uname02
uname03
unlinkat01
unshare01
unshare02
utime01
utime02
utime03
utime04
utime05
utime06
utimensat01
vfork01
vfork02
wait01
wait02
wait402
waitid01
waitid02
waitpid02
waitpid03
waitpid04
waitpid05
writev02
writev05
writev06
</pre></code></details>

**Comment by kailun-qin** [comment]
We may want to revisit this once we have support for shared untrusted memory: https://github.com/gramineproject/gramine/pull/827.

**Comment by kailun-qin** [comment]
> I don't think #827 will solve this issue, isn't it only about `/dev/shm/`, not `mmap(..., MAP_SHARED, ...)`?

Isn't it about both `/dev/shm/` and `mmap(..., MAP_SHARED, ...)`? Pls kindly see the description:
https://github.com/gramineproject/gramine/blob/fcec280a7c84e9d4baa056c7b5d9643d891bece6/Documentation/manifest-syntax.rst?plain=1#L433-L434
and the associated test:
https://github.com/gramineproject/gramine/blob/fcec280a7c84e9d4baa056c7b5d9643d891bece6/libos/test/regression/shm.c#L20-L31

**Comment by dimakuv** [comment]
Yep, I think #827 could solve this issue (in an insecure way, but these functionality tests anyway).
