### ISSUE TITLE
DCAP quote generation fails with SGX_QL_ENCLAVE_LOST error

### ISSUE THREAD

**Issue by marcelamelara** [gramineproject/gramine#516]
## Description of the problem

On a machine with SGX HW and FLC support, I have a simple C program (following the LibOS/shim/regression test for attestation) that writes some report data to `/dev/attestation/user_report_data`, reads the quote from `/dev/attestation/quote` and writes the quote to another file. 

I am able to successfully write to the report data inside of Gramine-SGX, but reading the quote results in aesmd returning error code 46 (which corresponds to the `SGX_QL_ENCLAVE_LOST` error). According to the [DCAP API Guide](https://download.01.org/intel-sgx/latest/dcap-latest/linux/docs/Intel_SGX_ECDSA_QuoteLibReference_DCAP_API.pdf), this error means that the QL enclave is lost through a power transition or because it is used in a child process spawned by fork(). 

I have checked that DCAP quote generation works properly via the SGXDataCenterAttestationPrimitives sample code.

Any insights would be greatly appreciated! Thank you.

## Steps to reproduce
Ubuntu 20.04 kernel 5.13
Gramine built from source using `-Dsgx=enabled -Ddcap=enabled -Ddcap_driver=upstream` flags
FLC-capable machine with SGX2, SGX PSW 2.15.1 (see output of `is-sgx-available` below)

```
gcc -o gramineattest gramine-attestation.c -I/home/user/gramine/Pal/src/host/Linux-SGX
gramine-manifest \
	-Dlog_level=error \
	-Darch_libdir=/lib/x86_64-linux-gnu \
	-Dscript_dir=/home/user/examples/helloworld \
	-Dkeys_dir=./test-keys \
	-Dtest_key=public.pem.sha \
	-Ddata_dir=./data \
	-Dquote_file=test.quote \
	gramineattest.manifest.template >gramineattest.manifest
gramine-sgx-sign \
	--key ~/.config/gramine/enclave-key.pem \
	--manifest gramineattest.manifest \
	--output gramineattest.manifest.sgx
gramine-sgx-get-token --output gramineattest.token --sig gramineattest.sig
gramine-sgx ./gramineattest -k test-keys/public.pem.sha -o data/test.quote
```

## Expected results

DCAP quote written to specified file. Debugging print statements should be printed (though this seems like an unrelated issue).

## Actual results

```
Testing gramineattest...
gramine-sgx ./gramineattest -k test-keys/public.pem.sha -o data/test.quote
Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

[P1:T1:] error: Detected deprecated syntax: 'fs.mounts[5].path' ("./test-keys") is not absolute. Consider converting it to absolute by adding "/" at the beginning.
[P1:T1:] error: Detected deprecated syntax: 'fs.mounts[6].path' ("./data") is not absolute. Consider converting it to absolute by adding "/" at the beginning.
error: aesm_service returned error: 46
error: Failed to get quote
```

Output of `is-sgx-availble`:
```
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): true
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): true
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): true
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): true
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x800000000000
EPC size: 0x5cc0000
SGX driver loaded: true
AESMD installed: true
SGX PSW/libsgx installed: true
```

## Gramine commit hash

3ec7e577b1b

**Comment by dimakuv** [comment]
> but reading the quote results in aesmd returning error code 46

This feels like a red herring. I think it's not the AESMD error. What happens, I believe, is that the Intel DCAP library tries to run the Quoting Enclave inside the Gramine process (along your main enclave), which is impossible in Gramine.

Please try to specify the environment variable `SGX_AESM_ADDR=1` (the easiest is to add this to the manifest template using `loader.env.SGX_AESM_ADDR="1"`).

See for more details https://github.com/gramineproject/graphene/issues/2033#issuecomment-795017968

**Comment by dimakuv** [comment]
@marcelamelara I also created this PR with Python script to generate the SGX quote: https://github.com/gramineproject/gramine/pull/521

Please check it. Maybe you're missing things like `sgx.remote_attestation = true` in your manifest file?

**Comment by marcelamelara** [comment]
@dimakuv Thanks for the suggestions. I had actually tried running with `SGX_AESM_ADDR=1` already (having seen that as a solution in another issue), but I was indeed also missing the needed fields in the manifest file as well.

That being said, with `SGX_AESM_ADDR=1` and the manifest file updated, I am now seeing a similar error to the one mentioned in the https://github.com/gramineproject/graphene/issues/2033 issue you linked. Since I am also unable to run the QuoteGenerationSample from the DCAP source in out-of-proc mode with an error of SGX_QL_SERVICE_UNAVAILABLE, just as the person described in that issue, it seems like the two problems I'm seeing may be related.

I will work on trying to address this issue with the QuoteGenerationSample, see how that impacts my ability to generate the quote in Gramine, and report back here.

**Comment by marcelamelara** [comment]
Ok. Resolved the issue! It turns out that having the EPID libraries and DCAP libraries installed side-by-side can cause these issues. 

My solution was to `apt purge` the following libraries from my system:
`libsgx-epid* libsgx-uae-service* libsgx-ae-epid libsgx-aesm-epid-plugin`

@dimakuv Thank you again for your help!
