### ISSUE TITLE
Issue with writing wrap key into /dev/attestation/protected_files_key pseudo-file 

### ISSUE THREAD

**Issue by Lio101** [gramineproject/gramine#520]
## Description of the problem
I am trying to read a Encrypted text file(encrypted using pf_crypt) in python inside SGX Enclave. For that I am trying to first write the key(wrap-key) inside the` /dev/attestation/protected_files_key` psudo-file, but after copying the content when I try to read the file size its shows zero bytes. I have also looked into `secret_prov_attest.c` for reference.

Is there any step I am missing or doing wrong? or do I need to make some change in the manifest file?
## Steps to reproduce

```
import os

with open('wrap-key','rb') as firstfile, open('/dev/attestation/protected_files_key','wb') as secondfile:
       for line in firstfile:
                secondfile.write(line)

print(os.path.getsize("/dev/attestation/protected_files_key"))
```

I have also added the` wrap-key` inside `sgx.allowed_files` in `python.manifest.template`.
## Expected results
16 (bytes)(wrap-key size)
## Actual results
0 (bytes)

**Comment by mkow** [comment]
This is perfectly normal, it's a special file, like most others in `/dev` on Linux. If you check e.g. `/dev/urandom` it will also say that it has size = 0.

**Comment by Lio101** [comment]
@mkow , thanks for response. So is there any other step I need to perform to decrypt the encrypted file? because after this step when I try to read the encrypted file in python I get `error: pf_open failed: wrap key was not provided` and `PermissionError: Permission denied: 'enctext.txt'`.

**Comment by dimakuv** [comment]
@Lio101 The wrap key must be exactly 16 bytes in size (= 32 symbols in hex representation). Maybe your input key (`wrap-key`) has a wrong size?

**Comment by Lio101** [comment]
@dimakuv I am using the sample wrap-key given [here](https://github.com/gramineproject/gramine/tree/master/CI-Examples/ra-tls-secret-prov/files). Also I checked the file size, its showing 16 bytes.

**Comment by dimakuv** [comment]
Hm, very strange. Can you re-build your example with `loader.log_level = "all"` in the manifest file and copy-paste the Gramine log here?

**Comment by Lio101** [comment]
@dimakuv [gramine_log.txt](https://github.com/gramineproject/gramine/files/8479181/gramine_log.txt)

**Comment by dimakuv** [comment]
I see these log messages:
```
[P1:T1:python3.8] trace: ---- shim_openat(AT_FDCWD, "wrap-key", O_RDONLY|0x80000, 0000) = 0x3
[P1:T1:python3.8] trace: ---- shim_openat(AT_FDCWD, "/dev/attestation/protected_files_key", O_WRONLY|O_CREAT|O_TRUNC|0x80000, 0666) = 0x4
[P1:T1:python3.8] trace: ---- shim_read(3, 0x1aa9c020, 0x2000) ...
[P1:T1:python3.8] trace: ---- return from shim_read(...) = 0x10
[P1:T1:python3.8] trace: ---- shim_write(4, 0x1aa9e030, 0x10) ...
[P1:T1:python3.8] trace: ---- return from shim_write(...) = 0x10
[P1:T1:python3.8] debug: /dev/attestation/protected_files_key: invalid length
[P1:T1:python3.8] debug: pseudo_str_flush() failed, proceeding with close
```

So this looks reasonable: there are 16 bytes (`0x10` bytes) read from the `wrap-key` file and written into the `/dev/attestation/protected_files_key` file.

However, Gramine complains about the "invalid length" of this write, which is weird. Let me check the Gramine source code.

**Comment by dimakuv** [comment]
Ok, I see the problem:
https://github.com/gramineproject/gramine/blob/ecb0c68df22d2cbe3d7404113436948cd56f6189/LibOS/shim/src/fs/dev/attestation.c#L267-L270

where `sizeof(g_pf_key_hex)` is equal to 32. So the only format that our `/dev/attestation/protected_files_key` recognizes is the 32-char hex ASCII representation of the 16-byte binary key.

So your script should be adjusted like this:
```python
with open('wrap-key','rb') as firstfile, open('/dev/attestation/protected_files_key','w') as secondfile:
       for line in firstfile:
                secondfile.write(line.hex())
```

Note two changes in the script:
1. The `/dev/attestation/protected_files_key` file is opened as a normal text file, not as a binary file.
2. The `.hex()` transformation on the `line` variable (i.e., transformation from `bytes` object to `string` hex-ASCII object)

**Comment by dimakuv** [comment]
@pwmarcz Should we allow another representation in our Gramine code? I mean here: https://github.com/gramineproject/gramine/blob/ecb0c68df22d2cbe3d7404113436948cd56f6189/LibOS/shim/src/fs/dev/attestation.c#L264

Maybe we should allow a 32-byte hex representation (as now), **and also** the 16-byte raw representation (in this case, Gramine first does `bytes2hex()` and only then calls `DkSetProtectedFilesKey()`).

**Comment by Lio101** [comment]
> Ok, I see the problem:
> 
> https://github.com/gramineproject/gramine/blob/ecb0c68df22d2cbe3d7404113436948cd56f6189/LibOS/shim/src/fs/dev/attestation.c#L267-L270
> 
> where `sizeof(g_pf_key_hex)` is equal to 32. So the only format that our `/dev/attestation/protected_files_key` recognizes is the 32-char hex ASCII representation of the 16-byte binary key.
> 
> So your script should be adjusted like this:
> 
> ```python
> with open('wrap-key','rb') as firstfile, open('/dev/attestation/protected_files_key','w') as secondfile:
>        for line in firstfile:
>                 secondfile.write(line.hex())
> ```
> 
> Note two changes in the script:
> 
> 1. The `/dev/attestation/protected_files_key` file is opened as a normal text file, not as a binary file.
> 2. The `.hex()` transformation on the `line` variable (i.e., transformation from `bytes` object to `string` hex-ASCII object)

This resolved the issue.

@dimakuv Thanks for your help!

**Comment by pwmarcz** [comment]
The problem with error being hidden was fixed recently, see #502. In the next version of Gramine, the write operation should fail if the format isn't right.

Also, I think [our documentation](https://gramine.readthedocs.io/en/latest/attestation.html) doesn't actually specify the format for `protected_files_key`. I made a note to fix that when working on the new version of encrypted files.

@dimakuv 

> Maybe we should allow a 32-byte hex representation (as now), **and also** the 16-byte raw representation (in this case, Gramine first does `bytes2hex()` and only then calls `DkSetProtectedFilesKey()`).

I would be strongly against allowing both formats in the same file, that sounds like a bad practice and potential for misuse. Maybe as a separate files, "raw" and "hex". But I don't think that's a very useful feature: the problem here was confusion about the format, not difficulty converting to the right format.

**Comment by dimakuv** [comment]
> But I don't think that's a very useful feature: the problem here was confusion about the format, not difficulty converting to the right format.

Ok, agreed. I'm closing this issue then.

You are right, our documentation doesn't mention the 32-byte hex string format. Thanks for fixing it (if I understood you right, otherwise I can submit a quick PR adding this info).

**Comment by mkow** [comment]
Btw. I think it would be more standard if the format used there was actually binary, not hex. Stuff in `/dev` usually works on binary data, and there's no point in passing this as hex other than to make debugging easier. I think all production deployments will actually need to convert the key to hex, and Gramine will unhex it right afterwards.

**Comment by pwmarcz** [comment]
@dimakuv Do you agree? Because we can change it for the new "encrypted files", but we'll need to do it now, before they're launched.

From my side - this will be inconsistent with the hex in manifest, but the hex in manifest is an insecure option anyway.

**Comment by dimakuv** [comment]
@mkow @pwmarcz Yes, please. Indeed, the file format for `/dev/attestation/keys/*` should be binary (not hex), just like all other files under `/dev/attestation/`. So Pawel please proceed with making the key files binary.
