### ISSUE TITLE
Trusted obtain environment information

### ISSUE THREAD

**Issue by AgentRX** [gramineproject/gramine#529]
Hi,
We need to obtain enclave environment information. Now we can get trusted CPU benchmark and memory speed informations that we can obtain without OCALLs.

But also we need more trusted informations, like network bandwidth, memory size, SSD/HDD sizes, etc.
I want to note that it's enough to get run environment information not of the whole system.

For example, can we get running RAM size from the manifest? What else trust information can we obtain from the environment?

**Comment by mkow** [comment]
You can't trust these by design and no TEE can provide you with such information. E.g. network bandwidth is external to the machine a TEE runs on and also changes in time. What would be a "trusted value" for it? With memory size and SSD/HDD it's similar, most TEE technologies run only on the CPU and the hard drive and RAM are untrusted. Also, what if someone plugs in an additional HDD later?

IMO relying on such values doesn't really make sense, the host owner will always be able to manipulate them.

**Comment by dimakuv** [comment]
As Michal mentioned above, information about the *network* and the *storage* will always be untrusted (Intel SGX only trusts the CPU and the "reserved-for-SGX-enclaves" part of RAM). So there is nothing "trusted" that Gramine could report about network and storage.

> I want to note that it's enough to get run environment information not of the whole system.
> For example, can we get running RAM size from the manifest? What else trust information can we obtain from the environment?

If by RAM you mean "how much trusted memory I have for my SGX enclave", then you basically want to know the value of `sgx.enclave_size` of the manifest file. In Gramine, you simply read the `/proc/meminfo` that contains the line `"MemTotal: XXX`, where `XXX` is the amount of SGX-enclave memory. Also, there are lines `"MemFree: XXX` and `"MemAvailable: XXX` -- both lines show the amount of SGX enclave memory left for use.

**Comment by AgentRX** [comment]
@mkow 
>You can't trust these by design and no TEE can provide you with such information. E.g. network bandwidth is external to the machine a TEE runs on and also changes in time. What would be a "trusted value" for it? With memory size and SSD/HDD it's similar, most TEE technologies run only on the CPU and the hard drive and RAM are untrusted. Also, what if someone plugs in an additional HDD later?

The main idea is to check if run environment is enough for the selected requirements. For example, we have an order to run mysql server with 16Gb RAM and 100 Mbit Network channel. Some TEE provider is processing the order. So, first of all, after run enclave we want to be sure (inside enclave) that TEE provider has provided enough configuration for the mysql server.

Of course the task is not trivial but I just want to understand how many trusted information could be obtained inside enclave.

**Comment by mkow** [comment]
And how will you know if the provider didn't accept 10 such tasks on this single machine and effectively have 1GB RAM and 10Mbit/s net for each? The provider will always be able to cheat with this. What you should measure is the real work executed and pay them for only it (not for any _declared_ capacity).

**Comment by boryspoplawski** [comment]
> the task is not trivial 

It's plain impossible. The host OS can just fake such information.
Even if there was some hypothetical TEE that could *somehow* measure network throughput, you could just lower it on the next network hope, after measurements. Infinite ways to cheat.

**Comment by lejunzhu** [comment]
> Can provider cheat with memory size for enclave?

That depends on the definition of "cheat". If you set sgx.enclave_size = 4G, you can use up to near 4G of code + data. This can be verified by allocating and filling a large memory buffer. There is no way to fake that result.

However, because of the over-subscription feature of Linux SGX driver, part of the memory may not be EPC. It can be regular memory or disk swap space. For example, you can start such a 4GB application on a PC with only 128M EPC, 4GB physical memory and a 4GB swap file.

**Comment by mkow** [comment]
> For example, comparing with standard cloud providers how do you understand that you got really characteristics you paid for?

In standard cloud provider setting you just trust the provider, i.e. click "rent" on an offer which _declares_ to provide the resources you want.

> This params we can check before every run for example.

First, this is not technically possible, second, even if it was, it still doesn't guarantee anything. The host may overbook the machine and you'll get your 128-core CPU, but will be scheduled on it for only 1% of the time.

Sorry to be blunt, but this whole request is just conceptually broken. If you want a billing system without trusting the provider then you have to bill for the completed work.
