### ISSUE TITLE
When I run meason setup build...there are some error.Could you help me?

### ISSUE THREAD

**Issue by Frinklin-Wang** [gramineproject/gramine#531]
In the Gramine process of building

Cd .../gramine-master
Run:$ meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled  -Dsgx_driver_include_path="/usr/src/linux-hwe-5.11-headers-5.11.0-27/arch/x86/include/uapi/"

Error:
WARNING: failed to download with error: could not get https://packages.gramineproject.io/distfiles/tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5.tar.gz is the internet available?. Trying after a delay...
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)>

meson.build:227:0: ERROR: could not get https://packages.gramineproject.io/distfiles/tomlc99-208203af46bdbdb29ba199660ed78d09c220b6c5.tar.gz is the internet available?

A full log can be found at /home/wmc/Downloads/gramine-master/build/meson-logs/meson-log.txt

But I copy the link given and I can download this zip file.
How should I solve this problem?
Could you help me?
Thanks a lot in advance!

**Comment by boryspoplawski** [comment]
Could you try using `wget` to download it? Maybe your browser has different CA list than your host OS.

**Comment by Frinklin-Wang** [comment]
> Could you try using `wget` to download it? Maybe your browser has different CA list than your host OS.
When I do the quick start in gramine latest
I did the following：
sudo curl -fsSLo /usr/share/keyrings/gramine-keyring.gpg https://packages.gramineproject.io/gramine-keyring.gpg

echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ stable main' | sudo tee /etc/apt/sources.list.d/gramine.list

sudo apt-get update

But there is an error:
 
root@18:~# sudo apt-get update
Hit:1 http://cn.archive.ubuntu.com/ubuntu bionic InRelease
Hit:2 http://security.ubuntu.com/ubuntu bionic-security InRelease                                                                                                                        
Hit:3 http://cn.archive.ubuntu.com/ubuntu bionic-updates InRelease                                                                       
Hit:4 http://ppa.launchpad.net/apt-fast/stable/ubuntu bionic InRelease                                                                   
Hit:5 http://cn.archive.ubuntu.com/ubuntu bionic-backports InRelease                                               
Err:6 https://packages.gramineproject.io stable InRelease                                    
  Cannot initiate the connection to packages.gramineproject.io:443 (2a00:1ca8:2a:d::10). - connect (101: Network is unreachable) Could not connect to packages.gramineproject.io:443 (5.255.91.88). - connect (111: Connection refused)
Reading package lists... Done                                     
W: Failed to fetch https://packages.gramineproject.io/dists/stable/InRelease  Cannot initiate the connection to packages.gramineproject.io:443 (2a00:1ca8:2a:d::10). - connect (101: Network is unreachable) Could not connect to packages.gramineproject.io:443 (5.255.91.88). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.

How do I solve this problem?Could you help me?
Thank you!

**Comment by dimakuv** [comment]
@Frinklin-Wang The `wget https://packages.gramineproject.io/dists/stable/InRelease` command works for me. Maybe you forgot to set up your proxy settings?

**Comment by Frinklin-Wang** [comment]
> @Frinklin-Wang The `wget https://packages.gramineproject.io/dists/stable/InRelease` command works for me. Maybe you forgot to set up your proxy settings?

I can access this URL when I enter it in the web page, but it cannot be executed when I enter it on the command line.
This problem has been bothering me for a long time, so I can't install gramine.
How should I do?

**Comment by dimakuv** [comment]
@Frinklin-Wang Do you know about HTTP/HTTPS proxy settings? Do you know that you should set them in your terminal sessions (if your company's internet access is behind a proxy)?
