### ISSUE TITLE
I began with the QuickStart but it didn`t work.

### ISSUE THREAD

**Issue by acknowledgexiongdei** [gramineproject/gramine#532]
```
sudo curl -fsSLo /usr/share/keyrings/gramine-keyring.gpg https://packages.gramineproject.io/gramine-keyring.gpg
echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/gramine-keyring.gpg] https://packages.gramineproject.io/ stable main' | sudo tee /etc/apt/sources.list.d/gramine.list
sudo apt-get update

sudo apt-get install gramine      # for 5.11+ upstream, in-kernel driver
sudo apt-get install gramine-oot  # for out-of-tree SDK driver
sudo apt-get install gramine-dcap # for out-of-tree DCAP driver
```
I used this command to install
The command:
 `is-sgx-available` 
worked

but the commad:
`gramine-sgx-gen-private-key`
it didn`t work，command not found

for the command:
```
git clone --depth 1 https://github.com/gramineproject/gramine.git 
cd gramine/CI-Examples/helloworld
make SGX=1
gramine-sgx helloworld
```
There was an error . The log was as below:
```
make SGX=1
cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c
cc   helloworld.o   -o helloworld
gramine-manifest \
	-Dlog_level=error \
	helloworld.manifest.template helloworld.manifest
gramine-sgx-sign \
	--manifest helloworld.manifest \
	--output helloworld.manifest.sgx
Usage: gramine-sgx-sign [OPTIONS]
Try "gramine-sgx-sign --help" for help.

Error: Missing option "--key" / "-k".
make: *** [Makefile:27：helloworld.manifest.sgx] 错误 2
```

**Comment by lejunzhu** [comment]
gramine-sgx-gen-private-key is not available in 1.1 release. See #477

**Comment by dimakuv** [comment]
@acknowledgexiongdei If you want to use the stable version of Gramine (as of this writing, version 1.1), you must use the `stable` version of the documentation: https://gramine.readthedocs.io/en/stable/quickstart.html

It seems that you used the `latest` (which tracks the latest and potentially breaking changes in Gramine) version of the documentation: https://gramine.readthedocs.io/en/latest/quickstart.html

**Comment by acknowledgexiongdei** [comment]
> gramine-sgx-gen-private-key is not available in 1.1 release. See #477

Thank you.

**Comment by acknowledgexiongdei** [comment]
> @acknowledgexiongdei If you want to use the stable version of Gramine (as of this writing, version 1.1), you must use the `stable` version of the documentation: https://gramine.readthedocs.io/en/stable/quickstart.html
> 
> It seems that you used the `latest` (which tracks the latest and potentially breaking changes in Gramine) version of the documentation: https://gramine.readthedocs.io/en/latest/quickstart.html

Thanks.

**Comment by acknowledgexiongdei** [comment]
> @acknowledgexiongdei If you want to use the stable version of Gramine (as of this writing, version 1.1), you must use the `stable` version of the documentation: https://gramine.readthedocs.io/en/stable/quickstart.html
> 
> It seems that you used the `latest` (which tracks the latest and potentially breaking changes in Gramine) version of the documentation: https://gramine.readthedocs.io/en/latest/quickstart.html

I used the command in stable [doc:](https://gramine.readthedocs.io/en/latest/quickstart.html)
`openssl genrsa -3 -out "$HOME"/.config/gramine/enclave-key.pem 3072`

It was useful .but when I used the command:
`make SGX=1 SGX_SIGNER_KEY="$HOME"/.config/gramine/enclave-key.pem`
There was an error . The log was as below:
```
make SGX=1 SGX_SIGNER_KEY="$HOME"/.config/gramine/enclave-key.pem

cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c
cc   helloworld.o   -o helloworld
gramine-manifest \
	-Dlog_level=error \
	helloworld.manifest.template helloworld.manifest
gramine-sgx-sign \
	--manifest helloworld.manifest \
	--output helloworld.manifest.sgx
Usage: gramine-sgx-sign [OPTIONS]
Try "gramine-sgx-sign --help" for help.

Error: Missing option "--key" / "-k".
make: *** [Makefile:27：helloworld.manifest.sgx] 错误 2
```

**Comment by woju** [comment]
> Usage: gramine-sgx-sign [OPTIONS]
> Try "gramine-sgx-sign --help" for help.
> 
> Error: Missing option "--key" / "-k".

This option was added after v1.1, so it's not a surprise that it doesn't work.
Please checkout v1.1 tag and then try again.
