### ISSUE TITLE
A little qusetion

### ISSUE THREAD

**Issue by acknowledgexiongdei** [gramineproject/gramine#535]
In this doc [https://gramine.readthedocs.io/en/stable/index.html](https://gramine.readthedocs.io/en/stable/index.html)

I don`t know the difference between the Quick start and the build.
The build seems to install the Prerequisites and gramine ,the quick is also for installing gramine.There is a big difference between the Quick start and the build.

Could you give me some idea?

**Comment by dimakuv** [comment]
QuickStart installs Gramine from prepared Ubuntu/RHEL packages. (Note that there is a step to that clones the GitHub repo, but this step is purely for testing.) QuickStart tracks the latest *stable* version of Gramine.

Build installs Gramine from GitHub sources. Build tracks the latest *tip* (*unstable*) version of Gramine.

QuickStart is what normal users should use. Build is what advanced users should use.

**Comment by woju** [comment]
For questions, next time please use the mailing list: ***@***.***,
as outlined in the bug template, which you've deleted. It's there for a reason.
