### ISSUE TITLE
ImportError: cannot import name 'get_tbssigstruct' from 'graminelibos' (/usr/local/lib/python3.8/dist-packages/graminelibos/__init__.py)

### ISSUE THREAD

**Issue by Frinklin-Wang** [gramineproject/gramine#544]
When I build gramine like:
cd ~/gramine/CI-Examples/bash
make SGX=1

It will get this error:
root@xxx:~/gramine/CI-Examples/bash# make SGX=1
gramine-sgx-sign \
	--key ../../Pal/src/host/Linux-SGX/signer/enclave-key.pem \
	--manifest bash.manifest \
	--output bash.manifest.sgx
Traceback (most recent call last):
  File "/usr/local/bin/gramine-sgx-sign", line 10, in <module>
    from graminelibos import Manifest, get_tbssigstruct, sign_with_local_key
ImportError: cannot import name 'get_tbssigstruct' from 'graminelibos' (/usr/local/lib/python3.8/dist-packages/graminelibos/__init__.py)
make: *** [Makefile:26: bash.manifest.sgx] Error 1

How should I solve this problem?
Could you help me?
Thanks a lot in advance!

**Comment by boryspoplawski** [comment]
1. Please use the template we have when submitting an issue - it's there for a reason.
2. Please use  markdown to format your message - it's now wall of text with command output mixed with your comments

**Comment by Frinklin-Wang** [comment]
> 

I am so sorry.
Thank you for your reminder!

**Comment by dimakuv** [comment]
1. What is your OS distribution -- Ubuntu? Which version?
2. How did you build/install Gramine?

Also, you can edit your GitHub issue to fix the problems mentioned by @boryspoplawski. Alternatively, you can close this issue and create a new one, following our template and rules.
