### ISSUE TITLE
nested mounts

### ISSUE THREAD

**Issue by aep** [gramineproject/gramine#548]
nesting a protected file inside a tmpfs doesnt work.
writes to the nested protected file do not make it to the host.

```toml
fs.mounts = [
  { path = "/lib",              uri = "file:{{ gramine.runtimedir() }}" },
  { path = "{{ arch_libdir }}", uri = "file:{{ arch_libdir }}" },
  { path = "/usr/lib",          uri = "file:/usr/lib" },
  { path = "/app",              uri = "file:/app" },
  { path = "/app/wordpress",    uri = "file:/app/wordpress",  type="tmpfs"},
]

sgx.protected_files = [
  "file:/app/wordpress/wp-config.php",
]
```

background:

the tmpfs is needed here to preload php code into the enclave memory, since we are required to use gramines fs implementation. but the code expects the directory to be persisted, so i tried making individual file exceptions

**Comment by dimakuv** [comment]
Yes, I think the complex combinations of `fs.mounts` and `sgx.protected_files` (like yours) do not work currently in Gramine.

However, we are close to finishing the rework of the whole FS subsystem: https://github.com/gramineproject/gramine/issues/371

After this rework, `sgx.protected_files` and `sgx.trusted_files` and `sgx.allowed_files` will become deprecated, and all FS hierarchy will be set up only through `fs.mounts` array. This will make nesting possible (the mounts will overlay each over), and your app will work as expected.

In fact, you can already try the latest Gramine with the `encrypted` FS mount. See also my reply here: https://github.com/gramineproject/gramine/issues/371#issuecomment-1109404140

**Comment by aep** [comment]
wait are you saying this should already work?

```toml
fs.mounts = [
 { path = "/app/wordpress",    uri = "file:/app/wordpress",  type="tmpfs"},
 { path = "/app/wordpress/wp-config.php", uri = "file:/app/persisted/wp-config.php", type = "encrypted", key_name = "default" },
]
```



it doesnt for me


```
warning: Disallowing access to file '/app/persisted/wp-config.php'; file is not protected, trusted or allowed.
```

**Comment by dimakuv** [comment]
Do you have the `"default"` key specified in your manifest? Like here: https://github.com/gramineproject/gramine/blob/9774ce1ca8551b868c1ca6c423dfcf1b010115d4/LibOS/shim/test/regression/manifest.template#L48

Also, what is the Gramine version/commit you're running? (You can find it when you enable `loader.log_level = "debug"`, it will be one of the first lines printed.)

This feature was merged in Gramine very recently, on 20. April.

**Comment by aep** [comment]
yes key is specified, debug doesnt show more info

however, adding it to allowed confusingly makes it work
```toml
sgx.allowed_files = [
    "file:/app/persisted/wp-config.php"
] 

```

is this intentional? i was assuming allowed means unencrypted write, but it actually looks encrypted on the host

gramine is git from last week, let me make sure to pull todays head instead.

**Comment by dimakuv** [comment]
> gramine is git from last week, let me make sure to pull todays head instead.

Please do. There was a small bug exactly as you describe (adding the file to `sgx.allowed_files` allows to use the file in an encrypted way). We fixed it on 20. April, see this PR: https://github.com/gramineproject/gramine/pull/534

**Comment by aep** [comment]
going to close because the new feature does what we need. thanks!
