### ISSUE TITLE
How to run other python demo

### ISSUE THREAD

**Issue by Frinklin-Wang** [gramineproject/gramine#553]
## Description of the problem
I want to run python code .I use the hellowworld template.I add some codes in helloworld.py,like:

#! /usr/bin/env python3
import unittest
from pypbc import *
.........

There are some errors when I do follows:
root@18:~/graphene/Examples/python# make
graphene-manifest \
	-Dlog_level=error \
	-Darch_libdir=/lib/x86_64-linux-gnu \
	-Dentrypoint=/usr/bin/python3.6 \
	python.manifest.template >python.manifest

root@18:~/graphene/Examples/python# graphene-direct ./python scripts/helloworld.py
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
Hello World
Traceback (most recent call last):
  File "scripts/helloworld.py", line 17, in <module>
    from pypbc import *
ImportError: libpbc.so.1: cannot open shared object file: No such file or directory

What should I add in python.manifest?
Could you help me?
Thank you very much!

## Expected results
hellow,world
private_key =  0x563B8E30037DDFF6116704CEF9D0710BA0239B86
public_key =  0320C88198B180309974DEB8CBD6DA057E01957B7D3DE55FE11FEB686D483496CBA809A3FA5270093722DEA19EAEA000130CEECF270CC2CE72B6A9BDD933491911
(0x738113037468D2E3C5F8DB7823DD1B9F51D96AD08A826392C9B9DEFD02D9196F835AE9600D72A7BA978623DB5F76EF4A96C354442999077EF69D2989C686AF29, 0x8B7C886EC7094B9AD5BC0B0E3C7829576975A3A8DFB38E2F24632D16813944E3B4A9170E1E8FC9A13F151A4A1002EF5A0BD0B5901B1E1BBFB1CF55ED47846DA2)
(0x738113037468D2E3C5F8DB7823DD1B9F51D96AD08A826392C9B9DEFD02D9196F835AE9600D72A7BA978623DB5F76EF4A96C354442999077EF69D2989C686AF29, 0x8B7C886EC7094B9AD5BC0B0E3C7829576975A3A8DFB38E2F24632D16813944E3B4A9170E1E8FC9A13F151A4A1002EF5A0BD0B5901B1E1BBFB1CF55ED47846DA2)
true

## Actual results

root@18:~/graphene/Examples/python# graphene-direct ./python scripts/helloworld.py
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
Hello World
Traceback (most recent call last):
  File "scripts/helloworld.py", line 17, in <module>
    from pypbc import *
ImportError: libpbc.so.1: cannot open shared object file: No such file or directory

**Comment by Frinklin-Wang** [comment]
> Please use proper Markdown formatting in your messages. This is impossible to read.

I want to from pypbc import * in my python template.
What code should I add in mainfest file?

**Comment by dimakuv** [comment]
Please use proper Markdown in your GitHub issues.

https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by mkow** [comment]
Please don't use GitHub issues for general support (see the information in the issue template), we use issues to keep track of bugs in Gramine.
If you need support then write an email to users@gramineproject.io or join our Gitter (https://gitter.im/gramineproject/community).
