### ISSUE TITLE
run error 

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#558]
host os is ubuntu20.04 with kernel 5.4 and with gsgx kernel module(.ko file) compiled from graphene source.

**Comment by mccoysc** [comment]
![43504EF2-E112-485C-A3DE-6EFE596C1F75](https://user-images.githubusercontent.com/18025276/166115596-1024f0b3-dbbb-4001-8a57-073a1ca43fe8.png)

**Comment by mccoysc** [comment]
@pwmarcz @boryspoplawski

**Comment by mccoysc** [comment]
![5E8D7659-5532-4A33-8437-6EC7DE3A4B0E](https://user-images.githubusercontent.com/18025276/166137703-1dce988d-16e5-46cb-b540-26ebbb4b8541.png)
![D223EB1C-15CE-4A28-9EF5-D7D14279D77C](https://user-images.githubusercontent.com/18025276/166137705-3b6b3a3d-240d-48cb-8a20-ff4769bbab63.png)

I have set load.pal_internal_mem_size to 2048M,but it still error.

**Comment by boryspoplawski** [comment]
Please use the template we have when submitting an issue - it's there for a reason.
Please use markdown to format your message - don't paste screenshots. If the log is too long you can attach a file.
