### ISSUE TITLE
Help needed: release 1.1 build failure

### ISSUE THREAD

**Issue by jtdaugherty** [gramineproject/gramine#560]
## Description of the problem

The build instructions for the stable release at

https://gramine.readthedocs.io/en/stable/quickstart.html#installation

say to run `make` in the `Clone the repository and run sample application` section, but that step fails with a reference to the documentation and build approach for `master`.

## Steps to reproduce

* Clone the repo and check out `v1.1`.
  * Assumption: the "stable" release documentation corresponds to the latest stable release; I also assume that the latest stable release corresponds to the repo tag `v1.1`.
* Consult the stable release documentation up to the `Clone the repository and run sample application` section.
  * Note: the documentation says to clone the repo, effectively pulling down the latest `master` code, *not* the stable release. My additional step not captured in the docs, done in an attempt to bring the code I'm building in line with the docs I'm reading, is to check out v1.1.
* Execute the `make` step,
```
make SGX=1 SGX_SIGNER_KEY="$HOME"/.config/gramine/enclave-key.pem
```

## Expected results

I expected the build to succeed.

## Actual results

The actual result:
```
Please build and install Gramine using Meson!
See https://gramine.readthedocs.io/en/latest/devel/building.html for more details.
```

* Meson is suggested, despite Meson not making an appearance in the stable release build documentation.
* The recommended URL in the error message is for the documentation for `master`, not the release I expected to be building.

## Gramine commit hash

`3623e6322f0e652cb4757be5d037295e3ac7fa95` (tag: `v1.1`)

**Comment by dimakuv** [comment]
I think you're confusing two parts of the QuickStart guide.

1. `Installation` section asks you to install Gramine from the OS distro package. The stable release of Gramine is *not* supposed to be built from GitHub sources, but installed via e.g. `apt install`.
2. `Clone the repository and run sample application` section is purely for testing the installed Gramine. Gramine is supposed to be installed via item 1. And this item 2 is to build (`make`) the HelloWorld example -- the "build" here means to create the SGX-required the `.manifest.sgx`, `.token`, `.sigstruct` files.

> Note: the documentation says to clone the repo, effectively pulling down the latest master code, not the stable release.

You are correct here. This is a bug in our documentation sources. We actually created a bug fix recently for this: https://github.com/gramineproject/gramine/pull/481/files. Unfortunately, because this bug fix was created *after* the v1.1 release of Gramine, we have to wait until we release v1.2 so that this bug fix is "visible" in the stable version of docs.

**Comment by jtdaugherty** [comment]
Okay, thanks for your clarification! I think the confusion for me arises because the documentation doesn't make this clear, so it wasn't clear to me that it was safe to skip the later steps (so I assumed I should go through all of them). I wasn't sure (from the docs) what the `apt-get` steps were installing, i.e., was it drivers, or more than that? It sounded from the comments in the docs like it was just drivers, but because of the project I'm working on, I *think* I need a working build tree to do my work. So yeah, I am probably confused, so I am relying on the docs to help me understand.

As for the `make` step, I also just happened to notice that the Building section of the stable docs *does* mention `meson`. So maybe the quickstart page just needs to be updated to mention the right `meson` command rather than `make`. It seems to me that that's incorrect regardless of what I might be confused about since the build fails immediately with the instruction to use Meson.

**Comment by dimakuv** [comment]
> It seems to me that that's incorrect regardless of what I might be confused about since the build fails immediately with the instruction to use Meson.

I think you forgot to perform the command `cd gramine/CI-Examples/helloworld`. This command is right after the `git clone` command. In other words, you're trying to *build Gramine*, but what that `Clone the repository and run sample application` section wants you to do is to *build the HelloWorld example*.

I see your point about the unclear documentation on the QuickStart page. What would be the best way to make this page more clear? Maybe renaming the sections?
- `Installation` -> `Install Gramine`
- `Clone the repository and run sample application` -> `Try sample application`

And in both these sections the very first sentence will give a quick explanation what exactly will happen by running the commands.

**Comment by jtdaugherty** [comment]
> I think you forgot to perform the command cd gramine/CI-Examples/helloworld. This command is right after the git clone command.

Sure enough, that's true - I totally missed it. I think I missed it because I saw "clone the repo" and after doing that step I didn't expect to see a `cd` command at that point. I guess I would recommend making that a separate step after the clone step, but it's a small thing. Mostly I think I was distracted at the time because I knew I needed to go figure out what to clone (i.e. not `master`).

> I see your point about the unclear documentation on the QuickStart page. What would be the best way to make this page more clear? Maybe renaming the sections?

My confusion probably results more from a lack of understanding Gramine's architecture than it does that specific page. My context is that I'm working on a project that used *Graphene* before its 1.0 release, and at that point using Graphene meant using it at the source tree level, not only in binary form. So part of my confusion probably arises from trying to adapt my (admittedly stale) understanding of how to work with Graphene to this new project. I don't know what that means for helpful doc updates, though.

**Comment by dimakuv** [comment]
Thanks @jtdaugherty for the feedback. I'll submit a PR to improve the QuickStart page tomorrow.

We'll release the next stable version of Gramine (v1.2) in a couple weeks, so you'll hopefully will see an updated stable QuickStart page with all writing-style bugs fixed :)

**Comment by jtdaugherty** [comment]
Okay, that's good to know. Thank you for your help!
