### ISSUE TITLE
Gramine Installation

### ISSUE THREAD

**Issue by ZiiDev** [gramineproject/gramine#563]
I am trying to install gramine for Intel SGX. I am following this setup https://gramine.readthedocs.io/en/latest/devel/building.html , nothing else. But when i come to the part 4 after installing SGX. 
**meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enabled \
    -Dsgx_driver=<driver> -Dsgx_driver_include_path=<path-to-sgx-driver-sources>**
This command is not working. Error comes up either meson.build not found. or this directory is not the build directory.
Also, there is written above **"In order to build Gramine, you need to first set up the build directory. In the root directory of Gramine repo, run the following command (recall that “direct” means non-SGX version):"** how to build directory and what is the root directory of Gramine repo?
Please help me solve that problem.

**Comment by dimakuv** [comment]
> how to build directory and what is the root directory of Gramine repo?

I'm sorry but you seem to be a complete Linux novice? I strongly suggest to first educate yourself on common Linux terminology (well, I think other OSes use the same terms).

The easiest is to google. For example, googling `what is the root directory` gives me this immediate hit: https://www.lifewire.com/what-is-a-root-folder-or-root-directory-2625989. And googling `how to build a directory in Linux` gives me this: https://www.cyberciti.biz/faq/how-to-make-a-folder-in-linux-or-unix/.

**Comment by ZiiDev** [comment]
After googling for few days, then i tried to put a request here. I think you did not understood my question, the things you are trying to say are somehow clear to me. So let me ask my question again if there is any confusion.
How to setup a build directory for Gramine? **"The build directory contains the project build files, including images, packages, kernel, and other files that comprise your build."** 
what is the root directory of gramine repo? I am not sure it, what they are asking.

**Comment by dimakuv** [comment]
> what is the root directory of gramine repo?

It is the directory where you git-cloned Gramine.

**Comment by dimakuv** [comment]
> How to setup a build directory for Gramine?

This is what is written in the Building doc. The `meson setup build/ ...` command is exactly the command that sets up the build directory of Gramine.

**Comment by ZiiDev** [comment]
I did not clone any thing. Please visit this page. Only 4 to 5 commands only. And then you will see the Building heading. Here i face the problem.

**Comment by ZiiDev** [comment]
I get this error

zii@zii:~$ meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enable -Dsgx_driver=dcap1.41 -Dsgx_driver_include_path=/opt/intel/sgxdriver/

ERROR: Neither directory contains a build file meson.build.

**Comment by ZiiDev** [comment]
It also says in the root directory of gramine repo run this command. Where is the root directory of gramine repo?

**Comment by dimakuv** [comment]
Ah, understood now.

The Building section implies that you're a Gramine dev, and you must git-clone Gramine.

Like this:
```
git clone https://github.com/gramineproject/gramine.git 
cd gramine  # this will become your Gramine root dir
```

**Comment by ZiiDev** [comment]
Now i get this error
zii@zii:~$ meson setup build/ --buildtype=release -Ddirect=enabled -Dsgx=enable -Dsgx_driver=dcap1.41 -Dsgx_driver_include_path=/opt/intel/sgxdriver/
The Meson build system
Version: 0.62.1
Source dir: /home/zii/gramine
Build dir: /home/zii/gramine/build
Build type: native build

meson.build:5:0: ERROR: Value "enable" (of type "string") for combo option "Build and install gramine-sgx (aka Linux-SGX)" is not one of the choices. Possible choices are (as string): "disabled", "enabled".

**Comment by woju** [comment]
Hey, guys, please move this discussion off the issue tracker, either to users@gramineproject.io or https://gitter.im/gramineproject/community. This venue is meant for tracking bugs and feature requests, not for user support.

**Comment by ZiiDev** [comment]
Ok Thanks for letting me know about this community.
