### ISSUE TITLE
ra-tls-mbedtls: -10496 - X509 - Read/write of file failed

### ISSUE THREAD

**Issue by VogelIBR** [gramineproject/gramine#574]
## Description of the problem
While figuring out #570 I noticed that `gramine-direct` for the mbedtls example failed to run with `epid`.

## Steps to reproduce
Build and install gramine from master. Build the ra-tls-mbedtls example with `SGX=1`. Run the server.

## Expected results

Output as when running the server natively.

```
gramine-direct server native

  . Creating normal server cert and key... ok
  . Bind on https://localhost:4433/ ... ok
  . Seeding the random number generator... ok
  . Setting up the SSL data.... ok
  . Waiting for a remote connection ...^C
```

## Actual results

```
$ sudo gramine-direct server epid

  . Creating the RA-TLS server cert and key... failed
  !  ra_tls_create_key_and_crt_der returned -10496

Last error was: -10496 - X509 - Read/write of file failed

```
## Gramine commit hash
af9cbc741bbfe2a1b60fd01977e88ccbad8d657d

**Comment by dimakuv** [comment]
> I noticed that `gramine-direct` for the mbedtls example failed to run with `epid`.

This is impossible. `gramine-direct` means "Gramine without SGX" (think of it as a simulation mode), and thus EPID/DCAP SGX attestation doesn't work on `gramine-direct`.

Maybe I should augment this example to give a meaningful error when trying to run with `gramine-direct`... Anyway, this is not a bug in Gramine.

**Comment by VogelIBR** [comment]
Oh my mistake. I just assumed #571 also ran it with dcap when saying "The code runs perfectly fine with gramine-direct."
