### ISSUE TITLE
memory problem: What's the relationship between share memory and enclave_size when run a Multi-Process App

### ISSUE THREAD

**Issue by yanzhichao** [gramineproject/gramine#576]
## Description of the problem
I run an app which have 4 processes,  and config the `sgx.enclave_size = "16G"` , then running on a plateform  that have 64GB memory and with EPC 128M。 I get the memory fault error。

while It can running successful， when I change a plateform that still have 64GB memory but with EPC 32GB。

I know gramine will create 4 enclave when app have 4 processes。 Does it means  （4*16Gb=64GB）the plateform must have at least 64GB free memory when EPC is very small？

Could you tell me What's the relationship between share memory and enclave_size when run a Multi-Process App ?

**Comment by dimakuv** [comment]
Your understanding is correct. Your multi-process application with 4 processes will consume the total of `4 * 16GB = 64GB` of total memory (RAM + swap file).

> while it can running successful, when I change a plateform that still have 64GB memory but with EPC 32GB.

I do not think that the size of EPC is a factor here. The *real cause* for the successful Gramine run is probably the fact that this second platform has not only 64GB of RAM, but also some amount of the swap space.

You can check how much swap space both of your platforms have with the `free -h` Linux command. For example, my system shows this:
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:            31G        1.2G         12G        2.3M         17G         29G
Swap:           31G         61M         31G
```

This means that I have 32GB of RAM and another 32GB of swap file. So, even though my machine has only 32GB of RAM, the actual total amount of memory available for applications is 64GB.

About swap space: https://opensource.com/article/18/9/swap-space-linux-systems

**Comment by mkow** [comment]
Please don't use GitHub issues for general support (see the information in the issue template), we use issues to keep track of bugs in Gramine.
If you need support then write an email to users@gramineproject.io or join our Gitter (https://gitter.im/gramineproject/community).
