### ISSUE TITLE
meson.build:58:4: ERROR: Program 'nasm' not found or not executable

### ISSUE THREAD

**Issue by kvijay1918** [gramineproject/gramine#580]
I am getting the below error during GSC build. Can anyone help me out quickly.

Step 6/21 : RUN cd /gramine     && meson setup build/ --prefix="/gramine/meson_build_output"        --buildtype=release        -Ddirect=enabled -Dsgx=enabled                -Dsgx_driver=upstream -Dsgx_driver_include_path=/gramine/driver             && ninja -C build     && ninja -C build install

 ---> Running in f617cf1b6598
The Meson build system
Version: 0.61.4
Source dir: /gramine
Build dir: /gramine/build
Build type: native build
Project name: gramine
Project version: 1.1post-UNRELEASED
C compiler for the host machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the host machine: cc ld.bfd 2.30
C++ compiler for the host machine: c++ (gcc 7.5.0 "c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the host machine: c++ ld.bfd 2.30
Host machine cpu family: x86_64
Host machine cpu: x86_64
Program check-no-reloc.sh found: YES (/gramine/Scripts/check-no-reloc.sh)
Program gen-pal-map.py found: YES (/gramine/Scripts/gen-pal-map.py)
Program get-python-platlib.py found: YES (/gramine/Scripts/get-python-platlib.py)
Program meson-clang-format.sh found: YES (/gramine/Scripts/meson-clang-format.sh)
Program objcopy found: YES (/usr/bin/objcopy)
meson.build:49: WARNING: Project targeting '>=0.55' but tried to use feature deprecated since '0.48.0': python3 module.
WARNING: You should add the boolean check kwarg to the run_command call.
         It currently defaults to false,
         but it will default to true in future releases of meson.
         See also: https://github.com/mesonbuild/meson/issues/9300
Program nasm found: NO

meson.build:58:4: ERROR: Program 'nasm' not found or not executable

A full log can be found at /gramine/build/meson-logs/meson-log.txt
NOTICE: You are using Python 3.6 which is EOL. Starting with v0.62.0, Meson will require Python 3.7 or newer
Failed to build unsigned graminized docker image `gsc-serverms-unsigned`.
root@a4bf01694f20:~/vijay/gsc#

**Comment by dimakuv** [comment]
Please post issues about GSC in the respective repo: https://github.com/gramineproject/gsc/issues. I will close this issue here, feel free to recreate this issue in the other repo.

But to your question: what is your `config.yaml` of GSC? In particular, what is the value of `Distro` there? Is it Ubuntu 18.04, 20.04, or something else?

Also, did you update your local GSC repository to the latest one? We recently (about ~1 week ago) added this requirement on the `nasm` program.

**Comment by kvijay1918** [comment]
I just deleted my local gsc clone repo and cloned again. This time I didn't get this error.
