### ISSUE TITLE
OpenJDK example gets stuck and does not finish

### ISSUE THREAD

**Issue by ColossusChang** [gramineproject/gramine#590]
## Description of the problem

When I tried to run the [OpenJDK example](https://github.com/gramineproject/examples/tree/master/openjdk) using `gramine-sgx` with `GRAMINE_LOG_LEVEL = trace`, the process would get stuck and would not finish. I waited a long time before ending it with Ctrl-C. Here is the log:
[sgx.log](https://github.com/gramineproject/examples/files/8706677/sgx.log)

## Steps to reproduce

1. Build the Gramine with the commit hash. 
2. Change the log level to `trace`
3. Prepare signing keys
4. Run the OpenJDK example with `gramine-sgx`

## Expected results

The process successfully finishes and exits.

## Actual results

The process gets stuck and will not stop. It keeps doing a set of specific operations, which makes me think it was stuck on these operations. 

## Gramine commit hash

c56a3536b182021fa0655d9d55f3076ceced6fff

**Comment by dimakuv** [comment]
@ColossusChang Let's not create duplicate issues for the same bug. You already created this one: https://github.com/gramineproject/examples/issues/26. Let's keep the discussions there. I'm closing this issue.

(I am currently looking at it.)
