### ISSUE TITLE
MariaDB requires O_PATH flag support

### ISSUE THREAD

**Issue by svenkata9** [gramineproject/gramine#591]
## Description
MariaDB fails to run it requires support for `O_PATH` flag. MariaDB opens the `/var/lib/mysql/` directory with flags including `O_PATH`. 

## Steps to reproduce

Install MariaDB in the system, use the attached manifest to graminize it, and use the following steps to run it.
[mysqld.manifest.template.txt](https://github.com/gramineproject/gramine/files/8715241/mysqld.manifest.template.txt)

1. systemctl stop mysqld
2. ps aux | grep mysqld or  ps aux | grep mariadb -> kill any instance of mariadb
3. cd /var/lib/mysql and delete all temp files and log files
	a. rm -rf aria_log.00000001  aria_log_control ib_buffer_pool ib_logfile0 multi-master.info ibdata1 ddl_recovery.log debian-10.7.flag 
4. Build mariadb server using the attached manifest with make SGX=1
5. gramine-sgx mysqld  --user=root 
6. rm -rf  /var/lib/mysql/ibdata before running the above command (5) again
7. Connect with the server:  mysql -u root -p -h 127.0.0.1   

## Expected results
MariaDB server should be starting when graminized and run.

## Actual results

MariaDB server fails to start with Gramine. We currently have the below check in shim_do_openat which fails for mariadb server. Commenting out this code starts the MariaDB server, but this may have other implications. So, we need to properly fix.
```
    if (flags & O_PATH) {
        return -EINVAL;
    }
```
## Gramine commit hash
e6b697521a35ae24809d79237ad814ca497b3470

**Comment by boryspoplawski** [comment]
@svenkata9 Could you check if https://github.com/gramineproject/gramine/pull/650 works for you?

**Comment by svenkata9** [comment]
> @svenkata9 Could you check if #650 works for you?

@boryspoplawski Yes, we tested it today and #650 fixes it.
