### ISSUE TITLE
[LibOS] `/proc/cpuinfo` doesn't have the `flags` line

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#592]
## Description of the problem

Some workloads parse the `flags` line in the pseudo-file `/proc/cpuinfo`. Case in point: https://github.com/intel/intel-extension-for-pytorch/blob/306aa1ea0baf51ed700c3abfead5e46c4e076427/intel_extension_for_pytorch/utils/_cpu_isa.py

This PyTorch extension from Intel looks for the `AVX2` word (upper-cased) in the `flags` line of `/proc/cpuinfo`.

However, currently Gramine doesn't provide the `flags` line at all, see our emulation code of `/proc/cpuinfo`: https://github.com/gramineproject/gramine/blob/e6b697521a35ae24809d79237ad814ca497b3470/LibOS/shim/src/fs/proc/info.c#L132

## Steps to reproduce

Just to verify, I ran:
```
gramine/CI-Examples/busybox$ gramine-sgx busybox sh

cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 158
model name      : Intel(R) Xeon(R) E-2176G CPU @ 3.70GHz
stepping        : 10
physical id     : 0
core id         : 0
cpu cores       : 6
bogomips        : 7399.70

... same for other CPU cores ...
```

As you can see, no flags printed.

## How to fix

- A workaround just to test this particular workload would be something like this diff:
```diff
diff --git a/LibOS/shim/src/fs/proc/info.c b/LibOS/shim/src/fs/proc/info.c
@@ -167,6 +167,7 @@ int proc_cpuinfo_load(struct shim_dentry* dent, char** out_data, size_t* out_siz
                 cores_in_socket++;
         }
         ADD_INFO("cpu cores\t: %zu\n", cores_in_socket);
+        ADD_INFO("flags\t\t: avx2\n");  /* FIXME: hard-coding is wrong, just for testing! */
         double bogomips = cpu->cpu_bogomips;
         // Apparently Gramine snprintf cannot into floats.
         ADD_INFO("bogomips\t: %lu.%02lu\n", (unsigned long)bogomips,
```

- A real fix would be to perform a bunch of `DkCpuIdRetrieve()` calls, find the currently enabled HW features, and add the corresponding flag-descriptions.

## Gramine commit hash

e6b697521a35ae24809d79237ad814ca497b3470

**Comment by dimakuv** [comment]
**UPDATE**: The file to fix was changed in the meantime.

Now the workaround should be applied here: `LibOS/shim/src/arch/x86_64/fs_proc/info.c`.

See https://github.com/gramineproject/gramine/blob/3f2478bfaf8e02194dc088964d1ed3f7d3f282dc/LibOS/shim/src/arch/x86_64/fs_proc/info.c#L43?plain=1

**Comment by dimakuv** [comment]
**UPDATE:** The file to fix was changed again (the path to it changed).

Now the workaround should be applied here: `LibOS/src/arch/x86_64/fs_proc/info.c`. (`shim/` intermediate dir was removed.)

**Comment by kailun-qin** [comment]
Some questions below:
1. I see there are ["whitelisted" flags](https://github.com/gramineproject/gramine/blob/ecca6b5567981626f5874a99594634754b691823/pal/src/arch/x86_64/pal_cpuid.c#L23) stored in `pal_cpu_info->cpu_flags` but seems like they are not actually used anywhere. May I know the intention for them?
2. Do we intend to support all CPU cap flags via `DkCpuIdRetrieve()` or just a subset of them?

Thanks!
