### ISSUE TITLE
[Feature request] Interface to get peak memory usage

### ISSUE THREAD

**Issue by kvinwang** [gramineproject/gramine#614]
The memory is precious for a program running in SGX. We used to build our App with intel `sgx-sdk`, and use the `g_peak_heap_used` from the SDK to track and see if our app would be about to run out of memory.

It would be great if Gramine provide the equivalent functionality via adding an item in the `/proc/meminfo`:
```
MemPeak:         1187612 kB
```

**Comment by boryspoplawski** [comment]
There is no such entry in `/proc/meminfo` (talking about normal Linux system)

**Comment by kvinwang** [comment]
> There is no such entry in `/proc/meminfo` (talking about normal Linux system)

It can be put somewhere else which doesn't matter to me. Hmm, I am looking forward to the feature itself.

**Comment by dimakuv** [comment]
@kvinwang I like this idea.

We have `Committed_AS` line in `/proc/meminfo` -- this line shows the *current* enclave-memory usage. Some references from the code, if you want to look into this deeper:
- https://github.com/gramineproject/gramine/blob/f17ca4525c38b880530597fae28fc43a0840b8a0/LibOS/shim/src/fs/proc/info.c#L49?plain=1
- https://github.com/gramineproject/gramine/blob/0affeefe376143614dd1122096ef8e79c782cc58/Pal/src/host/Linux-SGX/db_memory.c#L95?plain=1

However, you are right, there is no information about the *peak* enclave-memory usage. It could be easily added though, similarly to the already-existing `g_allocated_pages` variable.

@boryspoplawski @mkow Is this something you think is useful generally? Or is it a too obscure feature to add and promote to users?

**Comment by mkow** [comment]
I don't like the idea of adding custom (i.e. not present on Linux) stuff to `/proc/meminfo`. Also, in this version the app itself would need to read it and reply to the developer? Why not just print this in the debug logs when Gramine exits?

**Comment by dimakuv** [comment]
> Also, in this version the app itself would need to read it and reply to the developer?

That's how I understood @kvinwang's request -- every time the app reads `/proc/meminfo` (well, more specifically, when the app opens it), the `MemPeak` value is updated to reflect the last seen peak enclave memory. So the app must be "Gramine-aware".

> Why not just print this in the debug logs when Gramine exits?

Because the app wants to adjust itself based on this `MemPeak` value, e.g., perform some garbage collection or flush its caches. Something like this. Which needs a dynamically updated and accessible value.

**Comment by boryspoplawski** [comment]
> I don't like the idea of adding custom (i.e. not present on Linux) stuff to `/proc/meminfo`

Yeah, sounds like a bad idea to me too.

> Why not just print this in the debug logs when Gramine exits?

+1

> Because the app wants to adjust itself based on this MemPeak value, e.g., perform some garbage collection or flush its caches. Something like this. Which needs a dynamically updated and accessible value.

All these app should do based on the current usage, not peek, otherwise it doesnt make any sense.
For now I cannot think of any usage of peek memory for the app (but for the developer there sure is).

**Comment by kvinwang** [comment]
> I don't like the idea of adding custom (i.e. not present on Linux) stuff to `/proc/meminfo`.

Feel free to change the position.

> All these app should do based on the current usage, not peek, otherwise it doesnt make any sense.
> For now I cannot think of any usage of peek memory for the app (but for the developer there sure is).

We are building a blockchain-driven computing network. The tasks are dispatched to TEEs by each block at about 6s intervals.

The memory requirement grows along with the blockchain growth. The TEE program would do much allocation/deallocation when processing each block. And the memory requirement depends on the peak memory usage rather than the current because the peak usage could be 10x or more of the idle usage. 

So, our system needs to monitor the peak usage to ensure it's under a safe waterline so that we can decide:
- Whether to dispatch more tasks to a given TEE worker.
- Whether we should upgrade the software to allocate more TEE memory (turn up the memory limitation in the manifest).

**Comment by mkow** [comment]
> > I don't like the idea of adding custom (i.e. not present on Linux) stuff to /proc/meminfo.
>
> Feel free to change the position.

It's not about its position in the file, but about having something in that file which isn't there on Linux.

> So, our system needs to monitor the peak usage to ensure it's under a safe waterline so that we can decide:
>
> - Whether to dispatch more tasks to a given TEE worker.
> - Whether we should upgrade the software to allocate more TEE memory (turn up the memory limitation in the manifest).

This case seems super-specific to your app, we'd rather not introduce a public interface for this (consider that if we introduce it, then we'll need to support it for ever - so, if we'd do this for every app-specific request, they we'd end up with unmaintainable codebase).
What we could do instead, is to add a bookkeeping of this value internally and print it to the debug logs at the exit (as proposed previously). This would be useful to many more users, and then you could create and use a custom patch to expose this value however you like. It should be just a few lines to do this and we wouldn't need to maintain it as a public API (but you'll need to rebase your patch from time to time).
Would this solution satisfy you?

**Comment by kvinwang** [comment]
> It's not about its position in the file, but about having something in that file which isn't there on Linux.

I meant we can put it somewhere else rather than in that file. Linux put it in `/proc/[pid]/status` for example.
```
$ cat /proc/self/status | grep Peak
VmPeak:	   16860 kB
```


> This case seems super-specific to your app

I don't think `peak memory usage` is specific to our app. Both Linux and Intel sgx-sdk support it. It's just a fundamental and generic feature.
`Peak usage` is more important than `current usage` for a sgx applications because every app would have to configure the max available mem, which directly depends on the `peak usage`, in the manifest which isn't required for a normal linux app. To `sgx-sdk`, there even isn't a way to get `current usage` but away to get `peak usage`.


> It should be just a few lines to do this and we wouldn't need to maintain it as a public API (but you'll need to rebase your patch from time to time).

If every fundamental feature would require a patch, every app developer would have to maintain a long patch list to gramine for their app. This sounds isn't a good idea.

**Comment by h4x3rotab** [comment]
I agree with @kvinwang. On Linux you have basically two ways to get the peak memory usage. Either by reading VmPeak in `/proc/$PID/status`, or sampling the process periodically. However in the context of SGX, it's not really practical to attach some profiler to the process. So I'd love the earlier approach.

**Comment by dimakuv** [comment]
I think we can add `/proc/[pid]/status` without problems.

Our misunderstanding was that the first proposal was about `/proc/meminfo`. But introducing `/proc/[pid]/status` and having `VmPeak` there is surely reasonable.

**Comment by mkow** [comment]
> ```
> $ cat /proc/self/status | grep Peak
> VmPeak:	   16860 kB
> ```

Ok, that's a completely different case, here it's actually an interface which a real Linux exposes. Your original proposal was different and I was commenting on that version.

> `Peak usage` is more important than `current usage` for sgx applications because every app would have to configure the max available mem, which directly depends on the `peak usage`, in the manifest which isn't required for a normal Linux app.

Yes, but what you asked for was peak usage _in runtime_, _available only to the app inside Gramine_ (thus harder to retrieve for the developer tweaking manifest config manually). And what I proposed was actually more useful for the case you're mentioning here.

> If every fundamental feature would require a patch, every app developer would have to maintain a long patch list to gramine for their app. This sounds like not a good idea.

As above, the most common case is that you want this in Gramine debug logs, not somewhere in the app-visible filesystem, which requires you to modify the app to be able to read it.

Anyways, since it turns out that Linux actually has that info (but in `/proc/<pid>/status`) then we could add it there + print at exit.

**Comment by kvinwang** [comment]
> the most common case is that you want this in Gramine debug logs, not somewhere in the app-visible filesystem

Can't agree.
- Most serious apps would report runtime metrics to their monitor platform. As an SGX application, `peak memory usage` of cause should be added to the metrics list. And in many cases, the manifest config should be tuned according to the real-world metrics analysis instead of the original tweaking in the laboratory.
- We shouldn't only consider `the most common case`. If Linux considers like this, maybe 99% of its codes could be removed.

**Comment by dimakuv** [comment]
> If Linux considers like this, maybe 99% of its codes could be removed.

Hehe, I love this statement and fully agree :)

Anyway, looks like we have a consensus: we should add `VmPeak` stats into the pseudo-file `/proc/<pid>/status`. Can we assign someone to this @mkow ?

**Comment by mkow** [comment]
> * Most serious apps would report runtime metrics to their monitor platform. As an SGX application, `peak memory usage` of cause should be added to the metrics list. And in many cases, the manifest config should be tuned according to the real-world metrics analysis instead of the original tweaking in the laboratory.

I'm not that sure, your app is the only case doing this in SGX we heard of so far. And the latter part of the argument - this is equally possibly with the logs solutions. Maybe in non-SGX world this is more popular, but here you can't easily react to whatever you read as peak memory usage from the app perspective, it's only the orchestrator which can react to it, and it can do this equally well from the logs (and it actually needs to rebuild the enclave to grow it, which includes re-signing it, etc.).

> * We shouldn't only consider `the most common case`. If Linux considers like this, maybe 99% of its codes could be removed.

And also shouldn't accept all requests to add public APIs. There are maany APIs that Linux regrets ever adding, but they still have to support them to preserve backwards compatibility.

> Anyway, looks like we have a consensus: we should add `VmPeak` stats into the pseudo-file `/proc/<pid>/status`. Can we assign someone to this @mkow?

Sure, but from our side we're already busy for at least a few weeks, we got quite a lot of requests recently.
