### ISSUE TITLE
wrong "protected files" mode action

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#621]
## Description of the problem
current file position in a file opened with mode "a" or 'a+' should be set to the end of file for "append",but it's not in protected files.
## Steps to reproduce
in node js:
`fs.appendFileSync("/enc/encrypted_file.dat","data");//this function open file with mode "a" and append data to the end of file when run in normal os like linux or windows.`

## Expected results
if file exists,data would be written to the end of file;if file not exists,file would be created and data would be writen to the file.
## Actual results
data would always be written to the start of file with "file exist" or "file not exist".

## Gramine commit hash
the latest committed in 20022/05/30

**Comment by mccoysc** [comment]
@oshogbo @mkow

**Comment by mccoysc** [comment]
@pwmarcz

**Comment by mkow** [comment]
@mccoysc: Please stop spamming random people with pings, we see the issues you post. If you want us to help you, then:
- Reword your whole issue, it's full of typos and chaotic, it's hard to get what's exactly the problem. If you want us to spend time helping you, then you also need to give some time from yourself to state the problem clearly.
- Post a full reproduction steps, so we can confirm the problem easily on our side.
- In "Gramine commit hash" post _commit hash_, as asked, not some date.

I'm closing this issue and will reopen after you fixed these.
