### ISSUE TITLE
file api work wrong on encrypted mount path

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#622]
## Description of the problem
in nodejs:
fs.existsSync work wrong,it seems that file api have some bugs when work on encrypted mount path(mount params: type="encrypted",uri="file:encrypted",path="/encrypted/",key_name="_sgx_mrenclave").
## Steps to reproduce

fs.existsSync("/enc/encrypted_file.dat");//this function return true if file exists or return false if file not exists when run in normal os like linux or windows.

## Expected results
return true if file exists or return false if file not exists
## Actual results
always return false

nodejs version 18.2.0

## Gramine commit hash
latest commit in 2022/05/30

**Comment by mccoysc** [comment]
@pwmarcz @oshogbo @mkow

**Comment by mkow** [comment]
Same as https://github.com/gramineproject/gramine/issues/621#issuecomment-1141913872.
