### ISSUE TITLE
remote attestation error

### ISSUE THREAD

**Issue by mccoysc** [gramineproject/gramine#629]
## Description of the problem
in gramine/CI-Examples/ra-tls-secret-prov/:
`make app dcap files/input.txt`
and then run :
```
RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 \
RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 \
./secret_prov_server_dcap &

gramine-sgx ./secret_prov_client
```
would get error:
![image](https://user-images.githubusercontent.com/18025276/171781267-cfd2a49f-0ef6-44d6-8e35-4230907415ef.png)
 and run `service aesmd status` would get the following information:
 
![image](https://user-images.githubusercontent.com/18025276/171781353-27eb3b89-45e4-4aea-b549-6bf71d4ce2ef.png)

## Steps to reproduce
as the description

## Expected results
run as the readme in `gramine/CI-Examples/ra-tls-secret-prov/`
## Actual results
got error

## Gramine commit hash
any version would get the same result.

**Comment by mccoysc** [comment]
it seems it can't find local cert chain,but how i can resolve it?

**Comment by billionairiam** [comment]
I think you should configure a proxy server under **/etc/aesmd.conf**. below is my configuration.

`#Line with comments only
#empty line with comment
#proxy type    = direct #direct type means no proxy used
#proxy type    = default #system default proxy
proxy type    = manual #aesm proxy should be specified for manual proxy type
aesm proxy    = http://child-prc.intel.com:913
#whitelist url = http://sample_while_list_url/
#default quoting type = ecdsa_256
#default quoting type = epid_linkable
#default quoting type = epid_unlinkable`

**Comment by mkow** [comment]
I'm closing this as unrelated to Gramine - the problem seems to be in your setup of SGX PSW, which is a different project.
