### ISSUE TITLE
apt-get update and install gramine not working

### ISSUE THREAD

**Issue by mHassan11** [gramineproject/gramine#640]
Hey, I am trying to [quick install](https://gramine.readthedocs.io/en/stable/quickstart.html#install-gramine) Gramine OS on a machine with following specifications.

> Operating System: Debian GNU/Linux 9 (stretch)
> Kernel: Linux 5.13.9.rsk.1-amd64
> Architecture: x86-64

When I run `sudo apt-get update` I get following output (I have highlighted what seemed to be error/issue).

`Ign:1 http://mirrors.byted.org/debian stretch InRelease`
`Hit:2 http://apt.byted.org/private stretch-private InRelease`
`Hit:3 http://mirrors.byted.org/debian stretch-backports InRelease`
`Hit:4 http://mirrors.byted.org/debian-security stretch/updates InRelease`
`Hit:5 http://mirrors.byted.org/debian stretch Release      `                           
`Ign:7 https://packages.gramineproject.io stable InRelease         `                    
`Hit:8 https://download.01.org/intel-sgx/sgx_repo/ubuntu focal InRelease`
`Hit:9 https://download.01.org/intel-sgx/sgx_repo/ubuntu bionic InRelease`
`Ign:10 https://packages.gramineproject.io stable Release`
`Ign:11 https://packages.gramineproject.io stable/main amd64 Packages`
`Ign:12 https://packages.gramineproject.io stable/main all Packages`
`Ign:13 https://packages.gramineproject.io stable/main Translation-en_US`
`Ign:14 https://packages.gramineproject.io stable/main Translation-en`
`Ign:11 https://packages.gramineproject.io stable/main amd64 Packages`
`Ign:12 https://packages.gramineproject.io stable/main all Packages`
`Ign:13 https://packages.gramineproject.io stable/main Translation-en_US`
`Ign:14 https://packages.gramineproject.io stable/main Translation-en`
`Ign:11 https://packages.gramineproject.io stable/main amd64 Packages`
`Ign:12 https://packages.gramineproject.io stable/main all Packages`
`Ign:13 https://packages.gramineproject.io stable/main Translation-en_US`
`Ign:14 https://packages.gramineproject.io stable/main Translation-en`
`Ign:11 https://packages.gramineproject.io stable/main amd64 Packages`
`Ign:12 https://packages.gramineproject.io stable/main all Packages`
`Ign:13 https://packages.gramineproject.io stable/main Translation-en_US`
`Ign:14 https://packages.gramineproject.io stable/main Translation-en`
`Ign:11 https://packages.gramineproject.io stable/main amd64 Packages`
`Ign:12 https://packages.gramineproject.io stable/main all Packages`
`Ign:13 https://packages.gramineproject.io stable/main Translation-en_US`
`Ign:14 https://packages.gramineproject.io stable/main Translation-en`
**`Err:11 https://packages.gramineproject.io stable/main amd64 Packages server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`**
`Ign:12 https://packages.gramineproject.io stable/main all Packages`
`Ign:13 https://packages.gramineproject.io stable/main Translation-en_US`
`Ign:14 https://packages.gramineproject.io stable/main Translation-en`
`Reading package lists... Done`
**`W: The repository 'https://packages.gramineproject.io stable Release' does not have a Release file.`
`N: Data from such a repository can't be authenticated and is therefore potentially dangerous to use.`
`N: See apt-secure(8) manpage for repository creation and user configuration details.`
`E: Failed to fetch https://packages.gramineproject.io/dists/stable/main/binary-amd64/Packages  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`
`E: Some index files failed to download. They have been ignored, or old ones used instead.`**

Subsequently, when I run `sudo apt-get install gramine`, that does not work either.

```Reading package lists... Done```
```Building dependency tree```
```Reading state information... Done```
```E: Unable to locate package gramine```

I am fairly new to Linux Debian OS and intel SGX. Please let me know how can I fix these issues and make Gramine OS work? and if the commands in Quick Installation needs to be any different for my system? 
Any assistance will be appreciated. Thanks.

**Comment by woju** [comment]
On Tue, Jun 07, 2022 at 11:45:19PM -0700, Muhammad Hassan wrote:
> > Operating System: Debian GNU/Linux 9 (stretch)
[snip]
> **`Err:11 https://packages.gramineproject.io stable/main amd64 Packages server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`**

Debian stretch is very old (EOL'd two years ago, LTS ending this month).
I suspect too old ca-certificates package. Can you update this package before
adding our repo? If it won't, you'll have to update whole Debian (which you
should do anyway before end of June 2022).

Our certificate itself is fine, you can check by opening
https://packages.gramineproject.io/ in a browser.

**Comment by mHassan11** [comment]
@woju Which version for Debian would you recommend (any particular version that Gramine OS was developed/tested on for Debian)?

> On Tue, Jun 07, 2022 at 11:45:19PM -0700, Muhammad Hassan wrote: > Operating System: Debian GNU/Linux 9 (stretch)
> [snip]
> **`Err:11 https://packages.gramineproject.io stable/main amd64 Packages server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none`**
> Debian stretch is very old (EOL'd two years ago, LTS ending this month). I suspect too old ca-certificates package. Can you update this package before adding our repo? If it won't, you'll have to update whole Debian (which you should do anyway before end of June 2022). Our certificate itself is fine, you can check by opening https://packages.gramineproject.io/ in a browser.

**Comment by woju** [comment]
> @woju Which version for Debian would you recommend (any particular version
> that Gramine OS was developed/tested on for Debian)?

Gramine is built on Debian 11 (bullseye/current stable), and tested mostly on
Ubuntu 20.04 (focal).

**Comment by mHassan11** [comment]
> @woju Which version for Debian would you recommend (any particular version that Gramine OS was developed/tested on for Debian)?
> Gramine is built on Debian 11 (bullseye/current stable), and tested mostly on Ubuntu 20.04 (focal).

Thank you for response. Is there a docker image as well which I can use as well?

**Comment by woju** [comment]
> Thank you for response. Is there a docker image as well which I can use as well?

Please check GSC project (https://github.com/gramineproject/gsc), which is our
docker integration. We're thinking about "plain" docker with just gramine
installed, but it's not available yet.

**Comment by woju** [comment]
I'm closing this issue. I'm assuming you've solved the problem with too old ca-certificates, since the discussion moved away -- if not, please comment and I'll reopen. If you have any further questions about usage, please ask them on users@gramineproject.io.
