### ISSUE TITLE
Unknown Handle Exception

### ISSUE THREAD

**Issue by dzygann** [gramineproject/gramine#656]
Hi,

I did some tests with an enclaved nginx (See [Repo](https://github.com/enclaive/enclaive-docker-nginx-sgx)).
I left the nginx in the idle mode and after a while (approx. 5 min) the nginx was down.

Here are the information from the terminal output:

```
nginx-sgx \| Gramine   is starting. Parsing TOML manifest file, this may take some time...

nginx-sgx \| [P3:T3:nginx] assert failed   ../LibOS/shim/src/sys/shim_socket.c:1448 total_bytes < peek_buffer->end   - peek_buffer->start
nginx-sgx \| [P1:shim] error: Child   process (vmid: 0x3) got disconnected
nginx-sgx \| assert failed   ../Pal/src/db_object.c:51 !UNKNOWN_HANDLE(handle_array[i])
nginx-sgx exited with code 1
```

Do you have an idea what the issue is?

Thanks in advance!

Denis

**Comment by boryspoplawski** [comment]
The old networking code is buggy and was rewritten: https://github.com/gramineproject/gramine/pull/579. Should be merged ~soon.

**Comment by boryspoplawski** [comment]
@dzygann #579 was merged, please try the current master

**Comment by dzygann** [comment]
Hi @boryspoplawski, 

I  just tested it and I can't reproduce the issue. 
Seems to work 👍 

Thanks for your help!
