### ISSUE TITLE
RFC: Remove "shim" prefix from LibOS code

### ISSUE THREAD

**Issue by boryspoplawski** [gramineproject/gramine#660]
After https://github.com/gramineproject/gramine/pull/659 is merged it'll be time to finally get rid of "shim" prefix completely. To do that, we need to decide on how to do the rename exactly. My proposal - consists of a few cases:
A) Files - `shim_async.c` -> `libos_async.c`
B) Strucutres, types, defines etc. - `struct shim_handle` -> `struct libos_handle`.
C) Syscall wrappers - `shim_do_read` -> ~`syscall_handle_read`~ `libos_syscall_read`.
D) Other functions - simple rename `s/shim/libos` as in A and B.

I assumed `LibOS`/`libos` is the name we want to use. Do we have other alternatives?

**Comment by dimakuv** [comment]
For C, why not `libos_syscall_read`? This will make it clear that the LibOS component is handling the `read` syscall.

**Comment by boryspoplawski** [comment]
`libos_syscall_read` is nice! 

> we just add the `libos_` prefix

We also strip `do_`

**Comment by dimakuv** [comment]
@boryspoplawski This can be closed, right? I'll close it, and if anything, please reopen.
