### ISSUE TITLE
mmap(2) tests fail on SGX

### ISSUE THREAD

**Issue by oshogbo** [gramineproject/gramine#663]
## Description of the problem

As pointed out by @dimakuv, the `test_204_copy_dir_mmap_whole` test from the `test_fs.py` is marked as failing with the SGX. We would like to debug why this is happening.

**Comment by oshogbo** [comment]
I can look into this.

**Comment by dimakuv** [comment]
@oshogbo Found one more issue that you wanted to take a look at :)

**Comment by oshogbo** [comment]
It seems that we do not implement [mmap(PROT_WRITE)](https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux-sgx/pal_files.c#L261) which is used by this test. In my opinion, this test was added just to have the whole coverage for different flags for mmap - so it doesn't seem to be invalid.

At this point, we don't have workloads with this routine. So I propose to close this PR.

**Comment by mkow** [comment]
@oshogbo: Could you add a short comment there explaining why this test is disabled on SGX? Otherwise we'll have this very discussion again in a year :)

**Comment by oshogbo** [comment]
@mkow Sorry I didn't notice you have reopened this issue.
I have created PR.
