### ISSUE TITLE
pwrite03, write02 LTP tests passing with graphene direct but failing with GSGX

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/gramine#67]
## Description of the problem

With the `Fix filesystem corner cases commit 0012183743c3a9b4ea4b85a97e7859da4836b1ca`, the tests are passing with Graphene native but fail with GSGX. Originally these tests had started failing with the inode PR and the above commit was the fix for the tests. 

Graphene direct output:
```           
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
/home/intel/graphene/LibOS/shim/test/ltp/src/lib/tst_test.c:1248: TINFO: Timeout per run is 0h 05m 00s
/home/intel/graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/pwrite/pwrite03.c:25: TPASS: pwrite(fd, NULL, 0) == 0

Summary:
passed   0
failed   0
skipped  0
warnings 0
```

GSGX output:
```
error: Using insecure argv source. Graphene will continue application execution, but this configuration must not be used in production!
/home/intel/graphene/LibOS/shim/test/ltp/src/lib/tst_test.c:1248: TINFO: Timeout per run is 0h 05m 00s
/home/intel/graphene/LibOS/shim/test/ltp/src/testcases/kernel/syscalls/pwrite/pwrite03.c:20: TFAIL: pwrite() should have succeeded with ret=0: EACCES (13)

Summary:
passed   0
failed   0
skipped  0
warnings 0
```

## Steps to reproduce

In order to run the LTP tests with GSGX, you need to make a change to the src/lib/tst_test.c file and change the flag from MAP_SHARED to MAP_PRIVATE at this line: https://github.com/linux-test-project/ltp/blob/da2f34028f046a208aa2fed5e287df2538e69f91/lib/tst_test.c#L108

Rebuild LTP with SGX=1 flag.

`cd install/testcases/bin/`

`graphene-sgx pwrite03`

**Comment by dimakuv** [comment]
@pwmarcz Will you have time to look at this? Me and Michal quickly looked at this yesterday, looks like a legit bug that was introduced in your PR.

**Comment by pwmarcz** [comment]
Sure. I'll submit a PR, but if there are any issues during review, I'm  not sure if I'll have time to address them. If this is needed before next Friday, feel free to take over.
