### ISSUE TITLE
Domain name resolution stopped working

### ISSUE THREAD

**Issue by Villain88** [gramineproject/gramine#673]
## Description of the problem
Domain name resolution stopped working on the latest version (5a39aee217955701b412d4ff807c32da8e53ab94).
Previos version (57b2cb30e7def6e1f34f8875496952b9c1d310ae) didn't have that problem.

## Steps to reproduce
Some of my applications stopped recognizing domain names. I reproduced the problem by writing simple code:
```
int main(int argc, char *argv[])
{
    if (argc != 2) {
        printf("usage: %s <hostname>\n", argv[0]);
        exit(1);
    }

    hostent * record = gethostbyname(argv[1]);
    if(record == NULL) {
        printf("%s is unavailable\n", argv[1]);
        exit(1);
    }

    in_addr * address = (in_addr * )record->h_addr;
    string ip_address = inet_ntoa(* address);

    cout << argv[1] << " (" << ip_address << ")\n";

    return 0;
}
```
The required files are allowed in the manifest
```
...
sgx.allowed_files = [
  "file:/etc/nsswitch.conf",
  "file:/etc/ethers",
  "file:/etc/hosts",
  "file:/etc/group",
  "file:/etc/passwd",
  "file:/etc/localtime",
  "file:/etc/host.conf",
  "file:/etc/resolv.conf",
]
...
```

## Expected results
IP address of the passed name is determined
## Actual results
Getting an error: "hostname is unavailable"
## Additional information
 This error in the log:
`[P1:T1:gethostbyname] trace: ---- shim_setsockopt(3, 0, 11, 0x70b56191860c, 4) = -92`

I think it's related to [this](https://github.com/gramineproject/gramine/pull/579) commit

## Gramine commit hash
5a39aee217955701b412d4ff807c32da8e53ab94

**Comment by boryspoplawski** [comment]
I'll take a look.
@dimakuv you cannot change blockingness (`O_NONBLOCK`) with `setsockopt`. This one seems to be just a random IP socket option we do not support

**Comment by boryspoplawski** [comment]
This is `setsockopt(SOL_IP, IP_RECVERR)` which is not supported in Gramine. It allows for receiving errors from socket fd as `struct sock_extended_err` using `recvmsg` and `MSG_ERRQUEUE` flag. None of this is supported and adding it is non-trivial.

**Comment by boryspoplawski** [comment]
> Why did it work previously? 

Since there were no errors happening in runtime, the code did not try to retrieve them, so the only unsupported syscall made was this `setsockopt`, which completely ignored the option and returned `0`.

**Comment by boryspoplawski** [comment]
@dimakuv because everything happens under the hood. `gethostbyname` sounds innocent, but it has to query a DNS server which requires parsing all configuration and what not. Among others, it creates a UDP socket and tries to set that option on it.

**Comment by dimakuv** [comment]
> `gethostbyname` sounds innocent, but it has to query a DNS server which requires parsing all configuration and what not. Among others, it creates a UDP socket and tries to set that option on it.

Yes, I understand it. What I meant is that `gethostbyname()` standard lib function is widely used, and we need to support it.

Anyway, we discussed it offline, Borys will create a PR to fix this (in a "lazy fail" fashion).

**Comment by boryspoplawski** [comment]
@Villain88 Please verify if https://github.com/gramineproject/gramine/pull/678 fixes the issue (it does for the repro code)

**Comment by Villain88** [comment]
> @Villain88 Please verify if #678 fixes the issue (it does for the repro code)

Sorry for the long wait.
Thank you, a simple example in the issue header now works.

But when using boost, the problem is not solved:

```
  #include <boost/asio/io_context.hpp>
  #include <boost/asio/ip/tcp.hpp>
...
  boost::system::error_code ec;
  boost::asio::io_context io_context_;
  auto endpoints = boost::asio::ip::tcp::resolver(io_context_).resolve("lg.vie.alwyzon.net", "5201", ec);
  if (ec) {
      printf("Can't resolve, err: %s\n", ec.message().c_str());
  } else {
      printf("Resolve success\n");
  }
  ...
  g++ test.cpp -lpthread
  ...
  Ubuntu 20.04 LTS, boost-1.71.0
```
I get an error:  Host not found (non-authoritative), try again later.
Previos version (https://github.com/gramineproject/gramine/commit/57b2cb30e7def6e1f34f8875496952b9c1d310ae) didn't have that problem.


I am confused about the boost templates to find the implementation of the resolve method, but if necessary I can provide full details about it.
The trace didn't give any clues about the problem other than this one:

> [P1:T2:gethostbyname] trace: ---- shim_madvise(0x1030e000, 0x3b000, MADV_DONTNEED) = -38

**Comment by boryspoplawski** [comment]
@Villain88 Please check https://github.com/gramineproject/gramine/pull/684. It adds `FIONREAD` support for sockets. The example you posted works for me now.

**Comment by Villain88** [comment]
> @Villain88 Please check #684. It adds `FIONREAD` support for sockets. The example you posted works for me now.

Unfortunately, I was not able to build the version from the branch #684 . I get the error "api_fortified.h:37:25: error: expected declaration specifiers or '...' before '__builtin_object_size'". I tried gсс9, gcc10 and gcc11 compilers

**Comment by boryspoplawski** [comment]
@Villain88 Please clone the repo again - the recent rename we did caused some issues with Meson. I got the same error when I tried to build it in my old setup (even removing meson internal files and build dir didn't help, no idea why) but it works well on a fresh repo.

**Comment by Villain88** [comment]
> @Villain88 Please clone the repo again - the recent rename we did caused some issues with Meson. I got the same error when I tried to build it in my old setup (even removing meson internal files and build dir didn't help, no idea why) but it works well on a fresh repo.

Thanks, after cleaning the repository and rebuilding everything worked
