### ISSUE TITLE
[LibOS] tmpfs: no limit on file size

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#688]
## Description of the problem

Gramine implements `tmpfs` FS type, see https://github.com/gramineproject/gramine/blob/master/libos/src/fs/tmpfs/fs.c.

However, there is no limit on the file size or on the size of the whole `tmpfs` filesystem. The only limits are the natural ones: file size is limited by `int64_t` max representable value, and the size of the whole FS is limited by the size of the SGX enclave (more correctly, by the enclave heap left).

This leads to hard-to-reason-about lines of code like this: https://github.com/gramineproject/gramine/blob/f7eae7eafab97b74023aadf279fb024cff9b8c78/libos/src/fs/tmpfs/fs.c#L79

`mem_size` has no specific limit, so the fact that it doesn't overflow depends purely on the chosen types. (It doesn't overflow because `typeof(mem_size) == int64_t` and `typeof(cp_size) == uint64_t`, on 64-bit systems.)

This is very subtle. If we would have a limit on the file size it would be easier to reason about such code snippets. Also, it feels natural to limit the file sizes on `tmpfs` mounts.

I didn't find if Linux has any cap on individual file sizes on `tmpfs`, but at least it has a limit on the whole `tmpfs` FS. See https://man7.org/linux/man-pages/man5/tmpfs.5.html. This should be also useful -- otherwise the enclave availability can be seriously hampered.

**Comment by mkow** [comment]
I don't see why we should cap them, the reasoning about them is simple - these files are stored in memory, so by definition their size has to fit into `size_t`...

**Comment by lead4good** [comment]
I'm trying to fit a huge amount of data into `tmpfs` (+512GB). Will it suffice to increase `sgx.enclave_size` approprietly or do I also have to increase the size of `loader.pal_internal_mem_size`?

**Comment by boryspoplawski** [comment]
@lead4good `enclave_size` is enough (but `512GB` enclave is prooooobably not something you want to do).
Btw `pal_internal_mem_size` is deprecated as of current master (but it's still there in Gramine v1.3.x, i.e. latest release)

**Comment by lead4good** [comment]
If my understanding is correct, files written to tmpfs will be located in EPC memory. Via paging they might get encrypted and move to non EPC memory. And from there they might move to swap. Is this correct, also for SGX2? If so, can we configure gramine to only use EPC memory?

**Comment by lead4good** [comment]
> but 512GB enclave is prooooobably not something you want to do
Could you elaborate? Will I run into any hard coded limits?

**Comment by boryspoplawski** [comment]
I didn't work with such big enclaves so, but I would expect it to be super slow. On my testing machine (it's rather old, so maybe these numbers are much better for modern CPUs) it takes 3s for the enclave to start, for each 1G of enclave memory, which would make it ~25min of just startup time for 512G. And if your EPC is smaller that this (and I guess it is :) ) you would have to add swapping to non-EPC memory, which will make it much worse.

summon @dimakuv please validate what I said :) and maybe elaborate some more

**Comment by dimakuv** [comment]
What @boryspoplawski said is correct.

There are no issues (to the best of my knowledge) with running Gramine with `sgx.enclave_size = "512G"`. On the other hand, I've only seen people running 128GB workloads at a maximum -- on Icelake servers the performance and startup times are decent.

The performance in the end really depends on:
- whether you can tolerate slow startup times, because all 512GB of enclave pages must be EADDed;
- what size of EPC you have on your machine, and what amount of physical RAM you have (if you have both > 512GB, then you shouldn't notice any significant performance drops);
- your NUMA behavior of the application; without SGX v2 and EDMM, all enclave pages are added on a single NUMA node, and accesses from another NUMA node inevitably are slow.

All in all, there are no hard limits. Well, there is a hard limit on the enclave size (`MaxEnclaveSize_64` in CPUID leaf `0x12`), but this limit depends on the CPU, and typically on modern CPUs it is higher than 4TB.

---

> If my understanding is correct, files written to tmpfs will be located in EPC memory. Via paging they might get encrypted and move to non EPC memory. And from there they might move to swap. Is this correct, also for SGX2?

Yes, this understanding is correct.

> If so, can we configure gramine to only use EPC memory?

No, this is not possible. Not at the level of ring-3 software (which Gramine is). This could be done only at the level of the SGX driver inside the Linux kernel, but I haven't seen any such knobs. AFAIK, there is no way to disable swapping.

**Comment by lead4good** [comment]
I've done a test run with a 256GB enclave on a server with 256GB EPC, filling tmpfs with 125GB of files, this has worked without issues. Startup time is noticable, but less than a minute, so not an issue. On this same machine I have now started a 1TB enclave that will fill tmpfs with ~700GB of data. It will page both to non EPC memory as well as swap, lets see if that still works. My guess is that paging to non EPC memory should still be faster or comparable to disk io?

> No, this is not possible.

Interesting. It might become necessary for future implementations. Ethereum mainnet has a ~700GB database which the client wants to access from SGX without leaking any io access information to the host.

**Comment by dimakuv** [comment]
> My guess is that paging to non EPC memory should still be faster or comparable to disk io?

Yes, paging EPC -> RAM is typically faster than swapping RAM -> disk.

**Comment by lead4good** [comment]
Going back to the main topic of this issue. I think it would make sense to require a size definition for each tmpfs mount. [Linux does so as well](https://www.kernel.org/doc/Documentation/filesystems/tmpfs.txt) :

> size:      The limit of allocated bytes for this tmpfs instance. The 
>               default is half of your physical RAM without swap.

Also, with my first try I did run out of memory. I knew that it was likely due to tmpfs - however, the `Out-of-memory in library OS` error might be confusing for others. Here a tmpfs limit could also help.

**Comment by lead4good** [comment]
So running a 1TB memory SGX enclave on a server with 256GB EPC works very well. I did however run into `pal/src/slab.c:69:        log_error("*** Out-of-memory in PAL (try increasing 'loader.pal_internal_mem_size') ***");` and had to increase it. @boryspoplawski If `pal_internal_mem_size` is going to be deprecated, will it then be dynamically allocated? Otherwise, if it will stay static gramine might segfault for 512GB and 1TB memory loads.

**Comment by boryspoplawski** [comment]
> If pal_internal_mem_size is going to be deprecated

It already is (on the current master)

> will it then be dynamically allocated? 

What will be dynamically allocated?

**Comment by dimakuv** [comment]
I guess what @lead4good is asking is:

> Is "PAL internal memory" automatically expanded, or is this PAL internal memory hard-coded to some fixed value?

If this is the question, then it's the former: PAL internal memory is automatically allocated as requested by Gramine/application needs. So you don't need to worry about it. There is no limit on PAL internal memory now (on the latest master, and thus on the upcoming Gramine v1.4).

The only limit on memory allocations (**any** memory allocations) in Gramine v1.4 will be `sgx.enclave_size`.

**Comment by dimakuv** [comment]
Based on this comment from @mkow:

> I don't see why we should cap them, the reasoning about them is simple - these files are stored in memory, so by definition their size has to fit into `size_t`...

I'm closing this issue.
