### ISSUE TITLE
`handle.file.map_start` is unused

### ISSUE THREAD

**Issue by kailun-qin** [gramineproject/gramine#694]
## Description of the problem
`handle.file.map_start` initially introduced for fork emulation in https://github.com/gramineproject/graphene/commit/b8031c4224021f3943a87093f40c91ce4e431f34 was removed by https://github.com/gramineproject/gramine/commit/a95c063436053b218904d9da7e3e4dcaf4177397. It's not used any more so that we can remove it.

## Gramine commit hash
ecca6b5567981626f5874a99594634754b691823

**Comment by boryspoplawski** [comment]
Please do not create issues if you submit a PR fixing them at the very same time, the PR is enough :)

**Comment by kailun-qin** [comment]
> Please do not create issues if you submit a PR fixing them at the very same time, the PR is enough :)

Gotcha, thanks borys! (it was just from my team's ask ;))

**Comment by dimakuv** [comment]
Yes, please don't create issues if you already have a PR ready.

By the way, in this issue you have useful information: links to the actual commits. This kind of useful information should also go into PR descriptions. I copied this info there (in #695), but please do it in the future. The more information the PR contains, the better -- nobody wants to traverse a list of PRs and issues to get the full picture.

**Comment by kailun-qin** [comment]
> Yes, please don't create issues if you already have a PR ready.
> 
> By the way, in this issue you have useful information: links to the actual commits. This kind of useful information should also go into PR descriptions. I copied this info there (in #695), but please do it in the future. The more information the PR contains, the better -- nobody wants to traverse a list of PRs and issues to get the full picture.

Well noted, thanks!
