### ISSUE TITLE
Simplify file_getname, same for dir_getname in PALs

### ISSUE THREAD

**Issue by billionairiam** [gramineproject/gramine#705]
## Description of the problem
The function [static int file_getname(PAL_HANDLE handle, char* buffer, size_t count)](https://github.com/gramineproject/gramine/blob/bb7769a1c48cd6c39c009abc695f3db2f6985aba/pal/src/host/linux/db_files.c#L271)  

1. The function first copy [URI_PREFIX_FILE](https://github.com/gramineproject/gramine/blob/bb7769a1c48cd6c39c009abc695f3db2f6985aba/common/include/api.h#L403)  into `buffer` 
2. Then copy `handle->file.realpath` into` buffer` (after` URI_PREFIX_FILE` string)

The problem with this code is that it is very obscure. Mostly because of this weird [function:](https://github.com/gramineproject/gramine/blob/5a39aee217955701b412d4ff807c32da8e53ab94/common/include/api.h#L277)

In reality, we can just use the [alloc_concat()](https://github.com/gramineproject/gramine/blob/bb7769a1c48cd6c39c009abc695f3db2f6985aba/common/include/api.h#L266)
 function instead of all that code.

**Comment by dimakuv** [comment]
This is a very obscure description of the issue.

What is this numbered list at the very beginning? Which lines of code it describes? It would be better to give a link to the code snippet to which this description belongs.

Also, please use proper Markdown formatting. In particular, put variable names, function names, code quotes in backticks.

Finally, do not keep `Steps to reproduce`, `Expected results` in GitHub issues like this one. Just remove these section names. They only clutter the issue and make it harder to read.

**Comment by dimakuv** [comment]
@boryspoplawski I think this is just a misunderstanding. I guess @billionairiam is used to another style of development, where all tasks are first created as issues and then resolved with patches/PRs (looking at Jira...).

In our core Gramine development, we don't spend time on creating small issues if we want to fix them right away. We simply submit a PR, with all descriptions in the PR text body.
