### ISSUE TITLE
Allocating stack log error

### ISSUE THREAD

**Issue by billionairiam** [gramineproject/gramine#706]
## Description of the problem
At the start, Gramine often outputs allocating stack at 0x0

**Comment by dimakuv** [comment]
There is no need to create one-line GitHub issues.

If you're describing some issue/bug/missing functionality, please provide a better, more detailed description and some initial analysis. If you're describing it just for the sake of accountability, please don't do it. Just submit a PR that fixes it immediately. (Or submit a GitHub issue later, when you did some analysis on it and ready to share some results.)
