### ISSUE TITLE
PAL testcase `send_handle` failing on docker

### ISSUE THREAD

**Issue by aniket-intelx** [gramineproject/gramine#708]
## Description of the problem
The PAL testcase `test_pal.TC_23_SendHandle.test_000_send_handle` is failing on docker for both `gramine-direct` and `gramine-sgx` with the commit `[LibOS,Pal] Completely rewrite networking code`. However, it works fine when tried on baremetal. 
We checked with a commit prior to this and it executes successfully.
## Steps to reproduce

Run either of the below command
`gramine-sgx send_handle`
`gramine-direct send_handle`
## Actual results

```
Error at DkSocketBind(handle, &addr) (line 134): -22
Error at DkReceiveHandle(DkGetPalPublicState()->parent_process, &handle) (line 170): -18
```
## Gramine commit hash

Please find the attached error logs.
[PAL_send_handle_gramine-direct.txt](https://github.com/gramineproject/gramine/files/9019116/PAL_send_handle_gramine-direct.txt)
[PAL_send_handle_SGX_fail_log.txt](https://github.com/gramineproject/gramine/files/9019118/PAL_send_handle_SGX_fail_log.txt)

**Comment by boryspoplawski** [comment]
What you need to do is enabled ipv6 in your docker configuration.
