### ISSUE TITLE
Testing Numpy returns memory fault with Gramine when numpy installed using pip3 for ubuntu 18.04

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#739]
## Description of the problem
When numpy is installed using pip for ubuntu 18.04, it fails with memory fault error

**The installation location of numpy gets changed when it is installed using apt or pip. After updating the new installation path of numpy in manifest.template, it failed with error "No module named 'numpy'".** 

From the previous issue analysis, [559](https://github.com/gramineproject/gramine/issues/559)  i added **loader.insecure__use_host_env = true** and then it tried to load the numpy, and then it fails with memory fault.

**Why  I am installing numpy using pip3?**
I have to test 2 examples, numpy and pytorch with Gramine
If numpy is installed using apt then it is installed in **/usr/lib/python3/dist-packages** but for pytorch we need to install torchvision and numpy is a dependency for torchvision. 

The torchvision has to be installed by pip3, and it is installed in **/intel/.local/lib/python3.6/site-packages/** and it also moves numpy from dist-packages to site-packages.

## Steps to reproduce

1. Create a fresh ubuntu 18.04 container
2. Install numpy using pip3 (python3 -m pip install numpy)
3. Update the numpy path in manifest.template (pip3 show numpy)
4. Run gramine-sgx ./python scripts/test-numpy.py

## Expected results
```
numpy version: 1.19.5
numpy.dot: 0.017041180189698933 sec
```

## Actual results
`[P1:T4:python3.6] debug: memory fault at 0x00000000 (IP = 0x00000000)`

Trusted file list and same path is also mounted in fs
```
sgx.trusted_files = [
  "file:{{ gramine.libos }}",
  "file:{{ entrypoint }}",
  "file:{{ gramine.runtimedir() }}/",
  "file:{{ arch_libdir }}/",
  "file:/usr/{{ arch_libdir }}/",
  "file:{{ python.stdlib }}/",
  "file:{{ python.distlib }}/",
  "file:scripts/",
  "file:/intel/.local/lib/python3.6/site-packages/",
  "file:/etc/mime.types",
  "file:/etc/default/apport",
]
```

[numpy_memory_fault.log](https://github.com/gramineproject/gramine/files/9083195/numpy_memory_fault.log)

**Comment by dimakuv** [comment]
Interesting memory-fault bug. Any volunteers to look into it?

**Comment by boryspoplawski** [comment]
> Interesting memory-fault bug

It's fault inside user app (python), not Gramine (just making sure it's clear)

**Comment by anjalirai-intel** [comment]
No, the fault is inside Gramine not inside app, app works fine

**Comment by boryspoplawski** [comment]
No, the NULL pointer dereference happens in app.

**Comment by anjalirai-intel** [comment]
But, if i run this test without Gramine, it works fine

**Comment by dimakuv** [comment]
@anjalirai-intel Your bug report is correct. There is surely something going fishy in Gramine.

What @boryspoplawski mentioned is simply a fact that the segfault happens during app execution, not during internal Gramine execution (that may be important to keep in mind for a person who will debug this issue).

**Comment by lejunzhu** [comment]
From the log: return from shim_mmap(...) = -12, 12 means ENOMEM. Maybe you can try increase sgx.enclave_size in the manifest to some larger value, e.g. "8G". Also you may set sgx.thread_num = 256 if you are using a Xeon server.
If that works, maybe you can look at how many threads numpy tries to start, and how to limit the number.

**Comment by anjalirai-intel** [comment]
I tried with enclave size as 2GB and thread count as 64. it worked. I am closing the issue. Thank you @lejunzhu @dimakuv @boryspoplawski for your time
