### ISSUE TITLE
Registers used in sgx_report are not protected?

### ISSUE THREAD

**Issue by kvinwang** [gramineproject/gramine#759]
In the [original implementation](https://github.com/gramineproject/gramine/commit/83840d6c47150920230f6d727fc3eeb13f2b7c5f) of sgx_report/sgx_getkey, we protected the registers with `push` instructions:
```asm
sgx_report:
	.cfi_startproc

	pushq %rbx
	pushq %rcx
	movq %rdi, %rbx
	movq %rsi, %rcx
	movq $EREPORT, %rax
	ENCLU
	popq %rcx
	popq %rbx
	retq

	.cfi_endproc
	.size sgx_report, .-sgx_report
```

However in the [latest code](https://github.com/gramineproject/gramine/blob/master/pal/src/host/linux-sgx/enclave_api.S#L9-L24), the `pushq %rbx` and `pushq %rcx` gone, is this on purpose or a bug?

```asm
sgx_report:
    .cfi_startproc
    # int sgx_report(const sgx_target_info_t* targetinfo, const void* reportdata,
    #                sgx_report_t* report);

    movq %rbx, %r10
    .cfi_register %rbx, %r10

    # EAX = EREPORT
    # RBX = targetinfo
    # RCX = reportdata
    # RDX = report (already set)
    movl $EREPORT, %eax
    movq %rdi, %rbx
    movq %rsi, %rcx

    ENCLU
```

**Comment by kailun-qin** [comment]
IMO, in the latest code, RBX is saved on entry and restored afterwards while RCX is callee-owned/considered volatile (thus no need to be preserved) according to the x86-64 calling convention. Though other arch may specify it a bit differently, Gramine is primarily focus on x86-64 at this moment so it looks fine.

I'll let the Gramine team to elaborate further.

**Comment by kvinwang** [comment]
> RBX is saved on entry and restored afterwards while RCX is callee-owned/considered volatile (thus no need to be preserved) according to the x86-64 calling convention

I am not familiar with the calling convention. However, I searched and find it from [Wikipedia](https://en.wikipedia.org/wiki/X86_calling_conventions). It seems the `R10` and `RCX` is considered volatile only in `ms_abi`. Does it also apply to `sysv_abi`? Or does gramine always compiled with `ms_abi`?

**Comment by kailun-qin** [comment]
Yes, it should also apply to `sysv_abi`.

Just from the Wiki page that you pointed to, there is one line in the `System V AMD64 ABI` section:
> If the callee wishes to use registers RBX, RSP, RBP, and R12–R15, it must restore their original values before returning control to the caller. All other registers must be saved by the caller if it wishes to preserve their values.

It's also stated in the pg.23 of [SysV ABI spec](https://github.com/hjl-tools/x86-psABI/wiki/x86-64-psABI-1.0.pdf).

**Comment by dimakuv** [comment]
@kvinwang Kailun said everything correctly. Let me also explain, just for someone from "the Gramine team to elaborate further".

1. The source code for `sgx_report()` is the file `pal/src/host/linux-sgx/enclave_api.S`. So, we are in the component that uses Linux and works on Intel SGX. This limits us to the Intel implementation of the x86-64 architecture and to the Linux calling conventions (aka System V AMD64 ABI). So yes, when we look at this code, we also think `x86_64` and `sysv_abi`.

2. Now, the function `sgx_report()` calls the `EREPORT` instruction, that expects its arguments in registers `RAX`, `RBX`, `RCX` and `RDX`. If we look at the `sysv_abi` list of registers (here is a quick ref: https://stackoverflow.com/a/18024743/6325371), then we see that `RAX`, `RCX` and `RDX` have "no" in `Preserved across function calls`, which means that the caller (whoever calls `sgx_report()`) must save these registers before calling `sgx_report()` and restore these registers after calling `sgx_report()`. On the other hand, `RBX` has "yes" in `Preserved across function calls`, which means that the callee (= `sgx_report()` function itself) must save the register before modifying it and restore this register before `ret`.

We can see that the `RBX` register is indeed saved (not on the stack, but simply in the `R10` register which is unused by this function): https://github.com/gramineproject/gramine/blob/e5cbd1518d882844eb62dffaa1f1f10511fd40da/pal/src/host/linux-sgx/enclave_api.S#L14

And the `RBX` register is restored right-before returning from the function: https://github.com/gramineproject/gramine/blob/e5cbd1518d882844eb62dffaa1f1f10511fd40da/pal/src/host/linux-sgx/enclave_api.S#L30

Hope this explains it.

**Comment by kvinwang** [comment]
Great explaination. Thanks @dimakuv and @kailun-qin  so much!
