### ISSUE TITLE
SSL/TLS handshake failed for ra-tls-mbedtls example

### ISSUE THREAD

**Issue by akumar2709** [gramineproject/gramine#760]
While trying to run the ra-tls-mbedtls example, I get the following message when I run ./client dcap(I have provided MRENCLAVE, MRSIGNER etc). 

[ using default SGX-measurement verification callback (via RA_TLS_* environment variables) ]

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Installing RA-TLS callback ... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -0x3000

Last error was: -12288 - X509 - A fatal error occurred, eg the chain is too long or the vrfy callback failed

**Comment by kailun-qin** [comment]
Would you please kindly:
1) provide the commit hash of Gramine that you're working on?
2) verify your SGX PSW + DCAP SW stack is installed correctly (e.g., by following [DACP install guide]( https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html)) and can work properly in your env?
3) double check the other env factors (e.g if you're running w/ proxy) that may cause the handshake failure.

Thanks!

**Comment by kailun-qin** [comment]
Hi @akumar2709!

Would just like to follow up - has your issue been resolved? Thanks!

**Comment by dimakuv** [comment]
Let me close this issue, since the author is inactive.
