### ISSUE TITLE
server script gives me an error SO_REUSEPORT using GRPC

### ISSUE THREAD

**Issue by gus6202** [gramineproject/gramine#763]
## Description of the problem
Hello, 
I'm trying to run my server program (GRPC) using gramine-sgx but it gives me this error: 
```
~/Desktop/gramine/CI-Examples/python$ gramine-sgx python scripts/_sgx/server.py 
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

E0717 22:00:46.201856000       1 socket_utils_common_posix.cc:223] check for SO_REUSEPORT: {"created":"@1658095246.201781000",
/"description":"Protocol not available","errno":92,"file":"src/core/lib/iomgr
/socket_utils_common_posix.cc","file_line":202,"os_error":"Protocol not available","syscall":"getsockopt(SO_REUSEPORT)"}
```
Still, the server goes up and can communicate with client sending messages to the client and vice versa. The only problem here is that it doesn't show what the client is sending to the server (doesn't print any messages sent from the client).
PS: Using gramine-direct shows the same issue.

**Comment by kailun-qin** [comment]
`SO_REUSEPORT` is not supported by Gramine at this moment (and no plan to implement it based on a previous discussion as far as I recall). We would expect the workload to fallback to other alternatives when it finds out the flag is not supported.

BTW, would you pls kindly also:
1) provide the commit hash of Gramine that you're working on?
2) clarify/elaborate on whether the C<->S communication (sending/receiving) is working or it's just a no show of `print`?

Thanks!

**Comment by dimakuv** [comment]
@gus6202 Could you check this discussion: https://github.com/gramineproject/gramine/issues/361 ? It provides some explanations on what could be done with gRPC. Hopefully it helps.

**Comment by gus6202** [comment]
> 

Hey, I only managed to hide the error message (I added ```loader.env.GRPC_VERBOSITY="NONE"``` in my python.manifest.template file), but the main problem (print something in server.py or print messages received from the client) I couldn't do it.

**Comment by lejunzhu** [comment]
The server.py script actually works correctly, but its output is buffered by Gramine. Add 'flush=True' to the print() calls in server.py, and you will see all the output.

**Comment by mkow** [comment]
Should be fixed by https://github.com/gramineproject/gramine/pull/1031, which was just merged. If not, feel free to reopen.
