### ISSUE TITLE
I can not run any python-example.

### ISSUE THREAD

**Issue by Yang-yyf** [gramineproject/gramine#765]
### Question
I used this command to run python.
``` bash
make SGX=1
SGX=1 ./run-tests.sh
```
And I got this.
``` bash
Running helloworld.py:
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Cannot parse 'sgx.remote_attestation' (the value must be `true` or `false`)
error: Parsing manifest failed
error: load_enclave() failed with error -22


Running HTTP server dummy-web-server.py in the background:
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Cannot parse 'sgx.remote_attestation' (the value must be `true` or `false`)
error: Parsing manifest failed
error: load_enclave() failed with error -22
```
I checked the "python.manifest.sgx".I found that "sgx.remote_attestation" is "none".I trust there is some errors.
What is more? I overwrited the "sgx.remote_attestation" to be false.
And I got:
```bash
error: Detected EPID remote attestation parameters 'ra_client_spid' and/or 'ra_client_linkable' in the manifest but no 'remote_attestation' parameter. Please add 'sgx.remote_attestation = true' to the manifest.
error: Parsing manifest failed
error: load_enclave() failed with error -22
```
Can anyone help me ?
I can run helloworld.c,It is good.

**Comment by dimakuv** [comment]
You seem to have installed Gramine v1.2 package (via `apt install`).

But you seem to use the incompatible version of the Python example. Please use the `v1.2` branch of the git-cloned repository.

Reason: the latest Gramine switched from `sgx.remote_attestation = true|false` to `sgx.remote_attestation = "none"|"epid"|"dcap"`. So please switch to `v1.2` in the example and check the README carefully: https://github.com/gramineproject/gramine/tree/v1.2/CI-Examples/python

**Comment by Yang-yyf** [comment]
> 您似乎已经安装了 Gramine v1.2 软件包（通过`apt install`）。
> 
> 但是您似乎使用了不兼容的 Python 示例版本。请使用`v1.2`git 克隆存储库的分支。
> 
> `sgx.remote_attestation = true|false`原因：最新的Gramine 从`sgx.remote_attestation = "none"|"epid"|"dcap"`. 所以请切换到`v1.2`示例中并仔细检查自述文件：[https ://github.com/gramineproject/gramine/tree/v1.2/CI-Examples/python](https://github.com/gramineproject/gramine/tree/v1.2/CI-Examples/python)

II checked the code in the sample and found that it was indeed version 1.2. Then I used apt-show-versions to check the gramine software in the system and it was indeed version 1.2-1.

But after reading your reply, I think there is one place where the gramine used is a low version, which leads to the example not running successfully. But what else is possible besides the powercode and gramine system installed?

**Comment by llly** [comment]
You can use `git clone --depth 1 https://github.com/gramineproject/gramine.git -b v1.2` to clone version 1.2.

**Comment by Yang-yyf** [comment]
> You can use `git clone --depth 1 https://github.com/gramineproject/gramine.git -b v1.2` to clone version 1.2.

Thanks for your reply. I have cloned this project.
But I checked the file "python.manifest.sgx",the keyword"ra_ramote_attestation" should be "true|flase" or "none|dcap|epid".

**Comment by Yang-yyf** [comment]
Finally, with the sample code for the Clone1.2 version, the original error disappeared. But there were new mistakes, and I was confused and lost.
```bash
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: aesm_service returned error: 1
error: load_enclave() failed with error -1
```

**Comment by Yang-yyf** [comment]
> You can use `git clone --depth 1 https://github.com/gramineproject/gramine.git -b v1.2` to clone version 1.2.

I cloned it,and I run make SGX=1,I checked the file "python.manifest.sgx", the keyword "ra_ramote_attestation" is true. It should be "none",right?

**Comment by Yang-yyf** [comment]
New Question!

It seems that the asem service met some problem.
```bash
error: aesm_service returned error: 1
error: load_enclave() failed with error -1
```

**Comment by Yang-yyf** [comment]
> is-sgx-available

aya,here is the result!
```bash
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): true
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): false
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): false
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): true
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x100000000000000
EPC size: 0x3e0000000
SGX driver loaded: true
AESMD installed: true
SGX PSW/libsgx installed: true
```

**Comment by llly** [comment]
It's FLC(Flexible Launch Control) platform. You can enable SGX DCAP attestation following
https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html

**Comment by Yang-yyf** [comment]
> It's FLC(Flexible Launch Control) platform. You can enable SGX DCAP attestation following https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html

Thank u，I am trying to ignore the attestation,so I changed it.
```bash
remote_attestation = false
ra_client_spid = ""
ra_client_linkable = false
```
But It seems not work.And I got error.
```bash
error: Detected EPID remote attestation parameters 'ra_client_spid' and/or 'ra_client_linkable' in the manifest but no 'remote_attestation' parameter. Please add 'sgx.remote_attestation = true' to the manifest.
error: Parsing manifest failed
error: load_enclave() failed with error -22
```
What should I do to the other two keywords?

**Comment by llly** [comment]
Remove the two lines `ra_client_spid = ""` and `ra_client_linkable = false`.

**Comment by Yang-yyf** [comment]
> Remove the two lines `ra_client_spid = ""` and `ra_client_linkable = false`.

I tried to remove it.But I got this.
```bash
error: Initializing enclave failed: -1
error: load_enclave() failed with error -1
```
I'm so sad.

**Comment by llly** [comment]
If helloworld example can work, this python example should work too. Try make clean and make again.

**Comment by Yang-yyf** [comment]
> If helloworld example can work, this python example should work too. Try make clean and make again.

In helloworld example, here is my steps.
```bash
make SGX=1
gramine-sgx helloword

-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

Hello, world
```
And with the python-helloworld example.
```bash
make clean
make SGX=1
vim python.manifest.sgx
Delete Two Lines,And Change remote_attestation to be false.
gramine-sgx ./python ./scripts/helloworld.py

Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Initializing enclave failed: -1
error: load_enclave() failed with error -1
```

Puzzle.

**Comment by dimakuv** [comment]
@Yang-yyf You're not supposed to touch `*.manifest.sgx` files. You should always modify the `*.manifest.template` files.

So please try again:
1. Modify the `python.manifest.template` file.
2. Run `make clean`.
3. Run `make SGX=1`.
4. Try `gramine-sgx ./python ...` now.

**Comment by Yang-yyf** [comment]
> If helloworld example can work, this python example should work too. Try make clean and make again.

Thanks for your help!
I think I found the problems.
I should edit the python.manifest.templet instead of the python.manifest.sgx!

**Comment by Yang-yyf** [comment]
> @Yang-yyf You're not supposed to touch `*.manifest.sgx` files. You should always modify the `*.manifest.template` files.
> 
> So please try again:
> 
> 1. Modify the `python.manifest.template` file.
> 2. Run `make clean`.
> 3. Run `make SGX=1`.
> 4. Try `gramine-sgx ./python ...` now.

Yes, I made a mistake!
Now I am going to install the DCAP, I still need the remote_attestation to be true.
Thanks for you all!

**Comment by Yang-yyf** [comment]
> ```shell
> remote_attestation = false
> ```

Can dcap be installed into kernel 5.11.10-051110-generic (x86_64)?

**Comment by dimakuv** [comment]
Yes, it can.
