### ISSUE TITLE
Apt-get update fails due to expired certificate

### ISSUE THREAD

**Issue by bacox** [gramineproject/gramine#785]
## Description of the problem
I am trying to quick install Gramine OS on a machine with following specifications.

> Operating System: Ubuntu 20.04.4 LTS
> Kernel: Linux 5.14.0-1045-oem
> Architecture: x86-64

`apt-update` gives to following error:
```
Err:18 https://packages.gramineproject.io stable Release                                                                                                                                                                                     
  Certificate verification failed: The certificate is NOT trusted. The certificate chain uses expired certificate.  Could not handshake: Error in the certificate verification. [IP: 5.255.91.88 443]

E: The repository 'https://packages.gramineproject.io stable Release' no longer has a Release file.
```
Also the url `https://packages.gramineproject.io/` gives an expired certificate warning in my browser.
Certificate expiration data:

> Issued On	Sunday, April 24, 2022 at 2:25:38 AM
> Expires On	Saturday, July 23, 2022 at 2:25:37 AM

For me, the workaround for now is to disable gramine from apt until the certificate is updated (I only needed a working apt-update). 
However, I think other people might not able to install gramine at the moment due to the expired certificate.

**Comment by boryspoplawski** [comment]
Actually, should be resolved now, @bacox  please verify

**Comment by bacox** [comment]
Wonderful! It is working now
