### ISSUE TITLE
"/home/usr/.config/gramine/enclave-key.pem" does not exist while Executing PyTorch with Gramine in SGX Enclave

### ISSUE THREAD

**Issue by PoojaPrasd** [gramineproject/gramine#803]
## Description of the problem

I am following the steps in PyTorch PPML Framework Tutorial.
In section 'Executing PyTorch with Gramine in SGX Enclave', while executing make SGX=1, I am getting the following error

Invalid value for "--key" / "-k": File "/home/usr/.config/gramine/enclave-key.pem" does not exist.

## Steps to reproduce
git clone https://github.com/gramineproject/examples.git
cd examples/pytorch
make SGX=1

## Expected results
No error

## Actual results
gramine-sgx-sign \
	--manifest pytorch.manifest \
	--output pytorch.manifest.sgx
Usage: gramine-sgx-sign [OPTIONS]
Try "gramine-sgx-sign --help" for help.

Error: Invalid value for "--key" / "-k": File "/home/usr/.config/gramine/enclave-key.pem" does not exist.
make: *** [Makefile:36: sgx_sign] Error 2

**Comment by boryspoplawski** [comment]
https://gramine.readthedocs.io/en/stable/quickstart.html#prepare-a-signing-key

**Comment by PoojaPrasd** [comment]
After resolving the above error, now getting runtime memory error when executing 
gramine-sgx ./pytorch pytorchexample.py

RuntimeError: [enforce fail at alloc_cpu.cpp:73] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 150994944 bytes. Error code 12 (Cannot allocate memory)

**Comment by dimakuv** [comment]
Please try to increase the enclave size (and maybe you'll need to increase the number of enclave threads as well).

See this for an example: https://github.com/gramineproject/examples/pull/38/files

**Comment by imtypist** [comment]
> Please try to increase the enclave size (and maybe you'll need to increase the number of enclave threads as well).
> 
> See this for an example: https://github.com/gramineproject/examples/pull/38/files

Thank you! It works for me :)
