### ISSUE TITLE
Some file cannot be loaded into Gramine,but I have added it's path to "sgx.mounts" and "sgx.trusted_files".

### ISSUE THREAD

**Issue by Yang-yyf** [gramineproject/gramine#806]
As you see, my manifest.template is:
```bash

loader.entrypoint = "file:{{ gramine.libos }}"
libos.entrypoint = "helloworld"
loader.log_level = "{{ log_level }}"
loader.argv0_override = "helloworld"

loader.env.LD_LIBRARY_PATH = "/lib"

fs.mounts = [
  { path = "/lib", uri = "file:{{ gramine.runtimedir() }}" },
  { path = "/usr/lib/x86_64-linux-gnu/", uri = "file:/usr/lib/x86_64-linux-gnu/" },
]

sgx.debug = true
sgx.nonpie_binary = true

sgx.trusted_files = [
  "file:{{ gramine.libos }}",
  "file:helloworld",
  "file:{{ gramine.runtimedir() }}/",
  "file:/usr/lib/x86_64-linux-gnu/"
]
~
```
When I run this progrem without gramine, It looks well. But with gramine.
```bash
helloworld: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

**Comment by Yang-yyf** [comment]
I removed the code:
```C++
#include<iostream>
using namespace std
```
And It seems ok,but I need this "include".

**Comment by dimakuv** [comment]
I think that's because you don't have the directory `/usr/lib/x86_64-linux-gnu/` in `LD_LIBRARY_PATH`. See this example: https://github.com/gramineproject/gramine/blob/5b6f6db983a9ec23cf94408f5941eaaaea9a4d41/libos/test/regression/bootstrap_cpp.manifest.template#L5

Basically, replace your current `LD_LIBRARY_PATH` line with this:
```
loader.env.LD_LIBRARY_PATH = "/lib:/lib/x86_64-linux-gnu/:/usr//lib/x86_64-linux-gnu/"
```

**Comment by Yang-yyf** [comment]
I made a similar attempt before, and apparently my grammar was wrong. Now that the problem is solved, I take the initiative to close the issues.
Thank you!
