### ISSUE TITLE
Move to or add ECDHE-based key exchange support for secure channel establishment

### ISSUE THREAD

**Issue by kailun-qin** [gramineproject/gramine#817]
Currently Gramine is using the DHE-based key exchange (fixed to 3072 bit prime order multiplicative groups) plus the combination w/ SGX local attestation (for authentication) to establish secure channels between the parent and child enclaves.

Since DHE is considerably slower than ECDHE (and the performance penalty for DHE increases a lot more when increasing the number of bits), it may be better if we can move to/add ECDHE-based key exchange support for secure channel establishment. With a well-configured/selected curve, we should be able to gain comparatively more benefits.

Pls kindly find a reference benchmark below (testbed: Intel i9-9980HK@2.40GHz CPU, 64GB memory):
```
DHE-2048                 :     112 handshake/s
DHE-3072                 :      36 handshake/s

ECDHE-secp521r1          :      45 handshake/s
ECDHE-brainpoolP512r1    :      47 handshake/s
ECDHE-secp384r1          :     102 handshake/s
ECDHE-brainpoolP384r1    :     102 handshake/s
ECDHE-secp256r1          :     228 handshake/s
ECDHE-brainpoolP256r1    :     200 handshake/s
ECDHE-x25519             :     606 handshake/s
ECDHE-x448               :     254 handshake/s

/* ECDHE full handshake data - not comparable, just for ref. */
ECDHE-secp521r1          :      28 full handshake/s
ECDHE-brainpoolP512r1    :      29 full handshake/s
ECDHE-secp384r1          :      63 full handshake/s
ECDHE-brainpoolP384r1    :      62 full handshake/s
ECDHE-secp256r1          :     143 full handshake/s
ECDHE-brainpoolP256r1    :     125 full handshake/s
ECDHE-x25519             :     451 full handshake/s
ECDHE-x448               :     190 full handshake/s
```

**Comment by dimakuv** [comment]
This is an interesting proposal, but I would say this has very low priority for now.

First of all, we got an approval from an internal audit on Gramine that our DHE-based scheme was ok from the security perspective. I guess we'll need to get a new approval if we switch to ECDHE.

Second of all, the handshake between the parent and the child enclaves is a rare event. So I see no point in optimizing the performance of a rare event -- noone will ever notice this in real-world usage.

**Comment by kailun-qin** [comment]
OK, as it's very low priority, I'll close it for now.
