### ISSUE TITLE
/proc/meminfo returns host size

### ISSUE THREAD

**Issue by aep** [gramineproject/gramine#821]
libos/src/fs/proc/info.c  proc_meminfo_load
```
-- 38         { "MemTotal:      %8lu kB\n", g_pal_public_state->mem_total / 1024 },
```

this seems off. the enclave does not have access to this amount of memory.
shouldnt this be the value set in the manifest instead?

**Comment by boryspoplawski** [comment]
> this seems off. the enclave does not have access to this amount of memory.

What makes you think so? This is literally enclave size (minus some internal stuff).

**Comment by aep** [comment]
> No, it does not.

its 16GB for @klassiker , with a 16GB host, and enclave size 1GB.

> What makes you think so


https://github.com/gramineproject/gramine/blob/efdecf179fca5d9e99b0e19b0a9748ce1de1f0e4/pal/src/pal_main.c#L541

https://github.com/gramineproject/gramine/blob/efdecf179fca5d9e99b0e19b0a9748ce1de1f0e4/pal/src/host/linux/pal_memory.c#L148

**Comment by boryspoplawski** [comment]
> its 16GB for @klassiker , with a 16GB host, and enclave size 1GB.

This makes no sense.

You linked Linux PAL, not SGX. This is the correct file:
https://github.com/gramineproject/gramine/blob/efdecf179fca5d9e99b0e19b0a9748ce1de1f0e4/pal/src/host/linux-sgx/pal_memory.c#L89

I've also verified, it works correctly.

**Comment by aep** [comment]
hmm. i'll debug it further. maybe its a specific misinterpretation of proc meminfo inside gamine by that software

**Comment by aep** [comment]
the offending code is actually reading /proc/self/mem

https://github.com/mongodb/mongo/blob/0b7b26390896197c0cb4f31affcda7dc19dda85f/src/mongo/util/processinfo_linux.cpp#L77

**Comment by boryspoplawski** [comment]
1. You've linked `/proc/[pid]/stat`, not `mem`.
2. Neither `stat` nor `mem` are emulated in Gramine

**Comment by aep** [comment]
yeah, i have no idea how mongo comes up with these totally off numbers,
but i have confirmed they scale with enclave size so i dont think this is a gramine issue. closing.
