### ISSUE TITLE
Rewrite signal handling in SGX

### ISSUE THREAD

**Issue by chiache** [gramineproject/gramine#83]
The same design change is made for Linux (https://github.com/gramineproject/graphene/pull/281). The SGX PAL is left for future work but should be addressed in near future.

**Comment by dimakuv** [comment]
We should take a look at this after the release. In particular, we may want to test https://github.com/gramineproject/graphene/pull/2649 more and decide whether its simplicity and robustness outweighs its performance degradation.

**Comment by dimakuv** [comment]
Same explanation as for #85. I'm closing this issue.
