### ISSUE TITLE
Unexpected memory fault occurred inside PAL (strnlen at strlen.c)

### ISSUE THREAD

**Issue by Villain88** [gramineproject/gramine#840]
## Description of the problem
I found a very strange bug that is reproduced only by a set of certain steps and using the following gramineproject components:
gsc, encrypted_fs, tracing

## Steps to reproduce

1. Build a container with the following content
```
FROM ubuntu:20.04

RUN mkdir -p /solution/inputs /solution/output /solution/run
RUN apt update \
    && apt install -y libnss-mdns libnss-myhostname lsb-release \
    && apt install -y python3.8 python3-pip libcurl4

ENTRYPOINT ["/usr/bin/python3.8", "/solution/run/entrypoint.py"]
```
2. Graminize image using GSC with option **-d** (debug) and a manifest with the following content:
```
...
fs.mounts = [
  { type = "encrypted", path = "/solution/run", uri = "file:/solution/run", key_name = "default" },
]

fs.insecure__keys.default = "ffeeddccbbaa99887766554433221100"
loader.env.PYTHONDONTWRITEBYTECODE = "1"
loader.env.PYTHONUSERBASE = "/solution/run/pypi"
...
```

3. Take an example of pytorch from [here](https://github.com/gramineproject/examples/tree/master/pytorch)

4. Go to the directory with pytorch and do something like the following:

```
mv pytorchexample.py entrypoint.py
export PYTHONUSERBASE=$PWD/pypi
pip3 install --user --ignore-installed torchvision pillow
python3 download-pretrained-model.py
#encrypt pypi, script and resources
gramine-sgx-pf-crypt encrypt -w <KEY_ffeeddccbbaa99887766554433221100_FILE> -i <PYTORCH_FOLDER> -o /solution/run
```

5.  Run a graminized container:
```
docker run --rm --device=/dev/sgx_enclave -v /dev/sgx:/dev/sgx -v  /solution/run:/solution/run -v /var/run/aesmd/aesm.socket:/var/run/aesmd/aesm.socket -w /solution/run <GRAMINIZED_IMAGE>
```

## Expected results
The calculation results will appear in the encrypted file results.txt
## Actual results
Exception
```
[P1:T1:python3.8] debug: glibc register library /solution/run/pypi/lib/python3.8/site-packages/torch/lib/libtorch_global_deps.so loaded at 0x1c686d000
[P1:T1:python3.8] debug: append_r_debug: adding (null) at 0x1c686d000
error: Unexpected memory fault occurred inside PAL (strnlen at strlen.c, libpal.so+0x2bf31)
debug: (untrusted PAL sent PAL event 0x2)
debug: DkProcessExit: Returning exit code 1
```
If gramanize the image without the option **-d**, then the problem does not appear
If use the described scheme without using GSC, then the problem also does not reproduce, even if you add to the manifest
`loader.log_level = "trace"`

## Gramine commit hash
gsc config:

```
Distro: "ubuntu:20.04"
Gramine:
    Repository: "https://github.com/gramineproject/gramine.git"
    Branch:     "v1.2"
SGXDriver:
    Repository: "https://github.com/intel/SGXDataCenterAttestationPrimitives.git"
    Branch:     "DCAP_1.12 && cp -r driver/linux/* ."
```
_the problem also appears on the latest version from the master_
gsc commit hash **42199be577679703a4312edaec96cc9ea99eaec9**

**Comment by boryspoplawski** [comment]
Hmm, seems that opening a protected file does not set `handle->uri`? I guess that's a good entrypoint for anybody debugging this. https://github.com/gramineproject/gramine/blob/d8217c8ad08fc2be289384b90100e29c0506c097/libos/src/libos_rtld.c#L1037 here `hdl->uri == NULL` on encrypted file.

**Comment by Villain88** [comment]
> @Villain88 Could you check if #841 fixes the issue?
of course, but a little later, I will write the result here

**Comment by Villain88** [comment]
sorry for the long wait
checked both pull requests: #841 and #845. The problem no longer reproduces. Thanks.
