### ISSUE TITLE
[PAL] Host fds from checkpointing are leaked on `fork()`

### ISSUE THREAD

**Issue by boryspoplawski** [gramineproject/gramine#864]
## Description of the problem
When Gramine emulates `fork()` syscall, it spawns another Gramine instance by doing `fork() + execve()` on the host OS. All open file descriptors are supposed to have `O_CLOEXEC` flag set, so that they are all closed - Gramine then sends (via ancillary data on unix domain socket) only those that are required in the child process.
The problem is that these fds don't have `O_CLOEXEC` set as they are received in the child process. Sending fds via ancillary data is lie doing `dup()` - `O_CLOEXEC` is not set on the new fd.

## Steps to reproduce
```c
#define _GNU_SORUCE
#include <stdlib.h>
#include <unistd.h>
#include <sys/wait.h>
#include <stdio.h>
#include <fcntl.h>

#include "common.h"

static void open_fds(int* fds, size_t len) {
    for (size_t i = 0; i < len; i++) {
        fds[i] = CHECK(open("/bin/sh", O_RDONLY));
    }
}

int main(void) {
    setbuf(stdout, NULL);
    setbuf(stderr, NULL);

    /* Get some never-closed fds. */
    int fds[100];
    open_fds(fds, ARRAY_LEN(fds));

    pid_t p = CHECK(fork());
    if (p == 0) {
        while (1) {
            printf("process %d looping\n", getpid());
            p = CHECK(fork());
            if (p != 0) {
                /* parent */
                exit(0);
            }
        }
        return 0;
    }

    while (1) {
        __asm__ volatile ("pause");
    }
    return 0;
}
```

## Expected results
Inf loop without any errors (except for IPC notification, which are unrelated and due to parent exiting).

## Actual results
Processes run out of fds and error out.

## Gramine commit hash
33576d39a844c3ab554d76e150baa3058a97f638

**Comment by dimakuv** [comment]
> The problem is that these fds don't have `O_CLOEXEC` set as they are received in the child process. Sending fds via ancillary data is like doing `dup()` - `O_CLOEXEC` is not set on the new fd.

So the solution is to iterate through the FDs while the child process is receiving them and `fnctl(received-fd, F_SETFD, FD_CLOEXEC)`, and we're done?

**Comment by boryspoplawski** [comment]
Most likely, at least this is the easiest approach (though it would slow checkpointing even more). I'm currently looking at all useges of `CLOEXEC`, will submit a PR soon, I can also fix this in that PR

**Comment by boryspoplawski** [comment]
It turned out to be much easier than that - just use `MSG_CMSG_CLOEXEC` flag to `recv` syscall.
