### ISSUE TITLE
WebAssembly can not allocate memory properly

### ISSUE THREAD

**Issue by zcc35357949** [gramineproject/gramine#874]
## Description of the problem
We try to run a simple snarkjs sample in gsc container, but it starts up with out-of-memory error.

### Docker Image
enclaive/nodejs-sgx:latest(from https://github.com/enclaive/enclaive-docker-nodejs-sgx)

### Snarkjs Sample
```
const snarkjs = require("snarkjs")
const express = require('express')
const morgan = require('morgan')
const fs = require('fs')

const app = express()
const port = 3000

// create a write stream (in append mode)
const accessLogStream = fs.createWriteStream('/data/access.log', { flags: 'a' })

app.use(morgan('combined', { stream: accessLogStream }))

app.get('/hello', (req, res) => {
    res.send(run())
})

app.get('/shutdown', (req, res) => {
    process.exit()
})

app.listen(port, () => {
    console.log(`Example app listening on port ${port}`)
})

async function run() {
    const { proof, publicSignals } = await snarkjs.plonk.fullProve({a: 3, b: 11}, "/app/demo/circuit_js/circuit.wasm", "/app/demo/circuit_final.zkey");

    console.log("Proof: ");
    console.log(JSON.stringify(proof, null, 1));

    const vKey = JSON.parse(fs.readFileSync("/app/demo/verification_key.json"));

    const res = await snarkjs.plonk.verify(vKey, publicSignals, proof);

    if (res === true) {
        console.log("Verification OK");
    } else {
        console.log("Invalid proof");
    }
}
```

### CPU and Memory
Intel(R) Xeon(R) Gold 5318Y CPU @ 2.10GHz

```
             total         used        free
Mem:          247Gi        12Gi       201Gi
```

### manifest template
```
libos.entrypoint = "/usr/bin/node"

loader.entrypoint = "file:{{ gramine.libos }}"

# for generic usage with mounted applications
loader.insecure__use_host_env = true
loader.insecure__use_cmdline_argv = true

loader.env.LD_LIBRARY_PATH = "/lib:{{ arch_libdir }}:/usr/local/lib"

loader.log_level = "error"
#loader.log_file = "log.txt"

# Node.js requires eventfd2() emulation
sys.insecure__allow_eventfd = true

fs.mounts = [
    { path = "/tmp",                uri = "file:/tmp", type = "tmpfs" },
    { path = "/etc",                uri = "file:/etc" },
    { path = "/usr",                uri = "file:/usr" },
    { path = "/lib",                uri = "file:{{ gramine.runtimedir() }}" },
    { path = "{{ arch_libdir }}",   uri = "file:{{ arch_libdir }}" },
    { path = "/app",                uri = "file:/app" },
    { path = "/data",               uri = "file:/data", type = "encrypted", key_name = "data" },
]
fs.insecure__keys.data = "ffeeddccbbaa99887766554433221100"

sgx.enclave_size = "16G"
sgx.thread_num = 24

sgx.debug = false
sgx.isvprodid = 1
sgx.isvsvn    = 1

sgx.trusted_files = [
    "file:{{ gramine.libos }}",
    "file:{{ gramine.runtimedir() }}/",
    "file:{{ arch_libdir }}/",

    "file:/usr/bin/node",

    "file:/usr/share/zoneinfo/",
    "file:/usr/share/zoneinfo-icu/",

    "file:/etc/nsswitch.conf",
    "file:/etc/host.conf",

    "file:/etc/passwd",
    "file:/etc/os-release",
    "file:/etc/localtime",
    "file:/etc/ssl/openssl.cnf",
]

sgx.allowed_files = [
    "file:/app/",
    "file:/etc/hosts",
    "file:/etc/resolv.conf",
]

sgx.nonpie_binary = true
```

## Actual results
![image](https://user-images.githubusercontent.com/23046890/188055939-15260381-0651-4a86-9952-d105766ecbf4.png)

**Comment by dimakuv** [comment]
This seems to be related to this: https://github.com/nodejs/node/issues/30017

In particular:
> V8 right now reserves (not commits) 1 GB per WASM module

Or even to this: https://github.com/piscinajs/piscina/issues/158

In particular:
> How do you create your WASM module? I am using rust wasm-pack. It seems that it is allocating 10GB of virtual memory per worker

There is a command-line argument to WASM: `--wasm-max-mem-pages`. Maybe you should try decreasing this number.

See https://gist.github.com/kyranet/3331b1346b773e1b03f1da2127f73fd0#file-v8-options-L281

I have a vague recollection that someone already ran WASM with Gramine, and it worked. I wonder if they know about such problems. @mkow @boryspoplawski @aneessahib @svenkata9 ? Also, maybe @masomel?

**Comment by svenkata9** [comment]
How much is it carved out for SGX EPC out of the total memory? Could you do `sudo dmesg | grep sgx`?

**Comment by zcc35357949** [comment]
> 

`dmesg | grep sgx`:
```
[    1.880614] sgx: EPC section 0x2000c00000-0x207f7fffff
[    1.886324] sgx: EPC section 0x4000c00000-0x407fffffff
```
`nodejs allocate memory error`:
```
Could not allocate 2147418112 bytes. This may cause severe instability. Trying with 1073709056 bytes
Could not allocate 1073676288 bytes. This may cause severe instability. Trying with 536838144 bytes
Could not allocate 536805376 bytes. This may cause severe instability. Trying with 268402688 bytes
Could not allocate 268369920 bytes. This may cause severe instability. Trying with 134184960 bytes
Could not allocate 134152192 bytes. This may cause severe instability. Trying with 67076096 bytes
Could not allocate 67043328 bytes. This may cause severe instability. Trying with 33521664 bytes
Could not allocate 33488896 bytes. This may cause severe instability. Trying with 16744448 bytes
Could not allocate 16711680 bytes. This may cause severe instability. Trying with 8355840 bytes
Could not allocate 8323072 bytes. This may cause severe instability. Trying with 4161536 bytes
Could not allocate 4128768 bytes. This may cause severe instability. Trying with 2064384 bytes
Could not allocate 2031616 bytes. This may cause severe instability. Trying with 1015808 bytes
Could not allocate 983040 bytes. This may cause severe instability. Trying with 491520 bytes
Could not allocate 458752 bytes. This may cause severe instability. Trying with 229376 bytes
Could not allocate 196608 bytes. This may cause severe instability. Trying with 98304 bytes
/app/demo/node_modules/circom_runtime/build/main.cjs:85
            memory = new WebAssembly.Memory({initial:memorySize});
                     ^

RangeError: WebAssembly.Memory(): could not allocate memory
    at Object.builder [as WitnessCalculatorBuilder] (/app/demo/node_modules/circom_runtime/build/main.cjs:85:22)
    at wtnsCalculate (/app/demo/node_modules/snarkjs/build/main.cjs:1131:37)
    at async Object.plonkFullProve [as fullProve] (/app/demo/node_modules/snarkjs/build/main.cjs:7394:5)
    at async run (/app/demo/index.js:31:38)
```

**Comment by svenkata9** [comment]
What I suspected seems to be correct - the EPC is just 2GB. That's perhaps the reason you are hitting this error. Please enter the BIOS and in SGX EPC Size option, increase it to 64GB and you should see this error vanish.

**Comment by zcc35357949** [comment]
> This seems to be related to this: [nodejs/node#30017](https://github.com/nodejs/node/issues/30017)
> 
> In particular:
> 
> > V8 right now reserves (not commits) 1 GB per WASM module
> 
> Or even to this: [piscinajs/piscina#158](https://github.com/piscinajs/piscina/issues/158)
> 
> In particular:
> 
> > How do you create your WASM module? I am using rust wasm-pack. It seems that it is allocating 10GB of virtual memory per worker
> 
> There is a command-line argument to WASM: `--wasm-max-mem-pages`. Maybe you should try decreasing this number.
> 
> See https://gist.github.com/kyranet/3331b1346b773e1b03f1da2127f73fd0#file-v8-options-L281
> 
> I have a vague recollection that someone already ran WASM with Gramine, and it worked. I wonder if they know about such problems. @mkow @boryspoplawski @aneessahib @svenkata9 ? Also, maybe @masomel?

descreasing `--wasm-max-mem-pages` can not resolve it.

**Comment by svenkata9** [comment]
Please see my response. That should help. In your system, it might be present under 
Socket Configuration -> Processor Configuration -> PRMRR Size

* might because I don't know the customization that OEMs have in their BIOS.

**Comment by zcc35357949** [comment]
> 

already increase to 64GB, but it does't work.
```
[    1.863116] sgx: EPC section 0x1018000000-0x1fff7fffff
[    2.045779] sgx: EPC section 0x3018000000-0x3fffffffff
```

```
/app/demo/node_modules/blake2b-wasm/blake2b.js:32
  const instance = await WebAssembly.instantiate(await compiled, imports);
                                     ^
RangeError: WebAssembly.instantiate(): Out of memory: wasm memory
    at module.exports (/app/demo/node_modules/blake2b-wasm/blake2b.js:32:38)
```

**Comment by svenkata9** [comment]
Well, if I understand the error now seems to be at a different point (further down) in the flow, right? Couple of options to triage this:
1. Run the same workload with `gramine-direct` and see if it works - the gramine version without SGX. We expect it to work.
2. Increase the enclave size in the manifest to 32GB and see (along with decreasing wasm memory as @dimakuv mentioned)

**Comment by zcc35357949** [comment]
> 
got the error running with `gramine-direct`:
`error: PAL failed at ../pal/src/host/linux/pal_main.c:215: setting personality failed: -6`

**Comment by dimakuv** [comment]
Please check https://gramine.readthedocs.io/projects/gsc/en/latest/#execute-with-linux-pal-instead-of-linux-sgx-pal

For quick testing, you need to start your Docker container with `docker run ... --security-opt seccomp=unconfined`

**Comment by zcc35357949** [comment]
> Please check https://gramine.readthedocs.io/projects/gsc/en/latest/#execute-with-linux-pal-instead-of-linux-sgx-pal
> 
> For quick testing, you need to start your Docker container with `docker run ... --security-opt seccomp=unconfined`

Ok, after setting the option, PAL error indeed vanish. 
However, out-of-memory error still exists.I have expand enclave_size to 32G and `--wasm-max-mem-pages` to 16(1M?)

**Comment by zcc35357949** [comment]
> Well, if I understand the error now seems to be at a different point (further down) in the flow, right? Couple of options to triage this:
> 
> 1. Run the same workload with `gramine-direct` and see if it works - the gramine version without SGX. We expect it to work.
> 2. Increase the enclave size in the manifest to 32GB and see (along with decreasing wasm memory as @dimakuv mentioned)

It does't work even running with `gramine-direct`.

**Comment by boryspoplawski** [comment]
I did run wasm, but it was long time ago and I don't remember the details. For sure it worked, consumed a lot of memory even for simple stuff, but 1-2G was enough for me.

> It does't work even running with gramine-direct.

What's the problem? How does it fail? Can you add `loader.log_level = "all"` to the manifest file and attach the output?

**Comment by terminal69** [comment]
> This seems to be related to this: [nodejs/node#30017](https://github.com/nodejs/node/issues/30017)
> 
> In particular:
> 
> > V8 right now reserves (not commits) 1 GB per WASM module
> 
> Or even to this: [piscinajs/piscina#158](https://github.com/piscinajs/piscina/issues/158)
> 
> In particular:
> 
> > How do you create your WASM module? I am using rust wasm-pack. It seems that it is allocating 10GB of virtual memory per worker
> 
> There is a command-line argument to WASM: `--wasm-max-mem-pages`. Maybe you should try decreasing this number.
> 
> See https://gist.github.com/kyranet/3331b1346b773e1b03f1da2127f73fd0#file-v8-options-L281
> 
> I have a vague recollection that someone already ran WASM with Gramine, and it worked. I wonder if they know about such problems. @mkow @boryspoplawski @aneessahib @svenkata9 ? Also, maybe @masomel?

Saw you mentioned this issue from the piscina thread. We had that problem with virtual memory in nodejs 16 which was somehow fixed in nodejs 17.1 or 17.2 I think.

Your docker image from https://github.com/enclaive/enclaive-docker-nodejs-sgx seems to use nodejs 12, based on https://github.com/enclaive/enclaive-docker-nodejs-sgx/blob/main/Dockerfile ...

for example, I built this Dockerfile
```
FROM enclaive/gramine-os:jammy-33576d39
RUN apt-get update \
    && apt-get install -y nodejs
RUN node -v
```

Output:
```
...
STEP 3/3: RUN node -v
v12.22.9
...
```

If you can run gramine with nodejs 18 I would suggest trying that

**Comment by zcc35357949** [comment]
> I did run wasm, but it was long time ago and I don't remember the details. For sure it worked, consumed a lot of memory even for simple stuff, but 1-2G was enough for me.
> 
> > It does't work even running with gramine-direct.
> 
> What's the problem? How does it fail? Can you add `loader.log_level = "all"` to the manifest file and attach the output?

Thanks for the reply. This is the output of running with gramine-direct:
[debug.log](https://github.com/gramineproject/gramine/files/9486282/debug.log)

**Comment by zcc35357949** [comment]
> 

Thanks. It does't work after upgrading nodejs to v18.8.0.
```
docker-compose exec sgx node -v
v18.8.0
```

**Comment by zcc35357949** [comment]
> > This seems to be related to this: [nodejs/node#30017](https://github.com/nodejs/node/issues/30017)
> > In particular:
> > > V8 right now reserves (not commits) 1 GB per WASM module
> > 
> > 
> > Or even to this: [piscinajs/piscina#158](https://github.com/piscinajs/piscina/issues/158)
> > In particular:
> > > How do you create your WASM module? I am using rust wasm-pack. It seems that it is allocating 10GB of virtual memory per worker
> > 
> > 
> > There is a command-line argument to WASM: `--wasm-max-mem-pages`. Maybe you should try decreasing this number.
> > See https://gist.github.com/kyranet/3331b1346b773e1b03f1da2127f73fd0#file-v8-options-L281
> > I have a vague recollection that someone already ran WASM with Gramine, and it worked. I wonder if they know about such problems. @mkow @boryspoplawski @aneessahib @svenkata9 ? Also, maybe @masomel?
> 
> Saw you mentioned this issue from the piscina thread. We had that problem with virtual memory in nodejs 16 which was somehow fixed in nodejs 17.1 or 17.2 I think.
> 
> Your docker image from https://github.com/enclaive/enclaive-docker-nodejs-sgx seems to use nodejs 12, based on https://github.com/enclaive/enclaive-docker-nodejs-sgx/blob/main/Dockerfile ...
> 
> for example, I built this Dockerfile
> 
> ```
> FROM enclaive/gramine-os:jammy-33576d39
> RUN apt-get update \
>     && apt-get install -y nodejs
> RUN node -v
> ```
> 
> Output:
> 
> ```
> ...
> STEP 3/3: RUN node -v
> v12.22.9
> ...
> ```
> 
> If you can run gramine with nodejs 18 I would suggest trying that

> 

Thanks. It does't work after upgrading nodejs to v18.8.0.
```
docker-compose exec sgx node -v
v18.8.0
```

**Comment by dimakuv** [comment]
@zcc35357949 I looked at the attached `debug.log` file. I fail to see anything wrong in Gramine execution.

In particular, here is the snippet where the application starts to complain about insufficient memory (I cleaned it for readability):
```
Could not allocate 2147418112 bytes. This may cause severe instability. Trying with 1073709056 bytes
Could not allocate 1073676288 bytes. This may cause severe instability. Trying with 536838144 bytes
Could not allocate 536805376 bytes. This may cause severe instability. Trying with 268402688 bytes
Could not allocate 268369920 bytes. This may cause severe instability. Trying with 134184960 bytes
Could not allocate 134152192 bytes. This may cause severe instability. Trying with 67076096 bytes
Could not allocate 67043328 bytes. This may cause severe instability. Trying with 33521664 bytes
Could not allocate 33488896 bytes. This may cause severe instability. Trying with 16744448 bytes
Could not allocate 16711680 bytes. This may cause severe instability. Trying with 8355840 bytes
Could not allocate 8323072 bytes. This may cause severe instability. Trying with 4161536 bytes
Could not allocate 4128768 bytes. This may cause severe instability. Trying with 2064384 bytes
Could not allocate 2031616 bytes. This may cause severe instability. Trying with 1015808 bytes
Could not allocate 983040 bytes. This may cause severe instability. Trying with 491520 bytes
[P1:T1:node] trace: ---- mmap(0, 0x28000f000, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0x0) ...
[P1:T1:node] trace: ---- return from mmap(...) = 0x71ce8fff1000
```

So this is bizzare: the application complains that it cannot allocate memory, but at the same time Gramine is able to fullfill the request of the application to allocate `0x28000f000` bytes of memory (~10GB)... This is very weird, and I fail to see how Gramine can be at fault here.

**Comment by zcc35357949** [comment]
After increasing the enclave size in the manifest to 64GB and removing `--wasm-max-mem-pages` node argument, `gramine-direct` can work as expect.

however, after change back to `gramine-sgx`,  no error message print and the process stuck up.
[debug.log.zip](https://github.com/gramineproject/gramine/files/9488222/debug.log.zip)
