### ISSUE TITLE
error: PAL failed at ../../Pal/src/db_main.c:pal_main:457 (exitcode = 4, reason=argv handling wasn't configured in the manifest, but cmdline arguments were specified.) 

### ISSUE THREAD

**Issue by lili8808** [gramineproject/gramine#882]
## Description of the problem

I have installed Gramine using the link https://gramine.readthedocs.io/en/stable/cloud-deployment.html but when I run the command  ```gramine-sgx helloworld``` at the end I get error:
```~/v1.2/CI-Examples/helloworld$ gramine-sgx helloworld , Does any one know the reason and the solution?

Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

error: PAL failed at ../../Pal/src/db_main.c:pal_main:457 (exitcode = 4, reason=argv handling wasn't configured in the manifest, but cmdline arguments were specified.)

**Comment by dimakuv** [comment]
Unfortunately, our documentation is currently wrong. Instead of this:
```
git clone --depth 1 https://github.com/gramineproject/gramine.git v1.2
```

you should have done this:
```
git clone --branch v1.2 --depth 1 https://github.com/gramineproject/gramine.git
```

**Comment by lili8808** [comment]
Thanks for response now I get this error:
```gramine/CI-Examples/helloworld$ sudo make SGX=1
cc -Wall -Wextra -O3   -c -o helloworld.o helloworld.c
cc   helloworld.o   -o helloworld
gramine-manifest \
	-Dlog_level=error \
	helloworld.manifest.template helloworld.manifest
gramine-sgx-sign \
	--manifest helloworld.manifest \
	--output helloworld.manifest.sgx
Usage: gramine-sgx-sign [OPTIONS]
Try "gramine-sgx-sign --help" for help.

Error: Invalid value for "--key" / "-k": File "/root/.config/gramine/enclave-key.pem" does not exist.
make: *** [Makefile:44: sgx_sign] Error 2

**Comment by dimakuv** [comment]
@lili8808 Forgot this step? https://gramine.readthedocs.io/en/stable/cloud-deployment.html#prepare-a-signing-key

**Comment by lili8808** [comment]
Thanks for your reply, I successfulyy run helloworld in c, but when I want to run the helloworld.py in python path I get the error as below:
`~/gramine/CI-Examples/python$ gramine-sgx ./python scripts/helloworld.py
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: aesm_service returned error: 1
error: load_enclave() failed with error -1
`

**Comment by dimakuv** [comment]
@lili8808 This will be fixed (or how to say that... "made more reasonable") in the next release of Gramine.

Currently, you should read the README of the Python example carefully, especially this part: https://github.com/gramineproject/gramine/tree/v1.2/CI-Examples/python#building-for-sgx

Basically, you need to re-build the Python example like this:
```
make clean; RA_CLIENT_SPID=12345678901234567890123456789012 RA_CLIENT_LINKABLE=0 make SGX=1
```

**Comment by lili8808** [comment]
Does this new make command mean without remote attestation?

**Comment by dimakuv** [comment]
@lili8808 This means "dummy" (unused) remote attestation. So yes, without remote attestation.

**Comment by lili8808** [comment]
Thanks for help so I can not run python programs with remote attestation until new release am I right?

**Comment by dimakuv** [comment]
@lili8808 You can. But you need to set up remote attestation correctly when you build your apps. Please read https://github.com/gramineproject/gramine/tree/v1.2/CI-Examples/python#building-for-sgx carefully. Also read https://gramine.readthedocs.io/en/stable/attestation.html.

**Comment by dimakuv** [comment]
> now I am using Remote attestation right?

Yes, correct.

> As far as I got so far there is no need to create new SPID for a user each time he/she wants to execute the program but every time he/she should pas this ID. Right?

Yes, this is also correct. You're just reusing the same SPID.
