### ISSUE TITLE
[Doc] Issue in cloud deployment document for cloning the v1.2 release

### ISSUE THREAD

**Issue by enedellec** [gramineproject/gramine#891]
In the stable version of the documentation, it is proposed to clone the v1.2 version by proceeding that way :
`git clone --depth 1 https://github.com/gramineproject/gramine.git v1.2`

Actually, that command does not clone the version 1.2, but the last version in a directory named v1.2.
The right command is the following one :   
`git clone --depth 1 --branch v1.2 https://github.com/gramineproject/gramine.git`

I had a look in the git project in order to propose a PR, but it seems to be correct in the `master` branch.
So, I do not know what's going wrong.

**Comment by boryspoplawski** [comment]
The documentation for v1.2 is build well, from v1.2 :) It was found out and fixed only after the release, so v1.3 will be correct (the release should happen ~soon)
