### ISSUE TITLE
Unable to load binary execute when running python in Gramine

### ISSUE THREAD

**Issue by deliciousdish** [gramineproject/gramine#895]
## Description of the problem
I'm not sure whether it's a bug. I have tried helloworld.py in gramine/CI-Examples/python, and then I want to make some changes. Specifically, I want to load a binary executeable and got an error.

## Steps to reproduce
For example, I wrote a helloworld.c, then
```
gcc helloworld.c -o helloworld
```
And I modified python.manifest, add "file:scripts/helloworld" into allowed_files, then I want to execute helloworld in helloworld.py.
```
#!/usr/bin/env python3

import subprocess
output = subprocess.call("scripts/helloworld")

print("Hello World")
```
Then 
```
make clean
make SGX=1
gramine-sgx ./python scripts/helloworld.py
```

## Actual results
```
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: Unexpected memory fault occurred inside PAL (0x1edb83e8)
```

## Gramine commit hash
I installed Gramine from apt, and its version is 1.2-1

**Comment by boryspoplawski** [comment]
Please try the current master branch, this might have been already fixed (and I couldn't repro it there).

The problem might be that you have the same file - `scripts/helloworld` both in trusted and allowed files. This should be fine, but maybe we had some bugs in this area.

**Comment by deliciousdish** [comment]
But it didn't work on my machine. I removed old gramine using "apt purge" and build it from master branch following the instructions [here](https://gramine.readthedocs.io/en/latest/devel/building.html). But i start from Building section because I have installed sgx driver, sdk and psw from source. Then i test and get the following error message:
```
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

error: Unexpected memory fault occurred inside PAL (0x1edcf2d6)
[P1:T1:python3.8] error: failed writing checkpoint header to child process (ret = -32)
[P1:T1:python3.8] error: process creation failed
```
Any suggestions? Thanks!

**Comment by dimakuv** [comment]
@deliciousdish Can you check `which gramine-sgx`? What does it output? One suspicion I have is that you're still having an old version of Gramine (or parts of Gramine) installed on the machine.

If this error still persists, I would ask you to show us *all the steps* that you did. Including how you change sources, how you change manifest.template files, how you build and how you run.

Something is wrong here. Both me and Borys cannot reproduce your error.

**Comment by deliciousdish** [comment]
Maybe i set wrong parameter in meson setup. So, how to set sgx_driver_include_path when sgx_driver is set to upstream?
If i ignore this parameter, it will try to find "asm/sgx.h" when execute "ninja -C build/"
I search this file, and find it in 
```
./usr/src/linux-hwe-5.13-headers-5.13.0-30/arch/x86/include/uapi/asm/sgx.h
./usr/src/linux-hwe-5.13-headers-5.13.0-30/arch/x86/include/asm/sgx.h
```
Then i try to set sgx_driver_include_path to 
```
/usr/src/linux-hwe-5.13-headers-5.13.0-30/arch/x86/include/asm/sgx.h
```
but it got another error
```

Found ninja-1.10.0 at /usr/bin/ninja
Cleaning... 0 files.
[64/366] Compiling C object pal/src/host/linux-sgx/pal-sgx-generated-offsets-print.p/generated_offsets.c.o
FAILED: pal/src/host/linux-sgx/pal-sgx-generated-offsets-print.p/generated_offsets.c.o
cc -Ipal/src/host/linux-sgx/pal-sgx-generated-offsets-print.p -Ipal/src/host/linux-sgx -I../pal/src/host/linux-sgx -Ipal/include -I../pal/include -I../pal/include/pal -I../pal/include/arch/x86_64 -Icommon/include -I../common/include -I../common/include/arch/x86_64 -I../pal/include/arch/x86_64/linux -I../pal/include/host/linux-common -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 -O3 -Wa,--noexecstack -Wall -Wextra -Wmissing-prototypes -Wstrict-prototypes -Wwrite-strings -Wtrampolines -Wnull-dereference -DIN_PAL -fno-builtin -DHOST_TYPE=Linux-SGX -Wno-gnu-alignof-expression -MD -MQ pal/src/host/linux-sgx/pal-sgx-generated-offsets-print.p/generated_offsets.c.o -MF pal/src/host/linux-sgx/pal-sgx-generated-offsets-print.p/generated_offsets.c.o.d -o pal/src/host/linux-sgx/pal-sgx-generated-offsets-print.p/generated_offsets.c.o -c ../pal/src/host/linux-sgx/generated_offsets.c
In file included from pal/src/host/linux-sgx/host_gsgx.h:15,
                 from ../pal/src/host/linux-sgx/generated_offsets.c:4:
/usr/src/linux-hwe-5.13-headers-5.13.0-30/arch/x86/include/asm/sgx.h:10:10: fatal error: linux/bits.h: No such file or directory
   10 | #include <linux/bits.h>
      |          
compilation terminated.
[69/366] Generating pal/src/host/linux-sgx/pal.map with a custom command
ninja: build stopped: subcommand failed.
```
I can find bits.h in the following path
```
/usr/src/linux-hwe-5.13-headers-5.13.0-30/include/linux/bits.h
/usr/src/linux-hwe-5.13-headers-5.13.0-30/include/vdso/bits.h
```
So, the question is how to set sgx_driver_include_path when sgx_driver is set to upstream?

**Comment by dimakuv** [comment]
`sgx_driver_include_path="/usr/src/linux-hwe-5.13-headers-5.13.0-30/arch/x86/include/uapi"`

**Comment by deliciousdish** [comment]
Yes, it worked. Last time, i built gramine using wrong param value for sgx_driver and sgx_driver_include_path.
 Thanks very much! @dimakuv
