### ISSUE TITLE
[Doc] Incorrect git clone command in QuickStart Guide to run helloworld example

### ISSUE THREAD

**Issue by jinengandhi-intel** [gramineproject/gramine#896]
## Description of the problem
In the quickstart guide for v1.2 and stable the command to checkout gramine is incorrect: https://gramine.readthedocs.io/en/stable/quickstart.html
https://gramine.readthedocs.io/en/v1.2/quickstart.html

`git clone --depth 1 https://github.com/gramineproject/gramine.git v1.2` 

Here you are missing `-b` before `v1.2`: `git clone --depth 1 https://github.com/gramineproject/gramine.git -b v1.2`

For the latest version of the quickstart guide we are asking the user to checkout the latest master and compile helloworld example but when you do that and run with the package v1.2, it results in a failure: 

```
intel@intel-Ice-Lake-Client-Platform:~/gramine/CI-Examples/helloworld$ gramine-direct helloworld
error: PAL failed at ../../Pal/src/db_main.c:pal_main:457 (exitcode = 4, reason=argv handling wasn't configured in the manifest, but cmdline arguments were specified.)
```

The reason for this is that in the latest master we have removed `loader.argv0_override` manifest option, in summary the package which is v1.2 is not compatible with the latest source code. So for all versions of quickstart guide the source code version we checkout for helloworld should be equal to the package version installed on the system.

## Expected results
Have `git clone --depth 1 https://github.com/gramineproject/gramine.git -b v1.2` or the latest release tag for all versions of quickstart guide.

**Comment by mkow** [comment]
This was fixed by 1b83451a1e8e38e7d56c8e6b2fe923504a4dc6a0 some time ago.
