### ISSUE TITLE
Is it possible to connect to the mysql tables while running python script suing Gramine?

### ISSUE THREAD

**Issue by lili8808** [gramineproject/gramine#898]
How Gramine can connect to the mysql tables while running a python script (when the script is running inside the SGX)?

**Comment by boryspoplawski** [comment]
Please read the issue template:
```
IMPORTANT: please do not post general questions here;
if you have questions, please use our mailing list: users@gramineproject.io
```

**Comment by boryspoplawski** [comment]
You can also join our gitter chat: https://gitter.im/gramineproject/community
