### ISSUE TITLE
Implement support for `TCP_KEEPIDLE`, `TCP_KEEPCNT` and `TCP_KEEPINTVL`

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#902]
## Description of the problem

Gramine currently doesn't support `setsockopt(TCP_KEEPIDLE)` (same for `TCP_KEEPCNT` and `TCP_KEEPINTVL`).

Some applications set these socket options and fail if these options are not supported (like currently in Gramine):
```
setsockopt(TCP_KEEPIDLE) failed: Protocol not available
could not create socket: Address family not supported by protocol
```

One example is applications that use `libpq` (library for communication with PostgreSQL): https://www.postgresql.org/docs/current/libpq-connect.html

The proposed changes should go somewhere here: https://github.com/gramineproject/gramine/blob/5b160c68260eaa57a9342762b33dbff1e3c8fb5a/libos/src/net/ip.c#L463

These socket options are required in certain network configurations, e.g. the other end may expect keepalive probes in a shorter than default timeout (so the peers need to set these options correctly; we can't simply ignore them in Gramine)? Ignoring these options can seriously degrade performance and add noise (of frequently reconnecting sockets).

**Comment by dimakuv** [comment]
@kailun-qin will take this task. @kailun-qin Can you add a comment with I will take this task? Otherwise GitHub doesn't allow to assign you to the task.

**Comment by boryspoplawski** [comment]
I've just checked `libpq` sources and non of this options is required. Yes they print an error messages, but then the error is ignored (and program proceeds with the default values).

`could not create socket: Address family not supported by protocol`
This is the real error here and it seems that it tries to create an unsupported socket `conn->sock = socket(addr_cur->ai_family, SOCK_STREAM, 0);`, but hard to say which exactly, because the parameter is provided dynamically.

**Comment by dimakuv** [comment]
This is surprising. I will check with people who reported this issue.

The surprising part to me is that I was told the app worked before (with Gramine v1.2, before the Sockets Rewrite). And after the Sockets Rewrite, it stopped working, which was a strong indicator that it's about unsupported TCP flags.

**Comment by dimakuv** [comment]
Nope, based on the information and logs that these people shared with me, I'm sure the problem is in non-supported TCP flags. There are two indicators for this:

1. Gramine log:
```
trace: ---- socket(INET, STREAM, 0) = 0x4
trace: ---- setsockopt(4, 6, 1, 0x1e88a1b20, 4) = 0x0
trace: ---- fcntl(4, F_GETFL, 0x1) = 0x2
trace: ---- fcntl(4, F_SETFL, 0x802) = 0x0
trace: ---- fcntl(4, F_SETFD, 0x1) = 0x0
trace: ---- setsockopt(4, 1, 9, 0x1e88a1af8, 4) = 0x0
trace: ---- setsockopt(4, 6, 4, 0x1e88a1b20, 4) = -92
trace: ---- close(4) = 0x0
Unexpected exception: Dynamic exception type: pqxx::broken_connection
std::exception::what: setsockopt(TCP_KEEPIDLE) failed: Protocol not available
exiting [sanitized] with exit code 1
```

We can clearly see that after `setsockopt(TCP_KEEPIDLE)`, the code refuses to continue working with the socket and just `close`s it.

2. The problem was bisected to the commit with Big Sockets Rewrite.

It may be that I pointed you to a wrong library? The logs show that `libpqxx` lib is used, and I mentioned previously `libpq`. My bad, I should have paid more attention: apparently, `libpq` is a C lib standard for Postgres, but the used lib is `libpqxx` (not official but widely used). See https://stackoverflow.com/questions/25152111/is-libpq-or-libpqxx-the-official-c-postgres-interface
