### ISSUE TITLE
Paths with a trailing slash don't work with encrypted mounts

### ISSUE THREAD

**Issue by mkow** [gramineproject/gramine#904]
## Description of the problem

This does work:

```TOML
fs.mounts = [
  { path = "/files", uri = "file:enc_files", type = "encrypted" },
]
```

but this doesn't, despite it should:

```TOML
fs.mounts = [
  { path = "/files/", uri = "file:enc_files/", type = "encrypted" },
]
```
In both examples `enc_files/` is a directory. By not working I mean that `/files/` directory doesn't contain decrypted contents of `enc_files/` from the host.

Disclaimer: I haven't investigated the issue at all, so it may be something trivial.

## Gramine commit hash

7e7e31b1ac9cd94636245ba3c89f6f79c8c0dcc8

**Comment by dimakuv** [comment]
Looks like smth we'd like to fix sooner than later... Anyone has free cycles? @kailun-qin @boryspoplawski

**Comment by dimakuv** [comment]
FWIW: I couldn't reproduce it using `libos/test/regression/manifest.template`...

**Comment by dimakuv** [comment]
I was able to reproduce this in the latest master (with #884) on `ra-tls-secret-prov` example.

In particular, the problem is in `uri` (not `path`) -- adding `/` indeed makes the example fail. I'm debugging this...
