### ISSUE TITLE
error :Pal/src/host/Linux/db_main.c:pal_linux_main:214  (exitcode = 6, reason=setting personality failed)

### ISSUE THREAD

**Issue by lbb211** [gramineproject/gramine#906]
To test Gramine installation, I have installed Gramine using the link https://gramine.readthedocs.io/en/stable/quickstart.html but when I run the command gramine-direct helloworld at the end I get error:

root@1c7a50e4ba87:~/gramine/CI-Examples/helloworld# gramine-direct helloworld
error: PAL failed at ../../Pal/src/host/Linux/db_main.c:pal_linux_main:214 (exitcode = 6, reason=setting personality failed)

**Comment by dimakuv** [comment]
Looks like you run Gramine in a Docker container. You need to change the default Docker seccomp filter for `gramine-direct` to run (no need for this if you only care about `gramine-sgx`).

- https://hub.docker.com/r/gramineproject/gramine (see under `SGX`)
- https://gramine.readthedocs.io/projects/gsc/en/latest/#execute-with-linux-pal-instead-of-linux-sgx-pal

**Comment by lbb211** [comment]
> Looks like you run Gramine in a Docker container. You need to change the default Docker seccomp filter for `gramine-direct` to run (no need for this if you only care about `gramine-sgx`).
> 
> * https://hub.docker.com/r/gramineproject/gramine (see under `SGX`)
> * https://gramine.readthedocs.io/projects/gsc/en/latest/#execute-with-linux-pal-instead-of-linux-sgx-pal

hi dimakuv , I think use gramine-direct helloworld in docker conntainer , now ,how to set the default docker seccomp filter  
 ,can you tell me ,thank you !

**Comment by dimakuv** [comment]
I gave you the links which explain how to do it... But here's a quick (and not recommended) way of running Docker that allows to run `gramine-direct`: `docker run ... --security-opt seccomp=unconfined`

**Comment by lbb211** [comment]
> I gave you the links which explain how to do it... But here's a quick (and not recommended) way of running Docker that allows to run `gramine-direct`: `docker run ... --security-opt seccomp=unconfined`

yes, I do it ,but the  other question is happend 
error: PAL failed at ../../Pal/src/db_main.c:pal_main:457(exitcode =4, reason=argv handling wasn't configured in the manifest, but cmdline arguments were specified)

**Comment by dimakuv** [comment]
Ah, I see. We have a bug in the QuickStart guide (which will be fixed soon).

In your `~/gramine/CI-Examples/helloworld` directly, please type `git checkout v1.2`. This will "synchronize" the version of the Helloworld example with the version of Gramine that you installed.

After this, you can do `make clean; make`, and then `gramine-direct helloworld` will work fine.

**Comment by lbb211** [comment]
> Ah, I see. We have a bug in the QuickStart guide (which will be fixed soon).
> 
> In your `~/gramine/CI-Examples/helloworld` directly, please type `git checkout v1.2`. This will "synchronize" the version of the Helloworld example with the version of Gramine that you installed.
> 
> After this, you can do `make clean; make`, and then `gramine-direct helloworld` will work fine.

Do you have the full git command  like "git clone --depth 1 https://github.com/gramineproject/gramine.git v1.2". thank you

**Comment by dimakuv** [comment]
Well, the correct command should be `git clone --depth 1 --branch v1.2 https://github.com/gramineproject/gramine.git`

**Comment by lbb211** [comment]
The command : gramine-direct helloworld  is fine, thank you very much!
