### ISSUE TITLE
ra-tls-mbedtls: failed when it perform the SSL/TLS handshake

### ISSUE THREAD

**Issue by jasonkang1234** [gramineproject/gramine#914]
## Description of the problem
I tried the run ra-tls-mbedtls from the CI-Examples. However it failed when it perform the SSL/TLS handshake.

I am using Gramine version1.2. I am running it on the same virtual machine

Steps:
1) Azure confidential compute resource virtual machine terminal :
$gramine-sgx ./server dcap &

2) Another terminal on the same virtual machine with Azure confidential compute resource:
$RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1  RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 gramine-sgx ./client_dcap  dcap 10962357e54ef712c9c863df40bf6adf13342d386bc2228875066a456208aa39 7971dec9c905f2612eaf601b253c0e3202daa04e91aa2b0fab404c39f7e40805  0 0                                 

![error](https://user-images.githubusercontent.com/110457430/190569872-d957a3f2-f954-4cf7-96d2-69f6c46ee89e.JPG)

**Comment by dimakuv** [comment]
Interesting, I've never seen an error like this (`The CRT/CRL/CSR format is invalid`).

Does the non-gramine client work for you? I mean the third example from the README:
```
make clean
make app dcap

gramine-sgx ./server dcap &

RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 \
RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 \
RA_TLS_MRENCLAVE=<MRENCLAVE of the server enclave> \
RA_TLS_MRSIGNER=<MRSIGNER of the server enclave> \
RA_TLS_ISV_PROD_ID=<ISV_PROD_ID of the server enclave> \
RA_TLS_ISV_SVN=<ISV_SVN of the server enclave> \
./client dcap

# client will successfully connect to the server via RA-TLS/DCAP flows
kill %%
```

**Comment by kailun-qin** [comment]
Hi @jasonkang1234!

Would just like to follow up - has your issue been resolved? Thanks!

**Comment by dimakuv** [comment]
Let me close this issue, since the author is inactive.

**Comment by dzobbe** [comment]
Never mind. Just for information that could be useful for others, I didn't compile the server with `make app dcap RA_TYPE=dcap` but just with `make`. My bad.
