### ISSUE TITLE
error: PAL failed at ../Pal/src/db_main.c:pal_main:458 (exitcode = 4, reason=argv handling wasn't configured in the manifest, but cmdline arguments were specified.

### ISSUE THREAD

**Issue by jiangxu12** [gramineproject/gramine#918]
I have installed Gramine using the link https://gramine.readthedocs.io/en/stable/quickstart.html but when I run the command gramine-sgx XXXXX at the end I get error:

```
Gramine is starting. Parsing TOML manifest file, this may take some time...
error: PAL failed at ../Pal/src/db_main.c:pal_main:458 (exitcode = 4, reason=argv handling wasn't configured in the manifest, but cmdline arguments were specified.
```
I can run helloworld in c successfully but when I run python, bash and redis etc it produces error.
I am using CentOS8，and I can make them successfully.
But I got this error, when I use the command gramine-sgx to run these examples.

<img width="464" alt="1663573975115" src="https://user-images.githubusercontent.com/43697225/190972747-e014eb4d-d4f5-420c-883d-e6063fa55a67.png">

**Comment by dimakuv** [comment]
@jiangxu12 Please check this one: https://github.com/gramineproject/gramine/issues/882

**Comment by jiangxu12** [comment]
@dimakuv Yes，I have read this issue before,and I have use the new command  
`git clone --branch v1.2 --depth 1 https://github.com/gramineproject/gramine.git`.
After that,I could run helloworld.c in c successfully, but when I run python, bash and redis etc in the CI-Examples,they still  produce this error.
![image](https://user-images.githubusercontent.com/43697225/191027478-02bc2bbd-7fd8-4a7f-af7f-0da06a32f428.png)
<img width="463" alt="1663593879329" src="https://user-images.githubusercontent.com/43697225/191027650-a7de62b1-c0b8-4b81-9bd6-9cf87cb53916.png">
Why does this problem occur, is it a problem with my CentOS system?

**Comment by dimakuv** [comment]
Strange, this shouldn't happen. Please try `make clean` in these examples (Python and Bash), and then build again using `make SGX=1`.
