### ISSUE TITLE
How to get the host ip address and hostname inside Gramine?

### ISSUE THREAD

**Issue by bronzeMe** [gramineproject/gramine#926]
*  Example code, see it at [get_host_name.py](https://github.com/bronzeMe/gramine/blob/master/CI-Examples/python/scripts/get_hostname.py)
* Running this example code directly on the host, we got the result:
```bash
python3 scripts/get_hostname.py
sgx_host
10.xx.xx.26
```
* Running this example code inside Gramine , we got the following:
```bash
gramine-sgx python scripts/get_hostname.py
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)
  - sgx.allowed_files = [ ... ]                (some files are passed through from untrusted host without verification)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

localhost
127.0.0.1
```
* The expected result should be the same as that returned by running it on the host.
Q1: Can we get the expected result by setting the `manifest` file?
Q2:  Does Gramine support get the hostname and host ip?

**Comment by bronzeMe** [comment]
The above results were tested on an  old version gramine, I find the latest version gramine had overcome this issue, see details at [libos_uname.c](https://github.com/gramineproject/gramine/blob/master/libos/src/sys/libos_uname.c#L24)

**Comment by dimakuv** [comment]
Yes, exactly. We fixed it just a couple days ago :)
