### ISSUE TITLE
ra-tls-mbedtls example with DCAP fails to establish TLS handshake

### ISSUE THREAD

**Issue by asmprogrammer5** [gramineproject/gramine#941]
## Description of the problem
RA-TLS Sample with DCAP fails, but succeeds with EPID
It's similar to this issue:
https://github.com/gramineproject/gramine/issues/570

However, that issue only states to use EPID, but does not address DCAP. I can get the EPID to work, but not DCAP.

## Steps to reproduce
Followed instructions to build and install from source:
https://gramine.readthedocs.io/en/stable/devel/building.html

and verified Intel DCAP is installed correctly by following:
https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html

Then built the ra-tls as per:
https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-mbedtls/README.md

The EPID mechanism of attestation works. 

## Actual results
But the DCAP version fails:
Server:
```
$ gramine-sgx server dcap
...
  . Creating the RA-TLS server cert and key (using "dcap" as attestation type)... ok
  . Maliciously modifying SGX quote embedded in RA-TLS cert... ok
  . Bind on https://localhost:4433/ ... ok
  . Setting up the SSL data.... ok
  . Waiting for a remote connection ... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -30592
```

Client:
```
$ RA_TLS_ALLOW_DEBUG_ENCLAVE_INSECURE=1 RA_TLS_ALLOW_OUTDATED_TCB_INSECURE=1 RA_TLS_MRENCLAVE=<server_mrenclave> RA_TLS_MRSIGNER=<mr_signer> RA_TLS_ISV_PROD_ID=0 RA_TLS_ISV_SVN=0 ./client dcap
[ using default SGX-measurement verification callback (via RA_TLS_* environment variables) ]

  . Seeding the random number generator... ok
  . Connecting to tcp/localhost/4433... ok
  . Setting up the SSL/TLS structure... ok
  . Loading the CA root certificate ... ok
  . Installing RA-TLS callback ... ok
  . Performing the SSL/TLS handshake... failed
  ! mbedtls_ssl_handshake returned -0x3000

Last error was: -12288 - X509 - A fatal error occurred, eg the chain is too long or the vrfy callback failed
```

## Gramine commit hash
dcc0eb5c6b09e8f3703805923af6d30a72a7af7d

## Platform info
SGX1 with launch config supported
Using in-kernel SGX drivers and installed libsgx packages as per Intel SDK instructions
Ubuntu focal kernel 5.15.0-48-generic

**Comment by dimakuv** [comment]
1. Are you using a local configuration of DCAP, where you install Intel PCCS on your machine?
2. Please verify that the official sample code for DCAP infrastructure works correctly: https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/SampleCode
3. What is the output of `systemctl status aesmd`?
4. What is the output of `systemctl status pccs`?
5. Anything interesting in the PCCS logs (under `/opt/intel/sgx-dcap-pccs/logs/`)?

If nothing helps, please check the questions/answers on https://github.com/intel/SGXDataCenterAttestationPrimitives/search?q=pccs+log&type=issues. I have a very strong suspicion your PCCS is incorrectly installed or running. Maybe some proxy issues...

**Comment by asmprogrammer5** [comment]
Thanks! Please find my answers below:

> 1. Are you using a local configuration of DCAP, where you install Intel PCCS on your machine?
PCCS_URL=https://localhost:8081/sgx/certification/v3/

> 2. Please verify that the official sample code for DCAP infrastructure works correctly: https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/SampleCode
Yes, the QuoteGeneration and Verification Samples seem to work:
Generation:
```
SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample$ ./app 
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent: 
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:succeed!
Step2: Call create_app_report:succeed!
Step3: Call sgx_qe_get_quote_size:succeed!
Step4: Call sgx_qe_get_quote:succeed!cert_key_type = 0x5
sgx_qe_cleanup_by_policy is valid in in-proc mode only.

 Clean up the enclave load policy:succeed!
```

Verification:
```
SGXDataCenterAttestationPrimitives/SampleCode/QuoteVerificationSample$ ./app 
Info: ECDSA quote path: ../QuoteGenerationSample/quote.dat

Trusted quote verification:
	Error: Can't load SampleISVEnclave. 0x200f

===========================================

Untrusted quote verification:
	Info: sgx_qv_get_quote_supplemental_data_size successfully returned.
	Info: App: sgx_qv_verify_quote successfully returned.
	Warning: App: Verification completed with Non-terminal result: a007
	Info: Supplemental data version: 3
```

> 3. What is the output of `systemctl status aesmd`?
```
aesmd.service - Intel(R) Architectural Enclave Service Manager
     Loaded: loaded (/lib/systemd/system/aesmd.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-09-29 04:07:33 PDT; 13h ago
    Process: 5832 ExecStartPre=/opt/intel/sgx-aesm-service/aesm/linksgx.sh (code=exited, status=0/SUCCESS)
    Process: 5841 ExecStartPre=/bin/mkdir -p /var/run/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 5842 ExecStartPre=/bin/chown -R aesmd:aesmd /var/run/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 5843 ExecStartPre=/bin/chmod 0755 /var/run/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 5844 ExecStartPre=/bin/chown -R aesmd:aesmd /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 5845 ExecStartPre=/bin/chmod 0750 /var/opt/aesmd/ (code=exited, status=0/SUCCESS)
    Process: 5846 ExecStart=/opt/intel/sgx-aesm-service/aesm/aesm_service (code=exited, status=0/SUCCESS)
   Main PID: 5847 (aesm_service)
      Tasks: 4 (limit: 19110)
     Memory: 6.6M
     CGroup: /system.slice/aesmd.service
             └─5847 /opt/intel/sgx-aesm-service/aesm/aesm_service

Sep 29 08:06:01 sgx2 aesm_service[5847]: [QCNL] HTTP status code: 200
Sep 29 08:35:47 sgx2 aesm_service[5847]: [QCNL] Try remote service...
Sep 29 08:35:47 sgx2 aesm_service[5847]: [QCNL] Request URL https://localhost:8081/sgx/certification/v3/pckcert?qeid=<qe_id>&encrypted_ppid=<enc_ppid>
Sep 29 08:35:47 sgx2 aesm_service[5847]: [QCNL] HTTP status code: 200
Sep 29 08:35:48 sgx2 aesm_service[5847]: [QCNL] Try remote service...
Sep 29 08:35:48 sgx2 aesm_service[5847]: [QCNL] Request URL https://localhost:8081/sgx/certification/v3/pckcert?qeid=B9363A3B97ACB0119335621FE0ADF605&encrypted_ppid=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000>
Sep 29 08:35:48 sgx2 aesm_service[5847]: [QCNL] HTTP status code: 200
Sep 29 08:35:48 sgx2 aesm_service[5847]: [QCNL] Try remote service...
Sep 29 08:35:48 sgx2 aesm_service[5847]: [QCNL] Request URL https://localhost:8081/sgx/certification/v3/pckcert?qeid=B9363A3B97ACB0119335621FE0ADF605&encrypted_ppid=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000>
Sep 29 08:35:48 sgx2 aesm_service[5847]: [QCNL] HTTP status code: 200
```
> 4. What is the output of `systemctl status pccs`?
```
pccs.service - Provisioning Certificate Caching Service (PCCS)
     Loaded: loaded (/lib/systemd/system/pccs.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2022-09-29 04:07:43 PDT; 13h ago
       Docs: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md
   Main PID: 5864 (node)
      Tasks: 11 (limit: 19110)
     Memory: 62.1M
     CGroup: /system.slice/pccs.service
             └─5864 /usr/bin/node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js

Sep 29 17:13:09 sgx2 node[5864]: 2022-09-29 17:13:09.949 [info]: Client Request-ID : 8e84c9d06e1f497e9ada5e58372cc1c7
Sep 29 17:13:09 sgx2 node[5864]: 2022-09-29 17:13:09.952 [info]: 127.0.0.1 - - [30/Sep/2022:00:13:09 +0000] "GET /sgx/certification/v3/rootcacrl HTTP/1.1" 200 586 "-" "-"
Sep 29 17:14:18 sgx2 node[5864]: 2022-09-29 17:14:18.556 [info]: Client Request-ID : 89cf07387df7456ea9bd9f0fe3b5548e
Sep 29 17:14:18 sgx2 node[5864]: 2022-09-29 17:14:18.558 [info]: 127.0.0.1 - - [30/Sep/2022:00:14:18 +0000] "GET /sgx/certification/v3/pckcrl?ca=processor HTTP/1.1" 200 604 "-" "-"
Sep 29 17:14:18 sgx2 node[5864]: 2022-09-29 17:14:18.563 [info]: Client Request-ID : c9ae64c1e22d42b5b5f437f0c1597794
Sep 29 17:14:18 sgx2 node[5864]: 2022-09-29 17:14:18.565 [info]: 127.0.0.1 - - [30/Sep/2022:00:14:18 +0000] "GET /sgx/certification/v3/tcb?fmspc=00906EA10000 HTTP/1.1" 200 7725 "-" "-"
Sep 29 17:14:18 sgx2 node[5864]: 2022-09-29 17:14:18.571 [info]: Client Request-ID : 7c55c17430984c9b8fe19c67a964f0fb
Sep 29 17:14:18 sgx2 node[5864]: 2022-09-29 17:14:18.572 [info]: 127.0.0.1 - - [30/Sep/2022:00:14:18 +0000] "GET /sgx/certification/v3/qe/identity HTTP/1.1" 200 933 "-" "-"
Sep 29 17:14:18 sgx2 node[5864]: 2022-09-29 17:14:18.578 [info]: Client Request-ID : 042b1c84ea63413eb662d40e1e303971
Sep 29 17:14:18 sgx2 node[5864]: 2022-09-29 17:14:18.580 [info]: 127.0.0.1 - - [30/Sep/2022:00:14:18 +0000] "GET /sgx/certification/v3/rootcacrl HTTP/1.1" 200 586 "-" "-"
```

> 5. Anything interesting in the PCCS logs (under `/opt/intel/sgx-dcap-pccs/logs/`)?
No errors here. The CPUSVN, PCESVN, PCEID look ok to me
 
> If nothing helps, please check the questions/answers on https://github.com/intel/SGXDataCenterAttestationPrimitives/search?q=pccs+log&type=issues. I have a very strong suspicion your PCCS is incorrectly installed or running. Maybe some proxy issues...

Not using a proxy. Does anything stand out from the above to you? Thanks!
If not, will look at that list.

**Comment by dimakuv** [comment]
```
$ gramine-sgx server dcap
...
  . Creating the RA-TLS server cert and key (using "dcap" as attestation type)... ok
  . Maliciously modifying SGX quote embedded in RA-TLS cert... ok    # OUCH!
```

Hehe, this is the problem. Sorry I didn't notice this before.

The `ra-tls-mbedtls` example's server works in such a way that:
1. It runs a normal benign attestation **when no command-line arguments are given**.
2. It runs a *malicious* attestation **when any command-line argument is given**.

You gave the `dcap` argument, which is not needed (you already specified that the server needs to be built using DCAP attestation type). So the server code decided that `dcap` argument is a hint to trigger the malicious flow 2.

P.S. We changed the example at some point, about 2 months ago, to remove the need for an additional `dcap` argument. I guess you got used to the old way of running the example, that's why you started it with `gramine-sgx server dcap`, even though [our README](https://github.com/gramineproject/gramine/blob/master/CI-Examples/ra-tls-mbedtls/README.md#quick-start) doesn't require it.

**Comment by dimakuv** [comment]
This is the code in the server that forces this logic:
https://github.com/gramineproject/gramine/blob/bf9d2758b6dbe3b973d707df157ec54caec1bc05/CI-Examples/ra-tls-mbedtls/src/server.c#L180-L182

Maybe it was not smart to rely on "any command-line argument". Maybe I should have hard-coded some specific argument like `force-malicious`.

**Comment by dimakuv** [comment]
I cooked a PR that disallows such bloopers in the future: https://github.com/gramineproject/gramine/pull/943

**Comment by asmprogrammer5** [comment]
Aha! That worked, without "dcap" argument.

**Comment by asmprogrammer5** [comment]
Yes, it's not the right thing to inject malicious quote for no argument. Thanks for fixing it with the new argument, that's more intuitive :)
