### ISSUE TITLE
[LibOS] Add support for shrinking encrypted files via truncate(2) to arbitrary size

### ISSUE THREAD

**Issue by lead4good** [gramineproject/gramine#950]
Graminizing the ethereum [geth client](https://github.com/ethereum/go-ethereum), we are running into another issue regarding encrypted files. To protect the state of geth's persistent data from host access and manipulation, files are stored in a encrypted mount point. 

Syncing `goerli` testnet with geth into encrypted mount point on Gramine 1.3.1, we run into this error:
```
[P1:T12:geth] warning: encrypted_file_set_size: pf_set_size failed: Functionality not implemented
CRIT [10-03|17:28:11.357] Failed to truncate ancient data          number=1,325,056 err="truncate /root/.ethereum/goerli/geth/chaindata/ancient/chain/bodies.cidx: permission denied"
```
At times, geth needs to rewind the state of the blockchain to a previous block. It does so by shrinking the size of the database file to the specific block. Since shrinking encrypted files is not supported within gramine, this operation fails.

**Comment by dimakuv** [comment]
Indeed, shrinking to arbitrary size is not implemented yet: https://github.com/gramineproject/gramine/blob/b822d29c971dc7e277c7f2d3f4b8dd219ccf29bd/common/src/protected_files/protected_files.c#L1219-L1220

I can imagine a naive way to implement it:
1. Read the encrypted file completely into a temporary buffer
2. Shrink the encrypted file to zero
3. Write the temporary buffer completely into the encrypted file

This looks trivial to implement, but it has two downsides:
1. *Very slow* at it requires first reading the whole contents and then writing them back
2. *Memory consuming* as it requires a temporary buffer as big as the contents of the file itself

@lead4good How bad are the two downsides for your use case?

**Comment by lead4good** [comment]
@dimakuv 
Currently we haven't set any performance goals for this project. If there is a trivial implementation for shrinking, we can see how much this will affect the performance in a later stage and possibly supply a performance increasing patch.
Out of curiosity, how would you implement this to be performant?

**Comment by dimakuv** [comment]
> Out of curiosity, how would you implement this to be performant?

Well, just truncate the file using the host means to the required size. The problem with this approach is that it requires a new security analysis because it will rely on the new functionality from the host (truncation). In other words, my proposal for the "trivial implementation" builds on already-existing and known-secure primitives (read encrypted file, truncate to zero encrypted file, save encrypted file). But the performant proposal would build on a new primitive (truncate to size).

**Comment by dimakuv** [comment]
> this truncat implemention would cause new problems(truncate just set file size,and keep file node as the old,instead of a new file)……

My proposal doesn't create a new file. All the operations are done on the same file.

**Comment by mkow** [comment]
> geth needs to rewind the state of the blockchain to a previous block. It does so by shrinking the size of the database file to the specific block.

A bit unrelated to this issue, but please keep in mind that it's possible to do a replay attack with an older version of the file. So, you need to ensure that this won't compromise your app.

**Comment by lead4good** [comment]
@mkow Thanks for pointing this out. We agree it is a possible attack vector, but with low priority at this point.

@dimakuv We'd be happy to test a trivial implementation of encrypted file shrinking by syncing a graminized geth node and sharing our results.

**Comment by dimakuv** [comment]
@lead4good Please try https://github.com/gramineproject/gramine/pull/972

**Comment by lead4good** [comment]
@dimakuv Sorry for the delay. I've encountered severe performance issues (+100x overhead) while running `geth` from an encrypted mount point (this was tested with upstream gramine, so not related to this patch). I'm prioritising this before I can properly test #972.
