### ISSUE TITLE
Problem in Running Threshold Signature Scheme on Gramine

### ISSUE THREAD

**Issue by raoufro** [gramineproject/gramine#956]
## Description of the problem
As I mentioned in the mailing list of Gramine under the same title of this issue,  when I run [multi-party ECDSA](https://github.com/ZenGo-X/multi-party-ecdsa) on Gramine v1.3 and v1.2, I see unstable execution results in which in some cases, the execution completes without any problem, and in some cases, the execution halts and freezes that I have to cancel it.

To start, this the output is-sgx-available
```
raouf@user-System-Product-Name:~/git/tss-ecdsa-gramine$ is-sgx-available
SGX supported by CPU: true
SGX1 (ECREATE, EENTER, ...): true
SGX2 (EAUG, EACCEPT, EMODPR, ...): false
Flexible Launch Control (IA32_SGXPUBKEYHASH{0..3} MSRs): true
SGX extensions for virtualizers (EINCVIRTCHILD, EDECVIRTCHILD, ESETCONTEXT): false
Extensions for concurrent memory management (ETRACKC, ELDBC, ELDUC, ERDINFO): false
CET enclave attributes support (See Table 37-5 in the SDM): false
Key separation and sharing (KSS) support (CONFIGID, CONFIGSVN, ISVEXTPRODID, ISVFAMILYID report fields): false
Max enclave size (32-bit): 0x80000000
Max enclave size (64-bit): 0x1000000000
EPC size: 0x5d80000
SGX driver loaded: true
AESMD installed: true
SGX PSW/libsgx installed: true
```

I made a  [tss-ecdsa-gramine](https://github.com/raoufro/tss-ecdsa-gramine) repository  on github containing all the scripts and gramine config that I used to run multi-party ecdsa. In better words, [tss-ecdsa/pure](https://github.com/raoufro/tss-ecdsa-gramine/tree/main/tss-ecdsa/pure) contains it.

I added the logs to [GraminLog](https://github.com/raoufro/tss-ecdsa-gramine/tree/main/tss-ecdsa/pure/GramineLog) directory. BTW, I had changed the log-level to debug.

## Steps to reproduce
Please follow README in the repository and do these steps in order:
- Build the base container and execute its script
- Build the native container of multi-party ecdsa and execute its script without Gramine
- Execute tss-ecdsa-pure.sh to run multi-party ecdsa on Gramine

**Comment by boryspoplawski** [comment]
You should change the log_level to `all` or `trace` to get all the syscalls your app does and see what's happening there, maybe something's failing.
Also are you sure it freezes, not just takes an enormous amount of time to complete? Try adding `loader.env.MALLOC_ARENA_MAX = "1"` to your manifest (more details: https://gramine.readthedocs.io/en/stable/performance.html#glibc-malloc-tuning)

**Comment by raoufro** [comment]
Thank you! `loader.env.MALLOC_ARENA_MAX = "1"` works. It seems it was related to the large number of threads that the application runs. I asked about this problem in the mailing list, but it's the first time I hear about `loader.env.MALLOC_ARENA_MAX = "1"`. I run my scripts multiple times, and I haven't experienced any sort of freezing yet. Without this option, the execution completes in some cases, but in other cases, it seems it faces some sort of busy loop; in fact, I ran it with the trace log level, and it produced 2.1 GB of logs which kept increasing.

Another question is that I try to add user-space networking like snabb or DPDK to my enclave. I've also heard about gvisor, and I think about adding its networking part to my enclave for this purpose. Do you know any project or research which have tried to do the same thing? Do you have any suggestions to handle this task?

**Comment by boryspoplawski** [comment]
Running networking in enclave rarely makes sense. Why would you want to do it?

> Do you have any suggestions to handle this task?

In Gramine? Most likely impossible. We do not support raw sockets to begin with. If the networking run on top of UDP then maybe something would work.

**Comment by raoufro** [comment]
> Why would you want to do it?

In fact, I developed DTLS tunnel on top of UDP for mutual authentication in Go (pion/dtls package). In my first design, I tried to use TUN/TAP device to redirect traffic from the app to trusted tunnel in which both of them run on Gramine enclave, but I found Gramine does not support netlink, so managing and communicating with TUN/TAP was not possible inside enclave. I excluded the tunnel from the enclave, and I run it as another process in which uses the key/cert issued from the app running on Gramine. On the other side, the receiving tunnel use MRENCLAVE/MRSIGNER/ISV_PROD_ID/ISV_SVN for remote attestation verification. It works, but it does not comply with my initial security analysis in which the temporary key/cert must be issued inside the enclave (on Gramine) having the trusted tunnel.
>  If the networking run on top of UDP then maybe something would work.

Accordingly, to complete my initial design, I need to run my trusted tunnel, running on top UDP, inside the enclave beside the application that is multi-party ecdsa in this case. In fact, I need to redirect traffic from my app to the trusted tunnel using the generated key/cert inside the enclave to establish a secure channel. Therefore, the traffic must not leave the enclave unless it is encrypted by the trusted tunnel.

**Comment by boryspoplawski** [comment]
If you put the key out of enclave it's of course completely insecure.

Can't your app just communicate via some TLS encrypted channel? Why do you insist of putting whole networking stack inside enclave?

**Comment by dimakuv** [comment]
> Another question is that I try to add user-space networking like snabb or DPDK to my enclave. I've also heard about gvisor, and I think about adding its networking part to my enclave for this purpose. Do you know any project or research which have tried to do the same thing? Do you have any suggestions to handle this task?

Gramine currently doesn't have any support for user-space networking (which would require raw network sockets). We've done some research on this ~5 years ago (with the Snort application), see:
- https://arxiv.org/abs/1802.00508 -- paper
- https://github.com/cloud-security-research/sgx-ids -- corresponding repo

Please note that the implementation is **very old** and **very hacky**. This was just to research the concept, and required extensive changes in Gramine codebase. This **was not and never will be** upstreamed to Gramine. What you can do is to take some ideas from there and apply them in your private Gramine fork (if you want to modify Gramine core code).

Also, there were some conference papers about putting user-space networking (Click, mTCP, etc.) inside an SGX enclave. Some of them used Graphene/Gramine, some used other runtimes like SCONE or SGX SDK. It's easy to google them, if you're interested in the academic research on this topic. I'm not aware of any SGX runtime actually allowing this out of the box.

**Comment by raoufro** [comment]
> If you put the key out of enclave it's of course completely insecure.

I know, and that is why I need to find a solution to put my tunnel inside enclave beside my app.

> Can't your app just communicate via some TLS encrypted channel? 

As I said, I try to implement a mechanism for mutual authentication based on their SGX identity to harden a system, so I need to establish the trusted tunnel without considering the application that I need to run inside enclave; therefore, it may/may not use TLS channel, but I wrap its traffic inside a DTLS trusted channel established and verified using Gramine generated key/cert. 

> Why do you insist of putting whole networking stack inside enclave?

Actually, I'm not sure whether I need to put the whole network stack inside the enclave or not. I found [this paper](https://www.usenix.org/conference/usenixsecurity20/presentation/schwarz) which uses lwIP user-networking to make a tunnel inside enclave, but it's implementation is too hacky and complicated, and it is based on the old Graphene code base. I just need to redirect the traffic from the app (tss-ecdsa) to my implemented tunnel using Gramine key/Cert to handshake with the other end while the traffic is not leaving the enclave. The problem I'm facing is that I cannot find a solution to do that inside enclave. I could find OpenVPN solution using TUN/TAP for this purpose, but it is not fully aligned with my security analysis and specifically Gramine because of using Netlink call.

**Comment by boryspoplawski** [comment]
> As I said, I try to implement a mechanism for mutual authentication based on their SGX identity to harden a system, so I need to establish the trusted tunnel without considering the application that I need to run inside enclave; therefore, it may/may not use TLS channel, but I wrap its traffic inside a DTLS trusted channel established and verified using Gramine generated key/cert.

You can just run attestation in some global constructor (e.g. `init_array` or hijack some pre-main libc function) and simply do attestation there https://gramine.readthedocs.io/en/stable/attestation.html#high-level-secret-provisioning-interface. But I'm not sure if that fits your needs, you vaguely described how and when you connect different parties.

Anyway, @dimakuv described the current state, nothing more to add
