### ISSUE TITLE
Python example fails with Gramine-Direct with recent hardening changes on CentOS/RHEL.

### ISSUE THREAD

**Issue by anjalirai-intel** [gramineproject/gramine#973]
### Description of the problem

**Python example fails with Gramine-Direct with recent hardening changes on CentOS/RHEL.**

To make python work for Gramine in CentOS/RHEL, we initially removed distlib and apport from manifest files and changed the enclave size to 4GB
https://github.com/gramineproject/graphene/issues/2599

**_But with recent hardening changes, it fails, because of fs.mounts_**
Previously complete /usr folder was mounted, which has been now restrcited to /usr/arch_libdir

> `{ path = "/usr", uri = "file:/usr" }, replaced with { path = "/usr/{{ arch_libdir }}", uri = "file:/usr/{{ arch_libdir }}" },`

**With latest changes it is failing on RHEL with error "No module named six" and Numpy throws error for CentOS**

_We don't have docker setup right now for RHEL. In RHEL Baremetal Setup the "six" package is in /usr/local/lib which is not mounted now_
```
RHEL:
Numpy: /usr/lib64/python3.6/site-packages
Scipy: /usr/lib64/python3.6/site-packages
Six: /usr/local/lib/python3.6/site-packages
```

_Whereas for CentOS, numpy is getting installed in /usr/local/lib64 and scipy is /usr/local/lib which is also not mounted._
```
CentOS:
Numpy: /usr/local/lib64/python3.6/site-packages
Scipy: /usr/lib64/python3.6/site-packages
SIX: /usr/local/lib/python3.6/site-packages
```

So, in order to run Python with Gramine we need to make several changes. 
1. Remove distlib
2. Increase enclave size
3. Map the respective folder in fs.mount and sgx.trusted_files section

**Since we are officially supporting rpm packages now, we should also make sure all the examples in CI-Examples are compatible for Ubuntu, CentOS & RHEL**
https://gramine.readthedocs.io/en/stable/quickstart.html#install-gramine

> 	On RHEL-8-like distribution (like AlmaLinux 8, CentOS 8, Rocky Linux 8, …):
> 
> 	sudo curl -fsSLo /etc/yum.repos.d/gramine.repo https://packages.gramineproject.io/rpm/gramine.repo
> 	sudo dnf install gramine          # only the default, distro-provided kernel is supported

### Steps to reproduce

1. Checkout gramine package for CentOS/RHEL
2. make python example with **make SGX=1 ARCH_LIBDIR=/lib64**
3. Run make SGX=1 check

### Expected results

Python should work and no error should be seen

### Actual results

 **"No module named six" for RHEL and Numpy throws error for CentOS**

### Gramine commit hash

fd329ff42a0c5ce4edd171b2835c4e5796e90613

**Comment by anjalirai-intel** [comment]
@dimakuv Recently when we were testing Pytorch worload for CentOS & RHEL, we faced similar issue. So, we decided to just mount the respective library path instead of mounting stdlib & distlib path

https://github.com/gramineproject/examples/blob/master/pytorch/Makefile#L6

I have tested on CentOS after removing stdlib & distlib and replacing them with numpy, scipy & six libraries path. It worked

**Comment by sphadnix** [comment]
Its working, verified on gramine.

[intel@localhost python]$ gramine-sgx  ./python scripts/test-numpy.py
Gramine is starting. Parsing TOML manifest file, this may take some time...
-----------------------------------------------------------------------------------------------------------------------
Gramine detected the following insecure configurations:

  - sgx.debug = true                           (this is a debug enclave)
  - loader.insecure__use_cmdline_argv = true   (forwarding command-line args from untrusted host to the app)

Gramine will continue application execution, but this configuration must not be used in production!
-----------------------------------------------------------------------------------------------------------------------

numpy version: 1.14.3
numpy.dot: 0.07304496765136718 sec
