### ISSUE TITLE
Gramine 1.3.1-1 seems to require python3-protobuf >= 3.12.0 but installs with python3-protobuf == 3.6.1

### ISSUE THREAD

**Issue by jtdaugherty** [gramineproject/gramine#987]
### Description of the problem

When running `gramine-manifest` I encounter a Python traceback related to `protobuf`:
```
Traceback (most recent call last):
  File "/usr/bin/gramine-manifest", line 8, in <module>
    from graminelibos import Manifest
  File "/usr/lib/python3/dist-packages/graminelibos/__init__.py", line 24, in <module>
    from .sgx_get_token import get_token
  File "/usr/lib/python3/dist-packages/graminelibos/sgx_get_token.py", line 9, in <module>
    from . import aesm_pb2 # pylint: disable=import-error,no-name-in-module
  File "/usr/lib/python3/dist-packages/graminelibos/aesm_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'
```

### Steps to reproduce

* Install Ubuntu 20.04.
* Install `gramine-oot` version `1.3.1-1`.
  * This results in `python3-protobuf` version `3.6.1.3-2ubuntu5` being installed as well as C libraries with the same version (3.6.1).
* Run `gramine-manifest`.

### Expected results

`gramine-manifest` runs without issue. Here is some supporting information about the version that Gramine seems to require:

https://github.com/protocolbuffers/protobuf/issues/8279

That seems to be saying that the missing `_internal_create_key` attribute is only available starting in `python3-protobuf` starting at 3.12.0.

### Actual results

`gramine-manifest` fails to run.

### Gramine commit hash

1.3.1-1

**Comment by woju** [comment]
The bug is real, there should be a versioned dependency. It would cause install to fail if you picked the wrong suite. Yes, you should have used `focal` suite, not `stable` as described in documentation, but it should have failed at `apt-get install`, not tracebacked in python.

I'll release `1.3.1-2` with corrected dependencies.

**Comment by jtdaugherty** [comment]
@woju thank you!

**Comment by woju** [comment]
This is fixed in latest master. Upcoming v1.4 release drops `python3-protobuf` dependency.
