### ISSUE TITLE
`toml` Python package v0.10.0 is buggy; need v0.10.2

### ISSUE THREAD

**Issue by dimakuv** [gramineproject/gramine#990]
### Description of the problem

While testing #671, I encountered this bug.

#671 introduces a rather complex format for IOCTL data structures. Example from `device_ioctl.manifest.template` from #671:
```
sgx.ioctl_structs.gramine_test_dev_ioctl_write = [
    { size=8, type="out", name="buf_size" },     # buf_size
    { ptr=[ {size="buf_size", type="out"} ] },   # buf
    { size=8, type="inout" },                    # off
    { adjust=-4, size=12, type="in" },           # copied; adjust is just for testing
]
```

Gramine uses the `toml` Python package, including for manifest.template rendering:
- https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/python/gramine-manifest#L29
- https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/python/graminelibos/manifest.py#L84

The `toml` Python package on Ubuntu 20.04 is taken from `apt install`: https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/.ci/ubuntu20.04.dockerfile#L67

On Ubuntu 18.04, it is taken from `pip3 install`: https://github.com/gramineproject/gramine/blob/db86ad2eab2ab449508b85263818f4d6d6e10a50/.ci/ubuntu18.04.dockerfile#L89

So on Ubuntu 18.04, we get v0.10.2. But on Ubuntu 20.04, we get [v0.10.0](https://packages.ubuntu.com/focal/python3-toml).

Unfortunately, v0.10.0 had a bug that directly affects my TOML snippet above: ["Parsing fails on inline array of tables containing a nested table"](https://github.com/uiri/toml/issues/205). This bug [was fixed in v0.10.2](https://github.com/uiri/toml/commit/7bafb6eeb1905c5f0c778318f25414e4c03cbca2) though.

So on Ubuntu 20.04, if the `toml` Python package is installed as `apt install python3-toml` (from Ubuntu repos), then such TOML manifests fail.

**Proposed solutions:**
1. Switch to another TOML parser in Python. One suggestion was [`tomli`](https://github.com/hukkin/tomli).
2. Require to use `toml` Python package v0.10.2. For this:
    - If Gramine is built from source, then the package must be installed via `pip3 install toml`.
    - If Gramine is installed via our packages, then all packages must contain `python3-toml` package with v0.10.2 -- this can be taken from e.g. [Ubuntu 22.04](https://packages.ubuntu.com/jammy/python3-toml).

@dimakuv and @woju are fine with **solution 2**, at least in the short-term. But we should discuss it during the Gramine meeting.

### Steps to reproduce

Try #671 on Ubuntu 20.04 with `toml` Python package installed via `apt install python3-toml`.

### Expected results

`device_ioctl.manifest.template` from #671 is rendered correctly by `toml` Python package.

### Actual results

This is what I observed in #671 in Ubuntu 20.04 Jenkins jobs:
```
16:11:59  gramine-manifest -Darch_libdir=/lib/x86_64-linux-gnu -Dcoreutils_libdir=/usr/lib/x86_64-linux-gnu/coreutils -Dentrypoint=device_ioctl -Dbinary_dir=/home/jenkins/workspace/graphene-20.04/usr/lib/x86_64-linux-gnu/gramine/tests/libos/regression -Dlibc=glibc device_ioctl.manifest.template device_ioctl.manifest
16:11:59  Traceback (most recent call last):
16:11:59    File "/usr/lib/python3/dist-packages/toml/decoder.py", line 455, in loads
16:11:59      ret = decoder.load_line(line, currentlevel, multikey,
16:11:59    File "/usr/lib/python3/dist-packages/toml/decoder.py", line 725, in load_line
16:11:59      value, vtype = self.load_value(pair[1], strictly_valid)
16:11:59    File "/usr/lib/python3/dist-packages/toml/decoder.py", line 802, in load_value
16:11:59      return (self.load_array(v), "array")
16:11:59    File "/usr/lib/python3/dist-packages/toml/decoder.py", line 938, in load_array
16:11:59      nval, ntype = self.load_value(a[i])
16:11:59    File "/usr/lib/python3/dist-packages/toml/decoder.py", line 805, in load_value
16:11:59      self.load_inline_object(v, inline_object)
16:11:59    File "/usr/lib/python3/dist-packages/toml/decoder.py", line 621, in load_inline_object
16:11:59      raise ValueError("Invalid inline table value encountered")
16:11:59  ValueError: Invalid inline table value encountered
16:11:59  
16:11:59  During handling of the above exception, another exception occurred:
16:11:59  
16:11:59  Traceback (most recent call last):
16:11:59    File "/home/jenkins/workspace/graphene-20.04/usr/bin/gramine-manifest", line 33, in <module>
16:11:59      main() # pylint: disable=no-value-for-parameter
16:11:59    File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
16:11:59      return self.main(*args, **kwargs)
16:11:59    File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
16:11:59      rv = self.invoke(ctx)
16:11:59    File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
16:11:59      return ctx.invoke(self.callback, **ctx.params)
16:11:59    File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
16:11:59      return callback(*args, **kwargs)
16:11:59    File "/home/jenkins/workspace/graphene-20.04/usr/bin/gramine-manifest", line 29, in main
16:11:59      manifest = Manifest.from_template(template, define)
16:11:59    File "/home/jenkins/workspace/graphene-20.04/usr/lib/python3.8/site-packages/graminelibos/manifest.py", line 142, in from_template
16:11:59      return cls(_env.from_string(template).render(**(variables or {})))
16:11:59    File "/home/jenkins/workspace/graphene-20.04/usr/lib/python3.8/site-packages/graminelibos/manifest.py", line 84, in __init__
16:11:59      manifest = toml.loads(manifest_str)
16:11:59    File "/usr/lib/python3/dist-packages/toml/decoder.py", line 458, in loads
16:11:59      raise TomlDecodeError(str(err), original, pos)
16:11:59  toml.decoder.TomlDecodeError: Invalid inline table value encountered (line 34 column 1 char 1547)
```

### Gramine commit hash

d3b65ab395d26d6e4293b94a1a09abad0caab464 (in #671)

**Comment by mkow** [comment]
Let's just move to tomli instead of adding another hacks. The current toml library seems to be of really bad quality (see https://github.com/gramineproject/gsc/pull/101).

**Comment by dimakuv** [comment]
Ok, I will create a PR to move to `tomli`.
