### ISSUE TITLE
Syscall "clone3" Support

### ISSUE THREAD

**Issue by bigdata-memory** [gramineproject/gramine#991]
### Description of the feature

We have a service workload running in Gramine-SGX v1.3 which is failing when trying to create new threads to handle the increasing request traffic. the log info is 

`
warning: Unsupported system call clone3
...
error: There are no available TCS pages left for a new thread!
...
17 segment fault (core dump)
`

According to the results of our investigation. the syscall `clone3` got hit 372 times. which was invoked by `clone_thread(...)`, then it linked back to `sgx_ocall_clone_thread(...)` and mapped to `OCALL_CLONE_THREAD` in syscall table. Therefore it relies on `clone3` to add working threads

Regarding the the error "There are no available TCS pages left for a new thread!", we suspect there is also a problem with not handling system call failures correctly, because if the underlying system call fails, it should not consume TCS.

### Why Gramine should implement it?

It is a critical gating issue for an important product we are working on, and this issue will also fail all other workloads which relying on `clone3` to function, thanks.

**Comment by boryspoplawski** [comment]
`clone3` is quite new syscall and everything known to me has a fallback to other syscalls (e.g, glibc). The warning you are seeing is benign and can be ignored. `clone3` is not executed so the part about mapping cannot be true.

> Regarding the the error "There are no available TCS pages left for a new thread!", we suspect there is also a problem with not handling system call failures correctly, because if the underlying system call fails, it should not consume TCS.

Idk about this error, but it's definitely unrelated to `clone3` - it will never even reach PAL.

**Comment by bigdata-memory** [comment]
@boryspoplawski Thank you for your insights.
If it falls back through glibc to other system calls, it doesn't seem to work, because it ends up with segmentation faults.

**Comment by bigdata-memory** [comment]
I think the workload leveraged extra parameter of `clone3` to create a new thread, and that cannot be correctly covered/emulated by fallbacks, thanks.

**Comment by boryspoplawski** [comment]
Which parameter and in what way and why do you think it cannot be covered by `clone`/`clone2`?
What workload? Does it use glibc?
More details please.

**Comment by dimakuv** [comment]
I have the same questions as @boryspoplawski. We need to see at least a snippet from the Gramine trace log where `clone3()` is called, and what happens ~50 syscalls before and ~50 syscalls after that.

Until I see evidence to the contrary, I agree with Borys that all real-world programs fall back to e.g. `clone()` when they notice that `clone3()` is unavailable. I haven't seen any counter-example.

Also, "No available TCS pages left" seems orthogonal to `clone3()` issue. And segment fault also seems orthogonal to `clone3()` issue, but may be related to the "No available TCS pages left" message. All in all, needs more debugging and more logs.
