### ISSUE TITLE
No available TCS pages left for a new thread & segment fault (core dump)

### ISSUE THREAD

**Issue by bigdata-memory** [gramineproject/gramine#992]
### Description of the problem

We have a service workload running in Gramine-SGX v1.3 which is failing when trying to create new threads to handle the increasing request traffic. the trace log info is 

```
...
warning: Unsupported system call clone3
...
error: There are no available TCS pages left for a new thread!
...
17 segment fault (core dump)
```
Please also refer to the discussion of fallback path in https://github.com/gramineproject/gramine/issues/991

### Steps to reproduce

We utilized the GSC (24430f8d) tool to build Gramine from source and transform the workload container image to Graminized image, however, the workload is not open sourced which written in Go.
We tried the following settings for Gramine-SGX
    sgx.enclave_size = "16G"
    loader.pal_internal_mem_size = "1G"
    sgx.thread_num = 128
    sgx.preheat_enclave = true

### Expected results

+ The syscall `clone3` needs to be supported and the parameters passed to `clone3` should be well handled.
+ No error about "There are no available TCS pages left for a new thread!"
+ No segment fault 

### Actual results

- The syscall `clone3` fallbacks to Glibc (see https://github.com/gramineproject/gramine/issues/991).
- "There are no available TCS pages left for a new thread!" occurred
- "segment fault" triggered

### Gramine commit hash

v1.3

**Comment by boryspoplawski** [comment]
How many threads does your workload spawn? Maybe you just go over the limit. Try increasing `sgx.thread_num` even more.

> The syscall clone3 needs to be supported and the parameters passed to clone3 should be well handled.

This is unrelated.

> 17 segment fault (core dump)

Isn't this message from your app, not Gramine?

> The syscall `clone3` fallbacks to Glibc

What?

**Comment by dimakuv** [comment]
First, how is this issue different from https://github.com/gramineproject/gramine/issues/991 ?

Second, how can we reproduce any of this?

This issue is literally saying "We have some workload, it fails in different ways, please do something". This is not a helpful description.

**Comment by billionairiam** [comment]
Maybe `taskset `can solve your problem.
`taskset -c 0-3 gramine-sgx [your-application]`

**Comment by mkow** [comment]
A week passed without any clarification. I'm closing it until we get any useful info about the problem.
