### ISSUE TITLE
Alpine Linux support

### ISSUE THREAD

**Issue by mssun** [gramineproject/gramine#993]
### Description of the feature

Install/Run Gramine in container with Alpine Linux as base image.

### Why Gramine should implement it?

Many people use Alpine Linux as their container base image. Currently, Gramine only support Ubuntu, Debian and RHEL8-like distros. Therefore, they cannot containerize their workload and still keep the Apline Linux as their base image.

**Comment by dimakuv** [comment]
This feels like a feature request for GSC, not for Gramine. I don't want to have duplicate issues, so let's close this one and leave [gsc#105](https://github.com/gramineproject/gsc/issues/105) open.

**Comment by dimakuv** [comment]
It was pointed out to me that "Alpine support for Gramine" and "Alpine support for GSC" are two separate and legit tasks, so I'm reopening this issue.

**Comment by dimakuv** [comment]
This was done, see https://github.com/gramineproject/gramine/pull/1439.
